// @vitest-environment jsdom
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor,within} from '@testing-library/react';
import '@testing-library/jest-dom/vitest';
import {createSamplePlan} from '../src/domain';
import {ClientReviewPanel} from '../src/ClientReviewPanel';
import {ClientReviewViewer} from '../src/ClientReviewViewer';
import {parseReviewSnapshot,reviewImagePreview,type ReviewView} from '../src/clientReview';
import * as api from '../src/clientReviewApi';
import {reviewedPhotoPrivacy} from '../src/photoPrivacy';
vi.mock('../src/clientReviewApi',async importOriginal=>{const real=await importOriginal<typeof import('../src/clientReviewApi')>();return {...real,reviewAvailability:vi.fn(),listClientReviews:vi.fn(),publishClientReview:vi.fn(),getOwnedReview:vi.fn(),getClientReview:vi.fn(),getReviewMedia:vi.fn(),submitReviewFeedback:vi.fn()};});
vi.mock('../src/ReviewScene',()=>({default:()=> <div>Read-only scene</div>}));
vi.mock('../src/clientReview',async importOriginal=>({...await importOriginal<typeof import('../src/clientReview')>(),reviewImagePreview:vi.fn(async()=> 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAg')}));
const token='a'.repeat(43);
function view():ReviewView{const plan=createSamplePlan(),floorId=plan.floors[0].id;return {revision:1,currentRevision:1,expiresAt:Date.now()+3600000,media:[],feedback:[],snapshot:parseReviewSnapshot({version:1,title:'A cozy home',plan,stops:[{id:'stop1',title:'Reading corner',caption:'A quiet room',narration:'A shelf for favorite books.',floorId,camera:{version:1,kind:'orbit',floorId,target:{x:1,y:1,z:1},alpha:1,beta:1,radius:6,mode:0,fov:.8},marker:{xMm:1000,zMm:1000,facingDeg:90}}]})};}
beforeEach(()=>{vi.mocked(api.reviewAvailability).mockResolvedValue({available:true,signedIn:true});vi.mocked(api.listClientReviews).mockResolvedValue([]);vi.mocked(api.getOwnedReview).mockResolvedValue({review:{id:'review',projectId:'plan',revision:1,createdAt:Date.now(),expiresAt:Date.now()+3600000,revoked:false},revisions:[{revision:1,createdAt:Date.now()}],feedback:[],publication:{snapshot:view().snapshot,media:[],includeSelectedMedia:false}});});
afterEach(()=>{cleanup();vi.clearAllMocks();});
describe('review authoring and revision decisions',()=>{
 it('uses the explicitly selected privacy derivative and blocks an unselected copy',async()=>{
  const plan=createSamplePlan(),original='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a5RkAAAAASUVORK5CYII=',copy='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==';
  const privacy=reviewedPhotoPrivacy(original,{width:1,height:1,crop:{x:0,y:0,width:1,height:1},turns:0,masks:[]},copy),media=[{id:'selected',image:original,sourceImage:original,title:'Masked room',caption:'',kind:'photo' as const,seconds:4,privacy}];
  const {rerender}=render(<ClientReviewPanel plan={plan} floorId={plan.floors[0].id} media={media}/>);
  fireEvent.click(screen.getByRole('checkbox',{name:/Include selected photo/}));fireEvent.click(screen.getByRole('checkbox',{name:'Masked room · Property photo'}));fireEvent.change(screen.getByRole('combobox',{name:'Selected photo for this stop'}),{target:{value:'selected'}});fireEvent.click(screen.getByRole('button',{name:'Preview exact snapshot'}));
  expect(await screen.findByRole('alert')).toHaveTextContent('Choose the reviewed privacy copy');expect(reviewImagePreview).not.toHaveBeenCalled();expect(api.publishClientReview).not.toHaveBeenCalled();
  rerender(<ClientReviewPanel plan={plan} floorId={plan.floors[0].id} media={[{...media[0],privacy:{...privacy,selected:true}}]}/>);fireEvent.click(screen.getByRole('button',{name:'Preview exact snapshot'}));await screen.findByRole('button',{name:'Create private review link'});expect(reviewImagePreview).toHaveBeenCalledExactlyOnceWith(copy);
 });
 it('keeps previews local and private photos off until explicit selection; publishes only after exact snapshot confirmation',async()=>{
  const plan=createSamplePlan(),saved=structuredClone(plan);vi.mocked(api.publishClientReview).mockResolvedValue({review:{id:'review',projectId:plan.id,revision:1,createdAt:Date.now(),expiresAt:Date.now()+3600000,revoked:false},token});
  render(<ClientReviewPanel plan={plan} floorId={plan.floors[0].id} media={[{id:'private-photo',image:'data:image/png;base64,aA==',sourceImage:'private-original',title:'Private photo',caption:'',kind:'photo',seconds:4}]}/>);
  await screen.findByRole('button',{name:'Preview exact snapshot'});expect(screen.getByRole('checkbox',{name:/Include selected photo/})).not.toBeChecked();expect(api.publishClientReview).not.toHaveBeenCalled();
  fireEvent.click(screen.getByRole('button',{name:'Preview exact snapshot'}));await screen.findByRole('button',{name:'Create private review link'});expect(api.publishClientReview).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Create private review link'}));await waitFor(()=>expect(api.publishClientReview).toHaveBeenCalledTimes(1));
  const sent=vi.mocked(api.publishClientReview).mock.calls[0][1];expect(sent.media).toEqual([]);expect(sent.includeSelectedMedia).toBe(false);expect(JSON.stringify(sent)).not.toContain('private-original');expect(plan).toEqual(saved);
  await waitFor(()=>expect((screen.getByRole('textbox',{name:'Review link'}) as HTMLInputElement).value).toContain('#review=review&key='));expect(screen.getByRole('button',{name:'Copy link'})).toBeVisible();
 });
 it('copies only a checked photo linked to a stop, after opt-in and exact-preview confirmation',async()=>{
  const plan=createSamplePlan();vi.mocked(api.publishClientReview).mockResolvedValue({review:{id:'review',projectId:plan.id,revision:1,createdAt:Date.now(),expiresAt:Date.now()+3600000,revoked:false},token});render(<ClientReviewPanel plan={plan} floorId={plan.floors[0].id} media={[{id:'selected',image:'saved-image',sourceImage:'private-original',title:'Living room',caption:'',kind:'staged',seconds:4},{id:'not-selected',image:'other-private-image',title:'Other room',caption:'',kind:'photo',seconds:4}]}/>);
  fireEvent.click(screen.getByRole('checkbox',{name:/Include selected photo/}));fireEvent.click(screen.getByRole('checkbox',{name:'Living room · Virtually staged'}));fireEvent.change(screen.getByRole('combobox',{name:'Selected photo for this stop'}),{target:{value:'selected'}});fireEvent.click(screen.getByRole('button',{name:'Preview exact snapshot'}));await screen.findByRole('button',{name:'Create private review link'});expect(api.publishClientReview).not.toHaveBeenCalled();expect(reviewImagePreview).toHaveBeenCalledExactlyOnceWith('saved-image');fireEvent.click(screen.getByRole('button',{name:'Create private review link'}));await waitFor(()=>expect(api.publishClientReview).toHaveBeenCalledTimes(1));const sent=vi.mocked(api.publishClientReview).mock.calls[0][1];expect(sent.includeSelectedMedia).toBe(true);expect(sent.media).toHaveLength(1);expect(sent.media[0]).toMatchObject({id:'selected',kind:'staged'});expect(JSON.stringify(sent)).not.toMatch(/private-original|other-private-image/);
 });
 it('ignores a publication response after the active project changes',async()=>{
  const plan=createSamplePlan();let resolve!: (value:Awaited<ReturnType<typeof api.publishClientReview>>)=>void;vi.mocked(api.publishClientReview).mockImplementation(()=>new Promise(r=>{resolve=r;}));const {rerender}=render(<ClientReviewPanel plan={plan} floorId={plan.floors[0].id}/>);
  fireEvent.click(screen.getByRole('button',{name:'Preview exact snapshot'}));fireEvent.click(await screen.findByRole('button',{name:'Create private review link'}));await waitFor(()=>expect(api.publishClientReview).toHaveBeenCalled());const other=createSamplePlan('Another home');rerender(<ClientReviewPanel plan={other} floorId={other.floors[0].id}/>);resolve({review:{id:'old-review',projectId:plan.id,revision:1,createdAt:Date.now(),expiresAt:Date.now()+3600000,revoked:false},token});await waitFor(()=>expect(screen.getByRole('textbox',{name:'Tour title'})).toHaveValue('Another home'));expect(screen.queryByRole('button',{name:'Copy link'})).not.toBeInTheDocument();
 });
 it('labels self-reported identity, requires exact-revision approval and retries an uncertain response with the same ID',async()=>{
  const snapshot=view();vi.mocked(api.getClientReview).mockResolvedValue(snapshot);vi.mocked(api.submitReviewFeedback).mockRejectedValueOnce(new Error('Connection interrupted')).mockResolvedValueOnce({});render(<ClientReviewViewer id="review" token={token} revision={1}/>);
  await screen.findByRole('heading',{name:'Reading corner'});expect(screen.getByText(/Names are self-reported/)).toBeVisible();expect(api.submitReviewFeedback).not.toHaveBeenCalled();fireEvent.change(screen.getByRole('textbox',{name:'Your name (self-reported)'}),{target:{value:'Alex'}});fireEvent.change(screen.getByLabelText('Response',{selector:'select'}),{target:{value:'approval'}});expect(screen.getByRole('button',{name:'Approve revision 1'})).toBeDisabled();fireEvent.click(screen.getByRole('checkbox',{name:'I approve the design shown in revision 1.'}));fireEvent.click(screen.getByRole('button',{name:'Approve revision 1'}));await screen.findByRole('button',{name:'Retry same response'});const first=vi.mocked(api.submitReviewFeedback).mock.calls[0][2];expect(first).toMatchObject({revision:1,kind:'approval',authorName:'Alex',anchor:{kind:'snapshot'}});fireEvent.click(screen.getByRole('button',{name:'Retry same response'}));await waitFor(()=>expect(api.submitReviewFeedback).toHaveBeenCalledTimes(2));expect(vi.mocked(api.submitReviewFeedback).mock.calls[1][2]).toEqual(first);
 });
 it('blocks responses on a stale revision and requires explicit navigation to the latest version',async()=>{
  const snapshot=view();vi.mocked(api.getClientReview).mockResolvedValue({...snapshot,currentRevision:2});render(<ClientReviewViewer id="review" token={token} revision={1}/>);await screen.findByText(/You are viewing an older revision/);expect(screen.getByRole('textbox',{name:'Your name (self-reported)'})).toBeDisabled();expect(api.submitReviewFeedback).not.toHaveBeenCalled();vi.mocked(api.getClientReview).mockResolvedValue({...snapshot,revision:2,currentRevision:2});fireEvent.click(screen.getByRole('button',{name:'Review revision 2'}));await screen.findByText('Respond to revision 2');expect(vi.mocked(api.getClientReview).mock.calls.at(-1)?.[2]).toBe(2);expect(within(screen.getByRole('region',{name:'Story tour'})).queryByRole('button',{name:/Save|Edit|Delete/})).not.toBeInTheDocument();
 });
});
