import {afterEach,expect,it,vi} from 'vitest';
import {connectPlannerCollaboration,plannerCollaborationActive,usePlanner,savePlan} from '../src/store';
import {CollaborationSession,type CollaborationQueueStore} from '../src/collaborationSession';
import {applyCollaborationBatch,makeCollaborationBatch,type CollaborationSnapshot} from '../src/collaborationProtocol';
import {collaborationFixture} from './collaboration-fixture';
let detach:(()=>void)|undefined;
afterEach(()=>{detach?.();detach=undefined;usePlanner.getState().replacePlan(collaborationFixture());});
async function attach(role:'owner'|'viewer'='owner'){
 let head:CollaborationSnapshot={roomId:'practice-source',revision:1,plan:collaborationFixture(),me:{id:'alice',name:'Alice',role,epoch:1,active:true},members:[],presence:[],archived:false};let edits=0;
 const storage:CollaborationQueueStore={load:async()=>undefined,save:async()=>{},remove:async()=>{}};
 const session=new CollaborationSession('alice',head.roomId,'tab',{snapshot:async()=>structuredClone(head),submit:async(_id,b)=>{head={...head,plan:await applyCollaborationBatch(head.plan,head.revision,b),revision:head.revision+1};edits++;return {revision:head.revision};},presence:async()=>({})},storage);await session.start();detach=connectPlannerCollaboration(session);
 return {session,edits:()=>edits,head:()=>head,remote:async()=>{const next=structuredClone(head.plan);next.furniture[1].z+=400;const op=await makeCollaborationBatch(head.plan,next,head.revision,1,'Remote B');head={...head,plan:await applyCollaborationBatch(head.plan,head.revision,op!),revision:head.revision+1};await session.refresh();}};
}
const settled=()=>vi.waitFor(()=>expect(usePlanner.getState().collaborationPending).toBe(false));
it('routes real furniture edits through durable session commits and reverses only own changes after a remote edit',async()=>{const f=await attach();const originalFloors=usePlanner.getState().plan.floors,untouched=usePlanner.getState().plan.furniture[1];usePlanner.getState().setView('top');expect(f.edits()).toBe(0);usePlanner.getState().updateFurniture('piece-a',{x:1400});expect(usePlanner.getState().collaborationPending).toBe(true);await settled();expect(f.edits()).toBe(1);expect(usePlanner.getState().plan.floors).toBe(originalFloors);expect(usePlanner.getState().plan.furniture[1]).toBe(untouched);expect(usePlanner.getState().past).toHaveLength(1);await f.remote();expect(usePlanner.getState().plan.camera.mode).toBe('top');expect(usePlanner.getState().plan.furniture[1].z).toBe(1400);usePlanner.getState().undo();await settled();expect(usePlanner.getState().plan.furniture[0].x).toBe(1000);expect(usePlanner.getState().plan.furniture[1].z).toBe(1400);usePlanner.getState().redo();await settled();expect(usePlanner.getState().plan.furniture[0].x).toBe(1400);expect(usePlanner.getState().plan.furniture[1].z).toBe(1400);});
it('commits a held turn once and discards its draft if another editor changed the base',async()=>{const f=await attach();usePlanner.getState().beginTurn('piece-a');usePlanner.getState().turnFurniture('piece-a',10);usePlanner.getState().turnFurniture('piece-a',10);expect(f.edits()).toBe(0);usePlanner.getState().finishTurn();await settled();expect(f.edits()).toBe(1);expect(usePlanner.getState().plan.furniture[0].rotation).toBe(20);usePlanner.getState().beginTurn('piece-a');usePlanner.getState().turnFurniture('piece-a',5);await f.remote();usePlanner.getState().finishTurn();expect(usePlanner.getState().plan.furniture[0].rotation).toBe(20);expect(usePlanner.getState().plan.furniture[1].z).toBe(1400);expect(usePlanner.getState().placementNotice).toContain('Another editor');expect(f.edits()).toBe(1);});
it('blocks viewer edits through actions and direct setters, but keeps camera and selection usable',async()=>{const f=await attach('viewer'),before=usePlanner.getState().plan;usePlanner.getState().moveFurniture('piece-a',2000,1000);expect(usePlanner.getState().plan).toBe(before);const changed=structuredClone(before);changed.furniture[0].x+=500;usePlanner.setState({plan:changed});expect(usePlanner.getState().plan).toBe(before);usePlanner.getState().setView('top');expect(usePlanner.getState().plan.camera.mode).toBe('top');usePlanner.getState().select('piece-a');expect(usePlanner.getState().selectedId).toBe('piece-a');expect(f.edits()).toBe(0);});
it('requires leaving before project replacement and does not let old callbacks rewrite the next project',async()=>{await attach();const privatePlan=collaborationFixture();privatePlan.id='new-private';usePlanner.getState().replacePlan(privatePlan);expect(usePlanner.getState().plan.id).toBe('practice-source');expect(plannerCollaborationActive()).toBe(true);detach!();detach=undefined;usePlanner.getState().replacePlan(privatePlan);expect(usePlanner.getState().plan.id).toBe('new-private');expect(plannerCollaborationActive()).toBe(false);});

it('blocks ordinary autosave of a room and synchronously rejects unsupported preview application',async()=>{await attach();const state=usePlanner.getState();await expect(savePlan(state.plan)).rejects.toThrow('recovery queue');const next={...state.plan,name:'Unexpected rename'};expect(()=>state.commitDesign(state.plan,next)).toThrow('private copy');expect(usePlanner.getState().plan.name).toBe(state.plan.name);});