import {expect,it,vi} from 'vitest';
import {CollaborationSession,type CollaborationQueue,type CollaborationQueueStore} from '../src/collaborationSession';
import {CollaborationApiError,type CollaborationTransport} from '../src/collaborationApi';
import {applyCollaborationBatch,makeCollaborationBatch,reverseCollaborationEdit,type CollaborationSnapshot} from '../src/collaborationProtocol';
import {collaborationFixture} from './collaboration-fixture';
function fixture(){let head:CollaborationSnapshot={roomId:'room',revision:1,plan:collaborationFixture(),me:{id:'member',name:'Alice',role:'editor',epoch:1,active:true},members:[],presence:[],archived:false},online=true,loseAck=false;const saved=new Map<string,CollaborationQueue>(),seen=new Map<string,number>();const storage:CollaborationQueueStore={load:async k=>structuredClone(saved.get(k)),save:async(k,v)=>{saved.set(k,structuredClone(v));},remove:async k=>{saved.delete(k);}};const transport:CollaborationTransport={snapshot:async()=>{if(!online)throw new Error('Offline');return structuredClone(head);},submit:async(_id,b)=>{if(!online)throw new Error('Offline');if(seen.has(b.id))return {revision:seen.get(b.id)!};try{head={...head,plan:await applyCollaborationBatch(head.plan,head.revision,b),revision:head.revision+1};seen.set(b.id,head.revision);}catch(e){throw new CollaborationApiError((e as Error).message,409);}if(loseAck){loseAck=false;throw new Error('Acknowledgement lost');}return {revision:head.revision};},presence:async()=>({})};return {storage,transport,saved,session:()=>new CollaborationSession('alice','room','tab-1',transport,storage),offline:()=>{online=false;},online:()=>{online=true;},loseAck:()=>{loseAck=true;},head:()=>head,remote:async(piece:number)=>{const next=structuredClone(head.plan);next.furniture[piece].z+=90;const b=await makeCollaborationBatch(head.plan,next,head.revision,1,'Remote');head={...head,plan:await applyCollaborationBatch(head.plan,head.revision,b!),revision:head.revision+1};}};}
it('persists an offline queue across reload and reconciles independent edits',async()=>{const f=fixture(),s=f.session();await s.start();f.offline();await s.refresh();const base=s.getState().local!,next=structuredClone(base);next.furniture[0].x+=120;await s.edit(base,next,'Local');expect(s.getState().queued).toBe(1);s.dispose();await f.remote(1);const resumed=f.session();await resumed.start();expect(resumed.getState().local!.furniture[0].x).toBe(next.furniture[0].x);f.online();await resumed.reconnect();expect(resumed.getState().queued).toBe(0);expect(resumed.getState().local!.furniture[1].z).toBe(f.head().plan.furniture[1].z);resumed.dispose();});
it('retains conflicting geometry until explicit recovery/discard and can recover a lost acknowledgement',async()=>{const f=fixture(),s=f.session();await s.start();f.loseAck();let base=s.getState().local!,next=structuredClone(base);next.furniture[0].x++;await s.edit(base,next,'Once');expect(s.getState().queued).toBe(1);await s.reconnect();expect(s.getState().queued).toBe(0);expect(f.head().revision).toBe(2);f.offline();await s.refresh();base=s.getState().local!;next=structuredClone(base);next.furniture[0].z+=30;await s.edit(base,next,'Offline conflict');await f.remote(0);f.online();await s.reconnect();expect(s.getState().status).toBe('conflict');expect(s.recovery().plan.furniture[0].z).toBe(next.furniture[0].z);expect(s.recovery().queuedOperations).toHaveLength(1);await s.acceptLatest();expect(s.getState().queued).toBe(0);expect(s.getState().local).toEqual(f.head().plan);s.dispose();});
it('never accepts a local edit when durable queue storage fails',async()=>{const f=fixture(),s=f.session();await s.start();const before=s.getState().local!;f.storage.save=async()=>{throw new Error('Quota');};const next=structuredClone(before);next.furniture[0].x++;await expect(s.edit(before,next,'Unstored')).rejects.toThrow('recovery queue');expect(s.getState().local).toEqual(before);expect(s.getState().queued).toBe(0);expect(f.head().revision).toBe(1);s.dispose();});
it('cleans polling and aborts pending work on dispose',async()=>{vi.useFakeTimers();const f=fixture(),s=f.session();await s.start();const spy=vi.spyOn(f.transport,'snapshot');s.startPolling();s.dispose();await vi.advanceTimersByTimeAsync(20_000);expect(spy).not.toHaveBeenCalled();await expect(s.refresh()).rejects.toThrow('closed');vi.useRealTimers();});
it('retains locks until an explicit fresh unlock and never unlocks and moves protected furniture together',async()=>{const base=collaborationFixture();base.furnitureGroups={version:1,groups:[],lockedItemIds:['piece-a']};const move=structuredClone(base);move.furniture[0].x++;await expect(makeCollaborationBatch(base,move,1,1,'Move locked')).rejects.toThrow('Unlock');const unlocked=structuredClone(base);unlocked.furnitureGroups!.lockedItemIds=[];await expect(makeCollaborationBatch(base,unlocked,1,1,'Implicit unlock')).rejects.toThrow('Unlock');const explicit=await makeCollaborationBatch(base,unlocked,1,1,'Unlock',undefined,{allowUnlock:true});expect((await applyCollaborationBatch(base,1,explicit!)).furnitureGroups!.lockedItemIds).toEqual([]);unlocked.furniture[0].x++;await expect(makeCollaborationBatch(base,unlocked,1,1,'Unlock and move',undefined,{allowUnlock:true})).rejects.toThrow('Unlock');});

it('undoes only local furniture changes and rejects undo over another editor touching that item',async()=>{const before=collaborationFixture(),after=structuredClone(before);after.furniture[0].x+=100;const current=structuredClone(after);current.furniture[1].z+=200;const undone=await reverseCollaborationEdit(before,after,current);expect(undone.furniture[0].x).toBe(before.furniture[0].x);expect(undone.furniture[1].z).toBe(current.furniture[1].z);current.furniture[0].x+=100;await expect(reverseCollaborationEdit(before,after,current)).rejects.toThrow('another editor');});