import {afterEach,expect,it} from 'vitest';
import {DatabaseSync} from 'node:sqlite';
import {mkdtempSync,readFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {ParallelSqliteD1} from './collaboration-sqlite';
import {collaborationFixture} from './collaboration-fixture';
import {collaborationPlan,collaborationLayout,collaborationHash,makeCollaborationBatch} from '../src/collaborationProtocol';
// @ts-expect-error Worker JavaScript is bundled by the app build.
import {createCollaborationApi,collaborationApi} from '../worker/collaboration.js';
const cleaners:Array<()=>Promise<void>>=[];
afterEach(async()=>{for(const cleanup of cleaners.splice(0))await cleanup();});
async function fixture(){const dir=mkdtempSync(join(tmpdir(),'nook-collab-')),filename=join(dir,'test.sqlite'),sql=new DatabaseSync(filename);sql.exec('PRAGMA journal_mode=WAL; CREATE TABLE project_versions(owner_id TEXT,project_id TEXT,revision INTEGER,document TEXT);');sql.exec(readFileSync('drizzle/0008_live_collaboration.sql','utf8'));const source=collaborationFixture();sql.prepare('INSERT INTO project_versions VALUES(?,?,?,?)').run('alice',source.id,1,JSON.stringify(source));sql.close();const a=new ParallelSqliteD1(filename),b=new ParallelSqliteD1(filename);cleaners.push(async()=>{await a.close();await b.close();rmSync(dir,{recursive:true,force:true});});let time=1_800_000_000_000;const api=createCollaborationApi({enabled:true,now:()=>time});
 const call=async(db:ParallelSqliteD1,path:string,user='alice',body?:unknown,extra:Record<string,string>={}):Promise<Response>=>api(new Request('https://nest.test/api/collaboration'+path,{method:body===undefined?'GET':'POST',headers:{'oai-authenticated-user-id':user,origin:'https://nest.test','content-type':'application/json',...extra},...(body===undefined?{}:{body:JSON.stringify(body)})}),{DB:db});
 const created=await call(a,'','alice',{sourceProjectId:source.id,sourceRevision:1,name:'Shared practice',displayName:'Alice',reviewed:true,reviewedHash:await collaborationHash({units:source.units,...collaborationLayout(source)})});expect(created.status).toBe(201);const {id}=await created.json();
 async function invite(user:string,role='editor'){const i=await (await call(a,'/'+id+'/invites','alice',{role})).json();const joined=await call(b,'/join',user,{displayName:user},{authorization:'Bearer '+i.token});expect(joined.status).toBe(200);return (await (await call(b,'/'+id,user)).json());}
 return {a,b,call,id,invite,source,advance:(ms:number)=>{time+=ms;}};
}
it('keeps production gated and source ownership/revision explicit',async()=>{const f=await fixture();const status=await collaborationApi(new Request('https://nest.test/api/collaboration/status'),{DB:f.a});expect((await status.json()).available).toBe(false);expect((await f.call(f.a,'','mallory',{sourceProjectId:f.source.id,sourceRevision:1,name:'Stolen',displayName:'M',reviewed:true,reviewedHash:'a'.repeat(64)})).status).toBe(404);expect((await f.call(f.a,'','alice',{sourceProjectId:f.source.id,sourceRevision:2,name:'Old',displayName:'A',reviewed:true,reviewedHash:'a'.repeat(64)})).status).toBe(409);expect((await f.call(f.a,'/'+f.id,'mallory')).status).toBe(404);expect((await f.call(f.a,'/'+f.id+'/invites','alice',{role:'editor'},{origin:'https://evil.test'})).status).toBe(403);});
it('rejects a changed browser account even when both accounts are members of the same room',async()=>{const f=await fixture(),bob=await f.invite('bob'),next=structuredClone(bob.plan);next.furniture[0].x+=100;const batch=await makeCollaborationBatch(bob.plan,next,1,bob.me.epoch,'Queued as Bob');const expected={'x-nook-collaboration-account':'bob'};expect((await f.call(f.a,'/'+f.id,'alice',undefined,expected)).status).toBe(401);expect((await f.call(f.a,'/'+f.id+'/operations','alice',batch,expected)).status).toBe(401);expect((await(await f.call(f.a,'/'+f.id)).json()).revision).toBe(1);});
it('merges disjoint entity edits from truly parallel SQLite writers and rejects overlaps without losing either version',async()=>{const f=await fixture(),bob=await f.invite('bob'),alice=await (await f.call(f.a,'/'+f.id)).json();const left=structuredClone(alice.plan),right=structuredClone(bob.plan);left.furniture[0].x+=100;right.furniture[1].z+=200;const [ba,bb]=await Promise.all([makeCollaborationBatch(alice.plan,left,1,alice.me.epoch,'Move A'),makeCollaborationBatch(bob.plan,right,1,bob.me.epoch,'Move B')]);const outcomes=await Promise.all([f.call(f.a,'/'+f.id+'/operations','alice',ba),f.call(f.b,'/'+f.id+'/operations','bob',bb)]);expect(outcomes.map(r=>r.status)).toEqual([200,200]);const head=await (await f.call(f.a,'/'+f.id)).json();expect(head.revision).toBe(3);expect(head.plan.furniture[0].x).toBe(left.furniture[0].x);expect(head.plan.furniture[1].z).toBe(right.furniture[1].z);const conflict=structuredClone(alice.plan);conflict.furniture[0].x+=900;const old=await makeCollaborationBatch(alice.plan,conflict,1,alice.me.epoch,'Offline overlapping move');expect((await f.call(f.a,'/'+f.id+'/operations','alice',old)).status).toBe(409);expect((await (await f.call(f.a,'/'+f.id+'?revision=1')).json()).plan).toEqual(alice.plan);expect((await (await f.call(f.a,'/'+f.id)).json()).revision).toBe(3);});
it('rechecks revocation atomically after validation and denies viewers and stale role epochs',async()=>{const f=await fixture(),bob=await f.invite('bob'),viewer=await f.invite('viewer','viewer');const next=structuredClone(bob.plan);next.furniture[0].x++;const batch=await makeCollaborationBatch(bob.plan,next,1,bob.me.epoch,'Move');expect((await f.call(f.b,'/'+f.id+'/operations','viewer',{...batch,memberEpoch:viewer.me.epoch})).status).toBe(403);let revoked=false;f.b.beforeRun=async sql=>{if(sql.startsWith('INSERT INTO collaboration_commits')&&!revoked){revoked=true;expect((await f.call(f.a,'/'+f.id+'/members','alice',{memberId:bob.me.id,epoch:bob.me.epoch,revoke:true})).status).toBe(200);}};expect((await f.call(f.b,'/'+f.id+'/operations','bob',batch)).status).toBe(403);expect((await f.call(f.b,'/'+f.id,'bob')).status).toBe(404);expect((await (await f.call(f.a,'/'+f.id)).json()).revision).toBe(1);});
it('consumes invites once, expires presence, and archives without erasing recovery',async()=>{const f=await fixture(),invite=await (await f.call(f.a,'/'+f.id+'/invites','alice',{role:'editor'})).json();const joins=await Promise.all([f.call(f.a,'/join','bob',{displayName:'Bob'},{authorization:'Bearer '+invite.token}),f.call(f.b,'/join','carol',{displayName:'Carol'},{authorization:'Bearer '+invite.token})]);expect(joins.filter(r=>r.status===200)).toHaveLength(1);const winner=joins[0].status===200?'bob':'carol';expect((await f.call(f.b,'/'+f.id+'/presence',winner,{floorId:'practice-floor',selectionId:'piece-a'})).status).toBe(200);expect((await (await f.call(f.a,'/'+f.id)).json()).presence).toHaveLength(1);f.advance(45_001);expect((await (await f.call(f.a,'/'+f.id)).json()).presence).toHaveLength(0);expect((await f.call(f.a,'/'+f.id+'/archive','alice',{confirm:false})).status).toBe(400);expect((await f.call(f.a,'/'+f.id+'/archive','alice',{confirm:true})).status).toBe(200);expect((await f.call(f.b,'/'+f.id+'/presence',winner,{})).status).toBe(410);expect((await (await f.call(f.b,'/'+f.id,winner)).json()).archived).toBe(true);});
it('makes lost acknowledgements idempotent and denies retry ID reuse',async()=>{const f=await fixture(),base=await (await f.call(f.a,'/'+f.id)).json(),next=structuredClone(base.plan);next.furniture[0].x++;const batch=await makeCollaborationBatch(base.plan,next,1,base.me.epoch,'Move once');expect((await f.call(f.a,'/'+f.id+'/operations','alice',batch)).status).toBe(200);expect((await (await f.call(f.a,'/'+f.id+'/operations','alice',batch)).json()).idempotent).toBe(true);expect((await f.call(f.a,'/'+f.id+'/operations','alice',{...batch,label:'Changed retry'})).status).toBe(409);expect((await (await f.call(f.a,'/'+f.id)).json()).revision).toBe(2);});
it('omits nested private media and refuses operations that smuggle private fields',async()=>{const source=collaborationFixture();(source as any).futurePrivateProject={privateNote:'secret'};source.floors[0].referenceId='a'.repeat(64);source.furniture[0].personalItem={version:1,itemId:'personal-a',name:'Private item',representation:'catalog-proxy',status:'keep',notes:'secret-note',photoAssetId:'sha256:'+'a'.repeat(64)};(source.furniture[0] as any).futurePrivate={photo:'secret-url'};const clean=collaborationPlan(source);expect(JSON.stringify(clean)).not.toContain('secret');expect(clean.floors[0].referenceId).toBeUndefined();const f=await fixture(),base=await (await f.call(f.a,'/'+f.id)).json(),next=structuredClone(base.plan);next.furniture[0].x++;const batch=await makeCollaborationBatch(base.plan,next,1,base.me.epoch,'Move');(batch!.operations[0] as any).value.futurePrivate={photo:'secret-url'};expect((await f.call(f.a,'/'+f.id+'/operations','alice',batch)).status).toBe(400);});

it('rejects stale architecture and newly inserted private fields without silently replacing concurrent furniture',async()=>{const f=await fixture(),bob=await f.invite('bob'),base=await (await f.call(f.a,'/'+f.id)).json();const architecture=structuredClone(base.plan);architecture.floors[0].cells.pop();const layout=await makeCollaborationBatch(base.plan,architecture,1,base.me.epoch,'Resize room');const moved=structuredClone(bob.plan);moved.furniture[1].x+=50;const furniture=await makeCollaborationBatch(bob.plan,moved,1,bob.me.epoch,'Move B');expect((await f.call(f.b,'/'+f.id+'/operations','bob',furniture)).status).toBe(200);expect((await f.call(f.a,'/'+f.id+'/operations','alice',layout)).status).toBe(409);const head=await(await f.call(f.a,'/'+f.id)).json();expect(head.plan.floors).toEqual(base.plan.floors);expect(head.plan.furniture[1].x).toBe(moved.furniture[1].x);});
it('requires the exact reviewed source projection and makes expired/revoked invitations unusable',async()=>{const f=await fixture();expect((await f.call(f.a,'','alice',{sourceProjectId:f.source.id,sourceRevision:1,name:'Stale review',displayName:'Alice',reviewed:true,reviewedHash:'a'.repeat(64)})).status).toBe(409);const invite=await(await f.call(f.a,'/'+f.id+'/invites','alice',{role:'viewer'})).json();f.advance(86_400_001);expect((await f.call(f.b,'/join','bob',{displayName:'Bob'},{authorization:'Bearer '+invite.token})).status).toBe(404);const next=await(await f.call(f.a,'/'+f.id+'/invites','alice',{role:'viewer'})).json();await f.call(f.a,'/'+f.id+'/invites','alice',{revokeId:next.id});expect((await f.call(f.b,'/join','bob',{displayName:'Bob'},{authorization:'Bearer '+next.token})).status).toBe(404);});
it('only the owner can permanently delete an archived exact revision, atomically removing future access and history',async()=>{const f=await fixture();await f.invite('bob');expect((await f.call(f.b,'/'+f.id+'/delete','bob',{confirm:true,expectedRevision:1})).status).toBe(403);expect((await f.call(f.a,'/'+f.id+'/delete','alice',{confirm:true,expectedRevision:1})).status).toBe(409);await f.call(f.a,'/'+f.id+'/archive','alice',{confirm:true});expect((await f.call(f.a,'/'+f.id+'/delete','alice',{confirm:true,expectedRevision:2})).status).toBe(409);expect((await f.call(f.a,'/'+f.id+'/delete','alice',{confirm:true,expectedRevision:1})).status).toBe(200);expect((await f.call(f.b,'/'+f.id,'bob')).status).toBe(404);expect((await f.a.prepare('SELECT COUNT(*) AS n FROM collaboration_commits WHERE room_id=?').bind(f.id).first()).n).toBe(0);expect((await f.a.prepare('SELECT COUNT(*) AS n FROM collaboration_members WHERE room_id=?').bind(f.id).first()).n).toBe(0);});
