// @vitest-environment jsdom
import 'fake-indexeddb/auto';
import React,{StrictMode} from 'react';
import {afterEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {CollaborationPanel,CollaborationSessionPanel,downloadCollaborationRecovery} from '../src/CollaborationPanel';
import {CollaborationSession,type CollaborationQueueStore} from '../src/collaborationSession';
import type {CollaborationSnapshot} from '../src/collaborationProtocol';
import {collaborationFixture} from './collaboration-fixture';
afterEach(()=>{cleanup();vi.unstubAllGlobals();vi.restoreAllMocks();});
it('keeps an unavailable pilot useful without sending the private plan or automatically creating a copy',async()=>{const copy=vi.fn(),open=vi.fn(),fetch=vi.fn(async(_input:string)=>Response.json({available:false}));vi.stubGlobal('fetch',fetch);const p=collaborationFixture();render(<CollaborationPanel plan={p} onCreatePrivateCopy={copy} onOpenSession={open}/>);await screen.findByText(/Live collaboration is not enabled/);expect(copy).not.toHaveBeenCalled();expect(fetch).toHaveBeenCalledTimes(1);expect(fetch.mock.calls[0][0]).toBe('/api/collaboration/status');fireEvent.click(screen.getByRole('button',{name:'Make a private copy'}));await waitFor(()=>expect(copy).toHaveBeenCalledWith(p));expect(open).not.toHaveBeenCalled();});
it('downloads a recovery payload through a bounded object URL and releases it',async()=>{let blob:Blob|undefined;vi.stubGlobal('URL',class extends URL {static createObjectURL(v:Blob){blob=v;return 'blob:fixture';}static revokeObjectURL=vi.fn();});const click=vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});downloadCollaborationRecovery({plan:collaborationFixture(),queuedOperations:[]});expect(blob?.type).toBe('application/json');expect(click).toHaveBeenCalledOnce();await waitFor(()=>expect(URL.revokeObjectURL).toHaveBeenCalledWith('blob:fixture'));});
it('survives Strict Mode remounts and disables furniture rights for a viewer while retaining copy actions',async()=>{const snapshot:CollaborationSnapshot={roomId:'room',revision:1,plan:collaborationFixture(),me:{id:'me',name:'Viewer',role:'viewer',epoch:1,active:true},members:[],presence:[],archived:false};const storage:CollaborationQueueStore={load:async()=>undefined,save:async()=>{},remove:async()=>{}};const s=new CollaborationSession('viewer','room','tab',{snapshot:async()=>snapshot,submit:async()=>{throw new Error('must not submit');},presence:async()=>({})},storage);await s.start();const copy=vi.fn().mockResolvedValue(undefined);const view=render(<StrictMode><CollaborationSessionPanel session={s} onCreatePrivateCopy={copy} onClose={()=>{}}/></StrictMode>);await waitFor(()=>expect(s.getState().status).toBe('online'));expect(screen.getByRole('status').textContent).toContain('viewer');expect(screen.queryByRole('button',{name:'Create one-use invitation'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Continue as private copy'}));await waitFor(()=>expect(copy).toHaveBeenCalled());view.unmount();await waitFor(()=>expect(s.getState().status).toBe('closed'));});
