import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import 'fake-indexeddb/auto';
import {IDBFactory} from 'fake-indexeddb';
import {openDB} from 'idb';
import {createSamplePlan} from '../src/domain';
import {validateProjectBackup,type ProjectBackup} from '../src/projectBackup';
import {createListing} from '../src/listingTypes';
import {ONLINE_MEDIA_LIMITS as L,manifestDigest,mediaDigest,parseOnlineMediaManifest,type OnlineMediaManifest} from '../src/onlineMedia';
import {checkOnlineMedia,deleteOnlineMedia,downloadOnlineMedia,prepareMediaBytes,replaceOnlineMediaHead,restoreOnlineMediaCopy,resumeOnlineMedia,startOnlineMedia} from '../src/onlineMediaClient';
import {listPreparedMedia,loadPreparedMedia,savePreparedMedia} from '../src/onlineMediaStorage';
// @ts-expect-error Worker is independently bundled JavaScript.
import {onlineMediaApi} from '../worker/online-media.js';
const now=1800000000000,databases:DatabaseSync[]=[];
function database(){const sql=new DatabaseSync(':memory:');databases.push(sql);sql.exec('PRAGMA foreign_keys=ON');sql.exec(readFileSync('drizzle/0009_online_media.sql','utf8'));const db={sql,beforeRun:null as null|((query:string)=>void),prepare(query:string){return {bind(...values:any[]){const args=values.map(v=>v instanceof ArrayBuffer?new Uint8Array(v):v);const execute=()=>{db.beforeRun?.(query);return {meta:{changes:Number(sql.prepare(query).run(...args).changes)}};};return {_run:execute,async run(){return execute();},async first(){return sql.prepare(query).get(...args)??null;},async all(){return {results:sql.prepare(query).all(...args)};}};}};},async batch(statements:{_run:()=>unknown}[]){sql.exec('BEGIN');try{const result=statements.map(s=>s._run());sql.exec('COMMIT');return result;}catch(error){sql.exec('ROLLBACK');throw error;}}};return db;}
const environment=()=>({DB:database(),ONLINE_MEDIA_STORAGE:'d1-bounded-v1'});
const account=(owner='alice')=>mediaDigest(new TextEncoder().encode('nook-private-media-account-v1:'+owner));
async function call(e:ReturnType<typeof environment>,path:string,data?:unknown,options:{owner?:string;method?:string;now?:number;headers?:Record<string,string>}={}){const owner=options.owner??'alice',raw=data instanceof Uint8Array,method=options.method??(data===undefined?'GET':raw?'PUT':'POST');const request=new Request('https://nest.test/api/online-media'+path,{method,headers:{origin:'https://nest.test','content-type':raw?'application/octet-stream':'application/json',...(owner?{'oai-authenticated-user-id':owner,'X-Nook-Media-Account':await account(owner)}:{}),...options.headers},...(data===undefined?{}:{body:raw?data as BodyInit:JSON.stringify(data)})});return onlineMediaApi(request,e,()=>options.now??now) as Promise<Response>;}
async function manifest(projectId='local-project',content=new TextEncoder().encode('Portable private bytes')):Promise<OnlineMediaManifest>{const chunks=[];for(let i=0;i<content.length;i+=L.chunk){const bytes=content.subarray(i,i+L.chunk);chunks.push({hash:await mediaDigest(bytes),bytes:bytes.length});}return parseOnlineMediaManifest({format:'nook-private-media/1',projectId,projectName:'A private home',exportedAt:new Date(now).toISOString(),totalBytes:content.length,archiveHash:await mediaDigest(content),chunks,selections:{listing:false,references:false,personal:false},counts:{floors:1,listingMedia:0,references:0,personalAssets:0},notices:['Private images were omitted.']});}
async function begin(e:ReturnType<typeof environment>,m:OnlineMediaManifest,revision=0,owner='alice',id:string=crypto.randomUUID()){return call(e,'/uploads',{id,manifest:m,expectedRevision:revision,uploadConfirmed:true},{owner});}
async function reserve(e:ReturnType<typeof environment>,m:OnlineMediaManifest,revision=0,owner='alice'){const r=await begin(e,m,revision,owner);expect(r.status).toBe(201);return r.json();}
async function fill(e:ReturnType<typeof environment>,u:any,bytes:Uint8Array,owner='alice'){let offset=0;for(const c of u.manifest.chunks){expect((await call(e,'/uploads/'+u.snapshot.id+'/chunks/'+c.hash,bytes.slice(offset,offset+c.bytes),{owner})).status).toBe(200);offset+=c.bytes;}}
async function finalize(e:ReturnType<typeof environment>,u:any,owner='alice'){return call(e,'/uploads/'+u.snapshot.id+'/finalize',{manifestHash:u.snapshot.manifestHash,expectedVersion:u.snapshot.stateVersion},{owner});}
const head=(e:ReturnType<typeof environment>,project='local-project',owner='alice')=>e.DB.sql.prepare('SELECT head_id,revision FROM online_media_projects WHERE owner_id=? AND project_id=?').get(owner,project);
beforeEach(()=>vi.stubGlobal('indexedDB',new IDBFactory()));
afterEach(()=>{databases.splice(0).forEach(db=>db.close());vi.unstubAllGlobals();});
describe('private bounded D1 snapshots with real SQLite',()=>{
 it('requires opt-in, platform ownership, current account binding and origin; disabled uploads still allow owner recovery/deletion',async()=>{
  const e=environment(),m=await manifest(),input={id:'a',manifest:m,expectedRevision:0,uploadConfirmed:true};
  for(const [data,options,code] of [[{...input,uploadConfirmed:false},{},400],[input,{owner:''},401],[input,{headers:{origin:'https://evil.test'}},403],[input,{headers:{'X-Nook-Media-Account':await account('bob')}},409]] as const)expect((await call(e,'/uploads',data,options)).status).toBe(code);
  const u=await reserve(e,m);for(const path of ['/uploads/'+u.snapshot.id,'/uploads/'+u.snapshot.id+'/chunks/'+m.chunks[0].hash])expect((await call(e,path,undefined,{owner:'bob'})).status).toBe(404);
  expect((await call(e,'/uploads/'+u.snapshot.id,{expectedVersion:1},{method:'DELETE',owner:'bob'})).status).toBe(404);
  const paused={...e,ONLINE_MEDIA_STORAGE:''};expect((await call(paused,'/uploads',{...input,id:'disabled'})).status).toBe(503);expect((await(await call(paused,'/status')).json()).available).toBe(false);expect((await call(paused,'/uploads/'+u.snapshot.id)).status).toBe(200);expect((await call(paused,'/uploads/'+u.snapshot.id,{expectedVersion:1},{method:'DELETE'})).status).toBe(200);
 });
 it('rejects corrupt and undeclared chunks, preserves a complete head through partial failures and permits exact idempotent retry',async()=>{
  const e=environment(),bytes=new TextEncoder().encode('Known good private data'),m=await manifest('local-project',bytes),first=await reserve(e,m);await fill(e,first,bytes);expect((await finalize(e,first)).status).toBe(200);const next=await reserve(e,m,1);
  expect((await finalize(e,next)).status).toBe(409);expect(head(e)?.head_id).toBe(first.snapshot.id);
  expect((await call(e,'/uploads/'+next.snapshot.id+'/chunks/'+'a'.repeat(64),bytes)).status).toBe(400);expect((await call(e,'/uploads/'+next.snapshot.id+'/chunks/'+m.chunks[0].hash,new Uint8Array(bytes.length))).status).toBe(400);
  await fill(e,next,bytes);e.DB.beforeRun=query=>{if(query.startsWith("UPDATE online_media_uploads SET state='complete'"))throw Error('disk write failed');};expect((await finalize(e,next)).status).toBe(503);expect(head(e)?.head_id).toBe(first.snapshot.id);expect(e.DB.sql.prepare('SELECT state FROM online_media_uploads WHERE id=?').get(next.snapshot.id)?.state).toBe('uploading');e.DB.beforeRun=null;
  expect((await finalize(e,next)).status).toBe(200);expect((await finalize(e,next)).status).toBe(200);expect(head(e)?.revision).toBe(2);const repeated=await begin(e,m,1,'alice',next.snapshot.id);expect(repeated.status).toBe(200);expect(e.DB.sql.prepare('SELECT starts FROM online_media_daily').get()?.starts).toBe(2);
 });
 it('serializes competing finalize calls; explicit CAS rebase is required to replace the winner and stale consent cannot win',async()=>{
  const e=environment(),bytes=new TextEncoder().encode('Same valid bytes'),m=await manifest('local-project',bytes),a=await reserve(e,m),b=await reserve(e,m);await fill(e,a,bytes);await fill(e,b,bytes);
  const results=await Promise.all([finalize(e,a),finalize(e,b)]);expect(results.map(r=>r.status).sort()).toEqual([200,409]);const loser=head(e)?.head_id===a.snapshot.id?b:a,winner=head(e)?.head_id;
  expect((await call(e,'/uploads/'+loser.snapshot.id+'/rebase',{expectedRevision:0,expectedVersion:1,replaceConfirmed:true})).status).toBe(409);expect(head(e)?.head_id).toBe(winner);
  const r=await call(e,'/uploads/'+loser.snapshot.id+'/rebase',{expectedRevision:1,expectedVersion:1,replaceConfirmed:true});expect(r.status).toBe(200);expect((await finalize(e,loser)).status).toBe(409);expect((await finalize(e,await r.json())).status).toBe(200);expect(e.DB.sql.prepare("SELECT COUNT(*) AS n FROM online_media_uploads WHERE state='complete'").get()?.n).toBe(2);
 });
 it('reserves full logical bytes atomically across project, account and shared pilot quotas, including partial uploads',async()=>{
  const e=environment(),base=await manifest(),sized=(id:string,n:number)=>parseOnlineMediaManifest({...base,projectId:id,totalBytes:n,chunks:Array.from({length:n/L.chunk},()=>({hash:'a'.repeat(64),bytes:L.chunk}))});
  const project=await Promise.all([1,2].map(()=>begin(e,sized('project',12*1024*1024))));expect(project.map(r=>r.status).sort()).toEqual([201,409]);
  await reserve(e,sized('second',18*1024*1024));const accountRace=await Promise.all(['third','fourth'].map(p=>begin(e,sized(p,20*1024*1024))));expect(accountRace.map(r=>r.status).sort()).toEqual([201,409]);expect(e.DB.sql.prepare("SELECT SUM(total_bytes) AS n FROM online_media_uploads WHERE owner_id='alice'").get()?.n).toBe(L.account);
  for(let i=0;i<7;i++)await reserve(e,sized('other',20*1024*1024),0,'owner-'+i);const global=await Promise.all(['last-a','last-b'].map(owner=>begin(e,sized('other',10*1024*1024),0,owner)));expect(global.map(r=>r.status).sort()).toEqual([201,409]);expect(e.DB.sql.prepare('SELECT SUM(total_bytes) AS n FROM online_media_uploads').get()?.n).toBe(L.pilot);
 });
 it('deletes chunks atomically, restores the previous complete head, and tombstones prevent delayed requests recreating deleted data',async()=>{
  const e=environment(),bytes=new TextEncoder().encode('Owned snapshot'),m=await manifest('local-project',bytes),a=await reserve(e,m);await fill(e,a,bytes);await finalize(e,a);const b=await reserve(e,m,1);await fill(e,b,bytes);await finalize(e,b);
  expect((await call(e,'/uploads/'+b.snapshot.id,{expectedVersion:1},{method:'DELETE'})).status).toBe(409);expect(head(e)?.head_id).toBe(b.snapshot.id);
  expect((await call(e,'/uploads/'+b.snapshot.id,{expectedVersion:2},{method:'DELETE'})).status).toBe(200);expect(head(e)).toMatchObject({head_id:a.snapshot.id,revision:3});expect(e.DB.sql.prepare('SELECT COUNT(*) AS n FROM online_media_chunks WHERE upload_id=?').get(b.snapshot.id)?.n).toBe(0);
  expect((await begin(e,m,3,'alice',b.snapshot.id)).status).toBe(409);expect((await finalize(e,b)).status).toBe(404);
  const pending=await reserve(e,m,3);await fill(e,pending,bytes);e.DB.beforeRun=query=>{if(query.startsWith('UPDATE online_media_projects SET head_id=?,revision')){e.DB.beforeRun=null;e.DB.sql.prepare('INSERT INTO online_media_deleted VALUES(?,?,?)').run('alice',pending.snapshot.id,now);e.DB.sql.prepare('DELETE FROM online_media_uploads WHERE id=?').run(pending.snapshot.id);}};
  expect((await finalize(e,pending)).status).toBe(409);expect(head(e)?.head_id).toBe(a.snapshot.id);
 });
 it('expires incomplete reservations without exposing their chunks, and rolls back failed deletion without losing the last complete snapshot',async()=>{
  const e=environment(),bytes=new TextEncoder().encode('Private snapshot'),m=await manifest('local-project',bytes),a=await reserve(e,m);await fill(e,a,bytes);
  expect((await call(e,'/uploads/'+a.snapshot.id+'/chunks/'+m.chunks[0].hash)).status).toBe(404);expect((await call(e,'/uploads/'+a.snapshot.id+'/finalize',{manifestHash:a.snapshot.manifestHash,expectedVersion:1},{now:now+7*86400000})).status).toBe(409);expect(head(e)?.head_id).toBeNull();await finalize(e,a);
  e.DB.beforeRun=query=>{if(query.startsWith('DELETE FROM online_media_uploads'))throw Error('storage failure');};expect((await call(e,'/uploads/'+a.snapshot.id,{expectedVersion:2},{method:'DELETE'})).status).toBe(503);expect(head(e)?.head_id).toBe(a.snapshot.id);expect(e.DB.sql.prepare('SELECT COUNT(*) AS n FROM online_media_deleted').get()?.n).toBe(0);
 });
});
function backup(withReference=false):ProjectBackup {const plan=createSamplePlan('My saved home','metric');return validateProjectBackup({format:'nook-and-nest-project-backup',version:1,exportedAt:new Date(now).toISOString(),plan,references:withReference?[{floorId:plan.floors[0].id,status:'included',page:1,rotation:0,file:{name:'plan.pdf',type:'application/pdf',lastModified:now,data:'data:application/pdf;base64,'+btoa('%PDF-'+ 'x'.repeat(150000))}}]:[]});}
function transport(e:ReturnType<typeof environment>,hook?:(method:string,path:string,response:Response)=>Promise<Response>){return vi.fn(async(input:string|URL|Request,init:RequestInit={})=>{const url=new URL(String(input),'https://nest.test'),request=new Request(url,{...init,headers:{origin:url.origin,'oai-authenticated-user-id':'alice',...Object.fromEntries(new Headers(init.headers))}}),response=await onlineMediaApi(request,e,()=>now);return hook?hook(request.method,url.pathname,response):response;});}
describe('exact local recovery and safe new-identity restore',()=>{
 it('keeps resumable exact bytes after an ambiguous chunk response, skips received chunks and verifies before creating a separate project',async()=>{
  const e=environment(),source=backup(true),key=await account(),prepared=await prepareMediaBytes(source,{listing:false,personal:false,references:true},key,0);expect(prepared.manifest.chunks.length).toBeGreaterThan(1);
  let lost=false;const fetcher=transport(e,async(method,path,response)=>{if(method==='PUT'&&!lost){lost=true;throw Error('Connection lost after server stored the chunk');}return response;});vi.stubGlobal('fetch',fetcher);
  await expect(startOnlineMedia(prepared,true)).rejects.toThrow('Connection lost');expect(await listPreparedMedia(key)).toHaveLength(1);expect(head(e,source.plan.id)?.head_id).toBeNull();fetcher.mockClear();const complete=await resumeOnlineMedia(prepared.id,key);expect(complete.snapshot.state).toBe('complete');expect(fetcher.mock.calls.filter(([,o])=>o?.method==='PUT')).toHaveLength(prepared.manifest.chunks.length-1);
  const downloaded=await downloadOnlineMedia(prepared.id,key);expect(downloaded.backup.plan).toEqual(source.plan);expect(downloaded.notices.some(n=>n.includes('Listing details'))).toBe(true);const db=await openDB('nook-and-nest',1,{upgrade(db){db.createObjectStore('projects');}});await db.put('projects',source.plan,'project:'+source.plan.id);const restored=await restoreOnlineMediaCopy(downloaded.backup,true);expect(restored.id).not.toBe(source.plan.id);expect(await db.get('projects','project:'+source.plan.id)).toEqual(source.plan);expect(await db.get('projects','project:'+restored.id)).toMatchObject({id:restored.id});db.close();const refs=await openDB('nook-studio-references',1);const restoredRef=await refs.get('references',JSON.stringify([restored.id,restored.floors[0].id]));expect((downloaded.backup.references[0] as {file:{name:string}}).file.name).toBe('plan.pdf');expect(await restoredRef.file.text()).toBe('%PDF-'+'x'.repeat(150000));refs.close();
 });
 it('does not POST without consent, after local quota failure, or when the authenticated account changes; corrupt downloads never become restore inputs',async()=>{
  const e=environment(),key=await account(),prepared=await prepareMediaBytes(backup(),{listing:false,personal:false,references:false},key,0),fetcher=transport(e);vi.stubGlobal('fetch',fetcher);
  await expect(startOnlineMedia(prepared,false)).rejects.toThrow('Confirm');expect(fetcher).not.toHaveBeenCalled();
  for(let i=0;i<4;i++)await savePreparedMedia({...prepared,id:'cached-'+i});await expect(startOnlineMedia(prepared,true)).rejects.toThrow('cache is full');expect(fetcher).not.toHaveBeenCalled();
  vi.stubGlobal('indexedDB',new IDBFactory());const response=transport(e,async(_m,path,r)=>path.endsWith('/status')?Response.json({...await r.json(),accountKey:await account('bob')}):r);vi.stubGlobal('fetch',response);await expect(startOnlineMedia(prepared,true)).rejects.toThrow('account changed');expect(response.mock.calls.some(([,o])=>o?.method==='POST')).toBe(false);
  vi.stubGlobal('fetch',fetcher);await startOnlineMedia(prepared,true);vi.stubGlobal('fetch',transport(e,async(method,path,r)=>method==='GET'&&path.includes('/chunks/')?new Response(new Uint8Array(prepared.bytes.length)):r));await expect(downloadOnlineMedia(prepared.id,key)).rejects.toThrow('damaged');
 });
 it('resumes after explicit rebase without silently changing the stored original and rejects damaged recovery bytes',async()=>{
  const e=environment(),key=await account(),p=await prepareMediaBytes(backup(),{listing:false,personal:false,references:false},key,0);vi.stubGlobal('fetch',transport(e));await savePreparedMedia(p);expect((await begin(e,p.manifest,0,'alice',p.id)).status).toBe(201);const rival={...p,id:crypto.randomUUID()};await startOnlineMedia(rival,true);
  await expect(replaceOnlineMediaHead(p.id,key,1,1,false)).rejects.toThrow('Confirm');await replaceOnlineMediaHead(p.id,key,1,1,true);expect((await resumeOnlineMedia(p.id,key)).snapshot.state).toBe('complete');expect((await loadPreparedMedia(p.id,key)).baseRevision).toBe(0);
  await expect(savePreparedMedia({...p,id:'bad',bytes:new Uint8Array(p.bytes.length)})).rejects.toThrow('bytes changed');expect((await checkOnlineMedia()).signedIn).toBe(true);await deleteOnlineMedia(p.id,key,3);await expect(resumeOnlineMedia(p.id,key)).rejects.toThrow('quota');
 });
 it('preserves chosen listing and private photo originals, rejects false image fingerprints, and reports omitted references explicitly',async()=>{
  const e=environment(),key=await account(),source=backup(),image='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aVh0AAAAASUVORK5CYII=',bytes=Uint8Array.from(atob(image.split(',')[1]),c=>c.charCodeAt(0)),photoId='sha256:'+await mediaDigest(bytes);
  source.plan.furniture=[{id:'my-chair',catalogId:'armchair',floorId:source.plan.floors[0].id,x:1200,z:1200,rotation:0,widthMm:800,depthMm:800,heightMm:900,variant:'sage',personalItem:{version:1,itemId:'private-chair',name:'My chair',representation:'catalog-proxy',status:'keep',notes:'Private purchase note',photoAssetId:photoId}}];source.personalAssets={version:1,assets:[{version:1,id:photoId,original:image,preview:image,width:1,height:1,createdAt:new Date(now).toISOString()}],missing:[]};source.listing=createListing(source.plan.id,'A listing');source.listing.media=[{id:'photo',title:'Original room',caption:'Actual photo',kind:'photo',image,sourceImage:image,seconds:3}];
  const bad=structuredClone(source);bad.personalAssets!.assets[0].id='sha256:'+'a'.repeat(64);bad.plan.furniture[0].personalItem!.photoAssetId=bad.personalAssets!.assets[0].id;await expect(prepareMediaBytes(bad,{listing:true,personal:true,references:false},key,0)).rejects.toThrow('fingerprint');
  const prepared=await prepareMediaBytes(source,{listing:true,personal:true,references:false},key,0);expect(prepared.manifest.notices.some(n=>n.includes('reference'))).toBe(true);vi.stubGlobal('fetch',transport(e));await startOnlineMedia(prepared,true);const downloaded=await downloadOnlineMedia(prepared.id,key),restored=await restoreOnlineMediaCopy(downloaded.backup,true);expect(restored.furniture[0].personalItem).toEqual(source.plan.furniture[0].personalItem);const photos=await openDB('nook-personal-furniture',1);expect((await photos.get('photos',photoId)).original).toBe(image);photos.close();const listings=await openDB('nook-listing-studio',1);const listing=await listings.get('listings',restored.id);expect(listing.document.planId).toBe(restored.id);expect(listing.document.media[0]).toMatchObject({image,sourceImage:image});expect(listing.document.media[0].id).not.toBe('photo');listings.close();
 });
});
