// @vitest-environment jsdom
import {afterEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {OpeningReview} from '../src/OpeningReview';
import {createSamplePlan} from '../src/domain';
import {inspectOpening} from '../src/openingEvidence';
import type {BlueprintDraft} from '../src/blueprint';
vi.mock('../src/openingEvidence',()=>({inspectOpening:vi.fn(),prepareOpeningEvidence:vi.fn()}));
afterEach(()=>{cleanup();vi.clearAllMocks();});
const props=()=>{const base=createSamplePlan();base.furniture=[];const draft:BlueprintDraft={rooms:[{id:'r',name:'Living',kind:'Living',x:0,z:0,width:4000,depth:4000,enclosed:false}],walls:[],fixtures:[],omittedWalls:[]};return {base,floorId:base.floors[0].id,draft,reference:{url:'data:image/jpeg;base64,YQ==',width:400,height:400,pages:1,name:'test'},scale:10,span:{ax:100,ay:0,bx:190,by:0},disabled:false,onSpan:vi.fn(),onOverlay:vi.fn(),onDraw:vi.fn(),onCommit:vi.fn()};};
it('only applies a reviewed suggestion after an explicit action',async()=>{const p=props();vi.mocked(inspectOpening).mockResolvedValue({choiceId:'span-0',kind:'door',confidence:'high',note:'Jambs visible.'});render(<OpeningReview {...p}/>);fireEvent.click(screen.getByText('Check walls & openings · experimental'));fireEvent.click(screen.getByText('Inspect close-up with Luna'));await screen.findByText('Jambs visible.');expect(p.onCommit).not.toHaveBeenCalled();fireEvent.click(screen.getByText('Apply selected opening'));expect(p.onCommit).toHaveBeenCalledOnce();expect(p.onCommit.mock.calls[0][0].fixtures).toHaveLength(1);});
it('discards a late response after the drawing changes',async()=>{let finish!:(value:Awaited<ReturnType<typeof inspectOpening>>)=>void;vi.mocked(inspectOpening).mockImplementation(()=>new Promise(resolve=>{finish=resolve;}));const p=props(),view=render(<OpeningReview {...p}/>);fireEvent.click(screen.getByText('Check walls & openings · experimental'));fireEvent.click(screen.getByText('Inspect close-up with Luna'));view.rerender(<OpeningReview {...p} draft={{...p.draft}}/>);finish({choiceId:'span-0',kind:'door',confidence:'high',note:'Stale answer'});await waitFor(()=>expect(screen.queryByText('Luna is inspecting this close-up…')).toBeNull());expect(screen.queryByText('Stale answer')).toBeNull();expect(p.onCommit).not.toHaveBeenCalled();});
it('cancels a pending request when the review unmounts',()=>{let signal:AbortSignal|undefined;vi.mocked(inspectOpening).mockImplementation((_r,_c,s)=>{signal=s;return new Promise(()=>{});});const view=render(<OpeningReview {...props()}/>);fireEvent.click(screen.getByText('Check walls & openings · experimental'));fireEvent.click(screen.getByText('Inspect close-up with Luna'));view.unmount();expect(signal?.aborted).toBe(true);});
