import {afterEach,describe,expect,it,vi} from 'vitest';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {buildRemixSnapshot,originalRemixExamples,parseRemixAttribution,parseRemixSnapshot,remixCopySeed,remixCreditPath} from '../src/remixSnapshot';
import {createSamplePlan} from '../src/domain';
import {floorFromRooms,geometryKey} from '../src/blueprint';
import {readRemixShare,remixLink,remixLocation} from '../src/remixApi';
// @ts-expect-error Worker JavaScript is bundled by the server build.
import {remixGalleryApi} from '../worker/remix-gallery.js';
const databases:DatabaseSync[]=[];
function database(){const sql=new DatabaseSync(':memory:');databases.push(sql);sql.exec('PRAGMA foreign_keys=ON');sql.exec(readFileSync('drizzle/0006_remix_gallery.sql','utf8'));const db={sql,beforeRun:null as null|((query:string)=>void),prepare(query:string){return {bind(...args:(string|number|null)[]){const execute=()=>{db.beforeRun?.(query);return {meta:{changes:Number(sql.prepare(query).run(...args).changes)}};};return {_run:execute,async run(){return execute();},async first(){return sql.prepare(query).get(...args)??null;},async all(){return {results:sql.prepare(query).all(...args)};}};}};},async batch(statements:{_run:()=>unknown}[]){sql.exec('BEGIN');try{const result=statements.map(s=>s._run());sql.exec('COMMIT');return result;}catch(error){sql.exec('ROLLBACK');throw error;}}};return db;}
const now=1800000000000;
const env=()=>({DB:database(),IDEAS_CURATOR_IDS:'["curator"]'});
const snapshot=()=>originalRemixExamples()[0].snapshot;
const input=()=>({projectId:'my-private-project',snapshot:snapshot(),rightsConfirmed:true,expiryHours:24});
function request(path:string,data?:unknown,owner='alice',token?:string,method=data===undefined?'GET':'POST',headers:Record<string,string>={}){return new Request('https://nest.test/api/'+path,{method,headers:{origin:'https://nest.test','content-type':'application/json',...(owner?{'oai-authenticated-user-id':owner}:{}),...(token?{Authorization:'Bearer '+token}:{}),...headers},...(data===undefined?{}:{body:JSON.stringify(data)})});}
async function create(e:ReturnType<typeof env>){const r=await remixGalleryApi(request('remix',input()),e,()=>now);expect(r.status).toBe(201);return r.json();}
async function submit(e:ReturnType<typeof env>,created:any){const r=await remixGalleryApi(request('ideas/submit',{shareId:created.share.id,revision:1,publicConfirmed:true,rightsConfirmed:true}),e,()=>now);expect(r.status).toBe(201);return (await r.json()).submission;}
async function approve(e:ReturnType<typeof env>,submission:any){const r=await remixGalleryApi(request('ideas/'+submission.id+'/moderate',{revision:1,expectedVersion:submission.stateVersion,decision:'approve',note:''},'curator'),e,()=>now);expect(r.status).toBe(200);}
afterEach(()=>{for(const db of databases.splice(0))db.close();vi.unstubAllGlobals();});
describe('sanitized explicit room packages',()=>{
 it('keeps only selected measured room geometry/catalog pieces and copies rights without private metadata or arbitrary links',()=>{
  const p=createSamplePlan('Private address','metric');p.floors=p.floors.slice(0,1);const room={id:'r',name:'Secret room label',kind:'Living' as const,enclosed:true,x:0,z:0,width:4000,depth:3000};p.floors[0]=floorFromRooms(p.floors[0],p.gridSizeMm,[room]);p.floors[0].blueprint={geometryKey:geometryKey(p.floors[0]),rooms:[room],generatedWallIds:[],omittedWalls:[]};p.furniture=[{id:'my-chair',catalogId:'armchair',floorId:p.floors[0].id,x:1400,z:1300,rotation:0,widthMm:800,depthMm:800,heightMm:900,variant:'sage',personalItem:{version:1,itemId:'private-chair',name:'My owned chair',representation:'catalog-proxy',status:'keep',notes:'Private notes',photoAssetId:'sha256:'+'a'.repeat(64)}}];(p as any).privateAddress='Never upload';const before=structuredClone(p),s=buildRemixSnapshot(p,{kind:'room',floorId:p.floors[0].id,roomKey:'r',selectedIds:['my-chair'],title:'Reading room',creator:'A nickname',description:'A calm arrangement',tags:['reading'],allowCopy:true});expect(JSON.stringify(s)).not.toMatch(/Private|Secret room|private-chair|photoAssetId|personalItem|my-chair/);expect(p).toEqual(before);expect(s.plan.furniture[0]).toMatchObject({widthMm:800,heightMm:900,x:1400});const copy=remixCopySeed(s,{source:'gallery',id:'example',revision:1});expect(copy.remixAttribution?.credits[0]).toMatchObject({creator:'A nickname',permission:'remix-with-credit-v1'});expect(remixCreditPath(copy.remixAttribution!.credits[0])).toBe('/?#idea=example');expect(()=>parseRemixAttribution({version:1,credits:[{...copy.remixAttribution!.credits[0],url:'javascript:alert(1)'}]})).toThrow();expect(()=>remixCopySeed({...s,allowCopy:false},{source:'gallery',id:'x',revision:1})).toThrow('viewing');expect(()=>parseRemixSnapshot({...s,plan:{...s.plan,privateAddress:'hidden'}})).toThrow('sanitized');
 });
 it('ships usable original recipes without private assets and preserves a bounded attribution chain',()=>{const seeds=originalRemixExamples();expect(seeds).toHaveLength(3);for(const seed of seeds){expect(parseRemixSnapshot(seed.snapshot).allowCopy).toBe(true);const first=remixCopySeed(seed.snapshot,{source:'builtin',id:seed.id,revision:1});const credits=Array.from({length:8},(_,i)=>({...first.remixAttribution!.credits[0],id:'source-'+i}));expect(()=>remixCopySeed({...seed.snapshot,attribution:{version:1,credits}},{source:'gallery',id:'ninth',revision:1})).toThrow('too long');}});
});
describe('sharing and curated gallery with real SQLite guards',()=>{
 it('requires dispatcher auth/origin, scopes ownership, hashes bearer secrets and closes moderation when configuration is missing or malformed',async()=>{
  const e=env();for(const [owner,headers,code] of [['',{},401],['alice',{origin:'https://evil.test'},403],['alice',{'content-type':'text/plain'},415]] as const)expect((await remixGalleryApi(request('remix',input(),owner,undefined,'POST',headers),e,()=>now)).status).toBe(code);const created=await create(e),other=await create(e),stored=e.DB.sql.prepare('SELECT * FROM remix_shares WHERE id=?').get(created.share.id)!;expect(stored.token_hash).toMatch(/^[a-f0-9]{64}$/);expect(JSON.stringify(stored)).not.toContain(created.token);expect((await remixGalleryApi(request('remix/'+created.share.id,undefined,'bob'),e,()=>now)).status).toBe(404);expect((await remixGalleryApi(request('remix/'+other.share.id+'/view?revision=1',undefined,'',created.token),e,()=>now)).status).toBe(404);
  for(const config of [undefined,'[]','not-json','["curator",null]']){const disabled={...e,IDEAS_CURATOR_IDS:config};expect((await remixGalleryApi(request('ideas/submit',{shareId:created.share.id,revision:1,publicConfirmed:true,rightsConfirmed:true}),disabled,()=>now)).status).toBe(503);expect((await remixGalleryApi(request('ideas/moderation',undefined,'curator'),disabled,()=>now)).status).toBe(403);expect((await remixGalleryApi(request('ideas',undefined,''),disabled,()=>now)).status).toBe(503);}
 });
 it('publishes exactly one competing revision, rotates access and prevents stale work from reversing revocation',async()=>{
  const e=env(),created=await create(e),path='remix/'+created.share.id;const replies=await Promise.all(['A','B'].map(title=>remixGalleryApi(request(path+'/revisions',{...input(),snapshot:{...snapshot(),title},expectedRevision:1,expectedAccessVersion:1}),e,()=>now+1)));expect(replies.map((r:Response)=>r.status).sort()).toEqual([201,409]);expect(e.DB.sql.prepare('SELECT COUNT(*) AS n FROM remix_revisions').get()?.n).toBe(2);expect((await remixGalleryApi(request(path+'/view?revision=1',undefined,'',created.token),e,()=>now)).status).toBe(404);
  await remixGalleryApi(request(path+'/access',{expectedVersion:2,action:'revoke'}),e,()=>now+2);expect((await remixGalleryApi(request(path+'/revisions',{...input(),expectedRevision:2,expectedAccessVersion:2}),e,()=>now+3)).status).toBe(409);expect(e.DB.sql.prepare('SELECT revoked_at FROM remix_shares WHERE id=?').get(created.share.id)?.revoked_at).toBe(now+2);
 });
 it('requires opt-in, rejects cross-owner submissions and makes only curator-approved exact revisions public',async()=>{
  const e=env(),created=await create(e);expect((await remixGalleryApi(request('ideas/submit',{shareId:created.share.id,revision:1,publicConfirmed:false,rightsConfirmed:true}),e,()=>now)).status).toBe(400);expect((await remixGalleryApi(request('ideas/submit',{shareId:created.share.id,revision:1,publicConfirmed:true,rightsConfirmed:true},'bob'),e,()=>now)).status).toBe(409);const submitted=await submit(e,created);expect((await(await remixGalleryApi(request('ideas',undefined,''),e,()=>now)).json()).items).toEqual([]);expect((await remixGalleryApi(request('ideas/'+submitted.id+'/moderate',{revision:1,expectedVersion:1,decision:'approve',note:''},'alice'),e,()=>now)).status).toBe(403);await approve(e,submitted);const viewed=await remixGalleryApi(request('ideas/'+submitted.id,undefined,''),e,()=>now);expect(viewed.status).toBe(200);expect(JSON.stringify(await viewed.json())).not.toMatch(/owner_id|projectId|token_hash|email|my-private-project/);const page=await(await remixGalleryApi(request('ideas?tag=calm&q=reading',undefined,''),e,()=>now)).json();expect(page.items).toHaveLength(1);expect(page.items[0].thumbnail.pieces.length).toBeGreaterThan(0);
  await remixGalleryApi(request('remix/'+created.share.id+'/access',{expectedVersion:1,action:'revoke'}),e,()=>now);expect((await remixGalleryApi(request('ideas/'+submitted.id,undefined,''),e,()=>now)).status).toBe(404);expect((await(await remixGalleryApi(request('ideas',undefined,''),e,()=>now)).json()).items).toEqual([]);
 });
 it('enforces owner withdrawal, expiry and revocation inside moderation writes instead of trusting earlier reads',async()=>{
  const e=env(),created=await create(e),submitted=await submit(e,created);e.DB.beforeRun=query=>{if(query.startsWith('UPDATE idea_submissions SET state=?')){e.DB.beforeRun=null;e.DB.sql.prepare("UPDATE idea_submissions SET state='withdrawn',state_version=2 WHERE id=?").run(submitted.id);}};expect((await remixGalleryApi(request('ideas/'+submitted.id+'/moderate',{revision:1,expectedVersion:1,decision:'approve',note:''},'curator'),e,()=>now)).status).toBe(409);expect(e.DB.sql.prepare('SELECT state FROM idea_submissions WHERE id=?').get(submitted.id)?.state).toBe('withdrawn');
  const second=await create(e),s=await submit(e,second);e.DB.beforeRun=query=>{if(query.startsWith('UPDATE idea_submissions SET state=?')){e.DB.beforeRun=null;e.DB.sql.prepare('UPDATE remix_shares SET revoked_at=? WHERE id=?').run(now,second.share.id);}};expect((await remixGalleryApi(request('ideas/'+s.id+'/moderate',{revision:1,expectedVersion:1,decision:'approve',note:''},'curator'),e,()=>now)).status).toBe(409);expect((await remixGalleryApi(request('remix/'+created.share.id+'/view?revision=1',undefined,'',created.token),e,()=>now+86400000)).status).toBe(404);
 });
 it('serves bounded stable pages and hides an approved entry immediately after its source is revised',async()=>{
  const e=env(),entries=[];for(let i=0;i<13;i++){const created=await create(e),submitted=await submit(e,created);await approve(e,submitted);entries.push({created,submitted});}const first=await(await remixGalleryApi(request('ideas',undefined,''),e,()=>now)).json();expect(first.items).toHaveLength(12);expect(first.nextCursor).toMatch(/^\d+_/);expect(first.items.every((item:any)=>item.snapshot===undefined&&item.thumbnail.floor.flat().length<=256)).toBe(true);const next=await(await remixGalleryApi(request('ideas?cursor='+encodeURIComponent(first.nextCursor),undefined,''),e,()=>now)).json();expect(next.items).toHaveLength(1);expect(next.nextCursor).toBeNull();expect(new Set([...first.items,...next.items].map(i=>i.id)).size).toBe(13);
  const chosen=entries[0];expect((await remixGalleryApi(request('remix/'+chosen.created.share.id+'/revisions',{...input(),snapshot:{...snapshot(),allowCopy:false},expectedRevision:1,expectedAccessVersion:1}),e,()=>now)).status).toBe(201);expect((await remixGalleryApi(request('ideas/'+chosen.submitted.id,undefined,''),e,()=>now)).status).toBe(404);
 });
 it('bounds report spam atomically, keeps reports private, supports curator resolution and preserves other owners on deletion',async()=>{
  const e=env(),created=await create(e),s=await submit(e,created);await approve(e,s);const report=()=>({requestId:crypto.randomUUID(),reason:'rights',note:'Please check the creator credit.'});for(let i=0;i<4;i++)expect((await remixGalleryApi(request('ideas/'+s.id+'/report',report(),'reporter'),e,()=>now)).status).toBe(201);const replies=await Promise.all([1,2].map(()=>remixGalleryApi(request('ideas/'+s.id+'/report',report(),'reporter'),e,()=>now)));expect(replies.map((r:Response)=>r.status).sort()).toEqual([201,429]);expect((await remixGalleryApi(request('ideas/reports',undefined,'alice'),e,()=>now)).status).toBe(403);const reports=(await(await remixGalleryApi(request('ideas/reports',undefined,'curator'),e,()=>now)).json()).reports;expect(JSON.stringify(reports)).not.toContain('reporter');expect(reports).toHaveLength(5);expect((await remixGalleryApi(request('ideas/reports/'+reports[0].id,{resolved:true},'curator'),e,()=>now)).status).toBe(200);expect((await remixGalleryApi(request('ideas/'+s.id+'/report',report(),'reporter'),e,()=>now+3600000)).status).toBe(201);
  expect((await remixGalleryApi(request('remix/'+created.share.id,{expectedVersion:1},'bob',undefined,'DELETE'),e,()=>now)).status).toBe(404);expect((await remixGalleryApi(request('remix/'+created.share.id,{expectedVersion:1},'alice',undefined,'DELETE'),e,()=>now)).status).toBe(200);for(const table of ['remix_shares','remix_revisions','idea_submissions','idea_reports'])expect(e.DB.sql.prepare('SELECT COUNT(*) AS n FROM '+table).get()?.n).toBe(0);
 });
 it('does not insert partial revisions on storage failure and keeps capability keys out of URLs, cookies and attribution',async()=>{
  const e=env(),created=await create(e);e.DB.beforeRun=query=>{if(query.startsWith('INSERT INTO remix_revisions'))throw Error('storage failure');};await expect(remixGalleryApi(request('remix/'+created.share.id+'/revisions',{...input(),expectedRevision:1,expectedAccessVersion:1}),e,()=>now)).rejects.toThrow('storage failure');expect(e.DB.sql.prepare('SELECT current_revision FROM remix_shares WHERE id=?').get(created.share.id)?.current_revision).toBe(1);const value=snapshot(),fetcher=vi.fn(async()=>Response.json({id:created.share.id,revision:1,snapshot:value}));vi.stubGlobal('fetch',fetcher);const link=remixLink('https://nest.test',created.share,created.token),location=remixLocation(new URL(link).hash);expect(location).toMatchObject({kind:'share',token:created.token});await readRemixShare(created.share.id,1,created.token);const [url,options]=fetcher.mock.calls[0] as unknown as [string,RequestInit];expect(url).not.toContain(created.token);expect(options).toMatchObject({credentials:'omit',referrerPolicy:'no-referrer',redirect:'error'});expect(JSON.stringify(remixCopySeed(value,{source:'share',id:created.share.id,revision:1}))).not.toContain(created.token);
 });
});
