import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve,sep} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {build} from 'esbuild';
import {SQLiteD1} from './staging-d1-adapter.mjs';
const root=fileURLToPath(new URL('../',import.meta.url)),buildDir=await mkdtemp(join(tmpdir(),'nook-shared-tools-'));
const workerPath=join(buildDir,'worker.mjs'),fixturesPath=join(buildDir,'fixtures.mjs');
await build({entryPoints:[join(root,'worker/projects.js')],outfile:workerPath,bundle:true,platform:'browser',target:'es2022',format:'esm'});
await build({stdin:{contents:"export {createSamplePlan} from './domain'; export {originalRemixExamples} from './remixSnapshot'; export {mediaDigest,parseOnlineMediaManifest} from './onlineMedia';",resolveDir:join(root,'src'),loader:'ts'},outfile:fixturesPath,bundle:true,platform:'node',format:'esm'});
const {default:worker}=await import(pathToFileURL(workerPath)),{createSamplePlan,originalRemixExamples,mediaDigest,parseOnlineMediaManifest}=await import(pathToFileURL(fixturesPath));
const journal=JSON.parse(await readFile(join(root,'drizzle/meta/_journal.json'),'utf8'));
function headers(owner,extra={}){return {origin:'https://nest.test','content-type':'application/json',...(owner?{'oai-authenticated-user-id':owner}:{}),...extra};}
function request(path,body,owner='',extra={},method=body===undefined?'GET':'POST'){return new Request('https://nest.test'+path,{method,headers:headers(owner,extra),...(body===undefined?{}:{body:body instanceof Uint8Array?body:JSON.stringify(body)})});}
async function setup(){const DB=new SQLiteD1();for(const entry of journal.entries){const migration=await readFile(join(root,'drizzle',entry.tag+'.sql'),'utf8');for(const statement of migration.split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean)){if(entry.idx>=5)assert.ok((statement.match(/\bCREATE\s+(?:TABLE|(?:UNIQUE\s+)?INDEX|TRIGGER)\b/gi)??[]).length<=1,entry.tag+' needs a statement breakpoint between declarations');DB.db.exec(statement);}}return {DB,ASSETS:{fetch:async()=>new Response('static fixture',{headers:{'Content-Type':'text/html'}})}};}
test.after(async()=>{const checked=resolve(buildDir);assert.ok(checked.startsWith(resolve(tmpdir())+sep)&&checked.includes('nook-shared-tools-'));await rm(checked,{recursive:true,force:true});});
test('all registered migrations apply in order and current snapshot represents all tables, foreign keys and inventory guards',async()=>{
 const env=await setup();try{assert.deepEqual(journal.entries.map(e=>e.idx),Array.from({length:10},(_,i)=>i));const snapshot=JSON.parse(await readFile(join(root,'drizzle/meta/0009_snapshot.json'),'utf8')),actual=env.DB.db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'").all().map(r=>r.name).sort();assert.deepEqual(Object.keys(snapshot.tables).sort(),actual);assert.equal(actual.length,30);
  for(const [name,table] of Object.entries(snapshot.tables)){const columns=env.DB.db.prepare(`PRAGMA table_info("${name}")`).all();assert.deepEqual(columns.map(c=>c.name).sort(),Object.keys(table.columns).sort(),name+' columns');const fk=env.DB.db.prepare(`PRAGMA foreign_key_list("${name}")`).all();assert.equal(new Set(fk.map(f=>f.id)).size,Object.keys(table.foreignKeys).length,name+' foreign keys');}
  let previous=JSON.parse(await readFile(join(root,'drizzle/meta/0004_snapshot.json'),'utf8')).id;for(let i=5;i<=9;i++){const value=JSON.parse(await readFile(join(root,`drizzle/meta/000${i}_snapshot.json`),'utf8'));assert.equal(value.prevId,previous);previous=value.id;}
  assert.deepEqual(env.DB.db.prepare('PRAGMA foreign_key_check').all(),[]);const triggers=env.DB.db.prepare("SELECT name FROM sqlite_master WHERE type='trigger'").all().map(r=>r.name);for(const name of ['staging_booking_overlap','staging_event_no_update','staging_event_no_delete','staging_booking_no_delete'])assert.ok(triggers.includes(name));assert.match(env.DB.db.prepare("SELECT sql FROM sqlite_master WHERE name='staging_units'").get().sql,/stock_code TEXT NOT NULL COLLATE NOCASE/);
 }finally{env.DB.close();}
});
test('combined production dispatcher preserves static/private/ordinary sharing while optional pilots remain closed',async()=>{
 const env=await setup();try{assert.equal(await (await worker.fetch(request('/'),env)).text(),'static fixture');assert.equal((await worker.fetch(request('/api/projects'),env)).status,401);const session=await(await worker.fetch(request('/api/session'),env)).json();assert.equal(session.signedIn,false);
  for(const path of ['/api/client-reviews/status','/api/remix/status','/api/ideas/status']){const r=await worker.fetch(request(path),env);assert.equal(r.status,200);assert.equal((await r.json()).signedIn,false);}
  for(const path of ['/api/collaboration/status','/api/staging/status','/api/online-media/status']){const r=await worker.fetch(request(path),env);assert.equal(r.status,200);const data=await r.json();assert.equal(data.available??data.enabled,false,path);}
  const plan=createSamplePlan('Unchanged local home','metric'),save=await worker.fetch(request('/api/projects/'+plan.id,{plan,expectedRevision:0},'alice'),env);assert.equal(save.status,200);const share=await worker.fetch(request('/api/shares',{plan},'alice'),env);assert.equal(share.status,201);const {id}=await share.json();assert.equal((await worker.fetch(request('/api/shares/'+id),env)).status,200);assert.equal((await worker.fetch(request('/api/projects/'+plan.id,undefined,'bob'),env)).status,404);
  assert.equal((await worker.fetch(request('/api/ideas'),env)).status,503);assert.equal((await worker.fetch(request('/api/collaboration/rooms',{name:'No implicit enrollment'},'alice'),env)).status,503);
 }finally{env.DB.close();}
});
test('actual worker serves capability-only review/remix viewers before private auth and enforces owner revocation',async()=>{
 const env=await setup();try{const plan=createSamplePlan(),floorId=plan.floors[0].id,input={projectId:plan.id,expiryHours:24,includeSelectedMedia:false,snapshot:{version:1,title:'A proposed home',plan,stops:[{id:'welcome',title:'Welcome',caption:'Design proposal',narration:'A reading room',floorId,camera:{version:1,kind:'orbit',floorId,target:{x:1,y:1,z:1},alpha:1,beta:1,radius:5,mode:0,fov:.8},marker:{xMm:1000,zMm:1000,facingDeg:90}}]},media:[]};const r=await worker.fetch(request('/api/client-reviews',input,'alice'),env);assert.equal(r.status,201);const created=await r.json(),viewPath='/api/client-reviews/'+created.review.id+'/view?revision=1';assert.equal((await worker.fetch(request(viewPath,undefined,'',{Authorization:'Bearer '+created.token}),env)).status,200);assert.equal((await worker.fetch(request(viewPath),env)).status,404);assert.equal((await worker.fetch(request('/api/client-reviews/'+created.review.id,undefined,'bob'),env)).status,404);
  await worker.fetch(request('/api/client-reviews/'+created.review.id+'/access',{action:'revoke'},'alice'),env);assert.equal((await worker.fetch(request(viewPath,undefined,'',{Authorization:'Bearer '+created.token}),env)).status,404);
  const remix=await worker.fetch(request('/api/remix',{projectId:plan.id,snapshot:originalRemixExamples()[0].snapshot,rightsConfirmed:true,expiryHours:24},'alice'),env);assert.equal(remix.status,201);const shared=await remix.json();assert.equal((await worker.fetch(request('/api/remix/'+shared.share.id+'/view?revision=1',undefined,'',{Authorization:'Bearer '+shared.token}),env)).status,200);
 }finally{env.DB.close();}
});
test('actual worker stores scoped binary chunks only after explicit gated reservation and never enables other pilots',async()=>{
 const env=await setup();env.ONLINE_MEDIA_STORAGE='d1-bounded-v1';try{const status=await(await worker.fetch(request('/api/online-media/status',undefined,'alice'),env)).json(),key={'X-Nook-Media-Account':status.accountKey},bytes=new TextEncoder().encode('Synthetic bounded byte-storage fixture'),hash=await mediaDigest(bytes),manifest=parseOnlineMediaManifest({format:'nook-private-media/1',projectId:'synthetic',projectName:'Synthetic home',exportedAt:new Date().toISOString(),totalBytes:bytes.length,archiveHash:hash,chunks:[{hash,bytes:bytes.length}],selections:{listing:false,references:false,personal:false},counts:{floors:1,listingMedia:0,personalAssets:0,references:0},notices:['Synthetic byte fixture, not a restore package.']}),id=crypto.randomUUID(),reserved=await worker.fetch(request('/api/online-media/uploads',{id,manifest,expectedRevision:0,uploadConfirmed:true},'alice',key),env);assert.equal(reserved.status,201);const detail=await reserved.json(),chunk='/api/online-media/uploads/'+id+'/chunks/'+hash;
  assert.equal((await worker.fetch(request(chunk,bytes,'alice',{...key,'content-type':'application/octet-stream'},'PUT'),env)).status,200);assert.equal((await worker.fetch(request('/api/online-media/uploads/'+id+'/finalize',{manifestHash:detail.snapshot.manifestHash,expectedVersion:1},'alice',key),env)).status,200);const downloaded=await worker.fetch(request(chunk,undefined,'alice',key),env);assert.equal(downloaded.status,200);assert.deepEqual(new Uint8Array(await downloaded.arrayBuffer()),bytes);assert.equal((await worker.fetch(request(chunk,undefined,'bob',key),env)).status,409);
  assert.equal((await worker.fetch(request('/api/online-media/uploads/'+id,{expectedVersion:2},'alice',key,'DELETE'),env)).status,200);assert.equal((await worker.fetch(request(chunk,undefined,'alice',key),env)).status,404);assert.equal((await(await worker.fetch(request('/api/collaboration/status',undefined,'alice'),env)).json()).available,false);
 }finally{env.DB.close();}
});
