import 'fake-indexeddb/auto';
import {deleteDB,openDB} from 'idb';
import {afterEach,describe,expect,it,vi} from 'vitest';
import {createSamplePlan} from '../src/domain';
import {makeStillRecord,parseStillResult,retryStillRecord,stillHash,verifyStillRequest} from '../src/stillRender';
import {listStillRecords,saveStillRecord} from '../src/stillRenderStorage';
import {cancelStillJob,checkStillJob,discoverStillServer,startStillJob,stillEndpoint} from '../src/localStillRender';
import {buildStillEvaluationPack} from '../src/stillRenderEvaluation';
import {defaultSceneAtmosphere} from '../src/sceneAtmosphere';
const endpoint='https://my-renderer.example/v1';
const caps={schema:'nook-still-render/1',idempotency:'request-id',cancelByRequestId:true,resultType:'inline-image',models:[{id:'my-engine',name:'My fixed renderer',modes:['fixed-geometry'],qualities:['preview','final']}]};
function png(width=960,height=540){const bytes=Buffer.alloc(24);bytes.set([137,80,78,71,13,10,26,10]);bytes.write('IHDR',12);bytes.writeUInt32BE(width,16);bytes.writeUInt32BE(height,20);return 'data:image/png;base64,'+bytes.toString('base64');}
async function prepared(){const plan=createSamplePlan(),floorId=plan.floors[0].id;const shot={id:'camera',name:'Living room',camera:{version:1 as const,kind:'orbit' as const,floorId,target:{x:2,y:1,z:2},alpha:1,beta:1,radius:5,mode:0 as const,fov:.8}};return {plan,record:await makeStillRecord(plan,shot,'preview','fixed-geometry',false)};}
const result=(r:Awaited<ReturnType<typeof prepared>>['record'])=>({schema:'nook-still-result/1',requestId:r.id,payloadHash:r.request.payloadHash,image:png(),kind:'render',engine:'Local test',runtimeMs:100});
afterEach(async()=>{vi.unstubAllGlobals();vi.restoreAllMocks();await deleteDB('nook-still-render-queue');});
describe('still job integrity, transport and recovery',()=>{
 it('exports three synthetic, hashed evaluation scenes with genuinely different geometry and camera floors',async()=>{
  const pack=await buildStillEvaluationPack();expect(pack.cases).toHaveLength(3);for(const example of pack.cases){await expect(verifyStillRequest(example.request)).resolves.toMatchObject({payloadHash:example.request.payloadHash});expect(example.request.shot.referenceImage).toBeUndefined();expect(example.expected.placements).toHaveLength(3);}expect(pack.cases.map(c=>[c.expected.floorCount,c.expected.cellCount])).toEqual([[1,30],[1,26],[2,30]]);expect(pack.cases[2].request.shot.camera.floorId).toBe(pack.cases[2].request.plan.floors[1].id);
 });
 it('keeps the original private plan hash local, strips private metadata and requires separate pixel inclusion consent',async()=>{
  const {plan,record}=await prepared();(plan as any).privateNotes='never export';const atmosphere=defaultSceneAtmosphere();atmosphere.mode='mood';atmosphere.study.latitude=43.651;atmosphere.study.longitude=-79.347;atmosphere.savedMoods=[{id:'personal',name:'Private evening name',settings:atmosphere.mood}];plan.environment={background:'plain',grass:'off',atmosphere};const photoShot={...record.request.shot,referenceImage:png(),referenceProvenance:'saved-revision-unverified' as const};await expect(makeStillRecord(plan,photoShot,'preview','fixed-geometry',false)).rejects.toThrow('Confirm');const chosen=await makeStillRecord(plan,photoShot,'preview','fixed-geometry',true);expect(JSON.stringify(chosen.request)).not.toContain('privateNotes');expect(JSON.stringify(chosen.request)).not.toContain(chosen.sourcePlanHash);expect(chosen.request.shot.referenceImage).toBe(png());expect(chosen.request.plan.environment?.atmosphere?.mood).toEqual(atmosphere.mood);expect(chosen.request.plan.environment?.atmosphere?.study.latitude).toBeNull();expect(JSON.stringify(chosen.request)).not.toContain('Private evening name');
  await expect(verifyStillRequest({...chosen.request,settings:{...chosen.request.settings,quality:'final'}})).rejects.toThrow('changed');const injected={...chosen.request,plan:{...chosen.request.plan,privateNotes:'injected'}};const {payloadHash:_,...payload}=injected;await expect(verifyStillRequest({...injected,payloadHash:await stillHash(payload)})).rejects.toThrow('private');expect(()=>parseStillResult({...result(chosen),requestId:'another'},chosen.request)).toThrow();expect(()=>parseStillResult({...result(chosen),image:png(40000,40000)},chosen.request)).toThrow();expect(()=>parseStillResult({...result(chosen),kind:'photo'},chosen.request)).toThrow();
 });
 it('uses atomic reservations across tabs, preserves immutable requests and blocks backward or ambiguous retries',async()=>{
  const {record}=await prepared(),saved=await saveStillRecord(record,0);const attempts=await Promise.allSettled([saveStillRecord({...saved,state:'submitting'},saved.revision),saveStillRecord({...saved,state:'submitting'},saved.revision)]);expect(attempts.filter(r=>r.status==='fulfilled')).toHaveLength(1);const current=(await listStillRecords(record.projectId))[0];expect(current.state).toBe('submitting');await expect(retryStillRecord(current)).rejects.toThrow();await expect(saveStillRecord({...current,state:'queued'},current.revision)).rejects.toThrow('backwards');await expect(saveStillRecord({...current,request:{...current.request,shot:{...current.request.shot,name:'Changed'}}},current.revision)).rejects.toThrow('changed');expect(await listStillRecords('another-project')).toEqual([]);
 });
 it('requires explicit capability and consent, binds capabilities to the chosen origin and omits credentials/referrers',async()=>{
  const fetcher=vi.fn(async()=>Response.json(caps));vi.stubGlobal('fetch',fetcher);for(const address of ['http://my-renderer.example','https://u:secret@my-renderer.example','https://my-renderer.example?key=abc','https://fal.ai'])expect(()=>stillEndpoint(address)).toThrow();expect(stillEndpoint('http://localhost:31000')).toBe('http://localhost:31000/v1');const cap=await discoverStillServer(endpoint,'memory-only');expect(fetcher).toHaveBeenCalledTimes(1);const [url,options]=fetcher.mock.calls[0] as unknown as [string,RequestInit];expect(url).toBe(endpoint+'/nook/still-render/capabilities');expect(options).toMatchObject({method:'GET',credentials:'omit',redirect:'error',referrerPolicy:'no-referrer',cache:'no-store'});expect(options.body).toBeUndefined();const {record}=await prepared(),saved=await saveStillRecord(record,0);await expect(startStillJob(saved,{endpoint,model:'my-engine'},'memory-only',cap,false)).rejects.toThrow('approve');await expect(startStillJob(saved,{endpoint:'https://another.example',model:'my-engine'},'memory-only',cap,true)).rejects.toThrow('Check');expect(fetcher).toHaveBeenCalledTimes(1);expect(JSON.stringify(await listStillRecords(record.projectId))).not.toContain('memory-only');
 });
 it('persists before POST, keeps an interrupted submission recoverable without a duplicate and matches the returned result',async()=>{
  const fetcher=vi.fn<typeof fetch>();vi.stubGlobal('fetch',fetcher);fetcher.mockResolvedValueOnce(Response.json(caps));const cap=await discoverStillServer(endpoint,''),{record}=await prepared(),saved=await saveStillRecord(record,0);fetcher.mockImplementationOnce(async()=>{expect((await listStillRecords(record.projectId))[0].state).toBe('submitting');throw new Error('lost response');});await expect(startStillJob(saved,{endpoint,model:'my-engine'},'secret',cap,true)).rejects.toThrow('confirm');let current=(await listStillRecords(record.projectId))[0];expect(current.state).toBe('submission-unknown');await expect(startStillJob(current,{endpoint,model:'my-engine'},'secret',cap,true)).rejects.toThrow('queued');expect(fetcher.mock.calls.filter(([,o])=>o?.method==='POST')).toHaveLength(1);
  fetcher.mockResolvedValueOnce(Response.json({schema:'nook-still-job/1',id:'server-job',requestId:record.id,payloadHash:record.request.payloadHash,status:'completed',progress:100})).mockResolvedValueOnce(Response.json(result(record)));current=await checkStillJob(current,'secret');expect(current.state).toBe('needs-review');expect(current.result?.kind).toBe('render');expect(fetcher.mock.calls.filter(([,o])=>o?.method==='POST')).toHaveLength(1);await expect(saveStillRecord({...current,state:'accepted'},current.revision)).rejects.toThrow();const accepted=await saveStillRecord({...current,state:'accepted',evaluation:{geometry:true,furnishings:true,appearance:true,notes:'Compared with source'}},current.revision);expect(accepted.state).toBe('accepted');expect(JSON.stringify(accepted)).not.toContain('secret');
 });
 it('never POSTs when storage fails and keeps external cancellation honestly unconfirmed',async()=>{
  const {record}=await prepared(),saved=await saveStillRecord(record,0),db=await openDB('nook-still-render-queue',1);await db.put('jobs',{...saved,revision:99});db.close();const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);await expect(startStillJob(saved,{endpoint,model:'my-engine'},'',{...caps,endpoint} as any,true)).rejects.toThrow('another tab');expect(fetcher).not.toHaveBeenCalled();const other=(await prepared()).record,queued=await saveStillRecord(other,0),exported=await saveStillRecord({...queued,exportedAt:new Date().toISOString()},queued.revision),cancelled=await cancelStillJob(exported,'');expect(cancelled.state).toBe('cancel-unknown');await expect(retryStillRecord(cancelled)).rejects.toThrow();const confirmed=await saveStillRecord({...cancelled,state:'cancelled'},cancelled.revision),retry=await retryStillRecord(confirmed);expect(retry.id).not.toBe(confirmed.id);expect(retry.request.payloadHash).not.toBe(confirmed.request.payloadHash);expect(retry.sourcePlanHash).toBe(confirmed.sourcePlanHash);expect(retry.state).toBe('queued');
 });
});
