import {sql} from 'drizzle-orm';
import {check,customType,foreignKey,index,integer,primaryKey,sqliteTable,text,unique} from 'drizzle-orm/sqlite-core';
// 0007's overlap/immutable-ledger/event triggers remain authoritative. Future table
// rebuild migrations must explicitly recreate those triggers; ORM metadata cannot.
const stockCode=customType<{data:string}>({dataType:()=> 'text COLLATE NOCASE'});
export const stagingWorkspaces=sqliteTable('staging_workspaces',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),name:text('name').notNull(),createdAt:text('created_at').notNull()},t=>[index('staging_workspace_owner').on(t.ownerId)]);
export const stagingMembers=sqliteTable('staging_members',{workspaceId:text('workspace_id').notNull().references(()=>stagingWorkspaces.id),userId:text('user_id').notNull(),role:text('role').notNull(),revoked:integer('revoked').notNull().default(0)},t=>[primaryKey({columns:[t.workspaceId,t.userId]}),check('staging_member_role',sql`${t.role} IN ('manager','viewer')`),check('staging_member_revoked',sql`${t.revoked} IN (0,1)`)]);
export const stagingUnits=sqliteTable('staging_units',{workspaceId:text('workspace_id').notNull().references(()=>stagingWorkspaces.id),id:text('id').notNull(),requestId:text('request_id').notNull(),requestJson:text('request_json').notNull(),stockCode:stockCode('stock_code').notNull(),label:text('label').notNull(),catalogId:text('catalog_id').notNull(),widthMm:integer('width_mm').notNull(),depthMm:integer('depth_mm').notNull(),heightMm:integer('height_mm').notNull(),condition:text('condition').notNull(),retired:integer('retired').notNull().default(0),revision:integer('revision').notNull().default(1),updatedAt:text('updated_at').notNull(),actorId:text('actor_id').notNull()},t=>[primaryKey({columns:[t.workspaceId,t.id]}),unique().on(t.workspaceId,t.stockCode),unique().on(t.workspaceId,t.requestId),check('staging_width',sql`${t.widthMm} BETWEEN 10 AND 20000`),check('staging_depth',sql`${t.depthMm} BETWEEN 10 AND 20000`),check('staging_height',sql`${t.heightMm} BETWEEN 10 AND 20000`),check('staging_condition',sql`${t.condition} IN ('good','fair','damaged','missing')`),check('staging_retired',sql`${t.retired} IN (0,1)`),check('staging_unit_revision',sql`${t.revision} BETWEEN 1 AND 2000000000`)]);
export const stagingReservations=sqliteTable('staging_reservations',{workspaceId:text('workspace_id').notNull().references(()=>stagingWorkspaces.id),id:text('id').notNull(),requestId:text('request_id').notNull(),requestJson:text('request_json').notNull(),propertyLabel:text('property_label').notNull(),startDay:text('start_day').notNull(),endDay:text('end_day').notNull(),state:text('state').notNull(),unitCount:integer('unit_count').notNull(),revision:integer('revision').notNull().default(1),operation:text('operation').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),actorId:text('actor_id').notNull()},t=>[primaryKey({columns:[t.workspaceId,t.id]}),unique().on(t.workspaceId,t.requestId),index('staging_calendar').on(t.workspaceId,t.startDay,t.endDay),check('staging_dates',sql`${t.startDay}<${t.endDay}`),check('staging_reservation_state',sql`${t.state} IN ('building','reserved','packed','completed','cancelled')`),check('staging_unit_count',sql`${t.unitCount} BETWEEN 1 AND 50`),check('staging_reservation_revision',sql`${t.revision} BETWEEN 1 AND 200`)]);
export const stagingReservationUnits=sqliteTable('staging_reservation_units',{workspaceId:text('workspace_id').notNull(),reservationId:text('reservation_id').notNull(),unitId:text('unit_id').notNull(),stockCode:text('stock_code').notNull(),label:text('label').notNull(),catalogId:text('catalog_id').notNull(),widthMm:integer('width_mm').notNull(),depthMm:integer('depth_mm').notNull(),heightMm:integer('height_mm').notNull(),conditionOut:text('condition_out').notNull(),conditionIn:text('condition_in'),returnNote:text('return_note'),status:text('status').notNull(),packedAt:text('packed_at'),returnedAt:text('returned_at'),updatedAt:text('updated_at').notNull(),actorId:text('actor_id').notNull()},t=>[primaryKey({columns:[t.workspaceId,t.reservationId,t.unitId]}),foreignKey({columns:[t.workspaceId,t.reservationId],foreignColumns:[stagingReservations.workspaceId,stagingReservations.id]}),foreignKey({columns:[t.workspaceId,t.unitId],foreignColumns:[stagingUnits.workspaceId,stagingUnits.id]}),index('staging_booked_unit').on(t.workspaceId,t.unitId,t.status),check('staging_booking_status',sql`${t.status} IN ('reserved','packed','returned','cancelled')`)]);
export const stagingEvents=sqliteTable('staging_events',{id:integer('id').primaryKey({autoIncrement:true}),workspaceId:text('workspace_id').notNull().references(()=>stagingWorkspaces.id),unitId:text('unit_id'),reservationId:text('reservation_id'),kind:text('kind').notNull(),at:text('at').notNull(),actorId:text('actor_id').notNull(),detail:text('detail').notNull()},t=>[index('staging_event_scope').on(t.workspaceId,t.reservationId,t.id)]);
