import { ArcRotateCamera, Color3, Color4, DirectionalLight, Engine, HemisphericLight, Mesh, MeshBuilder, PointerEventTypes, Scene, ShadowGenerator, StandardMaterial, TransformNode, Vector3 } from "@babylonjs/core";
import { catalog } from "../catalog";
import { deriveBoundaryWalls } from "../domain";
import type { FloorPlan, FurniturePlacement, PlanDocumentV1, Tool } from "../types";
import { FurnitureFactory } from "./FurnitureFactory";
import { FurnitureModelLibrary } from "./FurnitureModelLibrary";

interface Callbacks { onCell(x: number, z: number): void; onSelect(id?: string): void; onMove(id: string, xMm: number, zMm: number): void; onWall(id: string): void }
export class SceneController {
  private engine: Engine; private scene: Scene; private camera: ArcRotateCamera; private root: TransformNode; private callbacks: Callbacks; private tool: Tool = "select"; private dragging?: string; private activePlan?: PlanDocumentV1; private activeFloorId = ""; private selectedId?: string; private shadow: ShadowGenerator; private furnitureFactory: FurnitureFactory; private furnitureModels: FurnitureModelLibrary;
  constructor(private canvas: HTMLCanvasElement, callbacks: Callbacks) {
    this.callbacks = callbacks; this.engine = new Engine(canvas, true, { preserveDrawingBuffer: true, stencil: true }, true);
    this.scene = new Scene(this.engine); this.scene.clearColor = new Color4(0.72, 0.78, 0.62, 1); this.scene.ambientColor = new Color3(.12,.11,.09); this.scene.imageProcessingConfiguration.exposure=.72; this.scene.imageProcessingConfiguration.contrast=1.12;
    this.camera = new ArcRotateCamera("camera", -Math.PI / 4, Math.PI / 3.1, 18, new Vector3(2, 0, 2), this.scene); this.camera.attachControl(canvas, true); this.camera.lowerRadiusLimit = 4; this.camera.upperRadiusLimit = 40; this.camera.wheelPrecision = 35; this.camera.panningSensibility = 100;
    const hemi = new HemisphericLight("sky", new Vector3(0.2, 1, 0.1), this.scene); hemi.intensity = .62; hemi.diffuse = new Color3(1, .91, .78); hemi.groundColor = new Color3(.3,.37,.28);
    const sun = new DirectionalLight("sun", new Vector3(-.8, -1.5, .7), this.scene); sun.position = new Vector3(10, 18, -10); sun.intensity = .72; sun.diffuse=new Color3(1,.86,.68); this.shadow = new ShadowGenerator(1024, sun); this.shadow.useBlurExponentialShadowMap = true; this.shadow.blurKernel = 24; this.shadow.setDarkness(.3);
    this.root = new TransformNode("root", this.scene); this.furnitureFactory = new FurnitureFactory(this.scene,this.shadow); this.furnitureModels = new FurnitureModelLibrary(this.scene,this.shadow,()=>{if(this.activePlan)this.update(this.activePlan,this.activeFloorId,this.selectedId)}); this.makeMeadow(); this.bindPointers(); let frame=0; this.engine.runRenderLoop(() => {this.scene.render();frame+=1;if(frame%30===0)this.canvas.dataset.fps=this.engine.getFps().toFixed(1);}); window.addEventListener("resize", this.resize);
  }
  private resize = () => this.engine.resize();
  dispose() { window.removeEventListener("resize", this.resize); this.furnitureModels.dispose(); this.scene.dispose(); this.engine.dispose(); }
  setTool(tool: Tool) { this.tool = tool; }
  screenshot() { return this.canvas.toDataURL("image/png"); }
  private material(name: string, hex: string, alpha = 1) { const mat = new StandardMaterial(name, this.scene); mat.diffuseColor = Color3.FromHexString(hex); mat.roughness = .92; mat.specularColor = new Color3(.08,.07,.05); mat.alpha = alpha; return mat; }
  private makeMeadow() { const ground = MeshBuilder.CreateDisc("meadow", { radius: 15, tessellation: 64 }, this.scene); ground.rotation.x = Math.PI / 2; ground.position.y = -.15; ground.material = this.material("meadow-mat", "#9cab77"); ground.receiveShadows = true; const pink=this.material("flower-pink","#d79aaa");const gold=this.material("flower-gold","#eed79b");const leaf=this.material("meadow-leaf","#72855f");const leafLight=this.material("meadow-leaf-light","#87986b"); for (let i=0;i<64;i++) { const flower=MeshBuilder.CreateSphere(`flower-${i}`,{diameter:.07+(i%3)*.018,segments:6},this.scene); const angle=i*2.18; const r=3.3+(i%11)*.46; flower.position=new Vector3(Math.cos(angle)*r,-.07,Math.sin(angle)*r); flower.material=i%3===0?pink:gold; } for(let i=0;i<26;i++){const bush=MeshBuilder.CreateSphere(`bush-${i}`,{diameter:1,segments:9},this.scene);const angle=i*1.71;const r=4.6+(i%6)*.62;bush.scaling=new Vector3(.28+(i%3)*.08,.18+(i%2)*.08,.3+(i%4)*.05);bush.position=new Vector3(Math.cos(angle)*r,.02,Math.sin(angle)*r);bush.material=i%2?leaf:leafLight;this.shadow.addShadowCaster(bush);} }
  update(plan: PlanDocumentV1, activeFloorId: string, selectedId?: string) {
    this.activePlan = plan; this.activeFloorId = activeFloorId; this.selectedId = selectedId; for (const node of [...this.root.getChildren()]) node.dispose(false, false); this.furnitureFactory.resetMaterials();
    const activeIndex = plan.floors.findIndex((f) => f.id === activeFloorId); const floors = plan.camera.mode === "dollhouse" ? plan.floors : plan.floors.filter((f, i) => f.id === activeFloorId || (plan.camera.ghostBelow && i === activeIndex - 1));
    for (const floor of floors) this.buildFloor(plan, floor, floor.id !== activeFloorId);
    const activeFloor = plan.floors[activeIndex];
    if (activeFloor?.cells.length) { const xs=activeFloor.cells.map(c=>c.x); const zs=activeFloor.cells.map(c=>c.z); const scale=plan.gridSizeMm/1000; const width=(Math.max(...xs)-Math.min(...xs)+1)*scale; const depth=(Math.max(...zs)-Math.min(...zs)+1)*scale; this.camera.setTarget(new Vector3((Math.min(...xs)+Math.max(...xs)+1)*scale/2, activeFloor.elevationMm/1000+.3, (Math.min(...zs)+Math.max(...zs)+1)*scale/2)); this.camera.radius=Math.max(6,Math.max(width,depth)*1.8); }
    if (activeFloor && (this.tool === "paint" || this.tool === "wall" || this.tool === "stairs")) { const editGrid = MeshBuilder.CreateGround("edit-grid", { width: 18, height: 18, subdivisions: 1 }, this.scene); editGrid.parent = this.root; editGrid.position = new Vector3(6, activeFloor.elevationMm / 1000 - .055, 6); editGrid.material = this.material("edit-grid-mat", "#f7f1e3", .001); editGrid.isPickable = true; }
    if (plan.camera.mode === "top") { this.camera.alpha = -Math.PI / 2; this.camera.beta = .05; this.camera.radius = Math.max(7,this.camera.radius*.95); } else if (plan.camera.mode === "dollhouse") { this.camera.alpha = -Math.PI / 4; this.camera.beta = Math.PI / 2.8; this.camera.radius = Math.max(9,this.camera.radius*1.3); } else { this.camera.alpha = -Math.PI / 4; this.camera.beta = Math.PI / 3.1; }
    this.canvas.dataset.meshes = String(this.scene.meshes.length);
  }
  private buildFloor(plan: PlanDocumentV1, floor: FloorPlan, ghost: boolean) {
    const scale = plan.gridSizeMm / 1000; const elevation = floor.elevationMm / 1000; const tileMat = this.material(`tile-${floor.id}`, ghost ? "#d6cfb4" : "#d8bd91", ghost ? .22 : 1); const groutMat = this.material(`grout-${floor.id}`, "#a98e6b", ghost ? .15 : .65);
    for (const cell of floor.cells) { const tile = MeshBuilder.CreateBox(`cell:${cell.x}:${cell.z}`, { width: plan.camera.showGrid ? scale*.94 : scale, depth: plan.camera.showGrid ? scale*.94 : scale, height: .08 }, this.scene); tile.parent=this.root; tile.position=new Vector3((cell.x+.5)*scale,elevation,(cell.z+.5)*scale); tile.material=tileMat; tile.receiveShadows=true; tile.isPickable=!ghost; if(plan.camera.showGrid){ const grout=MeshBuilder.CreateBox(`grout:${cell.x}:${cell.z}`,{width:scale,depth:scale,height:.025},this.scene); grout.parent=this.root; grout.position=new Vector3((cell.x+.5)*scale,elevation-.035,(cell.z+.5)*scale); grout.material=groutMat; } }
    const boundaries = deriveBoundaryWalls(floor.cells); for (const wall of [...boundaries, ...floor.walls]) this.buildWall(wall.id, wall.ax*scale, wall.az*scale, wall.bx*scale, wall.bz*scale, elevation, ghost, floor.openings.some((o)=>o.wallKey===wall.id) ? floor.openings.find((o)=>o.wallKey===wall.id)?.kind : undefined);
    for (const stair of floor.stairs) this.buildStairs(stair.x/1000, stair.z/1000, stair.widthMm/1000, stair.lengthMm/1000, elevation, ghost);
    for (const item of plan.furniture.filter((f) => f.floorId === floor.id)) this.buildFurniture(item, elevation, ghost);
  }
  private buildWall(id: string, ax:number,az:number,bx:number,bz:number,y:number,ghost:boolean,opening?:"door"|"window") { const length=Math.hypot(bx-ax,bz-az); const horizontal=Math.abs(az-bz)<.001; const facesCamera=(horizontal&&bx>ax)||(!horizontal&&bz>az); const wall=MeshBuilder.CreateBox(`wall:${id}`,{width:length,height:1.65,depth:.1},this.scene); wall.parent=this.root; wall.position=new Vector3((ax+bx)/2,y+.84,(az+bz)/2); wall.rotation.y=-Math.atan2(bz-az,bx-ax); wall.material=this.material(`wall-mat-${id}`,"#eadbb7",ghost?.18:facesCamera?.22:.94); wall.isPickable=!ghost&&this.tool!=="erase"; wall.receiveShadows=true; this.shadow.addShadowCaster(wall); if(opening){ const marker=MeshBuilder.CreateBox(`opening:${id}`,{width:opening==="door"?.68:.8,height:opening==="door"?1.25:.68,depth:.12},this.scene); marker.parent=this.root; marker.position=wall.position.clone(); marker.position.y=y+(opening==="door"?.64:1.02); marker.rotation.y=wall.rotation.y; marker.material=this.material(`opening-mat-${id}`,opening==="door"?"#8a6046":"#9ec8c3",ghost?.15:facesCamera?.25:.95); marker.isPickable=!ghost&&this.tool!=="erase"; } }
  private addBox(parent:TransformNode,name:string,size:[number,number,number],pos:[number,number,number],mat:StandardMaterial){const box=MeshBuilder.CreateBox(name,{width:size[0],height:size[1],depth:size[2]},this.scene);box.parent=parent;box.position=new Vector3(...pos);box.material=mat;box.receiveShadows=true;this.shadow.addShadowCaster(box);return box;}
  private buildFurniture(item:FurniturePlacement,elevation:number,ghost:boolean){ const def=catalog.find((c)=>c.id===item.catalogId); if(!def)return; const node=new TransformNode(`item:${item.id}`,this.scene);node.parent=this.root;node.position=new Vector3(item.x/1000,elevation+.05,item.z/1000);node.rotation.y=item.rotation*Math.PI/180; const w=item.widthMm/1000,d=item.depthMm/1000,h=item.heightMm/1000; if(!this.furnitureModels.build(node,def,item,w,d,h,ghost))this.furnitureFactory.build(node,def,item,w,d,h,ghost); if(this.activePlan?.camera.showClearance&&!ghost){const clearance=this.addBox(node,"clearance",[w+.6,.018,d+.6],[0,.012,0],this.material(`clear-${item.id}`,"#d89a73",.22));clearance.isPickable=false;} node.getChildMeshes().forEach(m=>{if(m.name!=="clearance"){m.name=`item:${item.id}`;m.isPickable=!ghost;}if(item.id===this.selectedId){m.renderOutline=true;m.outlineColor=new Color3(.42,.57,.31);m.outlineWidth=.025;}}); }
  private buildStairs(x:number,z:number,w:number,d:number,y:number,ghost:boolean){const mat=this.material(`stairs-${x}-${z}`,"#a9815f",ghost?.18:1);for(let i=0;i<10;i++){const step=this.addBox(this.root,"stairs",[w,.12,d/10],[x,y+.06+i*.12,z+i*d/10],mat);step.isPickable=!ghost;}}
  private bindPointers(){let moved=false;this.scene.onPointerObservable.add((info)=>{if(info.type===PointerEventTypes.POINTERDOWN){moved=false;const pick=this.scene.pick(this.scene.pointerX,this.scene.pointerY);const name=pick?.pickedMesh?.name||"";if(name.startsWith("item:")&&this.tool==="select"){this.dragging=name.split(":")[1];this.callbacks.onSelect(this.dragging);this.camera.detachControl();}else if(name.startsWith("cell:")){const[,x,z]=name.split(":");this.callbacks.onCell(Number(x),Number(z));}else if(name==="edit-grid"&&pick?.pickedPoint&&this.activePlan){const grid=this.activePlan.gridSizeMm/1000;this.callbacks.onCell(Math.floor(pick.pickedPoint.x/grid),Math.floor(pick.pickedPoint.z/grid));}else if(name.startsWith("wall:")){this.callbacks.onWall(name.slice(5));}else this.callbacks.onSelect(undefined);}if(info.type===PointerEventTypes.POINTERMOVE&&this.dragging){const ray=this.scene.createPickingRay(this.scene.pointerX,this.scene.pointerY,null,this.camera);const planeY=(this.activePlan?.floors.find(f=>f.id===this.activeFloorId)?.elevationMm||0)/1000;const distance=(planeY-ray.origin.y)/ray.direction.y;if(distance>0){const p=ray.origin.add(ray.direction.scale(distance));this.callbacks.onMove(this.dragging,Math.round(p.x*1000/50)*50,Math.round(p.z*1000/50)*50);moved=true;}}if(info.type===PointerEventTypes.POINTERUP&&this.dragging){this.dragging=undefined;this.camera.attachControl(this.canvas,true);if(moved)this.update(this.activePlan!,this.activeFloorId,this.selectedId);}});}
}
