from pathlib import Path
import json
root=Path('.');old=json.loads((root/'tools/blender/modern_inventory.json').read_text(encoding='utf-8-sig'));new=[]
def add(id,name,cat,w,d,h,shape,kind,style,mount='floor',color='porcelain'):
 new.append(dict(id=id,name=name,category=cat,widthMm=w,depthMm=d,heightMm=h,shape=shape,type=kind,style=style,mount=mount,color=color,description='Original detailed '+name.lower()+' with modeled construction and independently editable finishes'))
for id,name,w,d,h,sty,col in [('curve-sofa','Arc curved sofa',2600,1100,800,'curve','ivory'),('track-sofa','Linear track-arm sofa',2300,950,820,'track','slate'),('channel-sofa','Como channel sofa',2400,1000,760,'channel','moss'),('metal-frame-sofa','Bauhaus metal-frame sofa',2200,900,790,'metal','ivory'),('low-modular-sofa','Cloudline modular sofa',2800,1050,720,'low','blue'),('corner-pit-sofa','Cinema pit sectional',3000,2100,760,'pit','charcoal')]:add(id,name,'Living',w,d,h,'seat','Sofas',sty,color=col)
for id,name,cat,w,d,h,sty,col in [('swivel-barrel-chair','Orbit swivel barrel chair','Living',850,830,790,'barrel','ivory'),('cantilever-lounge-chair','Chrome sling lounge chair','Living',730,850,800,'cantilever','charcoal'),('boucle-lounge-chair','Cloud boucle lounge chair','Living',870,850,780,'boucle','ivory'),('shell-lounge-chair','Sculpted shell lounge chair','Living',820,800,840,'shell','blue'),('mesh-dining-chair','Air mesh dining chair','Dining',520,570,820,'mesh','charcoal'),('cantilever-dining-chair','Cantilever dining chair','Dining',520,570,850,'cantilever','slate'),('upholstered-dining-chair','Curved upholstered dining chair','Dining',560,580,800,'barrel','moss'),('swivel-dining-chair','Petal swivel dining chair','Dining',580,600,820,'swivel','ivory'),('counter-saddle-stool','Metal saddle counter stool','Dining',460,430,660,'saddle','slate'),('upholstered-bar-stool','Upholstered swivel bar stool','Dining',500,520,980,'stool','ivory'),('hm-aeron-chair','Herman Miller Aeron · study','Office',685,685,1090,'aeron','charcoal'),('hm-embody-chair','Herman Miller Embody · study','Office',750,750,1080,'embody','blue'),('leather-executive-chair','Leather executive captain chair','Office',760,790,1200,'executive','charcoal'),('aluminum-softpad-chair','Aluminum soft-pad executive chair','Office',650,650,1060,'softpad','ivory')]:add(id,name,cat,w,d,h,'seat','Chairs & stools',sty,color=col)
for id,name,cat,w,d,h,kind,sty,col in [('travertine-coffee-table','Travertine arch coffee table','Living',1200,700,380,'Coffee tables','arch','stone'),('pill-coffee-table','Pill ceramic coffee table','Living',1300,650,360,'Coffee tables','pill','porcelain'),('sculpture-glass-table','Sculpture glass coffee table','Living',1150,800,410,'Coffee tables','sculpture','charcoal'),('lacquer-block-table','Lacquer block coffee table','Living',950,950,340,'Coffee tables','block','blue'),('steel-tray-coffee-table','Steel tray coffee table','Living',1100,650,400,'Coffee tables','tray','slate'),('marble-plinth-side-table','Marble plinth side table','Living',400,400,500,'Side tables','block','stone'),('chrome-cantilever-side-table','Chrome cantilever side table','Living',450,420,550,'Side tables','c','porcelain'),('ribbed-pedestal-side-table','Ribbed lacquer side table','Living',450,450,520,'Side tables','pedestal','blue'),('glass-disc-side-table','Smoked glass disc side table','Living',480,480,520,'Side tables','glass','charcoal'),('ceramic-oval-dining-table','Ceramic oval dining table','Dining',2200,1100,760,'Tables','oval','porcelain'),('sculpture-dining-table','Sculpture pedestal dining table','Dining',2200,1050,760,'Tables','sculpture','stone'),('glass-dining-table','Glass and chrome dining table','Dining',1800,900,750,'Tables','glass','charcoal'),('round-marble-dining-table','Round marble dining table','Dining',1250,1250,750,'Tables','pedestal','stone'),('breakfast-tulip-table','Tulip breakfast table','Dining',850,850,750,'Tables','tulip','porcelain'),('breakfast-square-table','Compact ceramic breakfast table','Dining',800,800,750,'Tables','square','blue'),('breakfast-counter-table','Slim breakfast counter','Dining',1400,550,930,'Tables','sled','slate')]:add(id,name,cat,w,d,h,'table',kind,sty,color=col)
for id,name,w,d,h,sty,col in [('floating-platform-bed','Halo floating platform bed',1900,2200,950,'floating','charcoal'),('channel-upholstered-bed','Channel upholstered king bed',2100,2250,1250,'channel','ivory'),('wingback-bed','Wingback upholstered bed',1800,2200,1250,'wing','blue'),('low-platform-bed','Low lacquer platform bed',1850,2250,850,'low','porcelain'),('metal-canopy-bed','Slim steel canopy bed',1750,2150,2100,'canopy','charcoal'),('storage-lift-bed','Upholstered storage bed',1750,2150,1100,'storage','moss')]:add(id,name,'Bedroom',w,d,h,'bed','Beds',sty,color=col)
for id,name,w,d,h,sty,col in [('white-steel-desk','White steel studio desk',1500,750,750,'steel','porcelain'),('curved-executive-desk','Curved executive desk',1800,850,760,'curved','slate'),('glass-studio-desk','Glass studio desk',1500,700,750,'glass','charcoal'),('dual-motor-desk','Dual-motor standing desk',1600,800,1100,'standing','porcelain')]:add(id,name,'Office',w,d,h,'table','Desks',sty,color=col)
for id,name,cat,w,d,h,kind,sty,col in [('floating-media-console','Floating lacquer media console','Living',2200,420,360,'TV & media','floating','porcelain'),('stone-media-console','Stone-front media console','Living',2100,450,500,'TV & media','stone','stone'),('modular-media-console','Modular aluminum media console','Living',2000,430,450,'TV & media','open','charcoal'),('lacquer-sideboard','Lacquer groove sideboard','Storage',1600,450,800,'Cabinets & storage','groove','blue'),('glass-display-cabinet','Smoked glass display cabinet','Storage',900,420,1800,'Cabinets & storage','glass','charcoal'),('modular-low-storage','Modular low storage cabinet','Storage',1200,400,650,'Cabinets & storage','open','porcelain'),('modern-bedside-drawer','Floating-look bedside drawer','Bedroom',550,450,520,'Side tables','drawer','moss')]:add(id,name,cat,w,d,h,'storage',kind,sty,'wall' if sty=='floating' else 'floor',col)
for id,name,w,d,h,sty,col in [('white-convertible-crib','White convertible crib',1400,760,900,'crib','porcelain'),('sage-nursery-dresser','Sage nursery changing dresser',1200,550,950,'changing','moss'),('cloud-nursery-glider','Cloud nursery glider',820,900,1050,'glider','ivory'),('kids-round-play-table','Pastel round play table',750,750,500,'playtable','blue'),('kids-shell-chair','Pastel shell play chair',360,380,540,'kidschair','lavender'),('kids-book-display','Front-facing kids book display',850,350,850,'bookrack','porcelain'),('modular-play-sofa','Modular foam play sofa',1500,750,580,'playsofa','moss'),('modern-bassinet','Modern mesh bassinet',920,560,820,'bassinet','ivory')]:add(id,name,'Bedroom',w,d,h,'seat' if sty in ['glider','kidschair','playsofa'] else 'storage','Baby & kids',sty,color=col)
for id,name,w,d,h,sty,col in [('smart-pet-feeder','Camera automatic pet feeder',190,330,340,'feeder','porcelain'),('dual-pet-feeder','Dual-bowl automatic feeder',420,320,350,'dualfeeder','charcoal'),('pet-water-fountain','Flow stainless pet fountain',260,260,180,'fountain','porcelain'),('rotating-cat-litter-box','Orbital self-cleaning litter box',560,680,750,'litter','porcelain'),('modern-cat-condo','Sculptural cat condo',600,550,1350,'catcondo','ivory'),('upholstered-pet-sofa','Tailored pet sofa',900,650,350,'petsofa','blue')]:add(id,name,'Decor',w,d,h,'decor','Pet furniture',sty,color=col)
for id,name,w,d,h,sty,col in [('slab-drawer-base','Matte slab drawer base',600,620,910,'drawers','porcelain'),('navy-base-cabinet','Navy handleless base cabinet',900,620,910,'slab','blue'),('sage-pantry-cabinet','Sage appliance pantry',900,650,2200,'pantry','moss'),('ribbed-glass-upper','Ribbed glass upper cabinet',900,350,800,'glass','charcoal'),('open-metal-upper','Open metal wall cabinet',800,350,700,'open','slate'),('corner-kitchen-base','Modern corner base cabinet',1000,1000,910,'corner','porcelain'),('waterfall-kitchen-island','Waterfall stone kitchen island',2400,1000,940,'waterfall','porcelain'),('ribbed-kitchen-island','Ribbed lacquer kitchen island',2100,1000,940,'ribbed','moss'),('steel-prep-island','Stainless preparation island',1800,800,920,'steel','slate'),('modern-double-sink-counter','Double sink worktop cabinet',1500,650,930,'sink','porcelain')]:add(id,name,'Kitchen',w,d,h,'storage','Counters & islands' if 'island' in id or 'sink' in id else 'Kitchen cabinets',sty,'wall' if 'upper' in id else 'floor',col)
for id,name,w,d,h,sty in [('brick-hypercar','Brick-built hypercar',320,150,90,'hypercar'),('brick-formula-car','Brick-built formula car',380,160,95,'formula'),('brick-rally-car','Brick-built rally coupe',270,140,120,'rally'),('brick-ocean-liner','Brick-built ocean liner',600,100,180,'liner'),('brick-sailing-ship','Brick-built sailing frigate',420,160,380,'frigate'),('brick-space-cruiser','Brick-built star cruiser',400,220,120,'starship'),('ellen-display-figurine','Ellen · original fan figurine',170,140,300,'ellen'),('march7-display-figurine','March 7th · original fan figurine',160,140,300,'march'),('raiden-display-figurine','Raiden · original fan figurine',160,140,310,'raiden')]:add(id,name,'Decor',w,d,h,'decor','Collectibles',sty,'surface','blue')
for i,name in enumerate(['Skyrail at dusk','Moonlit observatory','Neon summer arcade']):add('anime-landscape-'+str(i+1),name+' · landscape','Decor',1200,35,650,'decor','Wall art & boards','poster'+str(i),'wall','charcoal')
# Sonos current product forms; each item is independently placeable, not a bundled room system.
for id,name,w,d,h,sty,mount in [('arc-ultra','Arc Ultra',1178,110.6,75,'soundbar','surface'),('beam-ultra','Beam Ultra',750,105,63,'soundbar','surface'),('beam-gen2','Beam (Gen 2)',651,100,68,'soundbar','surface'),('ray','Ray',557,93,70,'soundbar','surface'),('era-100','Era 100',120,130.5,182.5,'oval','surface'),('era-100-sl','Era 100 SL',120,130.5,182.5,'oval','surface'),('era-300','Era 300',260,160,185,'hourglass','surface'),('five','Five',364,154,203,'speaker','surface'),('move-2','Move 2',160,127,241,'portable','surface'),('roam-2','Roam 2',62,60,168,'roam','surface'),('play','Play',112.5,76.7,192.3,'portable','surface'),('sub-4','Sub 4',402,158,389,'subhole','floor'),('sub-mini','Sub Mini',230,230,305,'submini','floor'),('amp','Amp',217,217,64,'amp','surface'),('port','Port',138,138,41,'port','surface'),('ace','Ace',160,85,191,'headphones','surface'),('ace-ultra','Ace Ultra',163,90.8,193,'headphones','surface'),('architectural-wall','Architectural in-wall speaker',199.9,89,298.7,'wall','wall'),('architectural-ceiling','Architectural 6-inch ceiling speaker',235.5,235.5,120.3,'ceiling','ceiling'),('architectural-outdoor','Architectural outdoor speaker',191,199,329.2,'outdoor','wall')]:add('sonos-'+id,'Sonos '+name,'Living',w,d,h,'device','Speakers & audio',sty,mount,'charcoal')
add('sonos-era-100-pro','Sonos Era 100 Pro','Living',120,130.5,182.5,'device','Speakers & audio','oval','surface','charcoal')
add('sonos-amp-multi','Sonos Amp Multi','Living',436.8,265.2,64.5,'device','Speakers & audio','amp','surface','charcoal')
add('sonos-ceiling-8','Sonos Architectural 8-inch ceiling speaker','Living',283.5,283.5,135,'device','Speakers & audio','ceiling','ceiling','porcelain')
rows=[[r['id'],r['name'],r['category'],r['widthMm'],r['depthMm'],r['heightMm'],r['shape'],r['description'],r['mount'],r['type']] for r in new]
(root/'src/modernExpansion.json').write_text(json.dumps(rows,indent=2)+'\n')
types={'Sofas','Chairs & stools','Coffee tables','Side tables','Beds','Baby & kids','Cabinets & storage','Tables','Desks','Collectibles','Kitchen cabinets','Counters & islands','Dressers & chests','Closet modules','Pet furniture','Speakers & audio'}
selected=[r for r in old if r['type'] in types or r['id'] in ['tv-stand','slatted-tv-stand','open-media-bench','cane-tv-stand','pet-bed','open-pantry']]
for r in selected:
 r['style']=r['id'];r['color']=['porcelain','slate','moss','blue','ivory'][sum(map(ord,r['id']))%5]
 if r['id']=='nesting-tables':r['retired']=True
manifest={'revisited':selected,'added':new};(root/'tools/blender/modern_manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
variants={'moss':'sage','porcelain':'cream','ivory':'cream','blue':'navy','slate':'ink','charcoal':'ink','stone':'cream','lavender':'rose'}
(root/'src/modernDefaults.json').write_text(json.dumps({r['id']:variants[r['color']] for r in selected+new},indent=2)+'\n')
print(len(selected),'existing pieces,',len(new),'new models')
