import {parseRemixSnapshot,remixId,remixText,REMIX_LIMITS,remixTags} from '../src/remixSnapshot.ts';
import {makeRemixThumbnail} from '../src/remixThumbnail.ts';
import {encodeStoredPlan,decodeStoredPlan} from './plan-storage.js';
const headers={'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Vary':'Cookie, Authorization'};
const json=(value,status=200)=>new Response(JSON.stringify(value),{status,headers}),fail=(error,status)=>json({error},status),unavailable=()=>fail('This arrangement is unavailable, expired or withdrawn.',404);
const hash=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),b=>b.toString(16).padStart(2,'0')).join('');
const token=()=>btoa(String.fromCharCode(...crypto.getRandomValues(new Uint8Array(32)))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
const secretHash=async request=>{const s=/^Bearer ([A-Za-z0-9_-]{43})$/.exec(request.headers.get('authorization')??'');return s?hash(s[1]):null;};
const exact=(v,fields)=>!!v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).every(k=>fields.includes(k));
const integer=(n,min=1,max=1_000_000)=>Number.isSafeInteger(n)&&n>=min&&n<=max;
/** Dispatcher identities only. Missing/malformed config grants nobody curator permissions. */
function curators(env){try{const ids=JSON.parse(env.IDEAS_CURATOR_IDS??'');return Array.isArray(ids)&&ids.length>0&&ids.length<=20&&new Set(ids).size===ids.length&&ids.every(id=>typeof id==='string'&&id.length>0&&id.length<=200&&!/[\u0000-\u0020\u007f]/.test(id))?ids:null;}catch{return null;}}
async function body(request){const reader=request.body?.getReader();if(!reader)throw Error('Missing data');let size=0;const chunks=[];for(;;){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>REMIX_LIMITS.bytes+2000){await reader.cancel();throw Error('Too large');}chunks.push(value);}const bytes=new Uint8Array(size);let offset=0;for(const c of chunks){bytes.set(c,offset);offset+=c.length;}return JSON.parse(new TextDecoder().decode(bytes));}
const shareSummary=r=>({id:r.id,projectId:r.project_id,revision:r.current_revision,accessVersion:r.access_version,expiresAt:r.expires_at,revoked:r.revoked_at!==null,createdAt:r.created_at});
const ideaSummary=r=>({id:r.id,shareId:r.share_id,revision:r.revision,state:r.state,stateVersion:r.state_version,createdAt:r.created_at,updatedAt:r.updated_at,...(r.moderation_note?{moderationNote:r.moderation_note}:{})});
const visible='s.revoked_at IS NULL AND s.expires_at > ? AND s.current_revision=i.revision';
const publicJoin='FROM idea_submissions i JOIN remix_shares s ON s.id=i.share_id JOIN remix_revisions v ON v.share_id=s.id AND v.revision=i.revision';
const card=r=>({id:r.id,revision:r.revision,title:r.title,creator:r.creator,description:r.description,kind:r.kind,allowCopy:!!r.allow_copy,tags:JSON.parse(r.tags),thumbnail:JSON.parse(r.thumbnail),createdAt:r.created_at});
const ownerShare=(db,id,owner)=>db.prepare('SELECT * FROM remix_shares WHERE id=? AND owner_id=?').bind(id,owner).first();
async function sourceView(db,id,revision,key,now){return key?db.prepare('SELECT v.document,s.current_revision,s.expires_at FROM remix_revisions v JOIN remix_shares s ON s.id=v.share_id WHERE s.id=? AND v.revision=? AND s.current_revision=? AND s.token_hash=? AND s.revoked_at IS NULL AND s.expires_at>?').bind(id,revision,revision,key,now).first():null;}
function pageInput(url){const q=(url.searchParams.get('q')??'').trim(),tag=url.searchParams.get('tag')??'',cursor=url.searchParams.get('cursor');if(q.length>80||/[\u0000-\u001f\u007f]/.test(q)||tag&&!remixTags.includes(tag))throw Error();let before=null;if(cursor){const m=/^(\d{1,16})_([a-zA-Z0-9-]{1,100})$/.exec(cursor);if(!m||!Number.isSafeInteger(Number(m[1])))throw Error();before={time:Number(m[1]),id:m[2]};}return {q,tag,before};}
export async function remixGalleryApi(request,env,clock=Date.now){
 const url=new URL(request.url),isShare=url.pathname==='/api/remix'||url.pathname.startsWith('/api/remix/'),isIdeas=url.pathname==='/api/ideas'||url.pathname.startsWith('/api/ideas/');if(!isShare&&!isIdeas)return null;
 const path=url.pathname.slice(isShare?10:10),owner=request.headers.get('oai-authenticated-user-id'),db=env.DB,admins=curators(env),curator=!!owner&&!!admins?.includes(owner),now=clock();
 if(path==='/status'&&request.method==='GET')return json({available:!!db,signedIn:!!owner,moderationConfigured:!!db&&!!admins,isCurator:!!db&&curator});
 if(!db)return fail('Online sharing is unavailable. Original ideas and local room packages still work.',503);
 if(['POST','DELETE'].includes(request.method)){if(request.headers.get('origin')!==url.origin||request.headers.get('sec-fetch-site')==='cross-site')return fail('Use Share and Ideas from this website.',403);if(!request.headers.get('content-type')?.toLowerCase().startsWith('application/json'))return fail('Use JSON data.',415);}
 if(isShare){
  const match=/^\/([A-Za-z0-9_-]{1,100})(?:\/(view|revisions|access))?$/.exec(path);if(path&&!match)return fail('Not found.',404);const id=match?.[1],action=match?.[2];
  if(action==='view'&&request.method==='GET'){const revision=Number(url.searchParams.get('revision')),key=await secretHash(request);if(!integer(revision,1,10))return unavailable();const row=await sourceView(db,id,revision,key,now);if(!row)return unavailable();const snapshot=parseRemixSnapshot(await decodeStoredPlan(row.document));if(!await sourceView(db,id,revision,key,clock()))return unavailable();return json({id,revision,snapshot});}
  if(!owner)return fail('Sign in to manage your arrangement links.',401);
  if(!path&&request.method==='GET'){const projectId=url.searchParams.get('projectId');if(!remixId(projectId))return fail('Choose a project.',400);return json({shares:(await db.prepare('SELECT * FROM remix_shares WHERE owner_id=? AND project_id=? ORDER BY created_at DESC LIMIT 40').bind(owner,projectId).all()).results.map(shareSummary)});}
  let owned;if(id){owned=await ownerShare(db,id,owner);if(!owned)return unavailable();}
  if(id&&!action&&request.method==='GET'){const r=await db.prepare('SELECT document FROM remix_revisions WHERE share_id=? AND revision=?').bind(id,owned.current_revision).first();return json({share:shareSummary(owned),snapshot:parseRemixSnapshot(await decodeStoredPlan(r.document)),submissions:(await db.prepare('SELECT * FROM idea_submissions WHERE share_id=? AND owner_id=? ORDER BY created_at DESC LIMIT 10').bind(id,owner).all()).results.map(ideaSummary)});}
  if(id&&!action&&request.method==='DELETE'){let data;try{data=await body(request);if(!exact(data,['expectedVersion'])||!integer(data.expectedVersion))throw Error();}catch{return fail('Use the current link version.',400);}const result=await db.prepare('DELETE FROM remix_shares WHERE id=? AND owner_id=? AND access_version=?').bind(id,owner,data.expectedVersion).run();return result.meta.changes?json({deleted:true}):fail('The link changed. Refresh before deleting.',409);}
  if(id&&action==='access'&&request.method==='POST'){let data;try{data=await body(request);if(!exact(data,['expectedVersion','action'])||!integer(data.expectedVersion)||data.action!=='revoke')throw Error();}catch{return fail('Choose revoke and the current access version.',400);}const result=await db.prepare('UPDATE remix_shares SET revoked_at=?,token_hash=NULL,access_version=access_version+1 WHERE id=? AND owner_id=? AND access_version=?').bind(now,id,owner,data.expectedVersion).run();return result.meta.changes?json({revoked:true,accessVersion:data.expectedVersion+1}):fail('This link changed. Refresh before revoking.',409);}
  if(request.method==='POST'&&(!path||action==='revisions')){let data,snapshot,expiresAt;try{data=await body(request);if(!exact(data,['projectId','snapshot','expiryHours','expectedRevision','expectedAccessVersion','rightsConfirmed'])||data.rightsConfirmed!==true||!integer(data.expiryHours,1,2160)||!id&&!remixId(data.projectId)||id&&(!integer(data.expectedRevision,1,9)||!integer(data.expectedAccessVersion)))throw Error();snapshot=parseRemixSnapshot(data.snapshot);expiresAt=now+data.expiryHours*3600000;}catch{return fail('Check the exact snapshot, creator rights, copying permission and expiry.',400);}
   const document=await encodeStoredPlan(snapshot),thumbnail=JSON.stringify(makeRemixThumbnail(snapshot)),operation=crypto.randomUUID(),shareId=id??crypto.randomUUID(),revision=id?data.expectedRevision+1:1,key=token();
   const first=id?db.prepare('UPDATE remix_shares SET current_revision=?,access_version=access_version+1,publication_id=?,expires_at=?,token_hash=? WHERE id=? AND owner_id=? AND current_revision=? AND current_revision<10 AND access_version=? AND revoked_at IS NULL').bind(revision,operation,expiresAt,await hash(key),id,owner,data.expectedRevision,data.expectedAccessVersion):db.prepare('INSERT INTO remix_shares(id,owner_id,project_id,current_revision,created_at,expires_at,token_hash,publication_id) SELECT ?,?,?,1,?,?,?,? WHERE (SELECT COUNT(*) FROM remix_shares WHERE owner_id=?)<40').bind(shareId,owner,data.projectId,now,expiresAt,await hash(key),operation,owner);
   const insert=db.prepare('INSERT INTO remix_revisions(share_id,revision,created_at,document,title,creator,description,kind,allow_copy,tags,thumbnail) SELECT id,current_revision,?,?,?,?,?,?,?,?,? FROM remix_shares WHERE id=? AND owner_id=? AND current_revision=? AND publication_id=?').bind(now,document,snapshot.title,snapshot.creator,snapshot.description,snapshot.kind,snapshot.allowCopy?1:0,JSON.stringify(snapshot.tags),thumbnail,shareId,owner,revision,operation);
   const results=await db.batch([first,insert]);if(!results[0].meta.changes)return fail('A newer revision exists or your link limit was reached. Refresh before publishing.',409);return json({share:shareSummary(await ownerShare(db,shareId,owner)),token:key},201);
  }
  return fail('Method not allowed.',405);
 }
 if(!admins&&request.method==='GET'&&path!=='/mine'&&path!=='/moderation'&&path!=='/reports')return fail('The community gallery is closed until a curator is configured. Original local ideas are still available.',503);
 if(path===''&&request.method==='GET'){
  let filter;try{filter=pageInput(url);}catch{return fail('Use a valid search, tag or page cursor.',400);}const terms=["i.state='approved'",visible],args=[now];if(filter.q){terms.push('(instr(lower(v.title),lower(?))>0 OR instr(lower(v.description),lower(?))>0)');args.push(filter.q,filter.q);}if(filter.tag){terms.push('EXISTS(SELECT 1 FROM json_each(v.tags) WHERE value=?)');args.push(filter.tag);}if(filter.before){terms.push('(i.created_at<? OR (i.created_at=? AND i.id<?))');args.push(filter.before.time,filter.before.time,filter.before.id);}
  const rows=(await db.prepare('SELECT i.id,i.revision,i.created_at,v.title,v.creator,v.description,v.kind,v.allow_copy,v.tags,v.thumbnail '+publicJoin+' WHERE '+terms.join(' AND ')+' ORDER BY i.created_at DESC,i.id DESC LIMIT 13').bind(...args).all()).results,items=rows.slice(0,12),last=items.at(-1);return json({items:items.map(card),nextCursor:rows.length>12&&last?last.created_at+'_'+last.id:null});
 }
 if(path==='/mine'&&request.method==='GET'){if(!owner)return fail('Sign in to see your submissions.',401);return json({submissions:(await db.prepare('SELECT * FROM idea_submissions WHERE owner_id=? ORDER BY created_at DESC LIMIT 40').bind(owner).all()).results.map(ideaSummary)});}
 if(path==='/moderation'&&request.method==='GET'){if(!curator)return fail('Curator access is not available for this account.',403);let filter;try{filter=pageInput(url);}catch{return fail('Invalid page.',400);}const cursor=filter.before,args=[now];let after='';if(cursor){after=' AND (i.created_at<? OR (i.created_at=? AND i.id<?))';args.push(cursor.time,cursor.time,cursor.id);}const rows=(await db.prepare("SELECT i.*,v.title,v.creator,v.description,v.kind,v.allow_copy,v.tags,v.thumbnail "+publicJoin+" WHERE i.state='pending' AND "+visible+after+' ORDER BY i.created_at DESC,i.id DESC LIMIT 13').bind(...args).all()).results,items=rows.slice(0,12),last=items.at(-1);return json({items:items.map(r=>({...card(r),...ideaSummary(r)})),nextCursor:rows.length>12&&last?last.created_at+'_'+last.id:null});}
 if(path==='/reports'&&request.method==='GET'){if(!curator)return fail('Curator access is not available for this account.',403);return json({reports:(await db.prepare('SELECT id,idea_id AS ideaId,reason,note,created_at AS createdAt FROM idea_reports WHERE resolved=0 ORDER BY created_at,id LIMIT 50').bind().all()).results});}
 const reportMatch=/^\/reports\/([A-Za-z0-9_-]{1,100})$/.exec(path);if(reportMatch&&request.method==='POST'){if(!curator)return fail('Curator access is not available for this account.',403);let data;try{data=await body(request);if(!exact(data,['resolved'])||data.resolved!==true)throw Error();}catch{return fail('Choose to resolve the report after reviewing it.',400);}const result=await db.prepare('UPDATE idea_reports SET resolved=1 WHERE id=?').bind(reportMatch[1]).run();return result.meta.changes?json({resolved:true}):unavailable();}
 if(path==='/submit'&&request.method==='POST'){
  if(!owner)return fail('Sign in to submit an arrangement.',401);if(!admins)return fail('The community submission queue is closed until a curator is configured. Original ideas remain available.',503);let data;try{data=await body(request);if(!exact(data,['shareId','revision','publicConfirmed','rightsConfirmed'])||!remixId(data.shareId)||!integer(data.revision,1,10)||data.publicConfirmed!==true||data.rightsConfirmed!==true)throw Error();}catch{return fail('Explicitly confirm publishing this exact revision and its content rights.',400);}const id=crypto.randomUUID(),result=await db.prepare("INSERT INTO idea_submissions(id,share_id,revision,owner_id,state,created_at,updated_at) SELECT ?,id,current_revision,owner_id,'pending',?,? FROM remix_shares WHERE id=? AND owner_id=? AND current_revision=? AND revoked_at IS NULL AND expires_at>? AND (SELECT COUNT(*) FROM idea_submissions WHERE owner_id=? AND state='pending')<10 AND (SELECT COUNT(*) FROM idea_submissions WHERE owner_id=? AND created_at>?)<20 AND (SELECT COUNT(*) FROM idea_submissions)<1000 ON CONFLICT(share_id,revision) DO NOTHING").bind(id,now,now,data.shareId,owner,data.revision,now,owner,owner,now-86400000).run();if(!result.meta.changes)return fail('This revision changed, was already submitted, or a submission limit was reached. Refresh before retrying.',409);return json({submission:ideaSummary(await db.prepare('SELECT * FROM idea_submissions WHERE id=? AND owner_id=?').bind(id,owner).first())},201);
 }
 const match=/^\/([A-Za-z0-9_-]{1,100})(?:\/(withdraw|moderate|report|inspect))?$/.exec(path);if(!match)return fail('Not found.',404);const id=match[1],action=match[2];
 if(!action&&request.method==='GET'){const row=await db.prepare("SELECT i.id,i.revision,v.document "+publicJoin+" WHERE i.id=? AND i.state='approved' AND "+visible).bind(id,now).first();if(!row)return unavailable();const snapshot=parseRemixSnapshot(await decodeStoredPlan(row.document));const current=await db.prepare("SELECT i.id "+publicJoin+" WHERE i.id=? AND i.revision=? AND i.state='approved' AND "+visible).bind(id,row.revision,clock()).first();return current?json({id,revision:row.revision,snapshot}):unavailable();}
 if(action==='inspect'&&request.method==='GET'){if(!curator)return fail('Curator access is not available for this account.',403);const row=await db.prepare('SELECT i.*,v.document '+publicJoin+' WHERE i.id=? AND '+visible).bind(id,now).first();if(!row)return unavailable();return json({submission:ideaSummary(row),snapshot:parseRemixSnapshot(await decodeStoredPlan(row.document))});}
 if(!owner)return fail('Sign in to manage submissions or report an idea.',401);
 if(action==='withdraw'&&request.method==='POST'){let data;try{data=await body(request);if(!exact(data,['expectedVersion'])||!integer(data.expectedVersion))throw Error();}catch{return fail('Use the current submission version.',400);}const result=await db.prepare("UPDATE idea_submissions SET state='withdrawn',state_version=state_version+1,updated_at=? WHERE id=? AND owner_id=? AND state_version=? AND state IN ('pending','approved','rejected','removed')").bind(now,id,owner,data.expectedVersion).run();return result.meta.changes?json({withdrawn:true}):fail('Submission changed or is unavailable. Refresh first.',409);}
 if(action==='moderate'&&request.method==='POST'){if(!curator)return fail('Curator access is not available for this account.',403);let data;try{data=await body(request);if(!exact(data,['expectedVersion','revision','decision','note'])||!integer(data.expectedVersion)||!integer(data.revision,1,10)||!['approve','reject','remove'].includes(data.decision))throw Error();data.note=remixText(data.note,400,data.decision!=='approve');}catch{return fail('Choose a decision for the exact inspected version, with a reason for removal or rejection.',400);}const state={approve:'approved',reject:'rejected',remove:'removed'}[data.decision],from=data.decision==='remove'?'approved':'pending';const result=await db.prepare('UPDATE idea_submissions SET state=?,state_version=state_version+1,updated_at=?,moderator_id=?,moderation_note=? WHERE id=? AND revision=? AND state_version=? AND state=? AND EXISTS(SELECT 1 FROM remix_shares s WHERE s.id=idea_submissions.share_id AND s.current_revision=idea_submissions.revision AND s.revoked_at IS NULL AND s.expires_at>?)').bind(state,now,owner,data.note,id,data.revision,data.expectedVersion,from,clock()).run();return result.meta.changes?json({state,stateVersion:data.expectedVersion+1}):fail('The owner changed or withdrew this revision, or another decision won. Inspect it again.',409);}
 if(action==='report'&&request.method==='POST'){let data;try{data=await body(request);if(!exact(data,['requestId','reason','note'])||!remixId(data.requestId)||!['privacy','rights','unsafe','spam','other'].includes(data.reason))throw Error();data.note=remixText(data.note,500,data.reason==='other');}catch{return fail('Choose a report reason and a short plain-text explanation.',400);}const existing=await db.prepare('SELECT idea_id,reason,note FROM idea_reports WHERE reporter_id=? AND request_id=?').bind(owner,data.requestId).first();if(existing)return existing.idea_id===id&&existing.reason===data.reason&&existing.note===data.note?json({received:true}):fail('This report identity was already used.',409);const result=await db.prepare("INSERT INTO idea_reports(id,idea_id,reporter_id,request_id,reason,note,created_at) SELECT ?,i.id,?,?,?,?,? "+publicJoin+" WHERE i.id=? AND i.state='approved' AND "+visible+' AND (SELECT COUNT(*) FROM idea_reports WHERE reporter_id=? AND created_at>?)<5 AND (SELECT COUNT(*) FROM idea_reports WHERE idea_id=?)<100 ON CONFLICT(reporter_id,request_id) DO NOTHING').bind(crypto.randomUUID(),owner,data.requestId,data.reason,data.note,now,id,clock(),owner,now-3600000,id).run();return result.meta.changes?json({received:true},201):fail('The idea is unavailable or the report limit was reached. Try again later.',429);}
 return fail('Method not allowed.',405);
}
