import { Welcome } from "./Welcome";
import {useAppearance} from './useWelcomeTheme';
import { BlueprintControls } from "./BlueprintControls";
import {SlidingDoorSettings} from './SlidingDoorSettings';
import {slidingDoorIds} from './homeCollection';
import {TurnButton,FurnitureTurnButton} from "./TurnButton";
import { useEffect, useRef, useState, type PointerEvent as ReactPointerEvent } from "react";
import { Bathtub, Armchair, ArrowClockwise, ArrowCounterClockwise, Bed, Books, Buildings, Camera, Chair, Check, Copy, Door, DownloadSimple, Eye, FileArrowUp, FloppyDisk, FrameCorners, GridFour, HandGrabbing, Info, Lamp, MagnifyingGlass, PaintBrush, Plant, Plus, Ruler, ShareNetwork, SpeakerHigh, SpeakerSlash, SquaresFour, Stairs, Table, Trash, Wall, X } from "@phosphor-icons/react";
import { catalog, isKitchenWall, isCeilingMounted, isWallMounted, isWindow, isDoor, isStairs, isWallOpening, isSurfaceMounted, hasModelPreview, defaultMountHeight, variants } from "./catalog";
import { createSamplePlan, encodeShare, formatLength, furnitureOverlaps, parsePlan, rectangleCells, serializePlan, uid } from "./domain";
import { snapWindow, windowProblem, windowRotation } from "./windows";
import type { PlacementPoint } from "./tabletop";
import { floorRects, measuredRegion, type MeasuredRegion } from "./floorGeometry";
import { fitStair, stairWarnings } from "./building";
import { OutdoorSettings } from "./OutdoorSettings";
import { TabletopPlacement } from "./TabletopPlacement";
import { ShelfPlacement } from "./ShelfPlacement";
import { KitchenDetails, BacksplashShortcut } from "./KitchenDetails";
import { isBacksplash } from "./kitchenCatalog";
import { MeasuredRoom } from "./MeasuredRoom";
import { StairSettings } from "./StairSettings";
import { SceneController } from "./scene/SceneController";
import { CatalogLibrary as Catalog } from "./CatalogLibrary";
import { MaterialColors } from "./MaterialColors";
import "./expansion.css";
import { ProjectLibrary } from "./ProjectLibrary";
import { AgentControls, AgentPreviewNotice } from "./AgentControls";
import { useAgent } from "./webmcp";
import { FloorBar } from "./FloorBar";
import { WallVisibilityControl } from "./WallVisibilityControl";
import { savePlan, usePlanner } from "./store";
import { countertopFinishes, defaultCountertopFinish, doorFinishes, floorFinishes, supportsCountertopFinish, wallFinishes } from "./surfaces";
import type { CatalogItem, FurniturePlacement, PlanDocumentV1, TileCell, Tool, Units } from "./types";

const tools: Array<{ id: Tool; label: string; icon: typeof Armchair }> = [
  { id: "select", label: "Arrange", icon: Armchair }, { id: "paint", label: "Paint tiles", icon: PaintBrush }, { id: "erase", label: "Erase", icon: Trash },
  { id: "wall", label: "Inside wall", icon: Wall }, { id: "door", label: "Inside door", icon: Door }, { id: "window", label: "Window", icon: FrameCorners }, { id: "stairs", label: "Stairs", icon: Stairs },
];

function download(name: string, content: string, type: string) { const anchor = document.createElement("a"); anchor.href = URL.createObjectURL(new Blob([content], { type })); anchor.download = name; anchor.click(); URL.revokeObjectURL(anchor.href); }

function SetupDialog({ onDone }: { onDone(): void }) {
  const replacePlan = usePlanner((s) => s.replacePlan); const [name, setName] = useState("My cozy apartment"); const [units, setUnits] = useState<Units>("imperial"); const [width, setWidth] = useState(14); const [depth, setDepth] = useState(10); const [floorHeight,setFloorHeight]=useState(8); const [tileSize,setTileSize]=useState(1);
  const create = () => { const plan = createSamplePlan(name, units); const grid = units === "imperial" ? tileSize*304.8 : tileSize*1000; const heightMm=units==="imperial"?floorHeight*304.8:floorHeight*1000; const floor = { ...plan.floors[0], id: uid(), name: "Ground floor", heightMm, cells: rectangleCells(Math.max(3, width), Math.max(3, depth)) }; replacePlan({ ...plan, gridSizeMm: grid, floors: [floor], furniture: [] }); onDone(); };
  return <div className="modal-backdrop"><section className="setup-card" role="dialog" aria-modal="true" aria-labelledby="setup-title">
    <div className="setup-art"><img src="/assets/nook-nest-icon.png" alt="A tiny handcrafted room with an armchair and plant" /></div>
    <div className="setup-content"><span className="eyebrow">A little space for big ideas</span><h1 id="setup-title">Welcome to Nook &amp; Nest</h1><p>Sketch your apartment to scale, then make it feel like home. Everything saves quietly in this browser.</p>
      <label>Project name<input value={name} onChange={(e)=>setName(e.target.value)} /></label>
      <div className="segmented" aria-label="Measurement units"><button className={units==="imperial"?"active":""} onClick={()=>setUnits("imperial")}>Feet &amp; inches</button><button className={units==="metric"?"active":""} onClick={()=>setUnits("metric")}>Metric</button></div>
      <div className="setup-dimensions"><label>Width in tiles<input type="number" min="3" max="40" value={width} onChange={(e)=>setWidth(Number(e.target.value))} /></label><span>×</span><label>Depth in tiles<input type="number" min="3" max="40" value={depth} onChange={(e)=>setDepth(Number(e.target.value))} /></label></div>
      <div className="setup-dimensions secondary"><label>Tile size ({units==="imperial"?"feet":"metres"})<input type="number" min={units==="imperial"?.5:.1} step={units==="imperial"?.5:.05} value={tileSize} onChange={(e)=>setTileSize(Number(e.target.value))} /></label><span/><label>Floor height ({units==="imperial"?"feet":"metres"})<input type="number" min={units==="imperial"?6:1.8} step={units==="imperial"?.5:.1} value={floorHeight} onChange={(e)=>setFloorHeight(Number(e.target.value))}/></label></div>
      <div className="tile-note"><Ruler size={20} /><span>Each tile is <strong>{units==="imperial"?`${tileSize} foot`: `${tileSize} metre`}</strong>. Furniture can use finer measurements.</span></div>
      <button className="primary large" onClick={create}>Start decorating <Check weight="bold" /></button>
    </div>
  </section></div>;
}


function RoomFinishes() {
  const state=usePlanner(); const floor=state.plan.floors.find((item)=>item.id===state.activeFloorId)!; const [scope,setScope]=useState<"whole"|"sections">("sections");
  const chooser=(label:string,kind:"floorFinishId"|"wallFinishId",finishes:typeof wallFinishes,current:string|undefined)=><section className="finish-section"><div className="finish-heading"><div><span>{label}</span><small>{kind==="wallFinishId"?"Paint · masonry · wallpaper":"Wood · laminate · tile · carpet"}</small></div></div><div className="finish-grid">{finishes.map((finish)=><button key={finish.id} className={current===finish.id?"selected":""} onClick={()=>scope==="whole"&& !state.selectedWallId?state.setFloorFinish(kind,finish.id):kind==="wallFinishId"&&state.selectedWallId?state.finishWall(state.selectedWallId,finish.id):state.setSurfaceBrush(kind==="floorFinishId"?"floor-finish":"wall-finish",finish.id)} aria-label={`${label}: ${finish.name}`} title={`${finish.name} — ${finish.family}`}><span className="finish-thumb" style={{backgroundImage:`url(${finish.texture})`}}/><span className="finish-name">{finish.name}<small>{finish.family}</small></span>{current===finish.id&&<Check size={14} weight="bold"/>}</button>)}</div></section>;
  return <aside className="inspector-panel finishes-panel"><div className="panel-heading"><div><span className="eyebrow">Room finishes</span><h2>{floor.name}</h2></div><Buildings size={24} weight="duotone"/></div><MeasuredRoom/><OutdoorSettings/><BacksplashShortcut/><p className="finish-intro">Select a wall plate, then choose its finish. Floor finishes can be painted in regions. Every change can be undone.</p><div className="segmented" role="group" aria-label="Finish area"><button className={scope==="sections"?"active":""} onClick={()=>setScope("sections")}>Paint sections</button><button className={scope==="whole"?"active":""} onClick={()=>{setScope("whole");state.setTool("select")}}>Whole layer</button></div>{(state.tool==="floor-finish"||state.tool==="wall-finish")&&<p className="finish-intro">{state.tool==="floor-finish"?"Drag a floor rectangle, then press ✓ to apply the selected finish.":state.selectedWallId?"Wall plate selected — choose a wall finish below.":"Click a wall to select its whole straight plate, then choose a finish below."}<button onClick={()=>state.setTool("select")}>Done painting</button></p>}{state.tool==="door"&&<section className="finish-section door-finish-section"><div className="finish-heading"><div><span>New inside door</span><small>Pick a finish, then click a wall</small></div></div><div className="finish-grid">{doorFinishes.map((finish)=><button key={finish.id} className={state.activeDoorFinish===finish.id?"selected":""} onClick={()=>state.setDoorFinish(finish.id)} title={`${finish.name} — ${finish.family}`}><span className="finish-thumb" style={{backgroundImage:`url(${finish.texture})`}}/><span className="finish-name">{finish.name}<small>{finish.family}</small></span>{state.activeDoorFinish===finish.id&&<Check size={14} weight="bold"/>}</button>)}</div></section>}{chooser("Walls","wallFinishId",wallFinishes,(state.selectedWallId?floor.wallFinishes?.[state.selectedWallId]:undefined)??floor.wallFinishId??"cream-plaster")}{chooser("Floor","floorFinishId",floorFinishes,floor.floorFinishId??"honey-oak")}<div className="mini-tip"><Info size={17}/><span>{state.tool==="wall"?"Drag from a wall endpoint or grid corner. Release when the gold connection marker locks onto another wall.":state.tool==="door"?"Click any outer or inside wall to add the selected door.":"Deselect furniture anytime to return to these room finishes."}</span></div></aside>;
}

function Inspector() {
  const state=usePlanner(); const selected=state.plan.furniture.find((f)=>f.id===state.selectedId); const item=selected?catalog.find((c)=>c.id===selected.catalogId):undefined; const floor=selected?state.plan.floors.find((f)=>f.id===selected.floorId):undefined;
  if(!selected||!item)return <RoomFinishes/>;
  const overlaps=!isWallOpening(selected.catalogId)&&furnitureOverlaps(state.plan.furniture,selected); const updateNumber=(key:"widthMm"|"depthMm"|"heightMm",value:string)=>state.updateFurniture(selected.id,{[key]:Math.max(50,Number(value))});
  return <aside className="inspector-panel"><div className="panel-heading"><div><span className="eyebrow">Selected piece</span><h2>{item.name}</h2></div><button className="icon-button" onClick={()=>state.select(undefined)} aria-label="Close inspector"><X/></button></div>
    {isSurfaceMounted(selected.catalogId)&&<p className="finish-intro">Drag onto a table, counter or display shelf to rest this on it, or over the floor to put it down. Use Rest on a shelf for a precise shelf level. Pieces move independently.</p>}
    {item.category==="Bathroom"&&<p className="finish-intro">{isWallMounted(item.id)?"Place against a wall and adjust Height from floor below. ":""}Layout model only—check plumbing, access space and installation requirements separately.</p>}
    {isWallOpening(selected.catalogId)&&<p className="finish-intro">{isDoor(selected.catalogId)?"Wall-snapped door. Drag along a wall or flip its facing. The wall opening follows the frame.":"Wall-mounted window. Drag along a wall, flip its facing, or adjust the sill height below."}</p>}{isStairs(selected.catalogId)&&<StairSettings item={selected}/>}
    <div className="selection-preview"><img src="/assets/nook-nest-icon.png" alt=""/><div><strong>{item.category}</strong><span>On {floor?.name||"this floor"}</span></div></div>
    {overlaps&&<div className="warning"><Info weight="fill"/><span>This overlaps another piece. It’s allowed, but check the fit.</span></div>}
    <TabletopPlacement item={selected}/><ShelfPlacement item={selected}/><KitchenDetails item={selected}/><section className="inspector-section"><h3>Dimensions <span>millimetres</span></h3><div className="field-grid">{(["widthMm","depthMm","heightMm"] as const).map((key)=><label key={key}>{key.replace("Mm","").replace(/^./,c=>c.toUpperCase())}<input type="number" disabled={isStairs(selected.catalogId)&&key==="heightMm"} value={Math.round(selected[key])} onChange={(e)=>updateNumber(key,e.target.value)}/></label>)}</div><div className="field-grid position-fields"><label>X position<input type="number" value={Math.round(selected.x)} onChange={(e)=>state.updateFurniture(selected.id,{x:Number(e.target.value)})}/></label><label>Z position<input type="number" value={Math.round(selected.z)} onChange={(e)=>state.updateFurniture(selected.id,{z:Number(e.target.value)})}/></label>{(!isDoor(selected.catalogId)&&(isWallMounted(selected.catalogId)||isSurfaceMounted(selected.catalogId)||isCeilingMounted(selected.catalogId)))&&<label>{isWindow(selected.catalogId)?"Sill height":"Height from floor"}<input type="number" min={isSurfaceMounted(selected.catalogId)?0:100} value={Math.round(selected.elevationMm??defaultMountHeight(selected.catalogId)??0)} onChange={(e)=>state.updateFurniture(selected.id,{elevationMm:Math.max(isSurfaceMounted(selected.catalogId)?0:100,Number(e.target.value))})}/></label>}</div></section>
    <section className="inspector-section"><h3>Color &amp; finish <span className="active-color">{selected.variant}</span></h3><div className="swatches">{Object.entries(variants).map(([name,color])=><button key={name} aria-label={name} title={name} className={selected.variant===name?"selected":""} style={{backgroundColor:color}} onClick={()=>state.updateFurniture(selected.id,{variant:name})}>{selected.variant===name&&<Check/>}</button>)}</div></section>
    {supportsCountertopFinish(selected.catalogId)&&<section className="inspector-section countertop-section"><h3>{isBacksplash(selected.catalogId)?"Backsplash material":"Countertop"} <span>{countertopFinishes.find((finish)=>finish.id===(selected.surfaceVariant??defaultCountertopFinish.id))?.name}</span></h3><div className="countertop-grid">{countertopFinishes.map((finish)=><button key={finish.id} className={(selected.surfaceVariant??defaultCountertopFinish.id)===finish.id?"selected":""} onClick={()=>state.updateFurniture(selected.id,{surfaceVariant:finish.id})} title={`${finish.name} — ${finish.family}`}><span style={{backgroundImage:`url(${finish.texture})`}}/>{(selected.surfaceVariant??defaultCountertopFinish.id)===finish.id&&<Check size={14} weight="bold"/>}<small>{finish.name}</small></button>)}</div></section>}
    {isDoor(selected.catalogId)&&<section className="inspector-section"><h3>Door material</h3><div className="door-materials">{doorFinishes.map(f=><button key={f.id} aria-pressed={selected.surfaceVariant===f.id} onClick={()=>state.updateFurniture(selected.id,{surfaceVariant:f.id})}><img src={f.texture} alt=""/>{f.name}</button>)}</div></section>}{slidingDoorIds.has(selected.catalogId)&&<SlidingDoorSettings item={selected}/>}<MaterialColors item={selected}/>
    <section className="inspector-section"><h3>Rotation</h3><div className="rotation-row"><FurnitureTurnButton item={selected} direction={-1}>{isWallOpening(selected.catalogId)||isKitchenWall(selected.catalogId)?"Flip":isStairs(selected.catalogId)?"−90°":"−15°"}</FurnitureTurnButton><strong>{selected.rotation}°</strong><FurnitureTurnButton item={selected} direction={1}>{isWallOpening(selected.catalogId)||isKitchenWall(selected.catalogId)?"Flip":isStairs(selected.catalogId)?"+90°":"+15°"}</FurnitureTurnButton></div></section>
    <div className="inspector-actions"><button onClick={state.duplicateSelected}><Copy/> Duplicate</button><button className="danger" onClick={state.deleteSelected}><Trash/> Remove</button></div>
  </aside>;
}

function AppDialog({ kind, onClose }: { kind: "help"|"project"|"share"; onClose():void }) {
  const state=usePlanner(); const fileRef=useRef<HTMLInputElement>(null); const [copied,setCopied]=useState(false); const payload=encodeShare(state.plan); const shareUrl=`${location.origin}${location.pathname}#plan=${payload}`;
  const importFile=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;try{state.replacePlan(parsePlan(await file.text()));onClose()}catch(err){alert(err instanceof Error?err.message:"Could not import this project.")}};
  return <div className="modal-backdrop small"><section className="dialog" role="dialog" aria-modal="true"><button className="dialog-close icon-button" onClick={onClose}><X/></button>
    {kind==="help"&&<><span className="eyebrow">Quick guide</span><h2>Make yourself at home</h2><div className="shortcut-list"><p><kbd>1</kbd><span>Arrange furniture</span></p><p><kbd>2</kbd><span>Paint floor tiles</span></p><p><kbd>3</kbd><span>Erase floor tiles</span></p><p><kbd>R</kbd><span>Rotate selected piece</span></p><p><kbd>Ctrl Z</kbd><span>Undo the last change</span></p><p><kbd>Delete</kbd><span>Remove selected piece</span></p></div><p className="dialog-note">Tip: switch to Top View whenever you want to check clearances and exact dimensions.</p></>}
    {kind==="project"&&<><span className="eyebrow">Project file</span><h2>Keep a copy somewhere safe</h2><div className="dialog-actions"><button onClick={()=>download(`${state.plan.name}.nook.json`,serializePlan(state.plan),"application/json")}><DownloadSimple/> Export project</button><button onClick={()=>fileRef.current?.click()}><FileArrowUp/> Import project</button><button onClick={()=>{state.replacePlan({...structuredClone(state.plan),id:uid(),name:`${state.plan.name} copy`,createdAt:new Date().toISOString()});onClose()}}><Copy/> Duplicate project</button><button className="danger" onClick={()=>{if(confirm("Start over with a fresh project? Export first if you want to keep this plan.")){state.replacePlan(createSamplePlan("New apartment",state.plan.units));onClose()}}}><Trash/> Start fresh</button><input ref={fileRef} hidden type="file" accept="application/json,.json" onChange={importFile}/></div><p className="dialog-note"><FloppyDisk/> Your current project also autosaves privately in this browser.</p></>}
    {kind==="share"&&<><span className="eyebrow">No account needed</span><h2>Share an editable copy</h2><p>Anyone with this link can open a copy of your plan. Your original stays in this browser.</p><div className="share-box"><input readOnly value={shareUrl}/><button className="primary" disabled={payload.length>48000} onClick={async()=>{await navigator.clipboard.writeText(shareUrl);setCopied(true)}}>{copied?<Check/>:<Copy/>}{copied?"Copied":"Copy link"}</button></div>{payload.length>48000&&<div className="warning"><Info/><span>This project is too large for a reliable link. Export the project file instead.</span></div>}</>}
  </section></div>;
}

const showcaseMode = import.meta.env.DEV ? new URLSearchParams(location.search).get("showcase") : null;
const showcaseItem = import.meta.env.DEV ? new URLSearchParams(location.search).get("item") : null;
const furnitureShowcase = showcaseMode === "furniture" || showcaseMode === "stress" || showcaseMode === "detail";
function createFurnitureShowcase(stress=false,detailId?:string|null) {
  const detail=catalog.find((definition)=>definition.id===detailId);
  const plan=createSamplePlan(stress?"150-piece performance study":detail?`${detail.name} detail study`:"Handcrafted furniture study","metric"); const floor={...plan.floors[0],id:"showcase-floor",name:stress?"Performance study":detail?"Furniture detail":"Furniture study",cells:rectangleCells(stress?32:detail?20:76,stress?20:detail?20:60),walls:[],openings:[],stairs:[]};
  if(stress)return {...plan,floors:[floor],furniture:Array.from({length:150},(_,index)=>{const definition=catalog[index%catalog.length];return {id:`stress-${index}`,catalogId:definition.id,floorId:floor.id,x:350+(index%15)*500,z:350+Math.floor(index/15)*470,rotation:(index%4)*15,widthMm:definition.widthMm,depthMm:definition.depthMm,heightMm:definition.heightMm,variant:Object.keys(variants)[index%Object.keys(variants).length],elevationMm:defaultMountHeight(definition.id)};}),camera:{...plan.camera,ghostBelow:false,showGrid:false}};
  if(detail)return {...plan,floors:[floor],furniture:[{id:`showcase-${detail.id}`,catalogId:detail.id,floorId:floor.id,x:2500,z:2500,rotation:165,widthMm:detail.widthMm,depthMm:detail.depthMm,heightMm:detail.heightMm,variant:"sage",elevationMm:defaultMountHeight(detail.id)}],camera:{...plan.camera,ghostBelow:false,showGrid:false}};
  const palette=Object.keys(variants);
  return {...plan,floors:[floor],furniture:catalog.map((definition,index)=>({
    id:`showcase-${definition.id}`,catalogId:definition.id,floorId:floor.id,
    x:1500+(index%7)*2600,z:1600+Math.floor(index/7)*3400,rotation:index%3===0?345:index%3===1?0:15,
    widthMm:definition.widthMm,depthMm:definition.depthMm,heightMm:definition.heightMm,variant:palette[index%palette.length],elevationMm:defaultMountHeight(definition.id),
  })),camera:{...plan.camera,ghostBelow:false,showGrid:false}};
}

export function EditorApp({onHome}:{onHome?:()=>void}) {
  const appearance=useAppearance();
  const agentPreview=useAgent(s=>s.pending);
  const [blueprintBusy,setBlueprintBusy]=useState(false),[furnishingPreview,setFurnishingPreview]=useState<PlanDocumentV1>();
  const state=usePlanner(); const canvasRef=useRef<HTMLCanvasElement>(null); const controllerRef=useRef<SceneController|undefined>(undefined); const placementControlsRef=useRef<HTMLDivElement>(null); const selectedControlsRef=useRef<HTMLDivElement>(null); const tileControlsRef=useRef<HTMLDivElement>(null); const focusDraftControls=useRef(false); const [draft,setDraft]=useState<FurniturePlacement|undefined>(); const [tileDraft,setTileDraft]=useState<{cells:TileCell[];present:boolean;region?:MeasuredRegion}|undefined>(); const ready=true; const [showSetup,setShowSetup]=useState(false); const [dialog,setDialog]=useState<"help"|"project"|"share"|undefined>(new URLSearchParams(location.search).has("projects")?"project":undefined); const [muted,setMuted]=useState(true); const saveTimer=useRef<number|undefined>(undefined); const [saveStatus,setSaveStatus]=useState("Saving locally…");
  const dark=appearance?.dark??!!state.plan.camera.darkMode;
  const floor=state.plan.floors.find((f)=>f.id===state.activeFloorId)!; const area=floorRects(floor,state.plan.gridSizeMm).reduce((sum,r)=>sum+r.width*r.depth,0)/1_000_000; const placed=state.plan.furniture.filter((f)=>f.floorId===floor.id).length;
  const selected=state.plan.furniture.find((item)=>item.id===state.selectedId);
  const cancelTilePlacement=()=>{controllerRef.current?.cancelTileDraft();setTileDraft(undefined)};
  const confirmTilePlacement=()=>{if(!tileDraft)return;controllerRef.current?.cancelTileDraft();if(tileDraft.region)state.addMeasuredRoom(tileDraft.region);else if(state.tool==="floor-finish")state.finishCells(tileDraft.cells,state.activeSurfaceFinish);else state.paintCells(tileDraft.cells,tileDraft.present);setTileDraft(undefined)};
  const startPlacement=(item:CatalogItem,focusControls=false)=>{
    const xs=floor.cells.map((cell)=>cell.x),zs=floor.cells.map((cell)=>cell.z),grid=state.plan.gridSizeMm;
    const x=xs.length?Math.round(((Math.min(...xs)+Math.max(...xs)+1)*grid/2)/50)*50:1700;
    const z=zs.length?Math.round(((Math.min(...zs)+Math.max(...zs)+1)*grid/2)/50)*50:1700;
    const next: FurniturePlacement={id:uid(),catalogId:item.id,floorId:floor.id,x,z,rotation:controllerRef.current?.placementRotation(item.id,x,z)??0,widthMm:item.widthMm,depthMm:item.depthMm,heightMm:item.heightMm,variant:"sage",surfaceVariant:supportsCountertopFinish(item.id)?defaultCountertopFinish.id:undefined,elevationMm:defaultMountHeight(item.id)};
    cancelTilePlacement(); focusDraftControls.current=focusControls; state.select(undefined); state.setTool("select"); if(isStairs(item.id))next.toFloorId=state.plan.floors[state.plan.floors.indexOf(floor)+1]?.id; if(isDoor(item.id))next.surfaceVariant=state.activeDoorFinish;
    const mounted=fitStair(state.plan,snapWindow(state.plan,next)); setDraft(mounted); return mounted;
  };
  const beginPlacementDrag=(item:CatalogItem,event:ReactPointerEvent<HTMLButtonElement>)=>{
    if(event.button!==0)return; event.preventDefault();
    let next:FurniturePlacement|undefined; let latest:PlacementPoint|undefined;
    const move=(pointer:PointerEvent)=>{
      const rect=canvasRef.current?.getBoundingClientRect();
      if(!rect||pointer.clientX<rect.left||pointer.clientX>rect.right||pointer.clientY<rect.top||pointer.clientY>rect.bottom)return;
      const firstPosition=!next;if(!next)next=startPlacement(item);
      const position=controllerRef.current?.movePreviewFromClient(pointer.clientX,pointer.clientY,next);
      if(position){latest=position;const id=next.id;const facing=firstPosition?controllerRef.current?.placementRotation(item.id,position.x,position.z):undefined;setDraft(current=>current?.id===id?snapWindow(usePlanner.getState().plan,{...current,...position,...(facing===undefined?{}:{rotation:facing})}):current);}
    };
    const finish=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",finish);window.removeEventListener("pointercancel",finish);if(next&&latest){const id=next.id;setDraft(current=>current?.id===id?snapWindow(usePlanner.getState().plan,{...current,...latest}):current);}};
    window.addEventListener("pointermove",move);window.addEventListener("pointerup",finish);window.addEventListener("pointercancel",finish);
  };
  const confirmDraft=()=>{if(!draft||windowProblem(state.plan,draft))return;state.confirmFurniture(draft);setDraft(undefined)};
  const rotateDraft=(degrees:number)=>setDraft((current)=>current?{...current,rotation:windowRotation(current,degrees)}:current);

  useEffect(()=>{if(!ready||furnitureShowcase)return;let cancelled=false;setSaveStatus("Saving locally…");window.clearTimeout(saveTimer.current);saveTimer.current=window.setTimeout(()=>savePlan(state.plan).then(()=>{if(!cancelled)setSaveStatus("Saved locally")}).catch(()=>{if(!cancelled)setSaveStatus("Local save failed — export a backup")}),450);return()=>{cancelled=true;window.clearTimeout(saveTimer.current)}},[state.plan,ready]);
  useEffect(()=>{if(!ready||!canvasRef.current)return;const controller=new SceneController(canvasRef.current,{onCell:(x,z)=>{const s=usePlanner.getState();if(s.tool==="measured-room"&&s.roomSize){try{const region=measuredRegion(s.plan.gridSizeMm,{x,z},s.roomSize.widthMm,s.roomSize.depthMm);setTileDraft({cells:region.cells,present:true,region});}catch(e){usePlanner.setState({placementNotice:(e as Error).message});}}},onWallSegment:(wall)=>usePlanner.getState().addWall(wall),onTileDraft:(cells,present)=>setTileDraft({cells,present}),onSelect:(id)=>usePlanner.getState().select(id),onMove:(id,x,z,elevationMm)=>usePlanner.getState().updateFurniture(id,{x,z,...(elevationMm===undefined?{}:{elevationMm})}),onDraftMove:(x,z,elevationMm)=>setDraft((current)=>current?snapWindow(usePlanner.getState().plan,{...current,x,z,...(elevationMm===undefined?{}:{elevationMm})}):current),onWall:(id)=>{const s=usePlanner.getState();if(s.tool==="door"||s.tool==="window")s.addOpening(s.tool,id);else if(s.tool==="wall-finish"||s.tool==="select")s.selectWall(id)}});controllerRef.current=controller;return()=>{controllerRef.current=undefined;controller.dispose()}},[ready]);
  useEffect(()=>{const plan=furnishingPreview??agentPreview?.plan??state.plan;const viewPlan={...plan,camera:{...plan.camera,darkMode:dark}};controllerRef.current?.setTool(agentPreview?'select':state.tool);controllerRef.current?.setWallSelection(agentPreview?undefined:state.selectedWallId);controllerRef.current?.update(viewPlan,state.activeFloorId,agentPreview?undefined:state.selectedId,agentPreview?undefined:draft)},[state.plan,state.activeFloorId,state.selectedId,state.selectedWallId,state.tool,state.turnId,ready,draft,agentPreview,furnishingPreview,dark]);
  useEffect(()=>{setDraft(undefined);cancelTilePlacement()},[state.activeFloorId]);
  useEffect(()=>{cancelTilePlacement();if(state.tool!=="select")setDraft(undefined)},[state.tool]);
  useEffect(()=>{if(tileDraft?.region)controllerRef.current?.previewMeasuredRoom(tileDraft.region)},[tileDraft,state.plan,ready]);
  useEffect(()=>{if(!draft)return;let frame=0;const sync=()=>{const position=controllerRef.current?.projectPreview();const controls=placementControlsRef.current;if(controls&&position){controls.style.left=`${position.x}px`;controls.style.top=`${position.y}px`;controls.style.opacity="1";if(focusDraftControls.current){controls.querySelector<HTMLButtonElement>(".placement-confirm")?.focus();focusDraftControls.current=false}}frame=requestAnimationFrame(sync)};frame=requestAnimationFrame(sync);return()=>cancelAnimationFrame(frame)},[draft?.id]);
  useEffect(()=>{if(!selected||draft)return;let frame=0;const sync=()=>{const position=controllerRef.current?.projectSelected();const controls=selectedControlsRef.current;if(controls&&position){controls.style.left=`${position.x}px`;controls.style.top=`${position.y}px`;controls.style.opacity="1"}frame=requestAnimationFrame(sync)};frame=requestAnimationFrame(sync);return()=>cancelAnimationFrame(frame)},[selected?.id,draft]);
  useEffect(()=>{if(!tileDraft)return;let frame=0;const sync=()=>{const position=controllerRef.current?.projectTileDraft();const controls=tileControlsRef.current;if(controls&&position){controls.style.left=`${position.x}px`;controls.style.top=`${position.y}px`;controls.style.opacity="1"}frame=requestAnimationFrame(sync)};frame=requestAnimationFrame(sync);return()=>cancelAnimationFrame(frame)},[tileDraft]);
  useEffect(()=>{const onKey=(e:KeyboardEvent)=>{const tag=(e.target as HTMLElement).tagName;if(["INPUT","SELECT","TEXTAREA"].includes(tag))return;if(usePlanner.getState().tool==="planting"){if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"){e.preventDefault();usePlanner.getState().cancelPlanting();e.shiftKey?state.redo():state.undo()}else if(e.key==="Escape"){e.preventDefault();usePlanner.getState().cancelPlanting();usePlanner.getState().setTool("select")}else if(e.key==="Enter"&&tag!=="BUTTON"){e.preventDefault();usePlanner.getState().confirmPlanting()}return}if(tileDraft){if(e.key==="Escape"||e.key==="Delete"){e.preventDefault();cancelTilePlacement()}else if(e.key==="Enter"&&tag!=="BUTTON"){e.preventDefault();confirmTilePlacement()}return}if(draft){if(e.key==="Escape"||e.key==="Delete"){e.preventDefault();setDraft(undefined)}else if(e.key.toLowerCase()==="r"){e.preventDefault();rotateDraft(15)}else if(e.key==="Enter"&&tag!=="BUTTON"){e.preventDefault();confirmDraft()}return}if(tag==="BUTTON")return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"){e.preventDefault();e.shiftKey?state.redo():state.undo()}else if(e.key==="Delete")state.deleteSelected();else if(e.key.toLowerCase()==="r"&&state.selectedId){const item=usePlanner.getState().plan.furniture.find(f=>f.id===state.selectedId);if(item)state.updateFurniture(item.id,{rotation:windowRotation(item,15)})}else if(e.key==="1")state.setTool("select");else if(e.key==="2")state.setTool("paint");else if(e.key==="3")state.setTool("erase")};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[state.selectedId,draft,tileDraft]);
  useEffect(()=>{if(muted)return;const AudioContextClass=window.AudioContext;const context=new AudioContextClass();const gain=context.createGain();gain.gain.value=.012;gain.connect(context.destination);const tones=[174,220].map((frequency,index)=>{const oscillator=context.createOscillator();oscillator.type=index?"sine":"triangle";oscillator.frequency.value=frequency;const toneGain=context.createGain();toneGain.gain.value=index?.3:.18;oscillator.connect(toneGain).connect(gain);oscillator.start();return oscillator});return()=>{tones.forEach(t=>t.stop());void context.close()}},[muted]);
  const takeScreenshot=()=>{const data=controllerRef.current?.screenshot();if(!data)return;const a=document.createElement("a");a.href=data;a.download=`${state.plan.name}.png`;a.click()};
  if(!ready)return <main className="loading-screen"><img src="/assets/nook-nest-icon.png"/><span>Opening your little home…</span></main>;
  return <main className={`app-shell ${dark?"dark-mode":""}`}>
    <header className="topbar"><div className="brand">{onHome?<button className="brand-home" onClick={onHome} disabled={blueprintBusy||!!agentPreview} aria-label="Back to home" title="Back to home"><img src="/assets/nook-nest-icon.png" alt=""/></button>:<img src="/assets/nook-nest-icon.png" alt=""/>}<div><span>Nook &amp; Nest</span><small>cozy apartment planner</small></div></div><div className="project-title"><input aria-label="Project name" value={state.plan.name} onChange={(e)=>state.rename(e.target.value)}/><span className="saved"><Check weight="bold"/> {saveStatus}</span></div><nav className="top-actions"><AgentControls busy={blueprintBusy||!!draft||!!tileDraft||showSetup||!!dialog||state.tool!=='select'}/><button className="icon-button" onClick={()=>appearance?appearance.chooseTheme(dark?"light":"dark"):state.toggleCameraSetting("darkMode")} aria-label="Night mode" aria-pressed={dark} title="Toggle night mode for the menu, studio and editor"><Lamp/></button><button className="icon-button" onClick={state.undo} disabled={!state.past.length} aria-label="Undo"><ArrowCounterClockwise/></button><button className="icon-button" onClick={state.redo} disabled={!state.future.length} aria-label="Redo"><ArrowClockwise/></button><span className="divider"/><button onClick={()=>setDialog("share")}><ShareNetwork/> Share</button><button onClick={()=>setDialog("project")}><FloppyDisk/> Project</button><button className="icon-button" onClick={()=>setDialog("help")} aria-label="Help"><Info/></button></nav></header>
    <section className="workspace"><Catalog onBeginDrag={beginPlacementDrag} onStartPlacement={(item)=>startPlacement(item,true)}/><section className="canvas-stage"><canvas ref={canvasRef} aria-label="Interactive 3D apartment editor"/><div className="view-toggle"><button className={state.plan.camera.mode==="isometric"?"active":""} onClick={()=>{cancelTilePlacement();state.setView("isometric")}}><Buildings/> Cozy view</button><button className={state.plan.camera.mode==="top"?"active":""} onClick={()=>{cancelTilePlacement();state.setView("top")}}><GridFour/> Top view</button><button className={state.plan.camera.mode==="dollhouse"?"active":""} onClick={()=>{cancelTilePlacement();state.setView("dollhouse")}}><SquaresFour/> Dollhouse</button></div>
      <div className="bp-entry"><BlueprintControls busy={!!draft||!!tileDraft||showSetup||!!dialog||!!agentPreview||state.tool!=='select'} onCreated={()=>{const s=usePlanner.getState();controllerRef.current?.focusFloor(s.plan,s.activeFloorId)}} onPreview={setFurnishingPreview} onBusy={setBlueprintBusy}/></div>
      <AgentPreviewNotice/>
      {(state.placementNotice||(draft&&(isWallOpening(draft.catalogId)||isKitchenWall(draft.catalogId)||isCeilingMounted(draft.catalogId))))&&<div className="window-placement-note" role="status">{state.placementNotice||(draft&&(windowProblem(state.plan,draft)||(isCeilingMounted(draft.catalogId)?"Move over your island or table · ✓ to place":"Drag along a wall · arrows flip the facing · ✓ to place")))}</div>}
      {draft&&isStairs(draft.catalogId)&&<div className="window-placement-note" role="status">{stairWarnings(state.plan,draft)[0]??"Stairs connect to the next floor · reserve an opening above · rotate 90°"}</div>}
      {state.tool==="measured-room"&&!tileDraft&&<div className="window-placement-note" role="status">Click the floor to position your measured room preview.</div>}
      {draft&&<div ref={placementControlsRef} className="placement-controls" role="toolbar" aria-label={`Place ${catalog.find((item)=>item.id===draft.catalogId)?.name??"furniture"}`}><button className="placement-cancel" onClick={()=>setDraft(undefined)} title="Cancel placement" aria-label="Cancel placement"><X size={18} weight="bold"/></button><TurnButton direction={-1} onStep={rotateDraft} discrete={isWallOpening(draft.catalogId)||isKitchenWall(draft.catalogId)||isStairs(draft.catalogId)}><ArrowCounterClockwise size={18}/></TurnButton><button className="placement-confirm" disabled={!!windowProblem(state.plan,draft)} onClick={confirmDraft} onKeyDown={(event)=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();confirmDraft()}}} title="Confirm placement" aria-label="Confirm placement"><Check size={19} weight="bold"/></button><TurnButton direction={1} onStep={rotateDraft} discrete={isWallOpening(draft.catalogId)||isKitchenWall(draft.catalogId)||isStairs(draft.catalogId)}><ArrowClockwise size={18}/></TurnButton></div>}
      {tileDraft&&<div ref={tileControlsRef} className={`placement-controls tile-controls ${tileDraft.present?"adding":"erasing"}`} role="toolbar" aria-label={`${state.tool==="floor-finish"?"Finish":tileDraft.present?"Add":"Erase"} ${tileDraft.cells.length} floor tiles`}><span className="tile-draft-label"><GridFour size={16} weight="duotone"/>{tileDraft.region?`${tileDraft.region.widthMm} × ${tileDraft.region.depthMm} mm`: `${state.tool==="floor-finish"?"Finish":tileDraft.present?"Add":"Erase"} ${tileDraft.cells.length} tiles`}</span><button className="placement-cancel" onClick={cancelTilePlacement} title="Cancel tile change" aria-label="Cancel tile change"><X size={18} weight="bold"/></button><button className="placement-confirm" onClick={confirmTilePlacement} onKeyDown={(event)=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();confirmTilePlacement()}}} title="Confirm tile change" aria-label="Confirm tile change"><Check size={19} weight="bold"/></button></div>}
      {!draft&&!tileDraft&&selected&&<div ref={selectedControlsRef} className="placement-controls selected-controls" role="toolbar" aria-label={`Edit ${catalog.find((item)=>item.id===selected.catalogId)?.name??"furniture"}`}><div className="selected-action-row"><button className="placement-cancel" onClick={state.deleteSelected} title="Remove furniture" aria-label="Remove furniture"><X size={18} weight="bold"/></button><FurnitureTurnButton item={selected} direction={-1}><ArrowCounterClockwise size={18}/></FurnitureTurnButton><button className="placement-confirm" onClick={()=>state.select(undefined)} title="Done editing" aria-label="Done editing"><Check size={19} weight="bold"/></button><FurnitureTurnButton item={selected} direction={1}><ArrowClockwise size={18}/></FurnitureTurnButton></div><div className="selected-color-row" role="group" aria-label="Furniture color">{Object.entries(variants).map(([name,color])=><button key={name} className={selected.variant===name?"selected":""} style={{backgroundColor:color}} onClick={()=>state.updateFurniture(selected.id,{variant:name})} title={`${name} color`} aria-label={`${name} color`}>{selected.variant===name&&<Check size={13} weight="bold"/>}</button>)}</div></div>}
      <div className="tool-dock">{tools.map(({id,label,icon:Icon})=><button key={id} className={state.tool===id?"active":""} onClick={()=>{setDraft(undefined);cancelTilePlacement();if(id!=="select")state.select(undefined);if(id==="window"||id==="door"||id==="stairs"){state.setCategory(id==="door"?"Doors":id==="stairs"?"Stairs":"Windows");state.setSearch("");state.setTool("select")}else state.setTool(id)}} title={label}><Icon size={20} weight={state.tool===id?"fill":"regular"}/><span>{label}</span></button>)}</div>
      <div className="canvas-tools"><button onClick={()=>controllerRef.current?.zoom(.75)} aria-label="Zoom in" title="Zoom in">+</button><button onClick={()=>controllerRef.current?.zoom(1.333)} aria-label="Zoom out" title="Zoom out">−</button><button disabled={!selected} onClick={()=>controllerRef.current?.focusSelected()} aria-label="Focus selected furniture" title="Focus selected furniture for detail placement"><MagnifyingGlass/></button><WallVisibilityControl/><button className={state.plan.camera.showGrid?"active":""} onClick={()=>state.toggleCameraSetting("showGrid")} title="Grid labels"><Ruler/></button><button className={state.plan.camera.showClearance?"active":""} onClick={()=>state.toggleCameraSetting("showClearance")} title="Clearance guides"><Eye/></button><button onClick={takeScreenshot} title="Save screenshot"><Camera/></button><button onClick={()=>setMuted(!muted)} title={muted?"Turn sound on":"Mute sound"}>{muted?<SpeakerSlash/>:<SpeakerHigh/>}</button></div>
      <div className="floor-stats"><span><strong>{area.toFixed(1)} m²</strong> floor area</span><i/><span><strong>{placed}</strong> pieces</span><i/><span>Tile {formatLength(state.plan.gridSizeMm,state.plan.units)}</span></div>
    </section><Inspector/></section>
    <FloorBar onBeforeDelete={()=>{setDraft(undefined);cancelTilePlacement()}}/>
    {showSetup&&<SetupDialog onDone={()=>setShowSetup(false)}/>} {dialog==="project"?<ProjectLibrary onClose={()=>setDialog(undefined)}/>:dialog&&<AppDialog kind={dialog} onClose={()=>setDialog(undefined)}/>}<div className="desktop-gate"><img src="/assets/nook-nest-icon.png"/><h1>Your nest needs a little more room</h1><p>Nook &amp; Nest is ready for full editing on a desktop or wide tablet. Open this page on a larger screen to decorate.</p></div>
  </main>;
}

export function App(){return <Welcome Editor={EditorApp} showcase={furnitureShowcase?()=>createFurnitureShowcase(showcaseMode==="stress",showcaseItem):undefined}/>;}
