import { useEffect, useRef, useState, type PointerEvent as ReactPointerEvent } from "react";
import { Armchair, ArrowClockwise, ArrowCounterClockwise, Bed, Books, Buildings, Camera, Chair, Check, Copy, Door, DownloadSimple, Eye, FileArrowUp, FloppyDisk, FrameCorners, GridFour, HandGrabbing, Info, Lamp, MagnifyingGlass, PaintBrush, Plant, Plus, Ruler, ShareNetwork, SpeakerHigh, SpeakerSlash, SquaresFour, Stairs, Table, Trash, Wall, X } from "@phosphor-icons/react";
import { catalog, variants } from "./catalog";
import { createSamplePlan, encodeShare, formatLength, furnitureOverlaps, parsePlan, rectangleCells, serializePlan, uid } from "./domain";
import { SceneController } from "./scene/SceneController";
import { loadPlan, savePlan, usePlanner } from "./store";
import type { CatalogItem, FurniturePlacement, PlanDocumentV1, Tool, Units } from "./types";

const categoryIcons: Record<string, typeof Armchair> = { Living: Armchair, Bedroom: Bed, Dining: Table, Office: Chair, Storage: Books, Lighting: Lamp, Decor: Plant };
const shapeIcons: Record<string, typeof Armchair> = { seat: Armchair, table: Table, bed: Bed, storage: Books, lamp: Lamp, plant: Plant, rug: GridFour, decor: SquaresFour };
const tools: Array<{ id: Tool; label: string; icon: typeof Armchair }> = [
  { id: "select", label: "Arrange", icon: Armchair }, { id: "paint", label: "Paint tiles", icon: PaintBrush }, { id: "erase", label: "Erase", icon: Trash },
  { id: "wall", label: "Wall", icon: Wall }, { id: "door", label: "Door", icon: Door }, { id: "window", label: "Window", icon: FrameCorners }, { id: "stairs", label: "Stairs", icon: Stairs },
];

function download(name: string, content: string, type: string) { const anchor = document.createElement("a"); anchor.href = URL.createObjectURL(new Blob([content], { type })); anchor.download = name; anchor.click(); URL.revokeObjectURL(anchor.href); }

function SetupDialog({ onDone }: { onDone(): void }) {
  const replacePlan = usePlanner((s) => s.replacePlan); const [name, setName] = useState("My cozy apartment"); const [units, setUnits] = useState<Units>("imperial"); const [width, setWidth] = useState(14); const [depth, setDepth] = useState(10); const [floorHeight,setFloorHeight]=useState(8); const [tileSize,setTileSize]=useState(1);
  const create = () => { const plan = createSamplePlan(name, units); const grid = units === "imperial" ? tileSize*304.8 : tileSize*1000; const heightMm=units==="imperial"?floorHeight*304.8:floorHeight*1000; const floor = { ...plan.floors[0], id: uid(), name: "Ground floor", heightMm, cells: rectangleCells(Math.max(3, width), Math.max(3, depth)) }; replacePlan({ ...plan, gridSizeMm: grid, floors: [floor], furniture: [] }); onDone(); };
  return <div className="modal-backdrop"><section className="setup-card" role="dialog" aria-modal="true" aria-labelledby="setup-title">
    <div className="setup-art"><img src="/assets/nook-nest-icon.png" alt="A tiny handcrafted room with an armchair and plant" /></div>
    <div className="setup-content"><span className="eyebrow">A little space for big ideas</span><h1 id="setup-title">Welcome to Nook &amp; Nest</h1><p>Sketch your apartment to scale, then make it feel like home. Everything saves quietly in this browser.</p>
      <label>Project name<input value={name} onChange={(e)=>setName(e.target.value)} /></label>
      <div className="segmented" aria-label="Measurement units"><button className={units==="imperial"?"active":""} onClick={()=>setUnits("imperial")}>Feet &amp; inches</button><button className={units==="metric"?"active":""} onClick={()=>setUnits("metric")}>Metric</button></div>
      <div className="setup-dimensions"><label>Width in tiles<input type="number" min="3" max="40" value={width} onChange={(e)=>setWidth(Number(e.target.value))} /></label><span>×</span><label>Depth in tiles<input type="number" min="3" max="40" value={depth} onChange={(e)=>setDepth(Number(e.target.value))} /></label></div>
      <div className="setup-dimensions secondary"><label>Tile size ({units==="imperial"?"feet":"metres"})<input type="number" min={units==="imperial"?.5:.1} step={units==="imperial"?.5:.05} value={tileSize} onChange={(e)=>setTileSize(Number(e.target.value))} /></label><span/><label>Floor height ({units==="imperial"?"feet":"metres"})<input type="number" min={units==="imperial"?6:1.8} step={units==="imperial"?.5:.1} value={floorHeight} onChange={(e)=>setFloorHeight(Number(e.target.value))}/></label></div>
      <div className="tile-note"><Ruler size={20} /><span>Each tile is <strong>{units==="imperial"?`${tileSize} foot`: `${tileSize} metre`}</strong>. Furniture can use finer measurements.</span></div>
      <button className="primary large" onClick={create}>Start decorating <Check weight="bold" /></button>
    </div>
  </section></div>;
}

function Catalog({onBeginDrag,onStartPlacement}:{onBeginDrag(item:CatalogItem,event:ReactPointerEvent<HTMLButtonElement>):void;onStartPlacement(item:CatalogItem):void}) {
  const { search, category, setSearch, setCategory } = usePlanner(); const categories = ["All", ...new Set(catalog.map((i)=>i.category))];
  const filtered = catalog.filter((item) => (category === "All" || item.category === category) && `${item.name} ${item.description}`.toLowerCase().includes(search.toLowerCase()));
  return <aside className="catalog-panel"><div className="panel-heading"><div><span className="eyebrow">Furniture library</span><h2>Make it yours</h2></div><span className="count-pill">{filtered.length}</span></div>
    <label className="search"><MagnifyingGlass size={18}/><input aria-label="Search furniture" placeholder="Search cozy things…" value={search} onChange={(e)=>setSearch(e.target.value)} /></label>
    <div className="category-strip">{categories.map((cat)=>{const Icon=categoryIcons[cat]||SquaresFour;return <button key={cat} className={category===cat?"active":""} onClick={()=>setCategory(cat)} title={cat}><Icon size={18}/><span>{cat}</span></button>})}</div>
    <div className="catalog-grid">{filtered.map((item)=>{const Icon=shapeIcons[item.shape];return <button className="catalog-card" key={item.id} draggable={false} aria-label={`${item.name}, drag to place`} onPointerDown={(event)=>onBeginDrag(item,event)} onKeyDown={(event)=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();onStartPlacement(item)}}}><span className={`item-illustration ${item.shape}`}><Icon size={31} weight="duotone"/></span><span className="item-copy"><strong>{item.name}</strong><small>{formatLength(item.widthMm,usePlanner.getState().plan.units)} × {formatLength(item.depthMm,usePlanner.getState().plan.units)}</small></span><HandGrabbing className="add-dot" size={14} weight="bold"/></button>})}</div>
  </aside>;
}

function Inspector() {
  const state=usePlanner(); const selected=state.plan.furniture.find((f)=>f.id===state.selectedId); const item=selected?catalog.find((c)=>c.id===selected.catalogId):undefined; const floor=selected?state.plan.floors.find((f)=>f.id===selected.floorId):undefined;
  if(!selected||!item)return <aside className="inspector-panel empty-inspector"><div className="inspector-orbit"><Armchair size={38} weight="duotone"/></div><h3>Select something</h3><p>Choose a piece in your room to adjust its size, color, and placement.</p><div className="mini-tip"><Info size={17}/><span>Drag furniture directly in the room. Hold Alt for a freer feel.</span></div></aside>;
  const overlaps=furnitureOverlaps(state.plan.furniture,selected); const updateNumber=(key:"widthMm"|"depthMm"|"heightMm",value:string)=>state.updateFurniture(selected.id,{[key]:Math.max(50,Number(value))});
  return <aside className="inspector-panel"><div className="panel-heading"><div><span className="eyebrow">Selected piece</span><h2>{item.name}</h2></div><button className="icon-button" onClick={()=>state.select(undefined)} aria-label="Close inspector"><X/></button></div>
    <div className="selection-preview"><img src="/assets/nook-nest-icon.png" alt=""/><div><strong>{item.category}</strong><span>On {floor?.name||"this floor"}</span></div></div>
    {overlaps&&<div className="warning"><Info weight="fill"/><span>This overlaps another piece. It’s allowed, but check the fit.</span></div>}
    <section className="inspector-section"><h3>Dimensions <span>millimetres</span></h3><div className="field-grid">{(["widthMm","depthMm","heightMm"] as const).map((key)=><label key={key}>{key.replace("Mm","").replace(/^./,c=>c.toUpperCase())}<input type="number" value={Math.round(selected[key])} onChange={(e)=>updateNumber(key,e.target.value)}/></label>)}</div><div className="field-grid position-fields"><label>X position<input type="number" value={Math.round(selected.x)} onChange={(e)=>state.updateFurniture(selected.id,{x:Number(e.target.value)})}/></label><label>Z position<input type="number" value={Math.round(selected.z)} onChange={(e)=>state.updateFurniture(selected.id,{z:Number(e.target.value)})}/></label></div></section>
    <section className="inspector-section"><h3>Upholstery color <span className="active-color">{selected.variant}</span></h3><div className="swatches">{Object.entries(variants).map(([name,color])=><button key={name} aria-label={name} title={name} className={selected.variant===name?"selected":""} style={{backgroundColor:color}} onClick={()=>state.updateFurniture(selected.id,{variant:name})}>{selected.variant===name&&<Check/>}</button>)}</div></section>
    <section className="inspector-section"><h3>Rotation</h3><div className="rotation-row"><button onClick={()=>state.updateFurniture(selected.id,{rotation:(selected.rotation-15+360)%360})}>−15°</button><strong>{selected.rotation}°</strong><button onClick={()=>state.updateFurniture(selected.id,{rotation:(selected.rotation+15)%360})}>+15°</button></div></section>
    <div className="inspector-actions"><button onClick={state.duplicateSelected}><Copy/> Duplicate</button><button className="danger" onClick={state.deleteSelected}><Trash/> Remove</button></div>
  </aside>;
}

function AppDialog({ kind, onClose }: { kind: "help"|"project"|"share"; onClose():void }) {
  const state=usePlanner(); const fileRef=useRef<HTMLInputElement>(null); const [copied,setCopied]=useState(false); const payload=encodeShare(state.plan); const shareUrl=`${location.origin}${location.pathname}#plan=${payload}`;
  const importFile=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;try{state.replacePlan(parsePlan(await file.text()));onClose()}catch(err){alert(err instanceof Error?err.message:"Could not import this project.")}};
  return <div className="modal-backdrop small"><section className="dialog" role="dialog" aria-modal="true"><button className="dialog-close icon-button" onClick={onClose}><X/></button>
    {kind==="help"&&<><span className="eyebrow">Quick guide</span><h2>Make yourself at home</h2><div className="shortcut-list"><p><kbd>1</kbd><span>Arrange furniture</span></p><p><kbd>2</kbd><span>Paint floor tiles</span></p><p><kbd>3</kbd><span>Erase floor tiles</span></p><p><kbd>R</kbd><span>Rotate selected piece</span></p><p><kbd>Ctrl Z</kbd><span>Undo the last change</span></p><p><kbd>Delete</kbd><span>Remove selected piece</span></p></div><p className="dialog-note">Tip: switch to Top View whenever you want to check clearances and exact dimensions.</p></>}
    {kind==="project"&&<><span className="eyebrow">Project file</span><h2>Keep a copy somewhere safe</h2><div className="dialog-actions"><button onClick={()=>download(`${state.plan.name}.nook.json`,serializePlan(state.plan),"application/json")}><DownloadSimple/> Export project</button><button onClick={()=>fileRef.current?.click()}><FileArrowUp/> Import project</button><button onClick={()=>{state.replacePlan({...structuredClone(state.plan),id:uid(),name:`${state.plan.name} copy`,createdAt:new Date().toISOString()});onClose()}}><Copy/> Duplicate project</button><button className="danger" onClick={()=>{if(confirm("Start over with a fresh project? Export first if you want to keep this plan.")){state.replacePlan(createSamplePlan("New apartment",state.plan.units));onClose()}}}><Trash/> Start fresh</button><input ref={fileRef} hidden type="file" accept="application/json,.json" onChange={importFile}/></div><p className="dialog-note"><FloppyDisk/> Your current project also autosaves privately in this browser.</p></>}
    {kind==="share"&&<><span className="eyebrow">No account needed</span><h2>Share an editable copy</h2><p>Anyone with this link can open a copy of your plan. Your original stays in this browser.</p><div className="share-box"><input readOnly value={shareUrl}/><button className="primary" disabled={payload.length>48000} onClick={async()=>{await navigator.clipboard.writeText(shareUrl);setCopied(true)}}>{copied?<Check/>:<Copy/>}{copied?"Copied":"Copy link"}</button></div>{payload.length>48000&&<div className="warning"><Info/><span>This project is too large for a reliable link. Export the project file instead.</span></div>}</>}
  </section></div>;
}

const showcaseMode = import.meta.env.DEV ? new URLSearchParams(location.search).get("showcase") : null;
const showcaseItem = import.meta.env.DEV ? new URLSearchParams(location.search).get("item") : null;
const furnitureShowcase = showcaseMode === "furniture" || showcaseMode === "stress" || showcaseMode === "detail";
function createFurnitureShowcase(stress=false,detailId?:string|null) {
  const detail=catalog.find((definition)=>definition.id===detailId);
  const plan=createSamplePlan(stress?"150-piece performance study":detail?`${detail.name} detail study`:"Handcrafted furniture study","metric"); const floor={...plan.floors[0],id:"showcase-floor",name:stress?"Performance study":detail?"Furniture detail":"Furniture study",cells:rectangleCells(stress?32:detail?20:76,stress?20:detail?20:60),walls:[],openings:[],stairs:[]};
  if(stress)return {...plan,floors:[floor],furniture:Array.from({length:150},(_,index)=>{const definition=catalog[index%catalog.length];return {id:`stress-${index}`,catalogId:definition.id,floorId:floor.id,x:350+(index%15)*500,z:350+Math.floor(index/15)*470,rotation:(index%4)*15,widthMm:definition.widthMm,depthMm:definition.depthMm,heightMm:definition.heightMm,variant:Object.keys(variants)[index%Object.keys(variants).length]};}),camera:{...plan.camera,ghostBelow:false,showGrid:false}};
  if(detail)return {...plan,floors:[floor],furniture:[{id:`showcase-${detail.id}`,catalogId:detail.id,floorId:floor.id,x:2500,z:2500,rotation:165,widthMm:detail.widthMm,depthMm:detail.depthMm,heightMm:detail.heightMm,variant:"sage"}],camera:{...plan.camera,ghostBelow:false,showGrid:false}};
  const palette=Object.keys(variants);
  return {...plan,floors:[floor],furniture:catalog.map((definition,index)=>({
    id:`showcase-${definition.id}`,catalogId:definition.id,floorId:floor.id,
    x:1500+(index%7)*2600,z:1600+Math.floor(index/7)*3400,rotation:index%3===0?345:index%3===1?0:15,
    widthMm:definition.widthMm,depthMm:definition.depthMm,heightMm:definition.heightMm,variant:palette[index%palette.length],
  })),camera:{...plan.camera,ghostBelow:false,showGrid:false}};
}

export function App() {
  const state=usePlanner(); const canvasRef=useRef<HTMLCanvasElement>(null); const controllerRef=useRef<SceneController|undefined>(undefined); const placementControlsRef=useRef<HTMLDivElement>(null); const focusDraftControls=useRef(false); const [draft,setDraft]=useState<FurniturePlacement|undefined>(); const [ready,setReady]=useState(false); const [showSetup,setShowSetup]=useState(false); const [dialog,setDialog]=useState<"help"|"project"|"share"|undefined>(undefined); const [muted,setMuted]=useState(true); const saveTimer=useRef<number|undefined>(undefined);
  const floor=state.plan.floors.find((f)=>f.id===state.activeFloorId)!; const area=floor.cells.length*state.plan.gridSizeMm*state.plan.gridSizeMm/1_000_000; const placed=state.plan.furniture.filter((f)=>f.floorId===floor.id).length;
  const startPlacement=(item:CatalogItem,focusControls=false)=>{
    const xs=floor.cells.map((cell)=>cell.x),zs=floor.cells.map((cell)=>cell.z),grid=state.plan.gridSizeMm;
    const x=xs.length?Math.round(((Math.min(...xs)+Math.max(...xs)+1)*grid/2)/50)*50:1700;
    const z=zs.length?Math.round(((Math.min(...zs)+Math.max(...zs)+1)*grid/2)/50)*50:1700;
    const next: FurniturePlacement={id:uid(),catalogId:item.id,floorId:floor.id,x,z,rotation:0,widthMm:item.widthMm,depthMm:item.depthMm,heightMm:item.heightMm,variant:"sage"};
    focusDraftControls.current=focusControls; state.select(undefined); state.setTool("select"); setDraft(next); return next;
  };
  const beginPlacementDrag=(item:CatalogItem,event:ReactPointerEvent<HTMLButtonElement>)=>{
    if(event.button!==0)return; event.preventDefault();
    const next=startPlacement(item); let latest={x:next.x,z:next.z};
    const move=(pointer:PointerEvent)=>{const position=controllerRef.current?.movePreviewFromClient(pointer.clientX,pointer.clientY);if(position)latest=position;};
    const finish=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",finish);window.removeEventListener("pointercancel",finish);setDraft((current)=>current?.id===next.id?{...current,...latest}:current);};
    window.addEventListener("pointermove",move);window.addEventListener("pointerup",finish);window.addEventListener("pointercancel",finish);
  };
  const confirmDraft=()=>{if(!draft)return;state.confirmFurniture(draft);setDraft(undefined)};
  const rotateDraft=(degrees:number)=>setDraft((current)=>current?{...current,rotation:(current.rotation+degrees+360)%360}:current);
  useEffect(()=>{if(furnitureShowcase){state.replacePlan(createFurnitureShowcase(showcaseMode==="stress",showcaseItem));setReady(true);return;}loadPlan().then((plan)=>{if(plan)state.replacePlan(plan);else setShowSetup(true);setReady(true)}).catch(()=>{setShowSetup(true);setReady(true)})},[]);
  useEffect(()=>{if(!ready||furnitureShowcase)return;window.clearTimeout(saveTimer.current);saveTimer.current=window.setTimeout(()=>savePlan(state.plan),450);return()=>window.clearTimeout(saveTimer.current)},[state.plan,ready]);
  useEffect(()=>{if(!ready||!canvasRef.current)return;const controller=new SceneController(canvasRef.current,{onCell:(x,z)=>{const s=usePlanner.getState();if(s.tool==="paint"||s.tool==="erase")s.paintCell(x,z,s.tool==="paint");else if(s.tool==="wall")s.addWall({ax:x,az:z,bx:x+1,bz:z});else if(s.tool==="stairs")s.addStair((x+.5)*s.plan.gridSizeMm,(z+.5)*s.plan.gridSizeMm)},onSelect:(id)=>usePlanner.getState().select(id),onMove:(id,x,z)=>usePlanner.getState().moveFurniture(id,x,z),onDraftMove:(x,z)=>setDraft((current)=>current?{...current,x,z}:current),onWall:(id)=>{const s=usePlanner.getState();if(s.tool==="door"||s.tool==="window")s.addOpening(s.tool,id)}});controllerRef.current=controller;return()=>{controllerRef.current=undefined;controller.dispose()}},[ready]);
  useEffect(()=>{controllerRef.current?.setTool(state.tool);controllerRef.current?.update(state.plan,state.activeFloorId,state.selectedId,draft)},[state.plan,state.activeFloorId,state.selectedId,state.tool,ready,draft]);
  useEffect(()=>{setDraft(undefined)},[state.activeFloorId]);
  useEffect(()=>{if(!draft)return;let frame=0;const sync=()=>{const position=controllerRef.current?.projectPreview();const controls=placementControlsRef.current;if(controls&&position){controls.style.left=`${position.x}px`;controls.style.top=`${position.y}px`;controls.style.opacity="1";if(focusDraftControls.current){controls.querySelector<HTMLButtonElement>(".placement-confirm")?.focus();focusDraftControls.current=false}}frame=requestAnimationFrame(sync)};frame=requestAnimationFrame(sync);return()=>cancelAnimationFrame(frame)},[draft?.id]);
  useEffect(()=>{const onKey=(e:KeyboardEvent)=>{const tag=(e.target as HTMLElement).tagName;if(tag==="INPUT")return;if(draft){if(e.key==="Escape"||e.key==="Delete"){e.preventDefault();setDraft(undefined)}else if(e.key.toLowerCase()==="r"){e.preventDefault();rotateDraft(15)}else if(e.key==="Enter"&&tag!=="BUTTON"){e.preventDefault();confirmDraft()}return}if(tag==="BUTTON")return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"){e.preventDefault();e.shiftKey?state.redo():state.undo()}else if(e.key==="Delete")state.deleteSelected();else if(e.key.toLowerCase()==="r"&&state.selectedId){const item=usePlanner.getState().plan.furniture.find(f=>f.id===state.selectedId);if(item)state.updateFurniture(item.id,{rotation:(item.rotation+15)%360})}else if(e.key==="1")state.setTool("select");else if(e.key==="2")state.setTool("paint");else if(e.key==="3")state.setTool("erase")};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[state.selectedId,draft]);
  useEffect(()=>{if(muted)return;const AudioContextClass=window.AudioContext;const context=new AudioContextClass();const gain=context.createGain();gain.gain.value=.012;gain.connect(context.destination);const tones=[174,220].map((frequency,index)=>{const oscillator=context.createOscillator();oscillator.type=index?"sine":"triangle";oscillator.frequency.value=frequency;const toneGain=context.createGain();toneGain.gain.value=index?.3:.18;oscillator.connect(toneGain).connect(gain);oscillator.start();return oscillator});return()=>{tones.forEach(t=>t.stop());void context.close()}},[muted]);
  const takeScreenshot=()=>{const data=controllerRef.current?.screenshot();if(!data)return;const a=document.createElement("a");a.href=data;a.download=`${state.plan.name}.png`;a.click()};
  if(!ready)return <main className="loading-screen"><img src="/assets/nook-nest-icon.png"/><span>Opening your little home…</span></main>;
  return <main className="app-shell">
    <header className="topbar"><div className="brand"><img src="/assets/nook-nest-icon.png" alt=""/><div><span>Nook &amp; Nest</span><small>cozy apartment planner</small></div></div><div className="project-title"><input aria-label="Project name" value={state.plan.name} onChange={(e)=>state.rename(e.target.value)}/><span className="saved"><Check weight="bold"/> Saved locally</span></div><nav className="top-actions"><button className="icon-button" onClick={state.undo} disabled={!state.past.length} aria-label="Undo"><ArrowCounterClockwise/></button><button className="icon-button" onClick={state.redo} disabled={!state.future.length} aria-label="Redo"><ArrowClockwise/></button><span className="divider"/><button onClick={()=>setDialog("share")}><ShareNetwork/> Share</button><button onClick={()=>setDialog("project")}><FloppyDisk/> Project</button><button className="icon-button" onClick={()=>setDialog("help")} aria-label="Help"><Info/></button></nav></header>
    <section className="workspace"><Catalog onBeginDrag={beginPlacementDrag} onStartPlacement={(item)=>startPlacement(item,true)}/><section className="canvas-stage"><canvas ref={canvasRef} aria-label="Interactive 3D apartment editor"/><div className="view-toggle"><button className={state.plan.camera.mode==="isometric"?"active":""} onClick={()=>state.setView("isometric")}><Buildings/> Cozy view</button><button className={state.plan.camera.mode==="top"?"active":""} onClick={()=>state.setView("top")}><GridFour/> Top view</button><button className={state.plan.camera.mode==="dollhouse"?"active":""} onClick={()=>state.setView("dollhouse")}><SquaresFour/> Dollhouse</button></div>
      {draft&&<div ref={placementControlsRef} className="placement-controls" role="toolbar" aria-label={`Place ${catalog.find((item)=>item.id===draft.catalogId)?.name??"furniture"}`}><button className="placement-cancel" onClick={()=>setDraft(undefined)} title="Cancel placement" aria-label="Cancel placement"><X size={18} weight="bold"/></button><button onClick={()=>rotateDraft(-15)} title="Rotate left" aria-label="Rotate left"><ArrowCounterClockwise size={18}/></button><button className="placement-confirm" onClick={confirmDraft} onKeyDown={(event)=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();confirmDraft()}}} title="Confirm placement" aria-label="Confirm placement"><Check size={19} weight="bold"/></button><button onClick={()=>rotateDraft(15)} title="Rotate right" aria-label="Rotate right"><ArrowClockwise size={18}/></button></div>}
      <div className="tool-dock">{tools.map(({id,label,icon:Icon})=><button key={id} className={state.tool===id?"active":""} onClick={()=>{setDraft(undefined);state.setTool(id)}} title={label}><Icon size={20} weight={state.tool===id?"fill":"regular"}/><span>{label}</span></button>)}</div>
      <div className="canvas-tools"><button className={state.plan.camera.showGrid?"active":""} onClick={()=>state.toggleCameraSetting("showGrid")} title="Grid labels"><Ruler/></button><button className={state.plan.camera.showClearance?"active":""} onClick={()=>state.toggleCameraSetting("showClearance")} title="Clearance guides"><Eye/></button><button onClick={takeScreenshot} title="Save screenshot"><Camera/></button><button onClick={()=>setMuted(!muted)} title={muted?"Turn sound on":"Mute sound"}>{muted?<SpeakerSlash/>:<SpeakerHigh/>}</button></div>
      <div className="floor-stats"><span><strong>{area.toFixed(1)} m²</strong> floor area</span><i/><span><strong>{placed}</strong> pieces</span><i/><span>Tile {formatLength(state.plan.gridSizeMm,state.plan.units)}</span></div>
    </section><Inspector/></section>
    <footer className="floorbar"><div className="floor-tabs">{state.plan.floors.map((f,i)=><button key={f.id} className={f.id===state.activeFloorId?"active":""} onClick={()=>state.setActiveFloor(f.id)}><span>{i+1}</span>{f.name}</button>)}<button className="add-floor" onClick={state.addFloor}><Plus/> Add floor</button></div><div className="floor-options"><label><input type="checkbox" checked={state.plan.camera.ghostBelow} onChange={()=>state.toggleCameraSetting("ghostBelow")}/><span/> Ghost floor below</label><button className="icon-button" disabled={state.plan.floors.length===1} onClick={state.deleteFloor} title="Delete active floor"><Trash/></button></div></footer>
    {showSetup&&<SetupDialog onDone={()=>setShowSetup(false)}/>} {dialog&&<AppDialog kind={dialog} onClose={()=>setDialog(undefined)}/>}<div className="desktop-gate"><img src="/assets/nook-nest-icon.png"/><h1>Your nest needs a little more room</h1><p>Nook &amp; Nest is ready for full editing on a desktop or wide tablet. Open this page on a larger screen to decorate.</p></div>
  </main>;
}
