import { useEffect, useMemo, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react';
import { Door, DoorOpen, Wall, Eraser, ArrowsOut, SquaresFour, CookingPot, Cursor, ArrowCounterClockwise, ArrowClockwise, Check, FileArrowUp, GridFour, Hand, Minus, Plus, Ruler, Trash, X } from '@phosphor-icons/react';
import { catalog, isDoor, isWallOpening } from './catalog';
import { uid } from './domain';
import { floorBoundaryWalls } from './floorGeometry';
import { separateBlueprintRectangle, fixturesAfterWallCuts, combineBlueprintRooms, openPlanAreas, fixtureName, blueprintPlan, blueprintProblems, draftFromFloor, fixtureAt, roomKinds, roomGroups, type BlueprintDraft, type BlueprintRoom, type RoomKind } from './blueprint';
import { renderReference, type PlanReference } from './blueprintImport';
import {roomsOnlyRecognition,recognizeReference,draftFromRecognition} from './blueprintRecognition';
import {clearRecognitionCache} from './recognitionCache';
import { snapWindow } from './windows';
import { usePlanner } from './store';
import type { PlanDocumentV1 } from './types';
import './blueprint.css';
import {BlueprintSymbol,planItems,openingItems} from './BlueprintSymbol';
import {snapRoomMove} from './blueprintSnapping';
import {scaleAssessment,type Recognition} from './recognitionContract';
import {ScaleReview} from './ScaleReview';
import {useAppearance} from './useWelcomeTheme';

type Point={x:number;z:number};
type Mode='select'|'room'|'wall'|'fixture'|'scale'|'pan'|'resize'|'cut'|'combine';
const emptyDraft=():BlueprintDraft=>({rooms:[],walls:[],omittedWalls:[],fixtures:[]});
const colors:Record<RoomKind,string>={Living:'#d8dfc5',Bedroom:'#e6d4ce',Dining:'#eadab4',Office:'#c9dddd',Kitchen:'#ead5ad',Bathroom:'#bfdae3',Laundry:'#d1cce4',Hall:'#e5e1d6',Outdoor:'#bcd2ae',Closet:'#ddd2bd'};
function LengthField({label,value,factor,onChange}:{label:string;value:number;factor:number;onChange:(v:number)=>void}) {
  const [text,setText]=useState('');useEffect(()=>setText((value/factor).toFixed(factor===1?0:3)),[value,factor]);
  return <label>{label}<input type="number" step="any" value={text} onChange={e=>setText(e.target.value)} onBlur={()=>{const n=Number(text);if(text.trim()&&Number.isFinite(n))onChange(Math.round(n*factor));else setText((value/factor).toFixed(3));}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/></label>;
}
export function BlueprintStudio({onClose,onCreated}:{onClose:()=>void;onCreated?:()=>void}) {
  const appearance=useAppearance();
  const savedDark=usePlanner(s=>!!s.plan.camera.darkMode);
  const [base]=useState(()=>usePlanner.getState().plan),[floorId]=useState(()=>usePlanner.getState().activeFloorId);
  const [initial]=useState(()=>draftFromFloor(base,floorId));
  const [draft,setDraft]=useState<BlueprintDraft>(initial),[past,setPast]=useState<BlueprintDraft[]>([]),[future,setFuture]=useState<BlueprintDraft[]>([]);
  const [mode,setMode]=useState<Mode>('select'),[kind,setKind]=useState<RoomKind>('Living'),[selected,setSelected]=useState<string>(),[review,setReview]=useState(false),[checked,setChecked]=useState(false);
  const [reference,setReference]=useState<PlanReference>(),[file,setFile]=useState<File>(),[page,setPage]=useState(1),[rotation,setRotation]=useState(0),[loading,setLoading]=useState(false),[opacity,setOpacity]=useState(.65),[imageScale,setImageScale]=useState(10),[calibrated,setCalibrated]=useState(false);
  const [guidance,setGuidance]=useState('');
  const [error,setError]=useState(''),[notice,setNotice]=useState(''),[unit,setUnit]=useState<'m'|'ft'|'mm'>(base.units==='imperial'?'ft':'m');
  const [analysisNotes,setAnalysisNotes]=useState<string[]>([]),[printedDimensions,setPrintedDimensions]=useState<string[]>([]);
  const [menu,setMenu]=useState<'file'|'view'>(),[sidebar,setSidebar]=useState(true),[magnetic,setMagnetic]=useState(true),[snapped,setSnapped]=useState(false);
  const [palette,setPalette]=useState<'fixtures'|'openings'>();
  const paletteStart=useRef<{x:number;y:number}|undefined>(undefined),skipPaletteClick=useRef(false);
  const [palettePreview,setPalettePreview]=useState<{id:string;doorless?:boolean;x:number;z:number}>();
  const [editParts,setEditParts]=useState(false);
  const [combineIds,setCombineIds]=useState<string[]>([]),[combinedName,setCombinedName]=useState(''),[combinedKind,setCombinedKind]=useState<RoomKind>('Bedroom'),[combineNamed,setCombineNamed]=useState(false);
  const [pendingScale,setPendingScale]=useState<{reference:PlanReference;detection:Recognition;file:File;page:number;rotation:number;status:string;message:string}>();
  const analysisAbort=useRef<AbortController | undefined>(undefined);
  const [scaleLine,setScaleLine]=useState<{a:Point;b:Point}>(),[knownLength,setKnownLength]=useState(''),[fixtureId,setFixtureId]=useState('washer');
  const [entrance,setEntrance]=useState(false);
  const [view,setView]=useState({x:-500,z:-500,width:14000,height:11000}),[cursor,setCursor]=useState<Point>();
  const [gesture,setGesture]=useState<{a:Point;b:Point;before:BlueprintDraft;selected?:string;handle?:string;wholeRoom?:boolean;mode:Mode;view:typeof view}>();
  const svgRef=useRef<SVGSVGElement>(null),dialogRef=useRef<HTMLDialogElement>(null),loadGeneration=useRef(0),uploadRef=useRef<HTMLInputElement>(null);
  const handleSize=24/Math.max(.00001,Math.min((svgRef.current?.clientWidth||700)/view.width,(svgRef.current?.clientHeight||700)/view.height));
  const factor=unit==='m'?1000:unit==='ft'?304.8:1;
  const floorName=base.floors.find(f=>f.id===floorId)!.name;
  const currentPlan=usePlanner(s=>s.plan);
  const stale=currentPlan!==base;
  useEffect(()=>{dialogRef.current?.showModal();return()=>{loadGeneration.current++;analysisAbort.current?.abort();};},[]);
  const computed=useMemo(()=>{try{return {plan:blueprintPlan(base,floorId,draft),error:''};}catch(e){return {plan:undefined,error:(e as Error).message};}},[base,floorId,draft]);
  const plan=computed.plan,floor=plan?.floors.find(f=>f.id===floorId);
  const walls=useMemo(()=>floor?[...floorBoundaryWalls(floor,base.gridSizeMm),...floor.walls]:[],[floor,base.gridSizeMm]);
  const problems=useMemo(()=>plan?blueprintProblems(plan,floorId):[],[plan,floorId]);
  const groupedRooms=useMemo(()=>roomGroups(draft.rooms),[draft.rooms]);
  const spaces=groupedRooms;
  const combining=groupedRooms.filter(g=>combineIds.includes(g.id));
  useEffect(()=>{if(combineNamed)return;const preferred=combining.find(g=>g.kind==='Bedroom')??combining[0];if(preferred){setCombinedName(/^m[ ._-]*bedroom$/i.test(preferred.name)?'Master bedroom':preferred.name);setCombinedKind(preferred.kind);}},[combineIds,draft.rooms,combineNamed]);
  const toggleCombine=(id:string)=>setCombineIds(ids=>ids.includes(id)?ids.filter(i=>i!==id):[...ids,id]);
  const selectedPart=draft.rooms.find(r=>r.id===selected);
  const room=groupedRooms.find(r=>r.parts.some(p=>p.id===selected)),fixture=draft.fixtures.find(f=>f.id===selected);
  const commit=(next:BlueprintDraft)=>{setPast(p=>[...p.slice(-39),draft]);setFuture([]);setDraft(next);setChecked(false);setError('');};
  const fit=(rooms=draft.rooms,ref=reference,scale=imageScale)=>{
    const xs=rooms.flatMap(r=>[r.x,r.x+r.width]),zs=rooms.flatMap(r=>[r.z,r.z+r.depth]);
    if(ref){xs.push(0,ref.width*scale);zs.push(0,ref.height*scale);}
    if(!xs.length){setView({x:-500,z:-500,width:14000,height:11000});return;}
    const x=Math.min(...xs)-500,z=Math.min(...zs)-500;setView({x,z,width:Math.max(2000,Math.max(...xs)-x+500),height:Math.max(2000,Math.max(...zs)-z+500)});
  };
  useEffect(()=>{fit();},[]);
  const close=()=>{if((past.length||reference)&&!window.confirm('Discard this unconfirmed floor-plan draft? Your 3D home has not changed.'))return;onClose();};
  async function load(nextFile:File,nextPage=1,nextRotation=0,force=false) {
    setMenu(undefined);setPendingScale(undefined);setFile(nextFile);setPage(nextPage);setRotation(nextRotation);
    analysisAbort.current?.abort();const controller=new AbortController();analysisAbort.current=controller;
    const generation=++loadGeneration.current;setLoading(true);setError('');setNotice('Reading rooms and printed measurements…');
    try {
      const result=await renderReference(nextFile,nextPage,nextRotation);if(generation!==loadGeneration.current)return;
      let costStatus='';
      const detection=await recognizeReference(result,controller.signal,{model:'gpt-5.6-luna',force,guidance,status:text=>{costStatus=text;}});if(generation!==loadGeneration.current)return;
      const assessment=scaleAssessment(detection);
      if(assessment.scale===undefined){setPendingScale({reference:result,detection,file:nextFile,page:nextPage,rotation:nextRotation,status:costStatus,message:assessment.warnings.join(' ')});return;}
      acceptDetection(result,detection,nextFile,nextPage,nextRotation,costStatus);
    }catch(e){if(generation===loadGeneration.current)setError((e as Error).message||'This file could not be opened.');}finally{if(generation===loadGeneration.current)setLoading(false);}
  }
  function acceptDetection(result:PlanReference,detection:Recognition,nextFile:File,nextPage:number,nextRotation:number,costStatus:string,confirmedScale?:number) {
    const recognized=draftFromRecognition(base,floorId,roomsOnlyRecognition(detection),confirmedScale);
    setReference(result);setFile(nextFile);setPage(nextPage);setRotation(nextRotation);setCalibrated(true);setScaleLine(undefined);setMode('select');setImageScale(recognized.scale);
    commit(recognized.draft);setSelected(undefined);setMenu(undefined);setReview(false);fit(recognized.draft.rooms,result,recognized.scale);
    setAnalysisNotes(recognized.notes);setPrintedDimensions(recognized.dimensions);setPendingScale(undefined);
    setNotice(`${roomGroups(recognized.draft.rooms).length} spaces imported. ${costStatus}`);
  }
  const point=(event:{clientX:number;clientY:number}):Point=>{const svg=svgRef.current!,matrix=svg.getScreenCTM();if(!matrix)return {x:0,z:0};const p=new DOMPoint(event.clientX,event.clientY).matrixTransform(matrix.inverse());return {x:Math.round(p.x),z:Math.round(p.y)};};
  const snap=(p:Point):Point=>{
    const xPoints=draft.rooms.flatMap(r=>[r.x,r.x+r.width]),zPoints=draft.rooms.flatMap(r=>[r.z,r.z+r.depth]);
    for(const w of draft.walls){xPoints.push(w.ax*base.gridSizeMm,w.bx*base.gridSizeMm);zPoints.push(w.az*base.gridSizeMm,w.bz*base.gridSizeMm);}
    const closest=(n:number,values:number[])=>{let best=Math.round(n/10)*10,dist=Math.min(120,view.width/100);for(const v of values)if(Math.abs(v-n)<dist){best=v;dist=Math.abs(v-n);}return best;};
    return {x:closest(p.x,xPoints),z:closest(p.z,zPoints)};
  };
  function down(e:ReactPointerEvent<SVGSVGElement>) {
    if(e.button!==0||review||loading)return;e.currentTarget.setPointerCapture(e.pointerId);setError('');
    const handle=(e.target as Element).closest('[data-handle]')?.getAttribute('data-handle');
    const resizeId=(e.target as Element).closest('[data-part]')?.getAttribute('data-part');
    if(handle&&resizeId){const p=point(e);setGesture({a:p,b:p,before:draft,selected:resizeId,handle,wholeRoom:!editParts,mode:'resize',view});return;}
    const raw=point(e),hit=(e.target as Element).closest('[data-object]')?.getAttribute('data-object'),p=mode==='scale'||mode==='pan'||mode==='select'||draft.fixtures.some(f=>f.id===hit)?raw:snap(raw);
    if(mode==='combine'||(mode==='select'&&e.shiftKey)){const g=groupedRooms.find(r=>r.parts.some(p=>p.id===hit));if(g){if(mode!=='combine'){setMode('combine');setCombineNamed(false);setCombineIds([...new Set([...(room?[room.id]:[]),g.id])]);}else toggleCombine(g.id);}return;}
    if(mode==='cut'){const wall=walls.filter(w=>floor?.walls.some(f=>f.id===w.id)).map(w=>{const horizontal=w.az===w.bz,line=(horizontal?w.az:w.ax)*base.gridSizeMm,start=Math.min(horizontal?w.ax:w.az,horizontal?w.bx:w.bz)*base.gridSizeMm,end=Math.max(horizontal?w.ax:w.az,horizontal?w.bx:w.bz)*base.gridSizeMm,along=horizontal?raw.x:raw.z;return {w,horizontal,line,along:Math.max(start,Math.min(end,along)),distance:Math.hypot((horizontal?raw.z:raw.x)-line,Math.max(start-along,0,along-end))};}).sort((a,b)=>a.distance-b.distance)[0];if(!wall||wall.distance>view.width/50){setError('Start on an inside wall to remove a section.');return;}const p=wall.horizontal?{x:wall.along,z:wall.line}:{x:wall.line,z:wall.along};setGesture({a:p,b:p,before:draft,selected:wall.w.id,mode:'cut',view});return;}
    if(mode==='fixture'){placeItem(fixtureId,entrance,raw);return;}
    const id=(e.target as Element).closest('[data-object]')?.getAttribute('data-object')??undefined;
    if(mode==='select'){setSelected(id);if(id)setSidebar(true);}
    setGesture({a:p,b:p,before:draft,selected:id,mode,view});
  }
  function move(e:ReactPointerEvent<SVGSVGElement>) {
    const raw=point(e);setCursor(mode==='scale'||mode==='pan'?raw:snap(raw));if(!gesture)return;
    const p=gesture.mode==='select'||gesture.mode==='scale'||gesture.mode==='pan'||gesture.mode==='cut'||gesture.before.fixtures.some(f=>f.id===gesture.selected)?raw:snap(raw);setGesture(g=>g?{...g,b:p}:g);
    if(gesture.mode==='resize'){const group=roomGroups(gesture.before.rooms).find(g=>g.parts.some(p=>p.id===gesture.selected));const others=gesture.before.rooms.filter(r=>!group?.parts.some(p=>p.id===r.id));const closest=(n:number,values:number[])=>{let best=Math.round(n/10)*10,distance=magnetic?Math.min(150,view.width/100):0;for(const v of values)if(Math.abs(v-n)<distance){best=v;distance=Math.abs(v-n);}return best;};const rx=closest(raw.x,others.flatMap(r=>[r.x,r.x+r.width])),rz=closest(raw.z,others.flatMap(r=>[r.z,r.z+r.depth]));setSnapped(rx!==Math.round(raw.x/10)*10||rz!==Math.round(raw.z/10)*10);const old=gesture.wholeRoom?group:gesture.before.rooms.find(r=>r.id===gesture.selected);if(!old)return;const west=gesture.handle!.includes('w'),north=gesture.handle!.includes('n'),x=west?Math.min(rx,old.x+old.width-100):old.x,z=north?Math.min(rz,old.z+old.depth-100):old.z,width=west?old.x+old.width-x:Math.max(100,rx-old.x),depth=north?old.z+old.depth-z:Math.max(100,rz-old.z);setDraft({...gesture.before,rooms:gesture.before.rooms.map(r=>gesture.wholeRoom&&group?.parts.some(p=>p.id===r.id)?{...r,x:Math.round(x+(r.x-old.x)*width/old.width),z:Math.round(z+(r.z-old.z)*depth/old.depth),width:Math.round((r.x+r.width-old.x)*width/old.width)-Math.round((r.x-old.x)*width/old.width),depth:Math.round((r.z+r.depth-old.z)*depth/old.depth)-Math.round((r.z-old.z)*depth/old.depth)}:!gesture.wholeRoom&&r.id===old.id?{...r,x,z,width,depth}:r)});return;}
    if(gesture.mode==='pan'){setView(v=>({...v,x:v.x+gesture.a.x-raw.x,z:v.z+gesture.a.z-raw.z}));return;}
    if(gesture.mode!=='select'||!gesture.selected)return;
    const dx=p.x-gesture.a.x,dz=p.z-gesture.a.z,id=gesture.selected;
    const old=gesture.before.fixtures.find(f=>f.id===id);
    const moved=old&&plan?snapWindow(plan,{...old,x:Math.round(old.x+dx),z:Math.round(old.z+dz)}):undefined;
    const result=snapRoomMove(gesture.before.rooms,id,dx,dz,magnetic?Math.min(150,view.width/100):0);setSnapped(result.snapped);
    setDraft({...gesture.before,rooms:result.rooms,fixtures:gesture.before.fixtures.map(f=>f.id===id&&moved?moved:f)});
  }
  function up(e:ReactPointerEvent<SVGSVGElement>) {
    if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);
    if(!gesture)return;const {a,b,mode:active,before}=gesture;setGesture(undefined);setSnapped(false);
    if(active==='scale'){if(Math.hypot(b.x-a.x,b.z-a.z)>50)setScaleLine({a,b});return;}
    if(active==='select'||active==='resize'){if(JSON.stringify(before)!==JSON.stringify(draft)){setPast(p=>[...p.slice(-39),before]);setFuture([]);setChecked(false);}return;}
    if(active==='room') {
      const width=Math.abs(a.x-b.x),depth=Math.abs(a.z-b.z);if(width<100||depth<100)return;
      const r:BlueprintRoom={id:uid(),name:`${kind} ${draft.rooms.filter(r=>r.kind===kind).length+1}`,kind,x:Math.min(a.x,b.x),z:Math.min(a.z,b.z),width,depth,enclosed:!['Hall','Outdoor','Living','Dining'].includes(kind)};
      commit({...draft,rooms:[...draft.rooms,r]});setSelected(r.id);setMode('select');
    }
    if(active==='cut'){const wall=walls.find(w=>w.id===gesture.selected);if(!wall)return;const horizontal=wall.az===wall.bz,start=Math.min(horizontal?wall.ax:wall.az,horizontal?wall.bx:wall.bz)*base.gridSizeMm,end=Math.max(horizontal?wall.ax:wall.az,horizontal?wall.bx:wall.bz)*base.gridSizeMm,along=Math.max(start,Math.min(end,horizontal?b.x:b.z)),finish=horizontal?{x:along,z:a.z}:{x:a.x,z:along};if(Math.hypot(finish.x-a.x,finish.z-a.z)<50)return;const cut={id:uid(),ax:a.x/base.gridSizeMm,az:a.z/base.gridSizeMm,bx:finish.x/base.gridSizeMm,bz:finish.z/base.gridSizeMm};commit({...draft,wallCuts:[...draft.wallCuts??[],cut],fixtures:fixturesAfterWallCuts(draft.fixtures,[cut],base.gridSizeMm)});setNotice('Wall section removed. Doors or windows on that removed span were removed with it. Undo restores them.');return;}
    if(active==='wall') {
      const end=Math.abs(b.x-a.x)>Math.abs(b.z-a.z)?{x:b.x,z:a.z}:{x:a.x,z:b.z};if(Math.hypot(end.x-a.x,end.z-a.z)<100)return;
      const grid=base.gridSizeMm,id=uid();commit({...draft,walls:[...draft.walls,{id,ax:a.x/grid,az:a.z/grid,bx:end.x/grid,bz:end.z/grid}]});setSelected(id);setMode('select');
    }
  }
  const remove=()=>{if(!selected)return;commit({...draft,rooms:draft.rooms.filter(r=>!room?.parts.some(p=>p.id===r.id)&&r.id!==selected),fixtures:draft.fixtures.filter(f=>f.id!==selected),walls:draft.walls.filter(w=>w.id!==selected),omittedWalls:[...draft.omittedWalls,selected]});setSelected(undefined);};
  const updateRoom=(patch:Partial<BlueprintRoom>)=>{if((patch.width!==undefined&&patch.width<100)||(patch.depth!==undefined&&patch.depth<100))return;if(room)commit({...draft,rooms:draft.rooms.map(r=>room.parts.some(p=>p.id===r.id)?{...r,...patch,x:Math.round((patch.x??room.x)+(r.x-room.x)*(patch.width??room.width)/room.width),z:Math.round((patch.z??room.z)+(r.z-room.z)*(patch.depth??room.depth)/room.depth),width:Math.round(r.width*(patch.width??room.width)/room.width),depth:Math.round(r.depth*(patch.depth??room.depth)/room.depth)}:r)});};
  const updateFixture=(patch:Partial<NonNullable<typeof fixture>>)=>{if(fixture&&plan)commit({...draft,fixtures:draft.fixtures.map(f=>f.id===fixture.id?snapWindow(plan,{...f,...patch}):f)});};
  function placeItem(id:string,doorless:boolean|undefined,p:Point) {
    if(!plan){setError('Draw a room first.');return;}
    try{const item={...fixtureAt(plan,floorId,id,p.x,p.z),...(doorless?{doorless:true}:{})};commit({...draft,fixtures:[...draft.fixtures,item]});setSelected(item.id);setSidebar(true);setMode('select');setPalette(undefined);}catch(e){setError((e as Error).message);}
  }
  function combineSelected() {
    try{if(combineIds.length<2||!combinedName.trim())return;let next=draft;const remaining=[...combineIds],first=remaining.shift();if(!first)return;
      while(remaining.length){let joined=false;for(let i=0;i<remaining.length;i++){try{next=combineBlueprintRooms(next,first,remaining[i],base.gridSizeMm);remaining.splice(i,1);joined=true;break;}catch{/* Try another adjacent piece in the selection. */}}if(!joined)throw new Error('Selected areas must touch or overlap. Move their edges together first.');}
      const merged=roomGroups(next.rooms).find(g=>g.parts.some(p=>p.id===first))!;const ids=new Set(merged.parts.map(p=>p.id));next={...next,rooms:next.rooms.map(r=>ids.has(r.id)?{...r,name:combinedName.trim(),kind:combinedKind,enclosed:!['Living','Dining','Hall','Outdoor'].includes(combinedKind)}:r)};
      commit(next);setEditParts(false);setSelected(first);setCombineIds([]);setMode('select');setNotice('Areas combined. Rename or resize the room in Edit room.');
    }catch(e){setError((e as Error).message);}
  }
  function paletteButton(item:{id:string;label:string;symbol:string;doorless?:boolean}) {
    return <button key={item.label} aria-label={`Place ${item.label}`} title={`Drag ${item.label} onto plan`} onPointerDown={e=>{if(e.button!==0)return;skipPaletteClick.current=false;paletteStart.current={x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture?.(e.pointerId);}} onPointerMove={e=>{const start=paletteStart.current;if(!start||Math.hypot(e.clientX-start.x,e.clientY-start.y)<5)return;const bounds=svgRef.current!.getBoundingClientRect();if(e.clientX>=bounds.left&&e.clientX<=bounds.right&&e.clientY>=bounds.top&&e.clientY<=bounds.bottom)setPalettePreview({...item,...point(e)});else setPalettePreview(undefined);}} onPointerUp={e=>{const start=paletteStart.current;paletteStart.current=undefined;if(!start||Math.hypot(e.clientX-start.x,e.clientY-start.y)<5)return;skipPaletteClick.current=true;const bounds=svgRef.current!.getBoundingClientRect();if(e.clientX>=bounds.left&&e.clientX<=bounds.right&&e.clientY>=bounds.top&&e.clientY<=bounds.bottom)placeItem(item.id,item.doorless,point(e));setPalettePreview(undefined);}} onPointerCancel={()=>{paletteStart.current=undefined;setPalettePreview(undefined);}} onClick={()=>{if(skipPaletteClick.current){skipPaletteClick.current=false;return;}setFixtureId(item.id);setEntrance(!!item.doorless);setMode('fixture');setPalette(undefined);}}><BlueprintSymbol symbol={item.symbol} width={38} height={38}/><span>{item.label}</span></button>;
  }
  const zoom=(amount:number)=>setView(v=>{const width=Math.max(1500,Math.min(150000,v.width*amount)),height=v.height*width/v.width;return {x:v.x+(v.width-width)/2,z:v.z+(v.height-height)/2,width,height};});
  const apply=()=>{if(!plan||!checked||stale||problems.length)return;try{usePlanner.getState().commitDesign(base,plan);onCreated?.();onClose();}catch(e){setError((e as Error).message);}};
  return <dialog ref={dialogRef} className="blueprint-dialog" data-theme={(appearance?.dark??savedDark)?'dark':'light'} aria-labelledby="blueprint-title" onCancel={e=>{e.preventDefault();if(menu||palette||mode!=='select'){setMenu(undefined);setPalette(undefined);setMode('select');setCombineIds([]);}else close();}} onKeyDown={e=>{e.stopPropagation();if((e.key==='Delete'||e.key==='Backspace')&&!(e.target as Element).closest('input,select,textarea')&&!review){e.preventDefault();remove();}}}>
    <header className="bp-header"><div><span className="eyebrow">{floorName} · unsaved draft</span><h1 id="blueprint-title">Floor plan studio</h1></div><nav className="bp-menus" aria-label="Studio menus"><button disabled={loading||review} aria-expanded={menu==='file'} onClick={()=>setMenu(menu==='file'?undefined:'file')}>File</button><button aria-expanded={menu==='view'} onClick={()=>setMenu(menu==='view'?undefined:'view')}>View</button></nav><button disabled={loading||review||!file} title={file?"Run a fresh Luna analysis, bypassing saved results":"Import a PDF or image first"} onClick={()=>{if(file&&window.confirm("Run a fresh analysis? This uses Luna again and may incur an API charge. It replaces the studio drawing on success; Undo restores your edits."))void load(file,page,rotation,true);}}><ArrowClockwise size={18}/> Reanalyze</button><button onClick={close} aria-label="Close floor plan studio"><X size={22}/></button></header>
    <div className="bp-file-menu" hidden={menu!=='file'}><button disabled={loading} onClick={()=>{uploadRef.current?.click();setMenu(undefined);}}><FileArrowUp/> Import PDF or image…</button><small>New scans use online analysis and may incur an API charge. Cached scans are reused.</small><details className="bp-scan-guidance"><summary>Analysis guidance (optional)</summary><label>Tell Luna about this layout<textarea aria-label="Analysis guidance" maxLength={1500} rows={4} value={guidance} disabled={loading} onChange={e=>setGuidance(e.target.value)} placeholder="Example: The hallway stays left of the bedroom closets. The small room below the bathroom is laundry."/></label><small>Used on your next import or Reanalyze. Describe room boundaries, names or corrections; dimensions still need review.</small></details><input hidden ref={uploadRef} type="file" accept=".pdf,.png,.jpg,.jpeg,.webp" aria-label="Upload floor plan reference" onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;if(draft.rooms.length&&!window.confirm('Analyze a new floor plan from this file? This replaces only the unconfirmed drawing; your 3D home is unchanged.'))return;void load(f);}}/>
        <div className="bp-button-row"><button onClick={()=>{if(draft.rooms.length&&!window.confirm('Clear this unconfirmed drawing?'))return;commit(emptyDraft());setSelected(undefined);setReview(false);fit([]);}}>Blank drawing</button><button onClick={()=>{if(past.length&&!window.confirm('Replace the draft with the current 3D floor?'))return;commit(draftFromFloor(base,floorId));setReference(undefined);setFile(undefined);setSelected(undefined);fit(initial.rooms,undefined);}}>Use current floor</button></div>
<button onClick={()=>setNotice(clearRecognitionCache()?'Saved analyses cleared. Future imports may incur a charge.':'Could not clear cache.')}>Clear saved analyses</button></div>
    <div className="bp-file-menu bp-view-menu" hidden={menu!=='view'}>        {reference&&<div className="bp-reference-controls"><strong title={reference.name}>{reference.name}</strong><div className="bp-button-row"><label>PDF page<select aria-label="PDF page" disabled={loading} value={page} onChange={e=>file&&void load(file,Number(e.target.value),rotation)}>{Array.from({length:reference.pages},(_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></label><button disabled={loading} onClick={()=>file&&void load(file,page,(rotation+90)%360)}><ArrowClockwise/> Rotate scan</button></div><label>Reference opacity<input type="range" min="0" max="1" step="0.05" value={opacity} onChange={e=>setOpacity(Number(e.target.value))}/></label><small>Changing the page or orientation analyzes it again and replaces this draft.</small></div>}
        <label>Measurement units<select value={unit} onChange={e=>setUnit(e.target.value as typeof unit)}><option value="m">Metres</option><option value="ft">Feet (decimal)</option><option value="mm">Millimetres</option></select></label>
        {reference&&<div className="bp-calibration"><button disabled={draft.rooms.length>0} className={mode==='scale'?'active':''} onClick={()=>setMode('scale')}><Ruler/> {calibrated?'Scale set · recalibrate':'Set image scale'}</button>{mode==='scale'&&<><p>Drag between the ends of a printed dimension. Enter its real length below.</p><label>Known length ({unit})<input type="number" min="0" step="any" value={knownLength} onChange={e=>setKnownLength(e.target.value)}/></label><button disabled={!scaleLine||draft.rooms.length>0} onClick={()=>{if(!scaleLine)return;const length=Number(knownLength)*factor,distance=Math.hypot(scaleLine.b.x-scaleLine.a.x,scaleLine.b.z-scaleLine.a.z),next=imageScale*length/distance;if(!Number.isFinite(next)||length<100||length>60000||next<.1||next>200){setError('Use a known length from 0.1 to 60 metres and a longer reference line.');return;}setImageScale(next);setCalibrated(true);setScaleLine(undefined);setError('');setMode('room');fit([],reference,next);}}>Apply scale</button></>}{calibrated&&<small><Check/> Scale calibrated. Check each room’s exact size before conversion.</small>}</div>}
        <details><summary>Measurements & analysis notes</summary><ul>{printedDimensions.map((d,i)=><li key={i}>{d}</li>)}{analysisNotes.map((d,i)=><li key={i}>{d}</li>)}</ul></details></div>
    {pendingScale&&<ScaleReview reference={pendingScale.reference} result={pendingScale.detection} message={pendingScale.message} onCancel={()=>{setPendingScale(undefined);setNotice('Measurement review canceled. Your previous drawing is unchanged. The analysis remains available in the browser cache when storage is available.');}} onConfirm={scale=>{try{acceptDetection(pendingScale.reference,pendingScale.detection,pendingScale.file,pendingScale.page,pendingScale.rotation,pendingScale.status,scale);}catch(e){setPendingScale({...pendingScale,message:(e as Error).message});}}}/>}
    {loading&&<div className="bp-analysis-status" role="status"><strong>Reading your floor plan…</strong><p>Finding rooms and printed dimensions. Detailed scans can take a few minutes.</p><button onClick={()=>{analysisAbort.current?.abort();loadGeneration.current++;setLoading(false);setNotice('Analysis canceled. Your drawing is unchanged.');}}>Cancel analysis</button></div>}<div className={`bp-workspace ${sidebar||review?'':'bp-sidebar-hidden'}`} style={pendingScale?{display:'none'}:undefined} inert={loading||!!pendingScale} aria-busy={loading}><aside className="bp-sidebar" hidden={!sidebar&&!review}>
      {!review&&<>
        <section><h2>Rooms & spaces · {spaces.length}</h2><div className="bp-room-list">{spaces.map(r=><div key={r.id} className="bp-room-row">{mode==='combine'&&<input type="checkbox" aria-label={`Combine ${r.name}`} checked={combineIds.includes(r.id)} onChange={e=>setCombineIds(ids=>e.target.checked?[...ids,r.id]:ids.filter(id=>id!==r.id))}/>}<button className={(mode==='combine'?combineIds.includes(r.id):r.id===room?.id)?'active':''} aria-pressed={mode==='combine'?combineIds.includes(r.id):undefined} onClick={()=>{if(mode==='combine')toggleCombine(r.id);else {setSelected(r.id);setMode('select');}}}><span style={{background:colors[r.kind]}}/>{r.name}<small>{(r.width/factor).toFixed(2)} × {(r.depth/factor).toFixed(2)} {unit}</small></button></div>)}</div></section>
        {mode==='room'&&<label>New room type<select value={kind} onChange={e=>setKind(e.target.value as RoomKind)}>{roomKinds.map(k=><option key={k}>{k}</option>)}</select></label>}
        {room&&mode!=='combine'&&<section className="bp-selection"><h2>Edit room</h2><label>Room name<input maxLength={100} value={room.name} onChange={e=>updateRoom({name:e.target.value})}/></label><label>Room type<select value={room.kind} onChange={e=>updateRoom({kind:e.target.value as RoomKind})}>{roomKinds.map(k=><option key={k}>{k}</option>)}</select></label><div className="bp-fields">{(['x','z','width','depth'] as const).map(key=><LengthField key={key} label={`${key==='x'?'Left':key==='z'?'Top':key} (${unit})`} value={room[key]} factor={factor} onChange={v=>updateRoom({[key]:v})}/>)}</div><label className="bp-check"><input type="checkbox" checked={room.enclosed} onChange={e=>updateRoom({enclosed:e.target.checked})}/> Add room dividers</label><button onClick={remove}><Trash/> Delete room</button></section>}
        {room&&mode!=='combine'&&room.parts.length>1&&selectedPart&&<section className="bp-selection"><label className="bp-check"><input type="checkbox" checked={editParts} onChange={e=>setEditParts(e.target.checked)}/> Edit individual rectangles</label>{editParts&&<><h2>Rectangles in {room.name}</h2>{room.parts.map((part,index)=><button key={part.id} className={selected===part.id?'active':''} onClick={()=>setSelected(part.id)}>Rectangle {index+1}</button>)}<button onClick={()=>{commit(separateBlueprintRectangle(draft,selectedPart.id));}}>Separate rectangle</button><button onClick={()=>{commit({...draft,rooms:draft.rooms.filter(r=>r.id!==selectedPart.id)});setSelected(room.parts.find(r=>r.id!==selectedPart.id)?.id);}}>Delete rectangle</button></>}</section>}
        {fixture&&<section className="bp-selection"><h2>{fixtureName(fixture)}</h2>{isDoor(fixture.catalogId)&&<label className="bp-check"><input type="checkbox" checked={!!fixture.doorless} onChange={e=>updateFixture({doorless:e.target.checked})}/> Entrance without a door</label>}<div className="bp-fields">{(['x','z','widthMm','depthMm','heightMm'] as const).map(key=><LengthField key={key} label={`${key==='x'?'Left':key==='z'?'Top':key.replace('Mm','')} (${unit})`} value={fixture[key]} factor={factor} onChange={v=>updateFixture({[key]:v})}/>)}</div><div className="bp-button-row"><button onClick={()=>updateFixture({rotation:(fixture.rotation+(isWallOpening(fixture.catalogId)?180:90))%360})}><ArrowClockwise/> Rotate</button><button onClick={remove}><Trash/> Delete object</button></div></section>}
        {selected&&!room&&!fixture&&<section><h2>Inside wall</h2><button onClick={remove}><Trash/> Remove divider</button></section>}
        {!!draft.fixtures.length&&<section><details><summary>Fixtures & openings · {draft.fixtures.length}</summary><div className="bp-room-list">{draft.fixtures.map(f=><button key={f.id} className={selected===f.id?'active':''} onClick={()=>{setSelected(f.id);setMode('select');}}>{fixtureName(f)}</button>)}</div></details></section>}
      </>}
      {review&&<section className="bp-review"><span className="eyebrow">Ready for your walkthrough</span><h2>Check the empty home</h2><p>Review room sizes, wall connections, doors, windows and fixture locations.</p><dl><dt>Rooms / spaces</dt><dd>{spaces.length}</dd><dt>Kitchen / bath / laundry & openings</dt><dd>{draft.fixtures.length}</dd><dt>Loose furniture</dt><dd>None</dd></dl><p>This replaces <strong>{floorName}</strong> and its contents. Other floors stay in place. Stair connections to this floor are removed. Undo restores the previous floor.</p><p>After conversion, use <strong>Auto furnish</strong> to preview an arrangement from your library. Room types guide the choices.</p>{analysisNotes.length>0&&<ul>{analysisNotes.map((n,i)=><li key={i}>{n}</li>)}</ul>}{reference&&!calibrated&&<p className="bp-error">Calibrate the reference before converting.</p>}{problems.length>0&&<div role="alert" className="bp-error"><strong>Fix these before converting:</strong><ul>{problems.slice(0,10).map((p,i)=><li key={i}>{p}</li>)}</ul></div>}<label className="bp-check"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/> I checked the dimensions, openings and fixtures.</label><button className="primary" disabled={!checked||!plan||stale||!!problems.length||!!reference&&!calibrated} onClick={apply}><Check/> Confirm & create 3D home</button><button onClick={()=>{setReview(false);setChecked(false);}}>Back to editing</button></section>}
    </aside><section className="bp-drawing"><div className="bp-toolbar"><div className="bp-button-row"><button aria-label="Toggle rooms panel" aria-pressed={sidebar} onClick={()=>setSidebar(!sidebar)}><SquaresFour/></button><button className={mode==='select'?'active':''} disabled={review} onClick={()=>setMode('select')}><GridFour/> Select / move</button><button className={mode==='pan'?'active':''} disabled={review} onClick={()=>setMode('pan')}><Hand/> Pan</button><button aria-label="Undo drawing" disabled={!past.length||review} onClick={()=>{const previous=past.at(-1)!;setFuture(f=>[draft,...f]);setPast(p=>p.slice(0,-1));setDraft(previous);setSelected(undefined);}}><ArrowCounterClockwise/></button><button aria-label="Redo drawing" disabled={!future.length||review} onClick={()=>{setPast(p=>[...p,draft]);setDraft(future[0]);setFuture(f=>f.slice(1));setSelected(undefined);}}><ArrowClockwise/></button></div><div className="bp-button-row"><button aria-label="Magnetic room snapping" aria-pressed={magnetic} className={magnetic?'active':''} onClick={()=>setMagnetic(!magnetic)}>Snap</button>{selected&&!review&&<button aria-label="Delete selected" onClick={remove}><Trash/></button>}<button onClick={()=>zoom(.8)} aria-label="Zoom drawing in"><Plus/></button><button onClick={()=>zoom(1.25)} aria-label="Zoom drawing out"><Minus/></button><button onClick={()=>fit()}>Fit plan</button></div></div>
      <div className="bp-instruction" role="status">{snapped?'Shared wall snapped':loading?'Reading rooms and dimensions…':review?'Review your floor plan before creating the 3D home.':mode==='room'?'Drag from one room corner to the opposite corner.':mode==='cut'?'Drag along an inside wall to remove only that section.':mode==='combine'?'Click each area to select it. Click again to deselect. Name the room below.':mode==='wall'?'Drag a straight inside wall; gold points show snapped ends.':mode==='fixture'?(entrance?'Click a wall to add an entrance without a door.':'Click to place the selected fixture, then drag or edit its dimensions.'):mode==='scale'?'Drag along a known measurement on the reference.':mode==='pan'?'Drag to move around the drawing.':'Drag to move · corners to resize · Shift-click to select several'}</div>
      <svg ref={svgRef} className={`bp-canvas mode-${mode}`} role="img" aria-label="Top-down floor plan drawing" viewBox={`${view.x} ${view.z} ${view.width} ${view.height}`} onPointerDown={e=>{setMenu(undefined);down(e);}} onPointerMove={move} onPointerUp={up} onPointerCancel={()=>{if(gesture)setDraft(gesture.before);setGesture(undefined);setSnapped(false);}}>
        <defs><pattern id="bp-grid" width="500" height="500" patternUnits="userSpaceOnUse"><path d="M 500 0 L 0 0 0 500" fill="none" stroke="var(--bp-grid,#657b8520)" strokeWidth="1" vectorEffect="non-scaling-stroke"/></pattern></defs><rect x={view.x} y={view.z} width={view.width} height={view.height} fill="var(--bp-canvas,#f9f8f3)"/><rect x={view.x} y={view.z} width={view.width} height={view.height} fill="url(#bp-grid)"/>
        {reference&&<image href={reference.url} x="0" y="0" width={reference.width*imageScale} height={reference.height*imageScale} opacity={opacity} pointerEvents="none"/>}
        {groupedRooms.map(r=>{const label=r.parts.reduce((a,b)=>a.width*a.depth>b.width*b.depth?a:b);return <g key={r.id} data-object={r.id} className="bp-object">{r.parts.map(part=><rect key={part.id} data-object={part.id} x={part.x} y={part.z} width={Math.max(0,part.width)} height={Math.max(0,part.depth)} fill={colors[r.kind]} fillOpacity={mode==='combine'&&combineIds.includes(r.id)?'.8':reference?'.38':'.7'} stroke={(mode==='combine'?combineIds.includes(r.id):editParts&&r.id===room?.id)?'#be8226':'none'} strokeWidth={(mode==='combine'?combineIds.includes(r.id):editParts&&r.id===room?.id)?4:0} vectorEffect="non-scaling-stroke"/>)}<text x={label.x+label.width/2} y={label.z+label.depth/2} textAnchor="middle" fontSize={Math.min(view.width/65,label.width/9)} fill="#34483c" fontWeight="800">{r.name}</text><text x={label.x+label.width/2} y={label.z+label.depth/2+Math.min(view.width/60,label.width/8)} textAnchor="middle" fontSize={Math.min(view.width/85,label.width/12)} fill="#455d50">{(r.width/factor).toFixed(2)} × {(r.depth/factor).toFixed(2)} {unit}</text></g>;})}
        {walls.map(w=><line key={w.id} data-object={floor?.walls.some(f=>f.id===w.id)?w.id:undefined} x1={w.ax*base.gridSizeMm} y1={w.az*base.gridSizeMm} x2={w.bx*base.gridSizeMm} y2={w.bz*base.gridSizeMm} stroke={selected===w.id?'#be8226':'var(--bp-wall,#42584d)'} strokeWidth={selected===w.id?7:4} vectorEffect="non-scaling-stroke"/>)}
        {draft.fixtures.map(f=>{const symbol=f.doorless?'entrance':isDoor(f.catalogId)?'door':planItems.find(i=>i.id===f.catalogId)?.symbol??(isWallOpening(f.catalogId)?'window':'pantry');return <g key={f.id} data-object={f.id} transform={`translate(${f.x},${f.z}) rotate(${f.rotation})`} className="bp-object"><title>{fixtureName(f)}</title><rect x={-f.widthMm/2} y={-f.depthMm/2} width={f.widthMm} height={f.depthMm} fill={selected===f.id?'#f5c96366':'#fffaf0bb'} stroke={selected===f.id?'#b7771e':'#627b84'} strokeWidth={selected===f.id?3:1} vectorEffect="non-scaling-stroke"/><BlueprintSymbol symbol={symbol} x={-f.widthMm/2} y={-f.depthMm/2} width={f.widthMm} height={f.depthMm} color="#384d4e" pointerEvents="none"/></g>;})}
        {palettePreview&&<BlueprintSymbol symbol={palettePreview.doorless?'entrance':planItems.find(i=>i.id===palettePreview.id)?.symbol??openingItems.find(i=>i.id===palettePreview.id)?.symbol??'window'} x={palettePreview.x-250} y={palettePreview.z-250} width={500} height={500} color="#b7771e" opacity={.6} pointerEvents="none"/>}

        {room&&!review&&mode==='select'&&!editParts&&<rect x={room.x} y={room.z} width={room.width} height={room.depth} fill="none" stroke="#be8226" strokeWidth="2" strokeDasharray="5 4" vectorEffect="non-scaling-stroke" pointerEvents="none"/>}
        {room&&!review&&mode==='select'&&(editParts?room.parts:[room]).map((part,index)=>[['nw',part.x,part.z],['ne',part.x+part.width,part.z],['sw',part.x,part.z+part.depth],['se',part.x+part.width,part.z+part.depth]].map(([handle,x,z])=><rect key={`${part.id}-${handle}`} data-handle={handle} data-part={part.id} aria-label={editParts?`Resize ${room.name} rectangle ${index+1} ${handle}`:`Resize ${room.name} ${handle}`} x={Number(x)-handleSize/2} y={Number(z)-handleSize/2} width={handleSize} height={handleSize} fill="#f5c963" stroke="#795118" strokeWidth="2" vectorEffect="non-scaling-stroke" style={{cursor:handle==='nw'||handle==='se'?'nwse-resize':'nesw-resize'}}/>))}
        {gesture?.mode==='room'&&<rect x={Math.min(gesture.a.x,gesture.b.x)} y={Math.min(gesture.a.z,gesture.b.z)} width={Math.abs(gesture.a.x-gesture.b.x)} height={Math.abs(gesture.a.z-gesture.b.z)} fill="#be822630" stroke="#be8226" strokeWidth="2" strokeDasharray="6 4" vectorEffect="non-scaling-stroke"/>}
        {(gesture?.mode==='scale'||gesture?.mode==='wall'||gesture?.mode==='cut'||scaleLine)&&(()=>{const line=gesture??scaleLine!;let b=line.b;if(gesture?.mode==='cut'){const w=walls.find(w=>w.id===gesture.selected);if(w)b=w.az===w.bz?{x:b.x,z:line.a.z}:{x:line.a.x,z:b.z};}if(gesture?.mode==='wall')b=Math.abs(b.x-line.a.x)>Math.abs(b.z-line.a.z)?{x:b.x,z:line.a.z}:{x:line.a.x,z:b.z};return <g pointerEvents="none"><line x1={line.a.x} y1={line.a.z} x2={b.x} y2={b.z} stroke="#bd8225" strokeWidth="3" vectorEffect="non-scaling-stroke"/>{[line.a,b].map((p,i)=><circle key={i} cx={p.x} cy={p.z} r={view.width/180} fill="#bd8225"/>)}</g>;})()}
        {!draft.rooms.length&&!reference&&<text x={view.x+view.width/2} y={view.z+view.height/2} textAnchor="middle" fontSize={view.width/45} fill="var(--bp-muted,#7d8c84)">Upload a plan or draw your first room</text>}
      </svg>
      {mode==='combine'&&<section className="bp-combine-bar" aria-label="Combine selected areas"><header><strong>{combining.length} areas selected</strong><button aria-label="Cancel combining" onClick={()=>{setMode('select');setCombineIds([]);}}><X/></button></header><div className="bp-combine-chips">{combining.map(g=><button key={g.id} aria-label={`Deselect ${g.name}`} onClick={()=>toggleCombine(g.id)}>{g.name}<X size={14}/></button>)}</div><div className="bp-combine-fields"><label>Combined room name<input maxLength={100} value={combinedName} onChange={e=>{setCombinedName(e.target.value);setCombineNamed(true);}}/></label><label>Combined room type<select value={combinedKind} onChange={e=>{setCombinedKind(e.target.value as RoomKind);setCombineNamed(true);}}>{roomKinds.map(k=><option key={k}>{k}</option>)}</select></label><button className="primary" disabled={combining.length<2||!combinedName.trim()} onClick={combineSelected}>Combine selected ({combining.length})</button></div></section>}
      <footer className="bp-footer"><span>{cursor?`${(cursor.x/factor).toFixed(2)}, ${(cursor.z/factor).toFixed(2)} ${unit}`:'500 mm grid'} · {spaces.length} rooms / spaces · {draft.fixtures.length} fixtures</span>{!review&&<button className="primary" disabled={!plan||loading||stale||!!reference&&!calibrated} onClick={()=>{setReview(true);setSelected(undefined);setChecked(false);}}>Review & create 3D →</button>}</footer>
      {(error||computed.error||stale)&&<div className="bp-error bp-message" role="alert">{stale?'The home changed while this draft was open. Close and reopen the studio to use the latest version.':error||computed.error}</div>}
      {error.includes('Sign in')&&<a href="/signin-with-chatgpt?return_to=%2F" target="_top">Sign in with ChatGPT</a>}{notice&&!error&&<div className="bp-note">{notice}</div>}
    </section>    <aside className="bp-tool-rail" aria-label="Drawing tools" inert={review||loading}>
      <button aria-label="Select and resize rooms" title="Select and resize rooms" className={mode==='select'?'active':''} onClick={()=>setMode('select')}><Cursor size={24}/><span>Select</span></button>
      <button aria-label="Draw room area" className={mode==='room'?'active':''} disabled={!!reference&&!calibrated} onClick={()=>{setMode('room');setSidebar(true);}}><ArrowsOut size={24}/><span>Room</span></button>
      <button aria-label="Inside wall" className={mode==='wall'?'active':''} disabled={!draft.rooms.length} onClick={()=>setMode('wall')}><Wall size={24}/><span>Wall</span></button>
      <button aria-label="Remove wall section" className={mode==='cut'?'active':''} disabled={!draft.rooms.length} onClick={()=>setMode('cut')}><Eraser size={24}/><span>Cut wall</span></button>
      <button aria-label="Combine rooms" className={mode==='combine'?'active':''} disabled={groupedRooms.length<2} onClick={()=>{setMode('combine');setCombineNamed(false);setCombinedName('');setCombineIds(room?[room.id]:[]);}}><SquaresFour size={24}/><span>Combine</span></button>
      <button aria-label="Doors, entrances and windows" aria-expanded={palette==='openings'} onClick={()=>setPalette(palette==='openings'?undefined:'openings')}><DoorOpen size={24}/><span>Openings</span></button>
      <button aria-label="Choose optional fixtures" aria-expanded={palette==='fixtures'} onClick={()=>setPalette(palette==='fixtures'?undefined:'fixtures')}><CookingPot size={24}/><span>Fixtures</span></button>
      {palette&&<div className="bp-fixture-picker"><div className="bp-picker-heading"><h2>{palette==='fixtures'?'Fixtures':'Openings'}</h2><button aria-label="Close item menu" onClick={()=>setPalette(undefined)}><X/></button></div><div className="bp-quick-fixtures">{(palette==='fixtures'?planItems:openingItems).map(paletteButton)}</div></div>}
    </aside></div>
  </dialog>;
}
