import {useState} from 'react';
import {captureItems,type CaptureReviewSnapshot} from './captureReview';
import {captureBenchmarkReport,deleteCaptureBenchmark,loadCaptureBenchmarks,saveCaptureBenchmark,type CaptureBenchmarkCase,type CaptureExpected} from './captureBenchmark';
import {captureAttemptDuration,type CaptureAttempt} from './captureAttempt';

function download(value:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),0);}
export function CaptureBenchmarkPanel({review,attempt}:{review:CaptureReviewSnapshot;attempt?:CaptureAttempt}) {
  const captureDurationMs=captureAttemptDuration(attempt,review);
  const items=captureItems(review),[target,setTarget]=useState(items[0]?.id??''),[values,setValues]=useState<Record<string,string>>({}),[expected,setExpected]=useState<CaptureExpected[]>([]),[cases,setCases]=useState<CaptureBenchmarkCase[]>([]);
  const [consent,setConsent]=useState(false),[label,setLabel]=useState(''),[sourceKind,setSourceKind]=useState<CaptureBenchmarkCase['sourceKind']>('image'),[readability,setReadability]=useState<CaptureBenchmarkCase['readability']>('clear'),[complexity,setComplexity]=useState<CaptureBenchmarkCase['complexity']>('simple'),[tolerance,setTolerance]=useState('50'),[error,setError]=useState(''),[loaded,setLoaded]=useState(false);
  const [manualSeconds,setManualSeconds]=useState(''),[sameTiming,setSameTiming]=useState(false);
  const item=items.find(i=>i.id===target),kind=item?.kind==='dimension'?'dimension':item?.kind==='wall'?'wall':'bounds';
  const fields=kind==='dimension'?['millimetres']:kind==='wall'?['axMm','ayMm','bxMm','byMm']:['widthMm','heightMm'];
  const labels:Record<string,string>={millimetres:'Verified length (mm)',axMm:'Wall start X (mm)',ayMm:'Wall start Y (mm)',bxMm:'Wall end X (mm)',byMm:'Wall end Y (mm)',widthMm:'Verified width (mm)',heightMm:'Verified depth (mm)'};
  const act=(fn:()=>void)=>{try{fn();setError('');}catch(e){setError((e as Error).message);}};
  const report=captureBenchmarkReport(cases);
  return <details className="capture-benchmark"><summary>Optional local accuracy benchmark</summary>
    <p>Measure this reference independently, then compare its original and corrected proposals. Cases stay in this browser, outside projects, cloud saves and share links. Small personal samples do not establish representative accuracy.</p>
    <label>Case label<input maxLength={100} value={label} onChange={e=>setLabel(e.target.value)} placeholder="Avoid personal names or addresses"/></label>
    <div className="capture-fields"><label>Reference type<select value={sourceKind} onChange={e=>setSourceKind(e.target.value as typeof sourceKind)}><option value="image">Image</option><option value="pdf">PDF page</option><option value="manual">Manual reference</option></select></label><label>Readability<select value={readability} onChange={e=>setReadability(e.target.value as typeof readability)}><option value="clear">Clear</option><option value="faint">Faint</option><option value="mixed">Mixed</option></select></label><label>Layout<select value={complexity} onChange={e=>setComplexity(e.target.value as typeof complexity)}><option value="simple">Simple</option><option value="stepped">Stepped</option><option value="multi-room">Multiple rooms</option></select></label><label>Allowed error (mm)<input type="number" min={1} max={1000} value={tolerance} onChange={e=>setTolerance(e.target.value)}/></label></div>
    <label>Measured target<select value={target} onChange={e=>{setTarget(e.target.value);setValues({});}}>{items.map(i=><option key={i.id} value={i.id}>{i.label}</option>)}</select></label>
    <p>Enter independently checked values. Detected values are deliberately not prefilled as reference truth. Wall endpoints use the reference image's top-left origin after measurement calibration.</p>
    <div className="capture-fields">{fields.map(key=><label key={key}>{labels[key]}<input type="number" step="any" value={values[key]??''} onChange={e=>setValues({...values,[key]:e.target.value})}/></label>)}</div>
    <button onClick={()=>act(()=>{if(fields.some(k=>!(values[k]??'').trim()))throw new Error('Enter every independently measured value.');const entry={itemId:target,kind,...Object.fromEntries(fields.map(k=>[k,Number(values[k])]))} as CaptureExpected;setExpected([...expected.filter(e=>e.itemId!==target),entry]);setValues({});})}>Add measured reference</button>
    <ul>{expected.map(e=><li key={e.itemId}>{items.find(i=>i.id===e.itemId)?.label}: {Object.entries(e).filter(([k])=>!['itemId','kind'].includes(k)).map(([k,v])=>`${labels[k]}: ${v}`).join('; ')} <button aria-label={`Remove measurement ${e.itemId}`} onClick={()=>setExpected(expected.filter(v=>v.itemId!==e.itemId))}>Remove</button></li>)}</ul>
    <label className="capture-check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I have permission to use this reference and choose to store this geometry and these measurements locally for benchmarking.</label>
    {captureDurationMs!==undefined&&<details><summary>Optional comparison with manual tracing</summary><p>Recorded time to the capture proposal: {(captureDurationMs/1000).toFixed(1)} seconds. Add a separately timed manual run of this same reference, starting with the reference ready and ending with a verified layout.</p><label>Recorded manual tracing time (seconds)<input type="number" min={0} max={604800} value={manualSeconds} onChange={e=>setManualSeconds(e.target.value)}/></label><label className="capture-check"><input type="checkbox" checked={sameTiming} onChange={e=>setSameTiming(e.target.checked)}/>Both runs use that same start and finish protocol.</label></details>}
    {captureDurationMs===undefined&&<p>No source-matched timing was recorded for this review. Enable local benchmark timing before a new recognition attempt to compare with manual tracing. Restored or restarted reviews do not acquire old timings.</p>}
    <button disabled={!consent||!expected.length||!label.trim()} onClick={()=>act(()=>{const id=`local-${crypto.randomUUID()}`;const next=saveCaptureBenchmark(localStorage,{version:1,id,label,consent:'local-only',sourceKind,readability,complexity,review,expected,toleranceMm:Number(tolerance),...(captureDurationMs===undefined?{}:{captureDurationMs,attempt,...(manualSeconds.trim()?{manualDurationMs:Number(manualSeconds)*1000}:{}),...(sameTiming?{timingProtocol:'same-reference-ready-start' as const}:{})})},consent);setCases(next);setLoaded(true);setConsent(false);setExpected([]);setLabel('');})}>Compare and save locally</button>
    {!loaded&&<button onClick={()=>act(()=>{setCases(loadCaptureBenchmarks(localStorage));setLoaded(true);})}>Load this browser's saved cases</button>}
    {error&&<p role="alert">{error}</p>}
    {!!cases.length&&<><p>{report.sampleCount} local cases. Review time includes idle time. End-to-end timing is available only for explicitly timed, matching attempts.</p>{report.pairedTimingCases>0&&<p>{report.pairedTimingCases} paired manual comparisons; median recorded time saved: {(report.medianPairedTimeSavedMs!/1000).toFixed(1)} seconds. Negative values mean recognition took longer.</p>}<div className="capture-report"><table><caption>Measured error against independent reference values</caption><thead><tr><th>Case</th><th>Original mean geometry error</th><th>Corrected mean geometry error</th><th>Result</th><th>Action</th></tr></thead><tbody>{report.cases.map(c=><tr key={c.id}><td>{c.label} ({c.measuredTargets} targets)</td><td>{c.original.geometryMeanErrorMm===undefined?'Not measured':`${c.original.geometryMeanErrorMm.toFixed(1)} mm`}</td><td>{c.corrected.geometryMeanErrorMm===undefined?'Not measured':`${c.corrected.geometryMeanErrorMm.toFixed(1)} mm`}</td><td>{c.corrected.status.replace(/-/g,' ')}</td><td><button onClick={()=>act(()=>setCases(deleteCaptureBenchmark(localStorage,c.id)))}>Delete</button></td></tr>)}</tbody></table></div><button onClick={()=>download(report,'capture-benchmark-report.json')}>Export benchmark report</button></>}
  </details>;
}
