import type { CatalogItem } from "./types";
const rows: Array<[string,string,CatalogItem["category"],number,number,number,CatalogItem["shape"],string]> = [
  ["sofa","Cloud sofa","Living",2100,900,850,"seat","Deep and softly rounded"],["loveseat","Little loveseat","Living",1450,850,820,"seat","A snug two-seater"],["armchair","Nook chair","Living",880,820,900,"seat","A generous reading chair"],["ottoman","Puff ottoman","Living",650,500,420,"seat","Feet-up comfort"],["coffee-table","Pebble table","Living",1100,600,420,"table","Low rounded coffee table"],["side-table","Acorn side table","Living",480,480,520,"table","Small round companion"],
  ["modular-sectional","Hearth sectional","Living",2850,1900,820,"seat","A flexible L-shaped modular sofa"],["midcentury-sofa","Juniper sofa","Living",2050,860,830,"seat","Tailored cushions and splayed wood legs"],["sleeper-sofa","Foldaway sofa","Living",1980,920,840,"seat","A compact sofa with a pull-out bed"],
  ["nesting-tables","Nest tables","Living",620,480,560,"table","Two softly rounded tables that tuck together"],["tray-side-table","Tea tray table","Living",520,420,610,"table","A raised-edge tray on a folding frame"],["c-side-table","Cuddle-up table","Living",460,380,640,"table","Slides neatly beside a sofa"],["drawer-side-table","Keepsake table","Living",540,440,590,"storage","A compact end table with one drawer"],
  ["slim-tv","Picture TV","Living",1220,110,760,"decor","A slim screen on a warm easel stand"],["tv-stand","Hearth media bench","Living",1600,420,560,"storage","Sliding doors, open shelf and cable space"],
  ["queen-bed","Nest bed","Bedroom",1600,2100,760,"bed","Queen bed with soft headboard"],["single-bed","Daydream bed","Bedroom",1000,2000,700,"bed","Simple single bed"],["nightstand","Moon nightstand","Bedroom",520,430,560,"storage","One drawer and a shelf"],["dresser","Meadow dresser","Bedroom",1300,500,850,"storage","Low six-drawer dresser"],["wardrobe","Cottage wardrobe","Storage",1200,600,1900,"storage","Tall double-door storage"],["bookshelf","Story shelf","Storage",900,350,1800,"storage","Open shelves"],["cabinet","Linen cabinet","Storage",800,450,1200,"storage","Compact closed storage"],["bench","Entry bench","Storage",1100,420,520,"seat","Shoes below, seat above"],
  ["storage-platform-bed","Drawer platform bed","Bedroom",1650,2150,920,"bed","A low bed with deep under-bed drawers"],["arched-bed","Petal headboard bed","Bedroom",1650,2120,1200,"bed","A softly arched upholstered statement bed"],["daybed","Window daybed","Bedroom",2050,980,900,"bed","A sofa-like single bed with a bolster back"],["bunk-bed","Cottage bunk bed","Bedroom",1050,2100,1750,"bed","Two sturdy bunks with a built-in ladder"],
  ["dining-table","Harvest table","Dining",1600,900,760,"table","Room for six"],["round-table","Tea table","Dining",1050,1050,750,"table","Round four-seat table"],["dining-chair","Twig chair","Dining",480,520,880,"seat","Light wooden chair"],["bar-stool","Mushroom stool","Dining",420,420,720,"seat","Tucks under a counter"],["desk","Writing desk","Office",1300,650,760,"table","Calm work surface"],["office-chair","Leaf task chair","Office",620,620,950,"seat","A friendly desk chair"],
  ["standing-desk","Rise desk","Office",1400,700,1150,"table","An adjustable desk with chunky lift columns"],["trestle-desk","Maker trestle desk","Office",1500,720,760,"table","A broad wood top on open trestles"],["corner-desk","Corner studio desk","Office",1800,1500,760,"table","An L-shaped workspace with open shelving"],["secretary-desk","Fold-down secretary","Office",980,480,1480,"storage","Tall storage with a fold-down writing surface"],
  ["refrigerator","Pantry refrigerator","Kitchen",900,720,1850,"storage","Rounded French-door fridge with a freezer drawer"],["range-oven","Cottage range","Kitchen",760,680,920,"storage","Four-burner range with a windowed oven"],["dishwasher","Quiet dishwasher","Kitchen",600,620,860,"storage","Panel-front dishwasher with a simple control rail"],["base-cabinet","Base cabinet","Kitchen",900,620,910,"storage","Modular two-door kitchen base cabinet"],["wall-cabinet","Wall cabinet","Kitchen",800,360,760,"storage","Compact upper cabinet with framed doors"],["sink-cabinet","Apron sink cabinet","Kitchen",1000,640,930,"storage","Deep farmhouse sink over two cabinet doors"],["kitchen-counter","Prep counter","Kitchen",1200,650,930,"storage","Drawer-and-door counter with selectable worktop"],["kitchen-island","Gathering island","Kitchen",1800,900,940,"table","A substantial island with shelves and seating overhang"],
  ["washer","Meadow washer","Kitchen",680,700,900,"storage","Friendly front-loading washing machine"],["dryer","Warm-air dryer","Kitchen",680,700,900,"storage","Matching front-loading tumble dryer"],["stacked-laundry","Stacked laundry pair","Kitchen",700,720,1810,"storage","Space-saving washer and dryer tower"],
  ["floor-lamp","Bell floor lamp","Lighting",450,450,1550,"lamp","Warm pool of light"],["table-lamp","Glow lamp","Lighting",300,300,520,"lamp","Small cozy lamp"],["large-plant","Sunny plant","Decor",600,600,1300,"plant","A generous leafy plant"],["small-plant","Window plant","Decor",320,320,520,"plant","Fits anywhere"],["round-rug","Dewdrop rug","Decor",1800,1800,20,"rug","Soft round rug"],["runner-rug","Woven runner","Decor",800,2200,20,"rug","Long patterned runner"],["braided-rug","Hearth braid rug","Decor",1600,1000,25,"rug","Warm layered oval weave"],["scallop-rug","Petal edge rug","Decor",1700,1200,25,"rug","Playful scalloped border"],["checker-rug","Picnic check rug","Decor",1500,1500,25,"rug","Chunky cottage checks"],["mirror","Sunrise mirror","Decor",700,80,1100,"decor","Rounded standing mirror"],["pet-bed","Sleepy pet bed","Decor",700,550,180,"decor","A tiny nest for a companion"]
  ,["landscape-painting","Amber valley painting","Decor",900,70,650,"decor","A warm framed countryside painting"],["botanical-print","Garden study print","Decor",600,45,800,"decor","A quiet botanical illustration"],["abstract-poster","Shape & sun poster","Decor",600,35,850,"decor","Warm mid-century geometric art"],["coast-poster","Moon coast poster","Decor",650,35,900,"decor","A dreamy coastal night print"],["round-wall-mirror","Dewdrop wall mirror","Decor",720,55,720,"decor","Round mirror with a chunky wood rim"],["arch-wall-mirror","Window arch mirror","Decor",620,55,980,"decor","Tall softly arched wall mirror"],["whiteboard","Little plan board","Office",900,55,650,"decor","Whiteboard with tray, notes and markers"],["wall-shelf","Peg rail shelf","Storage",900,240,360,"storage","Wall shelf with pegs and a raised back"],["floating-shelves","Floating shelf pair","Storage",1000,240,720,"storage","Two staggered chunky floating shelves"],["books-upright","Storybook row","Decor",520,180,310,"decor","A varied row of standing books"],["books-stacked","Bedside book stack","Decor",420,280,260,"decor","Several books stacked horizontally"]
];
const wallMountedIds = new Set(["landscape-painting","botanical-print","abstract-poster","coast-poster","round-wall-mirror","arch-wall-mirror","whiteboard","wall-shelf","floating-shelves","books-upright","books-stacked"]);
export const isWallMounted = (catalogId: string) => wallMountedIds.has(catalogId);
export const catalog: CatalogItem[] = rows.map(([id,name,category,widthMm,depthMm,heightMm,shape,description]) => ({ id,name,category,widthMm,depthMm,heightMm,shape,description,icon:shape,mount:wallMountedIds.has(id)?"wall":"floor" }));
export const variants = {
  sage: "#97a67c", clay: "#c4775f", oat: "#d9c5a3", rose: "#c89490",
  ink: "#5d6965", navy: "#53687d", rust: "#9f5d47", cream: "#eee4d1",
};
