import {parseReviewPublication,parseReviewSnapshot,parseReviewFeedback,reviewId,REVIEW_LIMITS,type ReviewView,type ReviewPublication,type ReviewSummary,type ReviewFeedback,type ReviewFeedbackInput} from './clientReview';
import {isListingImage} from './listingTypes';
const base='/api/client-reviews';
const id=(v:string)=>{if(!reviewId(v))throw new Error('Invalid review identifier.');return encodeURIComponent(v);};
async function call(path:string,options:{method?:string;body?:unknown;token?:string;signal?:AbortSignal}={}){
 const response=await fetch(base+path,{method:options.method??'GET',credentials:options.token?'omit':'same-origin',cache:'no-store',redirect:'error',referrerPolicy:'no-referrer',signal:options.signal,headers:{...(options.body?{'Content-Type':'application/json'}:{}),...(options.token?{Authorization:`Bearer ${options.token}`}:{})},...(options.body?{body:JSON.stringify(options.body)}:{})});
 const value=await response.json().catch(()=>null);if(!response.ok)throw new Error(typeof value?.error==='string'?value.error:'Reviews are temporarily unavailable.');if(!value||typeof value!=='object')throw new Error('The review service returned an invalid response.');return value;
}
function summary(v:any):ReviewSummary {if(!v||!reviewId(v.id)||typeof v.projectId!=='string'||!Number.isSafeInteger(v.revision)||v.revision<1||v.revision>REVIEW_LIMITS.revisions||![v.createdAt,v.expiresAt].every(Number.isFinite)||typeof v.revoked!=='boolean')throw new Error('Invalid review status.');return {id:v.id,projectId:v.projectId,revision:v.revision,createdAt:v.createdAt,expiresAt:v.expiresAt,revoked:v.revoked};}
function access(v:any){if(!v||!reviewId(v.id)||!Number.isSafeInteger(v.revision)||!Number.isFinite(v.expiresAt)||v.token!==undefined&&!/^[A-Za-z0-9_-]{43}$/.test(v.token))throw new Error('Invalid review link.');return v as {id:string;revision:number;expiresAt:number;revoked?:boolean;token?:string};}
export async function reviewAvailability(signal?:AbortSignal){const v=await call('/status',{signal});if(typeof v.available!=='boolean'||typeof v.signedIn!=='boolean')throw new Error('Invalid review status.');return v as {available:boolean;signedIn:boolean};}
export async function listClientReviews(projectId:string,signal?:AbortSignal):Promise<ReviewSummary[]>{const v=await call('?projectId='+encodeURIComponent(projectId),{signal});if(!Array.isArray(v.reviews)||v.reviews.length>REVIEW_LIMITS.reviews)throw new Error('Invalid review list.');return v.reviews.map(summary);}
export async function publishClientReview(projectId:string,publication:ReviewPublication,expiryHours:number,previous?:{id:string;revision:number},signal?:AbortSignal){const v=await call(previous?'/'+id(previous.id)+'/revisions':'',{method:'POST',body:{projectId,...publication,expiryHours,...(previous?{expectedRevision:previous.revision}:{})},signal});const review=summary(v.review);if(v.token!==undefined)access({id:review.id,revision:review.revision,expiresAt:review.expiresAt,token:v.token});return {review,token:v.token as string|undefined};}
export async function manageReviewAccess(reviewIdValue:string,action:'rotate'|'revoke',expiryHours?:number){return access(await call('/'+id(reviewIdValue)+'/access',{method:'POST',body:{action,...(expiryHours===undefined?{}:{expiryHours})}}));}
export async function deleteClientReview(reviewIdValue:string){await call('/'+id(reviewIdValue),{method:'DELETE'});}
export async function getOwnedReview(reviewIdValue:string,signal?:AbortSignal):Promise<{review:ReviewSummary;revisions:Array<{revision:number;createdAt:number}>;feedback:ReviewFeedback[];publication:ReviewPublication}>{const v=await call('/'+id(reviewIdValue),{signal});if(!Array.isArray(v.revisions)||v.revisions.length>10||!Array.isArray(v.feedback)||v.feedback.length>REVIEW_LIMITS.feedback)throw new Error('Invalid review history.');return {...v,review:summary(v.review),publication:parseReviewPublication(v.publication)};}
export async function resolveReviewFeedback(reviewIdValue:string,feedbackId:string,resolved:boolean){await call('/'+id(reviewIdValue)+'/feedback/'+id(feedbackId),{method:'POST',body:{resolved}});}
export async function getClientReview(reviewIdValue:string,token:string,revision?:number,signal?:AbortSignal):Promise<ReviewView>{const v=await call('/'+id(reviewIdValue)+'/view'+(revision?'?revision='+revision:''),{token,signal});const snapshot=parseReviewSnapshot(v.snapshot);if(!Number.isSafeInteger(v.revision)||v.revision<1||!Number.isSafeInteger(v.currentRevision)||v.currentRevision<v.revision||!Number.isFinite(v.expiresAt)||!Array.isArray(v.media)||v.media.length>REVIEW_LIMITS.media||!Array.isArray(v.feedback)||v.feedback.length>REVIEW_LIMITS.feedback)throw new Error('Invalid review snapshot.');
 const media=v.media.map((m:any)=>{if(!reviewId(m.id)||!['photo','render','staged','concept'].includes(m.kind))throw new Error('Invalid review image.');return {id:m.id,kind:m.kind};});
 const feedback=v.feedback.map((f:any)=>{const parsed=parseReviewFeedback({requestId:f.requestId,revision:f.revision,kind:f.kind,authorName:f.authorName,text:f.text,anchor:f.anchor},snapshot);if(!reviewId(f.id)||!Number.isFinite(f.createdAt)||typeof f.resolved!=='boolean'||parsed.revision!==v.revision)throw new Error('Invalid review response.');return {...parsed,id:f.id,createdAt:f.createdAt,resolved:f.resolved};});return {...v,snapshot,media,feedback};}
export async function getReviewMedia(reviewIdValue:string,token:string,revision:number,mediaId:string,signal?:AbortSignal):Promise<string>{const v=await call('/'+id(reviewIdValue)+'/media/'+revision+'/'+id(mediaId),{token,signal});if(!isListingImage(v.dataUrl,REVIEW_LIMITS.imageChars))throw new Error('This photo preview is unavailable.');return v.dataUrl;}
export async function submitReviewFeedback(reviewIdValue:string,token:string,input:ReviewFeedbackInput){return call('/'+id(reviewIdValue)+'/feedback',{method:'POST',token,body:input});}
export function reviewLink(origin:string,reviewIdValue:string,token:string,revision:number){id(reviewIdValue);if(!/^[A-Za-z0-9_-]{43}$/.test(token)||!Number.isSafeInteger(revision)||revision<1)throw new Error('Invalid review link.');const url=new URL(origin);url.pathname='/';url.search='';url.hash=new URLSearchParams({review:reviewIdValue,key:token,revision:String(revision)}).toString();return url.href;}
export {reviewLocation} from './publicLinkRoutes';
