import {useEffect,useRef,useState} from 'react';
import type {PlanDocumentV1} from './types';
import type {ListingMedia} from './listingTypes';
import {mediaLabels} from './listingTypes';
import type {CameraShotPose} from './walkthrough';
import {homeShots} from './previewShots';
import {cameraReviewMarker,parseReviewPublication,reviewImagePreview,REVIEW_LIMITS,type ReviewStop,type ReviewSummary,type ReviewFeedback,type ReviewPublication,type ReviewMedia} from './clientReview';
import {deleteClientReview,getOwnedReview,listClientReviews,manageReviewAccess,publishClientReview,resolveReviewFeedback,reviewAvailability,reviewLink} from './clientReviewApi';
import {ReviewTour} from './ReviewTour';
import './clientReview.css';

function defaultCamera(plan:PlanDocumentV1,floorId:string):CameraShotPose {const shot=homeShots(plan,floorId)[0],floor=plan.floors.find(f=>f.id===floorId)!;return {version:1,kind:'orbit',floorId,target:{x:shot?.x??0,y:shot?.y??floor.elevationMm/1000+.5,z:shot?.z??0},alpha:shot?.alpha??Math.PI/2,beta:shot?.beta??.65,radius:shot?.radius??6,mode:0,fov:.8};}
function newStop(plan:PlanDocumentV1,camera:CameraShotPose,title='A new view'):ReviewStop {return {id:crypto.randomUUID(),title,caption:'',narration:'',floorId:camera.floorId,camera,marker:cameraReviewMarker(camera)};}
export interface ClientReviewPanelProps {plan:PlanDocumentV1;floorId:string;media?:ListingMedia[];captureCamera?:()=>CameraShotPose|null;onBusyChange?:(busy:boolean)=>void;onSignIn?:()=>void}
/** Embed inside the parent's dialog; this component never opens another dialog. */
export function ClientReviewPanel({plan,floorId,media:listingMedia=[],captureCamera,onBusyChange,onSignIn}:ClientReviewPanelProps){
 const [savedMedia,setSavedMedia]=useState<ReviewMedia[]>([]);
 const media:ListingMedia[]=[...savedMedia.map(m=>({id:m.id,title:'Published photo '+m.id.slice(0,8),caption:'',kind:m.kind,image:m.dataUrl,seconds:4})),...listingMedia.filter(m=>!savedMedia.some(s=>s.id===m.id))];
 const [title,setTitle]=useState(plan.name),[stops,setStops]=useState<ReviewStop[]>(()=>[newStop(plan,defaultCamera(plan,floorId),'Welcome home')]),[allowPhotos,setAllowPhotos]=useState(false),[selected,setSelected]=useState<string[]>([]),[expiry,setExpiry]=useState(168),[reviews,setReviews]=useState<ReviewSummary[]>([]),[reviewId,setReviewId]=useState(''),[feedback,setFeedback]=useState<ReviewFeedback[]>([]),[link,setLink]=useState(''),[access,setAccess]=useState<{available:boolean;signedIn:boolean}|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState<ReviewPublication|null>(null),[confirm,setConfirm]=useState<'publish'|'revoke'|'rotate'|'delete'|null>(null);
 const current=reviews.find(r=>r.id===reviewId),alive=useRef(true),generation=useRef(0),latestPlanId=useRef(plan.id);latestPlanId.current=plan.id;
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;generation.current++;};},[]);
 useEffect(()=>{onBusyChange?.(busy);return()=>onBusyChange?.(false);},[busy,onBusyChange]);
 useEffect(()=>{const controller=new AbortController();generation.current++;setBusy(false);setTitle(plan.name);setStops([newStop(plan,defaultCamera(plan,floorId),'Welcome home')]);setSelected([]);setSavedMedia([]);setAllowPhotos(false);setReviewId('');setReviews([]);setFeedback([]);setPreview(null);setLink('');setError('');setAccess(null);
  void reviewAvailability(controller.signal).then(async status=>{if(controller.signal.aborted)return;setAccess(status);if(status.available&&status.signedIn){const found=await listClientReviews(plan.id,controller.signal);if(!controller.signal.aborted)setReviews(found);}}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();
 // Project switches reset the draft. Ordinary plan edits are included only on explicit preview/publish.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[plan.id]);
 useEffect(()=>{setFeedback([]);setConfirm(null);setPreview(null);if(!reviewId){setSavedMedia([]);return;}const controller=new AbortController();setBusy(true);void getOwnedReview(reviewId,controller.signal).then(v=>{if(!controller.signal.aborted){setFeedback(v.feedback);setReviews(old=>old.map(r=>r.id===v.review.id?v.review:r));setTitle(v.publication.snapshot.title);setStops(v.publication.snapshot.stops);setSavedMedia(v.publication.media);setSelected(v.publication.media.map(m=>m.id));setAllowPhotos(v.publication.includeSelectedMedia);}}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});return()=>controller.abort();},[reviewId]);
 function editStop(id:string,change:Partial<ReviewStop>){setStops(old=>old.map(s=>s.id===id?{...s,...change}:s));setPreview(null);setConfirm(null);}
 async function task(run:(valid:()=>boolean)=>Promise<void>){if(busy)return;const epoch=++generation.current,project=plan.id;const valid=()=>alive.current&&generation.current===epoch&&latestPlanId.current===project;setBusy(true);setError('');setNotice('');try{await run(valid);}catch(e){if(valid())setError(e instanceof Error?e.message:'This action could not be completed.');}finally{if(valid())setBusy(false);}}
 async function publication():Promise<ReviewPublication>{const chosen=allowPhotos?media.filter(m=>selected.includes(m.id)):[],ids=new Set(chosen.map(m=>m.id));if(chosen.some(m=>!stops.some(s=>s.mediaId===m.id)))throw new Error('Link each checked photo to a tour stop, or uncheck unused photos.');const images=await Promise.all(chosen.map(async m=>({id:m.id,kind:m.kind,dataUrl:await reviewImagePreview(m.image)})));return parseReviewPublication({snapshot:{version:1,title,plan,stops:stops.map(s=>({...s,...(!s.mediaId||ids.has(s.mediaId)?{}:{mediaId:undefined})}))},media:images,includeSelectedMedia:allowPhotos});}
 function prepare(){void task(async valid=>{const p=await publication();if(valid()){setPreview(p);setConfirm('publish');setNotice('Preview the exact tour and selected images below. Nothing has been uploaded.');}});}
 function publish(){if(!preview)return;void task(async valid=>{try{const result=await publishClientReview(plan.id,preview,expiry,current?{id:current.id,revision:current.revision}:undefined);if(valid()){setReviews(old=>[result.review,...old.filter(r=>r.id!==result.review.id)]);setReviewId(result.review.id);setFeedback([]);setConfirm(null);setNotice(`Published fixed revision ${result.review.revision}. No message was sent.`);if(result.token)setLink(reviewLink(window.location.origin,result.review.id,result.token,result.review.revision));}}catch(error){if(valid()){setConfirm(null);setNotice('Publication could not be confirmed. Check the review list before publishing again; if a new review is listed, open it and create a replacement link.');try{const found=await listClientReviews(plan.id);if(valid())setReviews(found);}catch{/* Original publication error remains visible. */}}throw error;}});}
 async function copy(value:string){try{await navigator.clipboard.writeText(value);setNotice('Copied. Anyone with this link can view the snapshot and leave self-reported responses.');}catch{setError('Copy is unavailable. Select the link text and copy it.');}}
 function accessAction(){if(!current||!confirm||confirm==='publish')return;const action=confirm;void task(async valid=>{if(action==='delete'){await deleteClientReview(current.id);if(valid()){setReviews(old=>old.filter(r=>r.id!==current.id));setReviewId('');setLink('');setNotice('Review, stored photos and responses deleted.');}}else{const result=await manageReviewAccess(current.id,action,action==='rotate'?expiry:undefined);if(valid()){setReviews(old=>old.map(r=>r.id===current.id?{...r,expiresAt:result.expiresAt,revoked:!!result.revoked}:r));setLink(result.token?reviewLink(window.location.origin,result.id,result.token,result.revision):'');setNotice(action==='revoke'?'Link revoked. Previously downloaded content cannot be recalled.':'Replacement link created. The old link no longer works.');}}if(valid())setConfirm(null);});}
 const canPublish=access?.available&&access.signedIn;
 return <section className="client-review" aria-label="Client reviews and story tours"><header><p className="review-eyebrow">Present a home, gather decisions</p><h2>Story tour & client review</h2><p>Publish a fixed version with selected views. Visitors can comment or approve that version; your home stays editable only here.</p></header>
  {error&&<p role="alert" className="review-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
  {access&&!access.available&&<p>Online reviews are unavailable. You can build and preview the tour locally.</p>}{access?.available&&!access.signedIn&&<p>Sign in to create private review links. {onSignIn&&<button onClick={onSignIn}>Sign in</button>}</p>}
  <fieldset disabled={busy}><legend>Choose a review</legend><label>Review link<select value={reviewId} onChange={e=>{setReviewId(e.target.value);setLink('');}}><option value="">Create a new review</option>{reviews.map(r=><option key={r.id} value={r.id}>Revision {r.revision} · {new Date(r.createdAt).toLocaleDateString()} · {r.revoked?'Revoked':r.expiresAt<Date.now()?'Expired':'Active'}</option>)}</select></label>
   {current&&<p>A new publication becomes revision {current.revision+1}. Earlier snapshots and their responses stay unchanged. Existing links open their original revision and flag it as older.</p>}
   <label>Tour title<input value={title} maxLength={120} onChange={e=>{setTitle(e.target.value);setPreview(null);setConfirm(null);}}/></label>
   <label>New or replacement link expires after<select value={expiry} onChange={e=>setExpiry(Number(e.target.value))}><option value={24}>1 day</option><option value={168}>7 days</option><option value={720}>30 days</option></select></label>
  </fieldset>
  <fieldset disabled={busy}><legend>Tour stops ({stops.length}/{REVIEW_LIMITS.stops})</legend>{stops.map((s,index)=><details className="review-stop-editor" key={s.id} open={stops.length===1}><summary>{index+1}. {s.title} · {plan.floors.find(f=>f.id===s.floorId)?.name??'Missing floor'}</summary>
   <label>Stop name<input value={s.title} maxLength={100} onChange={e=>editStop(s.id,{title:e.target.value})}/></label><label>Floor<select value={s.floorId} onChange={e=>{const camera=defaultCamera(plan,e.target.value);editStop(s.id,{floorId:camera.floorId,camera,marker:cameraReviewMarker(camera)});}}>{plan.floors.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>
   <label>Caption<textarea value={s.caption} maxLength={1000} onChange={e=>editStop(s.id,{caption:e.target.value})}/></label><label>Story text (optional)<textarea value={s.narration} maxLength={2000} onChange={e=>editStop(s.id,{narration:e.target.value})}/></label>
   <div className="review-inline">{(['xMm','zMm','facingDeg'] as const).map(key=><label key={key}>{key==='xMm'?'Marker X (mm)':key==='zMm'?'Marker Z (mm)':'Facing (degrees)'}<input type="number" value={Number.isFinite(s.marker[key])?s.marker[key]:''} min={key==='facingDeg'?0:undefined} max={key==='facingDeg'?359.99:undefined} step="any" onChange={e=>editStop(s.id,{marker:{...s.marker,[key]:e.target.valueAsNumber}})}/></label>)}</div>
   {captureCamera&&<button onClick={()=>{const camera=captureCamera();if(camera)editStop(s.id,{floorId:camera.floorId,camera,marker:cameraReviewMarker(camera)});}}>Use current camera</button>}
   <label>Selected photo for this stop<select value={s.mediaId??''} onChange={e=>editStop(s.id,{mediaId:e.target.value||undefined})}><option value="">No photo</option>{media.filter(m=>selected.includes(m.id)).map(m=><option value={m.id} key={m.id}>{m.title} · {mediaLabels[m.kind]}</option>)}</select></label>
   <button disabled={index===0} onClick={()=>{setStops(old=>{const next=[...old];[next[index-1],next[index]]=[next[index],next[index-1]];return next;});setPreview(null);setConfirm(null);}}>Move earlier</button> <button disabled={stops.length===1} onClick={()=>{setStops(old=>old.filter(x=>x.id!==s.id));setPreview(null);setConfirm(null);}}>Remove stop</button>
  </details>)}<button disabled={stops.length>=REVIEW_LIMITS.stops} onClick={()=>{setStops(old=>[...old,newStop(plan,captureCamera?.()??defaultCamera(plan,floorId))]);setPreview(null);setConfirm(null);}}>Add a view</button></fieldset>
  <fieldset disabled={busy}><legend>Photos stay private until you choose them</legend><label className="review-check"><input type="checkbox" checked={allowPhotos} onChange={e=>{setAllowPhotos(e.target.checked);setPreview(null);setConfirm(null);}}/>Include selected photo previews in this review link</label><p>Only the checked, linked previews below are copied. Source originals, floor-plan references, personal uploads, notes, budgets and agent contact details are omitted. Uploaded photos retain their property/staging labels.</p>
   {allowPhotos&&<div className="review-photo-picker">{media.map(m=><label key={m.id}><img src={m.image} alt=""/><span><input type="checkbox" checked={selected.includes(m.id)} disabled={!selected.includes(m.id)&&selected.length>=REVIEW_LIMITS.media} onChange={e=>{setSelected(old=>e.target.checked?[...old,m.id]:old.filter(x=>x!==m.id));setPreview(null);setConfirm(null);}}/>{m.title} · {mediaLabels[m.kind]}</span></label>)}</div>}{allowPhotos&&!media.length&&<p>Add listing photos or save camera renders first.</p>}
  </fieldset>
  <button disabled={busy} onClick={prepare}>Preview exact snapshot</button>
  {preview&&<div className="review-preview"><h3>Ready for review</h3><ReviewTour snapshot={preview.snapshot} media={preview.media} images={Object.fromEntries(preview.media.map(m=>[m.id,m.dataUrl]))}/><p>{preview.media.length} selected image previews · {preview.snapshot.stops.length} stops. Anyone with the link can view and respond until it expires or you revoke it.</p>{confirm==='publish'&&<button disabled={busy||!canPublish} onClick={publish}>{current?`Publish revision ${current.revision+1}`:'Create private review link'}</button>}</div>}
  {link&&<div className="review-link"><label>Review link<input value={link} readOnly onFocus={e=>e.target.select()}/></label><button onClick={()=>void copy(link)}>Copy link</button><button onClick={()=>void copy(`<iframe src="${link.replaceAll('&','&amp;')}" title="Nook & Nest story tour" width="100%" height="760" loading="lazy" referrerpolicy="no-referrer" sandbox="allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox"></iframe>`)}>Copy tour embed</button><p>Embedding includes the access key in your page. Embed only where everyone viewing that page may see this design. Responses require opening the full review.</p></div>}
  {current&&<fieldset disabled={busy}><legend>Owner controls</legend><p>Links are shown only when created. Generate a replacement to copy a new one. Replacing or revoking a link stops future access; it cannot erase downloads.</p><button onClick={()=>setConfirm('rotate')}>Create replacement link</button><button disabled={current.revoked} onClick={()=>setConfirm('revoke')}>Revoke link</button><button onClick={()=>setConfirm('delete')}>Delete review</button>{confirm&&confirm!=='publish'&&<div className="review-warning"><p>{confirm==='delete'?'Delete this review, every stored snapshot/photo and all responses? This cannot be undone.':confirm==='revoke'?'Revoke this review link now?':'Create a replacement link and invalidate the previous one?'}</p><button onClick={accessAction}>Confirm {confirm==='delete'?'delete':confirm==='revoke'?'revoke':'replacement'}</button><button onClick={()=>setConfirm(null)}>Cancel</button></div>}
   <h3>All revision responses</h3>{feedback.length===0?<p>No responses yet.</p>:<ul className="review-feedback">{feedback.map(f=><li key={f.id}><strong>{f.authorName}</strong><small> Self-reported visitor · revision {f.revision}{f.revision!==current.revision?' (older revision)':''} · {f.kind}</small><p>{f.text||'Approved this design revision.'}</p><button onClick={()=>void task(async valid=>{await resolveReviewFeedback(current.id,f.id,!f.resolved);if(valid())setFeedback(old=>old.map(x=>x.id===f.id?{...x,resolved:!x.resolved}:x));})}>{f.resolved?'Reopen response':'Mark resolved'}</button></li>)}</ul>}
   <button onClick={()=>void task(async valid=>{const latest=await getOwnedReview(current.id);if(valid()){setFeedback(latest.feedback);setReviews(old=>old.map(r=>r.id===latest.review.id?latest.review:r));}})}>Refresh responses</button>
  </fieldset>}
 </section>;
}
