import {useEffect,useRef,useState,useSyncExternalStore} from 'react';
import {collaborationApiForAccount,collaborationInviteLink,collaborationRequest,type CollaborationRoomSummary,type CollaborationVersion} from './collaborationApi';
import {collaborationHash,collaborationLayout,collaborationPlan,collaborationRecovery,type CollaborationRole} from './collaborationProtocol';
import {CollaborationSession,collaborationClientId,listCollaborationRecoveries,removeCollaborationRecovery,type CollaborationQueue} from './collaborationSession';
import type {PlanDocumentV1} from './types';
import './collaboration.css';

export function downloadCollaborationRecovery(value:unknown,name='nook-collaboration-recovery.json'){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),0);}
export interface CollaborationPanelProps {
 plan:PlanDocumentV1;accountId?:string;sourceRevision?:number;inviteToken?:string;
 onOpenSession:(session:CollaborationSession)=>Promise<void>;
 /** Must save the current project and allocate a new local project identity before switching. */
 onCreatePrivateCopy:(plan:PlanDocumentV1)=>Promise<void>;
 onBusyChange?:(busy:boolean)=>void;
}
/** Embed in Project options. No automatic publication, account lookup, invitations or plan mutation. */
export function CollaborationPanel({plan,accountId,sourceRevision,inviteToken,onOpenSession,onCreatePrivateCopy,onBusyChange}:CollaborationPanelProps){
 const [available,setAvailable]=useState(false),[loaded,setLoaded]=useState(false),[rooms,setRooms]=useState<CollaborationRoomSummary[]>([]),[recoveries,setRecoveries]=useState<CollaborationQueue[]>([]),[name,setName]=useState(''),[title,setTitle]=useState(plan.name),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const abort=useRef(new AbortController());
 useEffect(()=>{const controller=new AbortController();abort.current=controller;void collaborationRequest<{available:boolean}>('/status',undefined,controller.signal).then(x=>{setAvailable(x.available);setLoaded(true);}).catch(()=>setLoaded(true));return()=>controller.abort();},[]);
 useEffect(()=>{let live=true;if(available&&accountId)void collaborationRequest<{rooms:CollaborationRoomSummary[]}>('',undefined,abort.current.signal,undefined,accountId).then(x=>{if(live)setRooms(x.rooms);}).catch(e=>{if(live&&!abort.current.signal.aborted)setError(e.message);});return()=>{live=false;};},[available,accountId]);
 useEffect(()=>{let live=true;setRecoveries([]);if(accountId)void listCollaborationRecoveries(accountId).then(rows=>{if(live&&!abort.current.signal.aborted)setRecoveries(rows);}).catch(()=>{if(live&&!abort.current.signal.aborted)setError('Could not read device recovery storage. Existing downloaded projects remain usable.');});return()=>{live=false;};},[accountId]);
 async function act(action:()=>Promise<void>){setBusy(true);onBusyChange?.(true);setError('');try{await action();}catch(e){if(!abort.current.signal.aborted)setError(e instanceof Error?e.message:'Could not complete this action.');}finally{if(!abort.current.signal.aborted)setBusy(false);onBusyChange?.(false);}}
 async function open(id:string){if(!accountId)throw new Error('Sign in before opening a private room.');const session=new CollaborationSession(accountId,id,collaborationClientId());await session.start();if(!session.getState().local){session.dispose();throw new Error('Could not open this room.');}try{await onOpenSession(session);}catch(e){session.dispose();throw e;}}
 return <section className="collaboration-panel" aria-label="Design together">
  <header><span className="collaboration-kicker">Private teamwork · Pilot</span><h2>Design together</h2><p>Work on a separate shared layout with named editors and viewers. Your original private project stays separate.</p></header>
  {!loaded?<p role="status">Checking availability…</p>:!available?<p className="collaboration-notice">Live collaboration is not enabled for production. The two-editor pilot and evidence that teams need it are still required. You can make a private copy or download the current layout today.</p>:null}
  <div className="collaboration-actions"><button type="button" disabled={busy} onClick={()=>void act(()=>onCreatePrivateCopy(plan))}>Make a private copy</button><button type="button" disabled={busy} onClick={()=>downloadCollaborationRecovery(plan,'nook-private-project.json')}>Download private project</button></div>
  {recoveries.length>0&&<div className="collaboration-card"><h3>Saved on this device</h3><p>These queued layouts remain available even while the pilot or your connection is unavailable.</p>{recoveries.map(r=><div className="collaboration-row" key={r.roomId+r.clientId}><span>{r.local.name}<small>{r.queue.length} queued · {new Date(r.savedAt).toLocaleString()}</small></span><div className="collaboration-actions"><button disabled={busy} onClick={()=>void act(()=>onCreatePrivateCopy(r.local))}>Recover private copy</button><button onClick={()=>downloadCollaborationRecovery(collaborationRecovery(r.roomId,r.snapshot,r.local,r.queue))}>Export queue</button><button disabled={busy} onClick={()=>void act(async()=>{await onCreatePrivateCopy(r.local);await removeCollaborationRecovery(r);setRecoveries(rows=>rows.filter(x=>x!==r));})}>Save copy and clear queue</button></div></div>)}</div>}
  {available&&<>
   {!accountId?<p>Sign in through your project library to create or join a private room.</p>:<>
    <label>Your display name<input value={name} maxLength={80} onChange={e=>setName(e.target.value)} autoComplete="off"/></label><small>Members see this self-reported name and your assigned role. No email is shown.</small>
    {inviteToken?<div className="collaboration-card"><h3>Accept invitation</h3><p>This single-use invitation grants the role chosen by the owner. Anyone you give the link to could claim it first.</p><button disabled={busy||!name.trim()} onClick={()=>void act(async()=>{const joined=await collaborationRequest<{id:string}>('/join',{displayName:name},abort.current.signal,inviteToken,accountId);await open(joined.id);})}>Join private room</button></div>:<div className="collaboration-card"><h3>Start a shared copy</h3><label>Room name<input value={title} maxLength={120} onChange={e=>setTitle(e.target.value)}/></label><p>Includes layout geometry, catalog furniture, finishes and locks. Excludes uploaded references, private photos, moodboards, notes, prices, checklists and saved alternatives. Personal artwork uses its catalog appearance.</p><label className="collaboration-check"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I reviewed the layout and room names for this invitation-only copy.</label><button disabled={busy||!reviewed||!name.trim()||!title.trim()||!sourceRevision} onClick={()=>void act(async()=>{const projected=collaborationPlan(plan);const reviewedHash=await collaborationHash({units:projected.units,...collaborationLayout(projected)});const room=await collaborationRequest<{id:string}>('',{sourceProjectId:plan.id,sourceRevision,name:title,displayName:name,reviewed:true,reviewedHash},abort.current.signal,undefined,accountId);await open(room.id);})}>Create shared copy</button>{!sourceRevision&&<small>Save this project online first. The server copies that exact revision.</small>}</div>}
    <h3>Your rooms</h3>{rooms.length?rooms.map(room=><div className="collaboration-row" key={room.id}><span>{room.name}<small>{room.role} · version {room.revision}{room.archived?' · archived':''}</small></span><button disabled={busy} onClick={()=>void act(()=>open(room.id))}>Open</button></div>):<p>No shared rooms yet.</p>}
   </>}
  </>}{error&&<p role="alert">{error}</p>}
 </section>;
}

export interface CollaborationSessionPanelProps {session:CollaborationSession;onCreatePrivateCopy:(plan:PlanDocumentV1)=>Promise<void>;onClose:()=>void;onBusyChange?:(busy:boolean)=>void}
/** Keep mounted beside an editable scene, not in a modal that prevents collaborators from arranging. */
export function CollaborationSessionPanel({session,onCreatePrivateCopy,onClose,onBusyChange}:CollaborationSessionPanelProps){
 const state=useSyncExternalStore(session.subscribe,session.getState),[busy,setBusy]=useState(false),[error,setError]=useState(''),[role,setRole]=useState<'editor'|'viewer'>('viewer'),[link,setLink]=useState(''),[versions,setVersions]=useState<CollaborationVersion[]>([]),[confirmLatest,setConfirmLatest]=useState(false),[confirmClose,setConfirmClose]=useState(false),[confirmArchive,setConfirmArchive]=useState(false),[confirmDelete,setConfirmDelete]=useState(false),[invites,setInvites]=useState<Array<{id:string;role:string;expiresAt:number;revoked:number;claimed:number}>>([]);const abort=useRef(new AbortController());
 useEffect(()=>{const controller=new AbortController();abort.current=controller;const release=session.retain();return()=>{controller.abort();release();};},[session]);
 const snapshot=state.snapshot,working=state.local,owner=snapshot?.me.role==='owner',disabled=busy||state.busy;
 async function act(action:()=>Promise<void>){setBusy(true);setError('');onBusyChange?.(true);try{await action();}catch(e){if(!abort.current.signal.aborted)setError(e instanceof Error?e.message:'Could not complete the action.');}finally{if(!abort.current.signal.aborted)setBusy(false);onBusyChange?.(false);}}
 const request=<T,>(suffix:string,value?:unknown)=>collaborationRequest<T>('/'+encodeURIComponent(session.roomId)+suffix,value,abort.current.signal,undefined,session.accountId);
 async function refreshInvites(){setInvites((await request<{invites:typeof invites}>('/invites')).invites);}
 async function membership(id:string,epoch:number,newRole?:CollaborationRole){await request('/members',{memberId:id,epoch,...(newRole?{role:newRole}:{revoke:true})});await session.refresh();}
 return <aside className="collaboration-panel collaboration-session" aria-label="Shared room">
  <header><span className="collaboration-kicker">Private collaboration pilot</span><h2>{working?.name??'Shared room'}</h2><p role="status">{state.status==='online'?'Connected':state.status.replaceAll('-',' ')} · {snapshot?.me.role??'loading'} · version {snapshot?.revision??'—'} · {state.queued} queued</p></header>
  <p>Changes to different furniture pieces can combine. Overlapping edits and changed architecture require review. Up to 20 shared versions are retained. Updates arrive about every five seconds while this tab is visible.</p>
  {(state.error||error)&&<p role="alert">{error||state.error}</p>}
  <div className="collaboration-actions"><button disabled={disabled} onClick={()=>void act(()=>session.reconnect())}>Reconnect / retry queued edits</button><button disabled={!working} onClick={()=>downloadCollaborationRecovery(session.recovery())}>Export recovery</button><button disabled={disabled||!working} onClick={()=>void act(()=>onCreatePrivateCopy(working!))}>Continue as private copy</button></div>
  {state.status==='conflict'&&<div className="collaboration-card"><h3>Keep both versions safe</h3><p>Your local layout and queued operations are retained. Export them or continue as a private copy before accepting the shared layout.</p><label className="collaboration-check"><input type="checkbox" checked={confirmLatest} onChange={e=>setConfirmLatest(e.target.checked)}/>I have kept any local work I need. Discard this queue and use the latest shared layout.</label><button disabled={disabled||!confirmLatest} onClick={()=>void act(async()=>{await session.acceptLatest();setConfirmLatest(false);})}>Use latest shared layout</button></div>}
  <h3>People</h3><ul className="collaboration-people">{snapshot?.members.map(member=><li key={member.id}><span>{member.name}<small>{member.role}{snapshot.presence.some(p=>p.memberId===member.id&&p.expiresAt>Date.now())?' · here recently':''}</small></span>{owner&&member.role!=='owner'&&!snapshot.archived&&<div className="collaboration-actions"><button disabled={disabled} onClick={()=>void act(()=>membership(member.id,member.epoch,member.role==='editor'?'viewer':'editor'))}>{member.role==='editor'?'Make viewer':'Make editor'}</button><button disabled={disabled} onClick={()=>void act(()=>membership(member.id,member.epoch))}>Revoke {member.name}</button></div>}</li>)}</ul>
  {owner&&!snapshot?.archived&&<div className="collaboration-card"><h3>Invite someone</h3><div className="collaboration-segments" role="group" aria-label="Invitation role">{(['viewer','editor'] as const).map(r=><button key={r} aria-pressed={role===r} onClick={()=>setRole(r)}>{r==='viewer'?'Viewer · look only':'Editor · arrange'}</button>)}</div><button disabled={disabled} onClick={()=>void act(async()=>{const invitation=await request<{token:string}>('/invites',{role});setLink(collaborationInviteLink(invitation.token));await refreshInvites();})}>Create one-use invitation</button>{link&&<label>Invitation link · expires in 24 hours<input readOnly value={link} onFocus={e=>e.currentTarget.select()}/></label>}<small>Share it yourself. The app sends no messages. Revoking access cannot recall previously downloaded copies.</small><button disabled={disabled} onClick={()=>void act(refreshInvites)}>Review invitations</button>{invites.filter(i=>!i.revoked&&!i.claimed).map(i=><div className="collaboration-row" key={i.id}><span>{i.role} · {new Date(i.expiresAt).toLocaleString()}</span><button disabled={disabled} onClick={()=>void act(async()=>{await request('/invites',{revokeId:i.id});setLink('');await refreshInvites();})}>Revoke invitation</button></div>)}</div>}
  <div className="collaboration-card"><h3>Recover earlier work</h3><button disabled={disabled} onClick={()=>void act(async()=>setVersions((await request<{versions:CollaborationVersion[]}>('/history')).versions))}>Show retained versions</button>{versions.map(v=><div className="collaboration-row" key={v.revision}><span>Version {v.revision} · {v.label}<small>{v.name} · {new Date(v.createdAt).toLocaleString()}</small></span><button disabled={disabled} onClick={()=>void act(async()=>{const old=await collaborationApiForAccount(session.accountId).snapshot(session.roomId,abort.current.signal,v.revision);await onCreatePrivateCopy(old.plan);})}>Recover private copy</button></div>)}</div>
  {owner&&!snapshot?.archived&&<details><summary>Archive this room</summary><p>Stops all editing and invitations. Existing members retain read-only history; exported copies remain usable.</p><label className="collaboration-check"><input type="checkbox" checked={confirmArchive} onChange={e=>setConfirmArchive(e.target.checked)}/>Archive this shared room for everyone.</label><button disabled={disabled||!confirmArchive} onClick={()=>void act(async()=>{await request('/archive',{confirm:true});await session.refresh();})}>Archive room</button></details>}
  {owner&&snapshot?.archived&&<details><summary>Permanently delete archived room</summary><p>Deletes this room, membership, invitations and all retained versions for everyone. Downloaded copies and device recovery files cannot be recalled.</p><label className="collaboration-check"><input type="checkbox" checked={confirmDelete} onChange={e=>setConfirmDelete(e.target.checked)}/>I have kept the copies I need. Permanently delete this archived room and its history.</label><button disabled={disabled||!confirmDelete} onClick={()=>void act(async()=>{await request('/delete',{confirm:true,expectedRevision:snapshot.revision});await session.refresh();})}>Permanently delete room</button></details>}
  {state.queued>0&&<label className="collaboration-check"><input type="checkbox" checked={confirmClose} onChange={e=>setConfirmClose(e.target.checked)}/>Leave with {state.queued} edits saved in this device’s recovery queue.</label>}<button disabled={disabled||state.queued>0&&!confirmClose} onClick={onClose}>Leave collaboration</button>
 </aside>;
}
