import {useEffect,useMemo,useRef,useState} from 'react';
import type {ProjectSummary} from './cloudProjects';
import {floorRects} from './floorGeometry';
import {listPersonalItems} from './personalStorage';
import type {PersonalCollectionItem} from './personalItems';
import type {PlanDocumentV1} from './types';
import {assessHomeComparison,buildHomeComparisonCopy,createHomeComparisonWorkspace,fingerprintHomePlan,MAX_COMPARISON_ITEMS,parseHomeComparisonWorkspace,type HomeComparisonCandidate,type HomeComparisonReport,type HomeComparisonWorkspace} from './homeComparison';
import {readHomeComparisonWorkspace,saveHomeComparisonCopies,saveHomeComparisonWorkspace} from './homeComparisonStorage';
import './home-comparison.css';

export interface CompareHomesPanelProps {
 localPlans:PlanDocumentV1[];onlineProjects:ProjectSummary[];disabled?:boolean;
 onLoadOnline(id:string):Promise<PlanDocumentV1>;onRefreshLocal():Promise<PlanDocumentV1[]>;
 onCopiesSaved?():Promise<void>;onOpenCopy?(plan:PlanDocumentV1):Promise<void>;onBusyChange?(busy:boolean):void;
}
type Choice={id:string;location:'local'|'online'};
type Loaded=Record<string,PlanDocumentV1>;
type Compared={workspace:HomeComparisonWorkspace;plans:PlanDocumentV1[];reports:HomeComparisonReport[]};

function ComparisonDrawing({plan,floorId,ownedIds}:{plan:PlanDocumentV1;floorId:string;ownedIds:Set<string>}){
 const floor=plan.floors.find(f=>f.id===floorId),rects=floor?floorRects(floor,plan.gridSizeMm):[],allPieces=plan.furniture.filter(p=>p.floorId===floorId),pieces=[...allPieces.filter(p=>p.personalItem&&ownedIds.has(p.personalItem.itemId)),...allPieces.filter(p=>!p.personalItem||!ownedIds.has(p.personalItem.itemId))].slice(0,600),points=[...rects.flatMap(r=>[{x:r.x,z:r.z},{x:r.x+r.width,z:r.z+r.depth}]),...pieces.flatMap(p=>[{x:p.x-p.widthMm,z:p.z-p.depthMm},{x:p.x+p.widthMm,z:p.z+p.depthMm}])];
 const left=points.reduce((value,p)=>Math.min(value,p.x),points.length?Infinity:0)-300,top=points.reduce((value,p)=>Math.min(value,p.z),points.length?Infinity:0)-300,right=points.reduce((value,p)=>Math.max(value,p.x),points.length?-Infinity:0)+300,bottom=points.reduce((value,p)=>Math.max(value,p.z),points.length?-Infinity:0)+300;
 return <svg className="home-comparison-drawing" viewBox={`${left} ${top} ${right-left} ${bottom-top}`} role="img" aria-label={`${plan.name}, ${floor?.name??'floor'} arrangement preview`}>
  <path className="home-comparison-floor" d={rects.slice(0,5000).map(r=>(r.polygon??[{x:r.x,z:r.z},{x:r.x+r.width,z:r.z},{x:r.x+r.width,z:r.z+r.depth},{x:r.x,z:r.z+r.depth}]).map((p,i)=>`${i?'L':'M'}${p.x},${p.z}`).join(' ')+'Z').join(' ')}/>
  {floor?.walls.map(w=><line key={w.id} x1={w.ax*plan.gridSizeMm} y1={w.az*plan.gridSizeMm} x2={w.bx*plan.gridSizeMm} y2={w.bz*plan.gridSizeMm} className="home-comparison-wall" vectorEffect="non-scaling-stroke"/>)}
  {pieces.slice(0,600).map(p=><rect key={p.id} x={p.x-p.widthMm/2} y={p.z-p.depthMm/2} width={p.widthMm} height={p.depthMm} transform={`rotate(${-p.rotation} ${p.x} ${p.z})`} className={p.personalItem&&ownedIds.has(p.personalItem.itemId)?'home-comparison-owned':'home-comparison-obstacle'}><title>{p.personalItem?.name??'Existing object'}</title></rect>)}
 </svg>;
}

/** Private, explicit source reads. The host owns project switching; this panel never replaces the active plan. */
export function CompareHomesPanel({localPlans,onlineProjects,disabled=false,onLoadOnline,onRefreshLocal,onCopiesSaved,onOpenCopy,onBusyChange}:CompareHomesPanelProps){
 const [collection,setCollection]=useState<PersonalCollectionItem[]>([]),[ready,setReady]=useState(false),[selectedHomes,setSelectedHomes]=useState<Choice[]>([]),[selectedItems,setSelectedItems]=useState<string[]>([]);
 const [workspace,setWorkspaceState]=useState<HomeComparisonWorkspace>(),[loaded,setLoaded]=useState<Loaded>({}),[compared,setCompared]=useState<Compared>(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[dirty,setDirty]=useState(false),[shownFloors,setShownFloors]=useState<Record<string,string>>({});
 const alive=useRef(true),running=useRef(false),blocked=useRef(disabled),revision=useRef(0);blocked.current=disabled;
 const setWorkspace=setWorkspaceState;
 const ensure=()=>{if(!alive.current)throw new Error('The comparison was closed. Saved copies remain in My projects.');if(blocked.current)throw new Error('Finish the active preview or leave the shared room before saving a comparison.');};
 useEffect(()=>{alive.current=true;void Promise.all([listPersonalItems(),readHomeComparisonWorkspace()]).then(([items,saved])=>{if(alive.current){setCollection(items);setReady(true);setWorkspace(saved);revision.current=saved?.revision??0;}}).catch(e=>{if(alive.current)setError(e instanceof Error?e.message:'Device storage is unavailable.');});return()=>{alive.current=false;};},[]);
 const run=(work:()=>Promise<void>)=>{if(running.current||disabled)return;running.current=true;setBusy(true);onBusyChange?.(true);setError('');setNotice('');void work().catch(e=>{if(alive.current)setError(e instanceof Error?e.message:'The comparison could not be saved.');}).finally(()=>{running.current=false;if(alive.current)setBusy(false);onBusyChange?.(false);});};
 const accept=(next:HomeComparisonWorkspace|undefined)=>{setWorkspace(next);revision.current=next?.revision??0;setDirty(false);};
 useEffect(()=>{if(!workspace||running.current||!Object.keys(loaded).length)return;const changed=workspace.homes.some(home=>{if(!home.copyId&&home.location!=='local')return false;const latest=localPlans.find(p=>p.id===(home.copyId??home.sourceId)),previous=loaded[home.sourceId];return !!latest&&!!previous&&JSON.stringify(latest)!==JSON.stringify(previous);});if(changed){setCompared(undefined);setLoaded({});setNotice('A loaded plan changed. Refresh saved plans before comparing again.');}},[localPlans,workspace,loaded]);
 const edit=(change:(w:HomeComparisonWorkspace)=>HomeComparisonWorkspace)=>{if(!workspace||busy||disabled)return;setWorkspace(change(workspace));setDirty(true);setCompared(undefined);setNotice('');};
 const editHome=(index:number,patch:Partial<HomeComparisonCandidate>)=>edit(w=>({...w,homes:w.homes.map((h,i)=>i===index?{...h,...patch}:h)}));
 const choices=[...localPlans.map(p=>({id:p.id,name:p.name,location:'local' as const})),...onlineProjects.map(p=>({id:p.id,name:p.name,location:'online' as const}))];
 const loadHomes=async(w:HomeComparisonWorkspace):Promise<Loaded>=>{
  const locals=await onRefreshLocal();ensure();const result:Loaded={};
  for(const home of w.homes){
   const plan=home.copyId?locals.find(p=>p.id===home.copyId):home.location==='local'?locals.find(p=>p.id===home.sourceId):await onLoadOnline(home.sourceId);ensure();
   if(!plan)throw new Error(`${home.name}: the saved ${home.copyId?'copy':'source'} is missing. Restore it from a backup or start a new comparison.`);
   if(!home.copyId&&(home.sourceFingerprint?await fingerprintHomePlan(plan)!==home.sourceFingerprint:plan.updatedAt!==home.sourceUpdatedAt))throw new Error(`${home.name} changed since the snapshot. Start a new comparison to review its updated source.`);
   ensure();result[home.sourceId]=structuredClone(plan);
  }
  return result;
 };
 const proposed=(w:HomeComparisonWorkspace,plans:Loaded)=>w.homes.map(h=>{const source=plans[h.sourceId];if(!source)throw new Error('Refresh saved plans before comparing or creating copies.');return h.copyId?source:buildHomeComparisonCopy(source,h,w.snapshot);});
 const capture=()=>run(async()=>{
  const locals=await onRefreshLocal(),freshItems=await listPersonalItems();ensure();
  const items=selectedItems.map(id=>{const item=freshItems.find(i=>i.id===id),shown=collection.find(i=>i.id===id);if(!item||JSON.stringify(item)!==JSON.stringify(shown))throw new Error('Your furniture collection changed. Refresh the collection and choose its current measurements.');return item;});
  const sources:Parameters<typeof createHomeComparisonWorkspace>[0]=[];
  for(const choice of selectedHomes){const plan=choice.location==='local'?locals.find(p=>p.id===choice.id):await onLoadOnline(choice.id);ensure();if(!plan)throw new Error('A selected saved plan is no longer available. Refresh the library.');sources.push({plan:structuredClone(plan),location:choice.location});}
  const next=createHomeComparisonWorkspace(sources,items);next.revision=revision.current;
  for(let i=0;i<next.homes.length;i++){next.homes[i].sourceFingerprint=await fingerprintHomePlan(sources[i].plan);ensure();}
  const saved=await saveHomeComparisonWorkspace(next);ensure();accept(saved);setLoaded(Object.fromEntries(sources.map(s=>[s.plan.id,s.plan])));setCompared(undefined);setNotice('Snapshot captured on this device. Review each starting arrangement before relying on its checks.');
 });
 const persist=async(w:HomeComparisonWorkspace)=>{ensure();const saved=await saveHomeComparisonWorkspace(parseHomeComparisonWorkspace(w));ensure();accept(saved);return saved;};
 const compare=()=>run(async()=>{if(!workspace)return;const plans=proposed(workspace,loaded),saved=dirty?await persist(workspace):workspace;ensure();const reports=plans.map((p,i)=>assessHomeComparison(p,saved.homes[i],saved.snapshot,saved.preferences));setCompared({workspace:saved,plans,reports});});
 const createCopies=()=>run(async()=>{
  if(!workspace)return;setCompared(undefined);const sources=await loadHomes(workspace);ensure();setLoaded(sources);const plans=proposed(workspace,sources),saved=await saveHomeComparisonCopies(workspace,plans);ensure();accept(saved);setLoaded(Object.fromEntries(saved.homes.map((h,i)=>[h.sourceId,plans[i]])));setNotice(`${plans.length} editable copies saved on this device. Open a copy to arrange its pieces. Save online explicitly when ready.`);
  if(onCopiesSaved)try{await onCopiesSaved();}catch{if(alive.current)setError('The copies were saved, but the project list could not refresh. Reopen My projects.');}
 });
 const refreshSavedPlans=()=>run(async()=>{if(!workspace)return;setCompared(undefined);setLoaded({});const plans=await loadHomes(workspace);ensure();let changed=false;const homes:HomeComparisonCandidate[]=[];for(const home of workspace.homes){if(!home.copyId){homes.push(home);continue;}const fingerprint=await fingerprintHomePlan(plans[home.sourceId]);ensure();if(home.copyFingerprint&&home.copyFingerprint!==fingerprint){changed=true;homes.push({...home,copyFingerprint:fingerprint,measurementsVerified:false,positions:home.positions.map(p=>({...p,reviewed:false}))});}else homes.push({...home,copyFingerprint:fingerprint});}setWorkspace({...workspace,homes});setDirty(true);setLoaded(plans);setNotice(changed?'Saved copies changed. Property and arrangement verification have been cleared; review them again.':'Saved plans refreshed. Compare again to review current copies.');});
 const restore=()=>run(async()=>{const saved=await readHomeComparisonWorkspace();ensure();accept(saved);setLoaded({});setCompared(undefined);setNotice(saved?'Saved comparison reopened. Refresh saved plans to review current copies.':'No comparison has been saved on this device.');});
 const existingCopies=!!workspace?.homes[0].copyId,locked=busy||disabled;
 const {previewPlans,previewError}=useMemo(()=>{if(!workspace||!Object.keys(loaded).length)return{previewPlans:[],previewError:''};try{return{previewPlans:proposed(workspace,loaded),previewError:''};}catch(e){return{previewPlans:[],previewError:e instanceof Error?e.message:'Review the placement choices.'};}},[workspace,loaded]);
 const ownedIds=new Set(workspace?.snapshot.items.map(i=>i.id)??[]);
 return <section className="home-comparison" aria-labelledby="home-comparison-title" aria-busy={busy}>
  <header><span className="eyebrow">Make room for what comes with you</span><h2 id="home-comparison-title">Compare homes with your furniture</h2><p>Use one measured set of belongings in two or three private saved homes. Review each arrangement and create an editable copy for every property.</p></header>
  <p className="home-comparison-help">Existing objects stay as obstacles. Checks use modeled footprints, a shared passage preference and chair allowance. They do not assess a delivery route, building rules or choose a best home.</p>
  {disabled&&<p role="status">Finish the active preview or leave the shared room to work on private comparisons.</p>}
  {error&&<p className="home-comparison-warning" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
  {!ready&&!error&&<p role="status">Opening the private device collection…</p>}
  {!workspace?<>
   <fieldset disabled={locked||!ready}><legend>1. Choose two or three private homes</legend><div className="home-comparison-options">{choices.map(choice=>{const checked=selectedHomes.some(h=>h.id===choice.id&&h.location===choice.location),other=selectedHomes.some(h=>h.id===choice.id&&!checked);return <label key={`${choice.location}:${choice.id}`}><input type="checkbox" checked={checked} disabled={other||!checked&&selectedHomes.length>=3} onChange={()=>setSelectedHomes(current=>checked?current.filter(h=>h.id!==choice.id):[...current,{id:choice.id,location:choice.location}])}/><span>{choice.name}<small>{choice.location==='local'?'Saved on this device':'Private online save · loads only when selected'}</small></span></label>;})}</div>{!choices.length&&<p>Save at least two measured plans in My projects first.</p>}</fieldset>
   <fieldset disabled={locked||!ready}><legend>2. Choose the same belongings for every home</legend><p>Choose 1–{MAX_COMPARISON_ITEMS} items from My furniture. Their current outside dimensions are frozen together when you capture the snapshot.</p><div className="home-comparison-options">{collection.map(item=><label key={item.id}><input type="checkbox" checked={selectedItems.includes(item.id)} disabled={!selectedItems.includes(item.id)&&selectedItems.length>=MAX_COMPARISON_ITEMS} onChange={()=>setSelectedItems(ids=>ids.includes(item.id)?ids.filter(id=>id!==item.id):[...ids,item.id])}/><span>{item.name}<small>{item.widthMm} × {item.depthMm} × {item.heightMm} mm · {item.status}</small></span></label>)}</div>{!collection.length&&<p>Add your measured belongings through Arrangements → My furniture in the 3D editor, then return here.</p>}</fieldset>
   <div className="home-comparison-actions"><button className="primary" disabled={locked||selectedHomes.length<2||!selectedItems.length} onClick={capture}>Capture comparison snapshot</button><button disabled={locked} onClick={()=>run(async()=>{const items=await listPersonalItems();ensure();setCollection(items);setSelectedItems(ids=>ids.filter(id=>items.some(i=>i.id===id)));setReady(true);})}>Refresh collection</button><button disabled={locked} onClick={restore}>Reload saved comparison</button></div>
  </>:<>
   <section className="home-comparison-snapshot" aria-label="Frozen furniture snapshot"><h3>Frozen furniture snapshot</h3><p>{workspace.snapshot.items.length} items · captured {new Date(workspace.snapshot.capturedAt).toLocaleString()}. Later collection edits do not change these measurements.</p><ul>{workspace.snapshot.items.map(item=><li key={item.id}><strong>{item.name}</strong><span>{item.widthMm} × {item.depthMm} × {item.heightMm} mm</span></li>)}</ul><label className="home-comparison-check"><input type="checkbox" disabled={locked} checked={workspace.snapshot.measurementsVerified} onChange={e=>edit(w=>({...w,snapshot:{...w.snapshot,measurementsVerified:e.target.checked}}))}/>I have checked these outside furniture measurements</label></section>
   <fieldset disabled={locked}><legend>Shared preferences and priorities</legend><div className="home-comparison-fields"><label>Preferred passage (mm)<input type="number" min={100} max={2500} value={workspace.preferences.passageMm} onChange={e=>edit(w=>({...w,preferences:{...w.preferences,passageMm:e.target.valueAsNumber}}))}/></label><label>Chair pull-out allowance (mm)<input type="number" min={100} max={1500} value={workspace.preferences.chairPulloutMm} onChange={e=>edit(w=>({...w,preferences:{...w.preferences,chairPulloutMm:e.target.valueAsNumber}}))}/></label></div><label>What matters to you<textarea maxLength={2000} value={workspace.priorities} onChange={e=>edit(w=>({...w,priorities:e.target.value}))} placeholder="A clear bedroom path, room for the dining table…"/></label></fieldset>
   <div className="home-comparison-actions"><button disabled={locked} onClick={refreshSavedPlans}>Refresh saved plans</button><button disabled={locked} onClick={()=>run(async()=>{await persist(workspace);setNotice('Snapshot, preferences and assumptions saved privately on this device.');})}>Save comparison notes</button><button disabled={locked} onClick={()=>{setWorkspace(undefined);setLoaded({});setCompared(undefined);setDirty(false);setNotice('Choose a new comparison. Capturing it replaces the saved comparison workspace; existing project copies stay saved.');}}>New comparison</button></div>
   {!Object.keys(loaded).length&&<p>Refresh saved plans to inspect the latest sources or edited copies.</p>}{previewError&&<p role="alert" className="home-comparison-warning">{previewError}</p>}
   <div className="home-comparison-homes">{workspace.homes.map((home,index)=>{const preview=previewPlans[index],source=loaded[home.sourceId],floorId=shownFloors[home.sourceId]??preview?.floors[0].id??'';return <article key={home.sourceId} aria-label={home.name}>
    <h3>{home.name}</h3><small>{home.copyId?'Editable comparison copy':'Source snapshot · uncommitted copy preview'}</small>
    {preview&&<><label>Preview floor<select disabled={locked} value={floorId} onChange={e=>setShownFloors(f=>({...f,[home.sourceId]:e.target.value}))}>{preview.floors.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><ComparisonDrawing plan={preview} floorId={floorId} ownedIds={ownedIds}/><small>Gold: your furniture. Muted: existing objects. Each drawing is fitted separately; compare measurements below.</small></>}
    <label className="home-comparison-check"><input type="checkbox" disabled={locked} checked={home.measurementsVerified} onChange={e=>editHome(index,{measurementsVerified:e.target.checked})}/>Property measurements verified</label>
    <label className="home-comparison-check"><input type="checkbox" disabled={locked||!source} checked={home.positions.every(p=>p.reviewed)} onChange={e=>editHome(index,{positions:home.positions.map(p=>({...p,reviewed:e.target.checked}))})}/>I reviewed this arrangement and support heights</label>
    <label>Assumptions and missing measurements<textarea disabled={locked} maxLength={2000} value={home.assumptions} onChange={e=>editHome(index,{assumptions:e.target.value})} placeholder="Room dimensions to verify, fixed furniture that stays, missing measurements…"/></label>
    {!home.copyId&&source&&<details><summary>Adjust starting positions</summary><p>Positions use millimetres from this plan’s origin. These are initial positions, not an optimized arrangement. Furniture dimensions stay identical.</p>{home.positions.map((position,pi)=><fieldset key={position.itemId} disabled={locked}><legend>{workspace.snapshot.items.find(i=>i.id===position.itemId)?.name}</legend><label>Floor<select value={position.floorId} onChange={e=>editHome(index,{positions:home.positions.map((p,j)=>j===pi?{...p,floorId:e.target.value,reviewed:false}:p)})}>{source.floors.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><div className="home-comparison-fields">{(['x','z','rotation','elevationMm'] as const).map(key=><label key={key}>{({x:'X (mm)',z:'Z (mm)',rotation:'Angle (degrees)',elevationMm:'Support height (mm)'})[key]}<input type="number" step="any" value={position[key]} onChange={e=>editHome(index,{positions:home.positions.map((p,j)=>j===pi?{...p,[key]:e.target.valueAsNumber,reviewed:false}:p)})}/></label>)}</div></fieldset>)}</details>}
    {home.copyId&&onOpenCopy&&source&&<button disabled={locked} onClick={()=>run(async()=>{if(dirty)await persist(workspace);const latest=(await onRefreshLocal()).find(p=>p.id===home.copyId);ensure();if(!latest)throw new Error('This saved copy is missing. Refresh the comparison before opening it.');await onOpenCopy(latest);})}>Open {home.name} copy</button>}
   </article>;})}</div>
   <div className="home-comparison-actions"><button className="primary" disabled={locked||!previewPlans.length} onClick={compare}>Compare these homes</button>{!existingCopies&&<button disabled={locked||!previewPlans.length} onClick={createCopies}>Create {workspace.homes.length} editable copies</button>}</div>
   {compared&&<section aria-label="Home comparison results"><div className="home-comparison-table-wrap"><table aria-label="Equivalent fit and clearance summaries"><caption>Same furniture snapshot · passage {compared.workspace.preferences.passageMm} mm · chair allowance {compared.workspace.preferences.chairPulloutMm} mm</caption><thead><tr><th scope="col">Check</th>{workspace.homes.map(h=><th key={h.sourceId} scope="col">{h.name}</th>)}</tr></thead><tbody>{(['overlap','floor-edge','gap','chair-pullout'] as const).map(kind=><tr key={kind}><th scope="row">{({'overlap':'Overlaps','floor-edge':'Floor edge crossings',gap:'Gaps below preference','chair-pullout':'Chair allowance obstructions'})[kind]}</th>{compared.reports.map((r,i)=><td key={i}>{r.issues.filter(issue=>issue.kind===kind).length}{r.limited?' · incomplete':''}</td>)}</tr>)}<tr><th scope="row">Items needing measurements or review</th>{compared.reports.map((r,i)=><td key={i}>{r.items.filter(item=>item.status==='needs-checking').length} / {r.items.length}</td>)}</tr><tr><th scope="row">Other retained objects</th>{compared.reports.map((r,i)=><td key={i}>{r.existingItems}</td>)}</tr>{workspace.snapshot.items.map(item=><tr key={item.id}><th scope="row">{item.name}</th>{compared.reports.map((r,i)=>{const result=r.items.find(p=>p.itemId===item.id)!;return <td key={i}>{result.status==='needs-checking'?'Needs checking':result.status==='review'?'Review arrangement':'No listed issues'} · {result.issues} {result.issues===1?'issue':'issues'}</td>;})}</tr>)}</tbody></table></div>
    {compared.reports.map((report,i)=><details key={workspace.homes[i].sourceId} open={!!report.unknowns.length}><summary>{workspace.homes[i].name}: {report.unknowns.length} unknowns · {report.issues.length} listed checks</summary>{!!report.unknowns.length&&<ul>{report.unknowns.map((note,j)=><li key={j}>{note}</li>)}</ul>}{report.issues.slice(0,40).map(issue=><p key={issue.id}><strong>{issue.title}.</strong> {issue.message}{issue.measuredMm!==undefined?` Measured ${Number(issue.measuredMm.toFixed(1))} mm.`:''}{issue.requiredMm!==undefined?` Preference ${issue.requiredMm} mm.`:''}</p>)}{report.issues.length>40&&<p>Showing the first 40 checks. Open the copy’s Fit review to inspect individual floors.</p>}{workspace.homes[i].assumptions&&<p>Assumptions: {workspace.homes[i].assumptions}</p>}</details>)}
    <p className="home-comparison-help">“No listed issues” only describes the reviewed modeled arrangement. Missing measurements remain unknown; gap checks do not establish a connected walking path. Door swings, drawer travel, delivery access and unsupported decorations need a separate check.</p>
   </section>}
   <p className="home-comparison-help">One comparison workspace is retained privately on this device, including its frozen measurements and notes. It is separate from project backups and public shares. Editable copies retain their measured furniture and can be saved online or backed up as ordinary private projects. Refresh after editing a copy; removed or resized pieces are reported explicitly.</p>
  </>}
 </section>;
}
