import { useEffect, useMemo, useRef, useState } from 'react';
import { ChoiceButtons } from './ChoiceButtons';
import { catalog } from './catalog';
import { validatePlan } from './planValidation';
import { challengeBrief, challengeDefinitions, challengeProgress, createChallengeProject, updateCreativeChallenge, type ChallengeBrief, type ChallengeId, type ChallengePlan } from './creativeChallenges';
import './living-play.css';
export interface ChallengeLaunch { base: ChallengePlan; brief: ChallengeBrief; signal: AbortSignal; createPlan(): ChallengePlan }
export function CreativeChallengesPanel({ plan, disabled = false, onLaunch, onChange, onBrowseCatalog, onClose }: { plan: ChallengePlan; disabled?: boolean; onLaunch(request: ChallengeLaunch): Promise<boolean>; onChange(base: ChallengePlan, next: ChallengePlan): void; onBrowseCatalog?(ids: string[]): void; onClose(): void }) {
  const [choice, setChoice] = useState<ChallengeId>('reading-nook'), [seed, setSeed] = useState('20260929'), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const operation = useRef<AbortController | undefined>(undefined), mounted = useRef(true), current = useRef(plan); current.current = plan;
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; operation.current?.abort(); }; }, []);
  const preview = useMemo(() => { try { if (!/^\d{1,10}$/.test(seed)) return undefined; return challengeBrief(choice, Number(seed)); } catch { return undefined; } }, [choice, seed]);
  const progress = useMemo(() => challengeProgress(plan), [plan]);
  const launch = async () => {
    if (!preview || disabled || busy) return; const origin = plan, controller = new AbortController(); operation.current?.abort(); operation.current = controller; setBusy(true); setError('');
    try { let candidate: ChallengePlan | undefined; const created = await onLaunch({ base: origin, brief: preview, signal: controller.signal, createPlan: () => { if (controller.signal.aborted) throw new Error('This challenge launch was cancelled.'); if (current.current !== origin) throw new Error('The current project changed. Start the brief again after saving it.'); return candidate ??= createChallengeProject(preview, origin.units); } }); if (created && !controller.signal.aborted && mounted.current) onClose(); }
    catch (e) { if (mounted.current && !controller.signal.aborted) setError(e instanceof Error ? e.message : 'The new creative project could not be opened.'); }
    finally { if (mounted.current && operation.current === controller) setBusy(false); }
  };
  return <section className="challenge-panel" aria-labelledby="challenge-heading"><header><div><span className="eyebrow">A prompt, not a competition</span><h2 id="challenge-heading">Small creative challenges</h2></div><button type="button" onClick={onClose}>Close</button></header><p>Start a separate editable project with an original brief. Your current work must be safely saved or handled by the app’s new-project flow first. There are no timers, ranks, public votes or activity tracking.</p>
    {progress && <section className="lp-card"><h3>Your private brief · {progress.brief.title}</h3><p>{progress.brief.description}</p><ul className="challenge-goals">{progress.goals.map(goal => <li key={goal.id}><span aria-label={goal.complete ? 'Constraint met' : 'Still to try'}>{goal.complete ? '✓' : '○'}</span><div><strong>{goal.label}</strong><small>{goal.detail}</small></div></li>)}</ul>{progress.bounded && progress.goals.every(g => g.complete) && <p>All measured constraints are met. Keep exploring if you like; the design is yours.</p>}<p className="lp-muted">These are geometric and catalog checks, not accessibility, safety, pet care or code certification. They do not judge artistic taste.</p>
      {plan.creativeChallenge?.hintsDismissed ? <button type="button" disabled={disabled} onClick={() => { try { onChange(plan, updateCreativeChallenge(plan, current.current, { ...plan.creativeChallenge!, hintsDismissed: false }, validatePlan)); } catch (e) { setError((e as Error).message); } }}>Show optional hints</button> : <><ul>{progress.brief.hints.map(hint => <li key={hint}>{hint}</li>)}</ul><button type="button" disabled={disabled} onClick={() => { try { onChange(plan, updateCreativeChallenge(plan, current.current, { ...plan.creativeChallenge!, hintsDismissed: true }, validatePlan)); } catch (e) { setError((e as Error).message); } }}>Dismiss hints</button></>}
      {onBrowseCatalog && <button type="button" onClick={() => onBrowseCatalog(progress.brief.requirements.flatMap(r => r.ids))}>Browse useful pieces</button>}<button type="button" disabled={disabled} onClick={() => { try { onChange(plan, updateCreativeChallenge(plan, current.current, undefined, validatePlan)); } catch (e) { setError((e as Error).message); } }}>Continue without the brief</button><small>Your furniture and project stay in place when the brief is removed. Progress remains private in project saves and backups.</small>
    </section>}
    <h3>Start another idea</h3><ChoiceButtons<ChallengeId> label="Creative brief" value={choice} options={challengeDefinitions.map(d => ({ value: d.id, label: d.title }))} onChange={setChoice}/><label>Variation number<input inputMode="numeric" value={seed} maxLength={10} onChange={e => setSeed(e.target.value)} aria-describedby="challenge-seed-note"/></label><small id="challenge-seed-note">The same whole number gives the same room orientation, suggestions and swatch. Each launch creates a new project identity.</small>
    {preview ? <div className="lp-card"><strong>{preview.title}</strong><p>{preview.description}</p><p>{preview.widthMm / 1000} × {preview.depthMm / 1000} m · up to {preview.maxPieces} pieces{preview.mainSwatch ? ` · ${preview.mainSwatch} main swatch` : ''}</p><ul>{preview.requirements.map(r => <li key={r.label}>{r.label}: {catalog.find(c => c.id === r.suggestion)?.name ?? 'Currently unavailable'}</li>)}</ul>{!preview.available && <p className="lp-notice">Required pieces unavailable: {preview.missing.join(', ')}. Choose another brief.</p>}<p className="lp-muted">Begins with one empty measured room. Use individual catalog pieces or room recipes, then edit freely.</p></div> : <p className="lp-notice">Enter a whole number from 0 to 4,294,967,295.</p>}
    {error && <p role="alert" className="lp-notice">{error}</p>}{disabled && <p>Finish the active preview before starting another project.</p>}<button type="button" disabled={disabled || busy || !preview?.available} onClick={() => void launch()}>{busy ? 'Preparing the new project…' : 'Start in a new project'}</button>
  </section>;
}
