import {useMemo,useState} from 'react';
import {catalog} from './catalog';
import {ChoiceButtons} from './ChoiceButtons';
import {validatePlan} from './planValidation';
import type {PlanDocumentV1} from './types';
import {assessDeliveryStep,blankDeliveryItem,blankDeliveryPlanning,blankDeliveryStep,deliveryItemSourceStatus,deliveryMeasurementFields,deliveryOrientations,deliveryRouteKinds,itemFromFurniture,MAX_DELIVERY_ITEMS,MAX_DELIVERY_STEPS,orientedDeliveryDimensions,printDeliveryPlanning,saveDeliveryPlanning,type DeliveryItem,type DeliveryPlanning,type DeliveryRouteStep} from './deliveryPlanning';
import './delivery-planning.css';

export interface DeliveryPlanningPanelProps {plan:PlanDocumentV1;disabled?:boolean;onCommit(base:PlanDocumentV1,next:PlanDocumentV1):void}
type Edit={base:PlanDocumentV1;kind:'route';value:DeliveryRouteStep}|{base:PlanDocumentV1;kind:'item';value:DeliveryItem};
const catalogNames=new Map(catalog.map(c=>[c.id,c.name]));
export function DeliveryPlanningPanel({plan,disabled=false,onCommit}:DeliveryPlanningPanelProps){
  const [view,setView]=useState<'route'|'item'|'checks'>('route'),[edit,setEdit]=useState<Edit>(),[units,setUnits]=useState<'mm'|'in'>(plan.units==='imperial'?'in':'mm'),[search,setSearch]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('');
  const data=plan.deliveryPlanning??blankDeliveryPlanning(),stale=!!edit&&edit.base!==plan,factor=units==='in'?25.4:1;
  const numberText=(n:number|null|undefined)=>n==null?'Unknown':`${Number((n/factor).toFixed(units==='in'?3:1))} ${units}`;
  const choices=useMemo(()=>plan.furniture.map(f=>({f,name:f.specification?.productName?.trim()||f.personalItem?.name||catalogNames.get(f.catalogId)||'Furniture',floor:plan.floors.find(floor=>floor.id===f.floorId)?.name??'Earlier floor'})),[plan]);
  const matches=choices.filter(c=>`${c.name} ${c.floor}`.toLowerCase().includes(search.trim().toLowerCase()));
  const attempt=(action:()=>void)=>{setError('');setMessage('');try{action();}catch(e){setError(e instanceof Error?e.message:'The delivery record could not be saved.');}};
  const commit=(base:PlanDocumentV1,nextData:DeliveryPlanning,success:string)=>{if(disabled)return;const next=saveDeliveryPlanning(base,plan,nextData,validatePlan);onCommit(base,next);setEdit(undefined);setMessage(success);};
  const start=(next:Edit)=>{if(edit||disabled)return;setEdit(next);setError('');setMessage('');};
  const patchRoute=(patch:Partial<DeliveryRouteStep>)=>setEdit(current=>current?.kind==='route'?{...current,value:{...current.value,...patch}}:current);
  const patchItem=(patch:Partial<DeliveryItem>)=>setEdit(current=>current?.kind==='item'?{...current,value:{...current.value,...patch}}:current);
  const save=()=>attempt(()=>{if(!edit)return;const original=edit.base.deliveryPlanning??blankDeliveryPlanning();if(edit.kind==='route'){const value=edit.value;commit(edit.base,{...original,steps:original.steps.some(s=>s.id===value.id)?original.steps.map(s=>s.id===value.id?value:s):[...original.steps,value]},'Route step saved. Undo restores the previous record.');}else{const value=edit.value;commit(edit.base,{...original,items:original.items.some(i=>i.id===value.id)?original.items.map(i=>i.id===value.id?value:i):[...original.items,value]},'Transport item saved. Undo restores the previous record.');}});
  const remove=()=>attempt(()=>{if(!edit)return;const original=edit.base.deliveryPlanning??blankDeliveryPlanning();commit(edit.base,edit.kind==='route'?{...original,steps:original.steps.filter(s=>s.id!==edit.value.id)}:{...original,items:original.items.filter(i=>i.id!==edit.value.id)},'Delivery record removed. Undo restores it.');});
  const move=(index:number,direction:-1|1)=>attempt(()=>{const steps=[...data.steps],other=index+direction;if(other<0||other>=steps.length)return;[steps[index],steps[other]]=[steps[other],steps[index]];commit(plan,{...data,steps},'Route order updated.');});
  const measurement=(label:string,value:number|null|undefined,onChange:(next:number|null)=>void)=><label key={label}>{label} ({units})<input type="number" min={0} max={100_000/factor} step="any" value={value==null?'':Number((value/factor).toFixed(6))} placeholder="Unknown" onChange={e=>onChange(e.target.value===''?null:e.target.valueAsNumber*factor)}/></label>;
  const route=edit?.kind==='route'?edit.value:undefined,item=edit?.kind==='item'?edit.value:undefined,sourceItem=item?.source?plan.furniture.find(f=>f.id===item.source!.furnitureId):undefined;
  const hasExisting=!!edit&&(edit.kind==='route'?data.steps:data.items).some(record=>record.id===edit.value.id);
  return <section className="delivery-planning" aria-labelledby="delivery-planning-title">
    <header><span className="eyebrow">Before ordering or moving</span><h2 id="delivery-planning-title">Check the delivery route</h2><p>Record the narrowest clear openings and the dimensions of each item as it will travel. These checks help find bottlenecks; they do not guarantee moving fit.</p></header>
    <div className="delivery-toolbar"><ChoiceButtons<'route'|'item'|'checks'> label="Delivery view" value={view} options={[{value:'route',label:'Route'},{value:'item',label:'Items'},{value:'checks',label:'Checks'}]} onChange={setView}/><ChoiceButtons<'mm'|'in'> label="Measurement units" value={units} options={[{value:'mm',label:'Millimetres'},{value:'in',label:'Inches'}]} onChange={setUnits}/></div>
    <p className="delivery-help">{units==='in'?'Enter decimal inches.':'Enter millimetres.'} Leave unmeasured fields blank. Measure clear space after handles, trim, rails and other obstructions. Check turning space, door approaches, lift rules and weight limits with the delivery team.</p>
    {view==='route'&&<>
      <div className="delivery-section-heading"><h3>Route from entrance to room</h3><span>{data.steps.length}/{MAX_DELIVERY_STEPS} steps</span><button disabled={disabled||!!edit||data.steps.length>=MAX_DELIVERY_STEPS} onClick={()=>start({base:plan,kind:'route',value:blankDeliveryStep('door')})}>Add route step</button></div>
      {!data.steps.length&&<p className="delivery-empty">Start with the entrance, then add each corridor, lift, turn or stair along the route.</p>}
      <ol className="delivery-records">{data.steps.map((step,index)=><li key={step.id}><div><strong>{index+1}. {step.name}</strong><small>{deliveryRouteKinds.find(k=>k.value===step.kind)?.label} · {deliveryMeasurementFields[step.kind].map(f=>`${f.label}: ${numberText(step.measurements[f.key])}`).join(' · ')}</small></div><div className="delivery-actions"><button disabled={disabled||!!edit} aria-label={`Edit ${step.name}`} onClick={()=>start({base:plan,kind:'route',value:structuredClone(step)})}>Edit</button><button disabled={disabled||!!edit||index===0} aria-label={`Move ${step.name} earlier`} onClick={()=>move(index,-1)}>↑</button><button disabled={disabled||!!edit||index===data.steps.length-1} aria-label={`Move ${step.name} later`} onClick={()=>move(index,1)}>↓</button></div></li>)}</ol>
      {route&&<div className="delivery-edit"><h3>{hasExisting?'Edit route step':'New route step'}</h3><label>Route step name<input maxLength={120} value={route.name} onChange={e=>patchRoute({name:e.target.value})} placeholder="e.g. Front entrance"/></label><ChoiceButtons label="Route step type" value={route.kind} options={deliveryRouteKinds} onChange={kind=>patchRoute({kind,measurements:blankDeliveryStep(kind).measurements})}/><div className="delivery-fields">{deliveryMeasurementFields[route.kind].map(field=>measurement(field.label,route.measurements[field.key],value=>patchRoute({measurements:{...route.measurements,[field.key]:value}})))}</div>{route.kind==='lift'&&<p className="delivery-help">Record the lift door and its usable cabin interior. Entry and cabin checks use the same item orientation.</p>}{(route.kind==='turn'||route.kind==='stair')&&<p className="delivery-help">This step always needs a manual check, even when all dimensions are entered.</p>}<label>Route notes<textarea maxLength={1000} value={route.notes} onChange={e=>patchRoute({notes:e.target.value})} placeholder="Obstructions, door removal, landings or arrangements to confirm"/></label>{stale&&<p role="alert">The project changed. Your draft is retained. Cancel and reopen the record before saving.</p>}<div className="delivery-actions"><button disabled={disabled||stale} onClick={save}>Save route step</button><button onClick={()=>setEdit(undefined)}>Cancel edit</button>{hasExisting&&<button disabled={disabled||stale} onClick={remove}>Remove route step</button>}</div></div>}
    </>}
    {view==='item'&&<>
      <div className="delivery-section-heading"><h3>Items to transport</h3><span>{data.items.length}/{MAX_DELIVERY_ITEMS} items</span><button disabled={disabled||!!edit||data.items.length>=MAX_DELIVERY_ITEMS} onClick={()=>start({base:plan,kind:'item',value:blankDeliveryItem()})}>Add manual item</button></div>
      <ul className="delivery-records">{data.items.map(record=><li key={record.id}><div><strong>{record.name}</strong><small>{record.basis} · {numberText(record.widthMm)} × {numberText(record.depthMm)} × {numberText(record.heightMm)}</small><small>{deliveryItemSourceStatus(plan,record).message}</small></div><button disabled={disabled||!!edit} aria-label={`Edit ${record.name}`} onClick={()=>start({base:plan,kind:'item',value:structuredClone(record)})}>Edit</button></li>)}</ul>
      <details open={!item}><summary>Copy assembled dimensions from placed furniture</summary><label>Find placed furniture<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name or floor"/></label><div className="delivery-furniture-choices">{matches.slice(0,24).map(c=><button key={c.f.id} disabled={disabled||!!edit||data.items.length>=MAX_DELIVERY_ITEMS} aria-label={`Use ${c.name} on ${c.floor}`} onClick={()=>start({base:plan,kind:'item',value:itemFromFurniture(c.f,c.name)})}>{c.name}<small>{c.floor} · {numberText(c.f.widthMm)} × {numberText(c.f.depthMm)} × {numberText(c.f.heightMm)}</small></button>)}</div>{matches.length>24&&<small>Showing 24 matches. Refine the search to find another item.</small>}{!matches.length&&<p>No matching placed furniture. Add a manual item for a shipping box or another piece.</p>}</details>
      {item&&<div className="delivery-edit"><h3>{hasExisting?'Edit transport item':'New transport item'}</h3><label>Transport item name<input maxLength={120} value={item.name} onChange={e=>patchItem({name:e.target.value})}/></label><ChoiceButtons label="Dimension basis" value={item.basis} options={[{value:'assembled',label:'Assembled'},{value:'packaged',label:'Packaged'},{value:'unknown',label:'Unknown'}]} onChange={basis=>{if(basis!==item.basis)patchItem({basis,widthMm:null,depthMm:null,heightMm:null,dimensionSource:'entered'});}}/><p className="delivery-help">Changing the basis clears dimensions. Packaged dimensions must come from you or the supplier; the model does not provide shipping-box sizes. Add a separate named record for every package you need to check.</p><div className="delivery-fields">{(['widthMm','depthMm','heightMm'] as const).map(key=>measurement(`Item ${key.replace('Mm','')}`,item[key],value=>patchItem({[key]:value,dimensionSource:'entered'})))}</div><ChoiceButtons label="Fixed transport orientation" value={item.orientation} options={deliveryOrientations} onChange={orientation=>patchItem({orientation})}/><p className="delivery-help">Across the opening: {numberText(orientedDeliveryDimensions(item).widthMm)} · along the route: {numberText(orientedDeliveryDimensions(item).depthMm)} · vertical: {numberText(orientedDeliveryDimensions(item).heightMm)}. This orientation is used for every step; carrying and changing orientation are not simulated.</p><p>{deliveryItemSourceStatus(plan,item).message}</p>{sourceItem&&<button onClick={()=>patchItem({...itemFromFurniture(sourceItem,item.name,item.id),notes:item.notes,orientation:item.orientation})}>Refresh assembled model dimensions</button>}<label>Transport notes<textarea maxLength={1000} value={item.notes} onChange={e=>patchItem({notes:e.target.value})} placeholder="Packaging source, removable parts or handling restrictions"/></label>{stale&&<p role="alert">The project changed. Your draft is retained. Cancel and reopen the record before saving.</p>}<div className="delivery-actions"><button disabled={disabled||stale} onClick={save}>Save transport item</button><button onClick={()=>setEdit(undefined)}>Cancel edit</button>{hasExisting&&<button disabled={disabled||stale} onClick={remove}>Remove transport item</button>}</div></div>}
    </>}
    {view==='checks'&&<><h3>Compare saved items with the route</h3><p>Positive spare clearance only compares bounding dimensions. It does not account for hands, protection, flex, door approaches or the movement between steps. Zero clearance needs checking.</p>{!data.steps.length||!data.items.length?<p className="delivery-empty">Add and save at least one route step and one transport item to compare them.</p>:data.items.map(record=><article className="delivery-check-item" key={record.id}><h4>{record.name}</h4><p>{record.basis} · {deliveryOrientations.find(o=>o.value===record.orientation)?.label}</p><small>{deliveryItemSourceStatus(plan,record).message}</small><ul>{data.steps.map((step,index)=>{const result=assessDeliveryStep(record,step,plan);return <li key={step.id} className={`delivery-check delivery-check-${result.state}`}><strong>{index+1}. {step.name}</strong><p>{result.message}</p>{result.missing.length>0&&<small>Missing: {result.missing.join('; ')}</small>}{result.clearances.length>0&&<small>Spare clearance: {result.clearances.map(c=>`${c.label} ${numberText(c.mm)}`).join(' · ')}</small>}</li>;})}</ul></article>)}</>}
    <footer><button disabled={!data.steps.length&&!data.items.length} onClick={()=>attempt(()=>printDeliveryPlanning(plan))}>Print saved delivery summary</button><small>These private records travel with your project backups and Undo. Public room links exclude them.</small></footer>
    {error&&<p role="alert">{error}</p>}<p role="status" aria-live="polite">{message}</p>
  </section>;
}
