import {useEffect,useRef,useState} from 'react';
import {catalog} from './catalog';
import {assistantGoals,assistantRooms,assistantStyles,buildAssistantProposal,suggestDesigns,type AssistantProposal,type DesignBrief} from './designAssistant';
import type {KitPreviewBridge} from './FurnitureKitsPanel';
import {formatMoney,moneyInput,parseMoneyInput} from './selectionSchedule';
import type {PlanDocumentV1} from './types';
import './design-assistant.css';
const initial=(floorId:string):DesignBrief=>({version:1,floorId,goal:'reading',style:'natural',householdSize:1,clearanceMm:300,keepItemIds:[],manualPrices:[]});
export function DesignAssistantPanel({plan,floorId,preview,onClose}:{plan:PlanDocumentV1;floorId:string;preview:KitPreviewBridge;onClose?():void}){
 const [brief,setBrief]=useState<DesignBrief>(()=>initial(floorId)),[budget,setBudget]=useState(''),[currency,setCurrency]=useState('USD'),[proposals,setProposals]=useState<AssistantProposal[]>([]),[conflicts,setConflicts]=useState<string[]>([]),[selected,setSelected]=useState<AssistantProposal>(),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[stageId,setStageId]=useState<string>();
 const bridge=useRef(preview),staged=useRef<string|undefined>(undefined),epoch=useRef(0),latest=useRef(plan);bridge.current=preview;latest.current=plan;
 function discard(){if(staged.current)bridge.current.discard(staged.current);staged.current=undefined;setStageId(undefined);}
 useEffect(()=>()=>{epoch.current++;if(staged.current)bridge.current.discard(staged.current);},[]);
 useEffect(()=>{epoch.current++;discard();setProposals([]);setSelected(undefined);setBrief(b=>({...b,floorId,roomKey:undefined,keepItemIds:[]}));setBusy(false);},[plan,floorId]);
 function change(patch:Partial<DesignBrief>){discard();setBrief(b=>({...b,...patch}));setProposals([]);setSelected(undefined);setConflicts([]);}
 async function generate(){if(busy||preview.blocked)return;const base=plan,request=++epoch.current;discard();setBusy(true);setError('');setNotice('');try{const amount=budget.trim()?parseMoneyInput(budget,currency):null;if(budget.trim()&&amount===null)throw new Error('Enter a valid budget amount.');const input={...brief,...(amount===null?{budget:undefined}:{budget:{amountMinor:amount,currency}})};await new Promise(resolve=>setTimeout(resolve,0));const result=suggestDesigns(base,input);if(request!==epoch.current||latest.current!==base)return;setProposals(result.proposals);setConflicts(result.conflicts);setSelected(undefined);setNotice(result.proposals.length?'Choose a local recipe to preview. No service was contacted.':'No safe placement was found for these constraints. Try another room, smaller pieces or less spacing.');}catch(e){if(request===epoch.current)setError((e as Error).message);}finally{if(request===epoch.current)setBusy(false);}}
 function stage(proposal:AssistantProposal){if(preview.blocked||proposal.preview.base!==plan){setError('The home changed. Generate fresh choices first.');return;}try{discard();const id=preview.stage(proposal.preview);staged.current=id;setStageId(id);setSelected(proposal);setError('');setNotice('Preview only. Apply commits one undoable arrangement.');}catch(e){setError((e as Error).message);}}
 function revise(next:AssistantProposal['operations']){if(!selected)return;try{stage(buildAssistantProposal(plan,selected.brief,next,selected.title));}catch(e){setError((e as Error).message);}}
 function apply(){if(!selected||!stageId||preview.activeId!==stageId||preview.blocked)return;try{preview.apply(stageId);staged.current=undefined;setStageId(undefined);setSelected(undefined);setProposals([]);setNotice('Arrangement applied. One Undo restores the previous home.');}catch(e){setError((e as Error).message);}}
 return <section className="design-tools" aria-label="Constrained design assistant"><header><p className="design-eyebrow">Local ideas, your decisions</p><h2>Help me arrange this room</h2><p>Three recipe choices from the existing catalog. Geometry, existing furniture, dimensions and locks stay unchanged. This is a local design aid, with no AI service or provider cost.</p></header>
 {error&&<p role="alert" className="design-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <fieldset disabled={busy||preview.blocked}><legend>Your brief</legend><label>Measured area<select value={brief.roomKey??''} onChange={e=>change({roomKey:e.target.value||undefined})}><option value="">Whole current floor</option>{assistantRooms(plan,floorId).map(r=><option key={r.key} value={r.key}>{r.name} · {r.kind}</option>)}</select></label>
 <div className="design-row"><label>What should this space support?<select value={brief.goal} onChange={e=>change({goal:e.target.value as DesignBrief['goal']})}>{assistantGoals.map(g=><option value={g} key={g}>{g}</option>)}</select></label><label>Favorite style<select value={brief.style} onChange={e=>change({style:e.target.value as DesignBrief['style']})}>{assistantStyles.map(s=><option key={s}>{s}</option>)}</select></label></div>
 <div className="design-row"><label>People<input type="number" min={1} max={8} value={brief.householdSize} onChange={e=>change({householdSize:e.target.valueAsNumber})}/></label><label>Gap from existing furniture (mm)<input type="number" min={0} max={1200} step={50} value={brief.clearanceMm} onChange={e=>change({clearanceMm:e.target.valueAsNumber})}/></label></div>
 <div className="design-row"><label>Maximum piece width (mm, optional)<input type="number" min={100} max={10000} value={brief.maxPieceWidthMm??''} onChange={e=>change({maxPieceWidthMm:e.target.value?e.target.valueAsNumber:undefined})}/></label><label>Maximum piece depth (mm, optional)<input type="number" min={100} max={10000} value={brief.maxPieceDepthMm??''} onChange={e=>change({maxPieceDepthMm:e.target.value?e.target.valueAsNumber:undefined})}/></label></div>
 <div className="design-row"><label>Budget for new additions (optional)<input inputMode="decimal" value={budget} onChange={e=>{setBudget(e.target.value);change({});}}/></label><label>Currency<select value={currency} onChange={e=>{setCurrency(e.target.value);change({manualPrices:[]});}}>{['USD','CAD','GBP','EUR','AUD','INR'].map(c=><option key={c}>{c}</option>)}</select></label></div><p>Catalog models have no retail prices. A known subtotal is never a complete budget check when any price is missing.</p><button onClick={()=>void generate()}>Find arrangements</button></fieldset>
 {conflicts.length>0&&<details open={!proposals.length}><summary>Constraints that could not be met</summary><ul>{conflicts.map((message,i)=><li key={i}>{message}</li>)}</ul></details>}
 <div className="design-options">{proposals.map(p=><article key={p.id}><h3>{p.title}</h3><p>{p.operations.map(o=>o.action==='place'?catalog.find(c=>c.id===o.catalogId)?.name:'').join(' · ')}</p><ul>{p.reasons.map(r=><li key={r}>{r}</li>)}</ul><p>{p.cost.currency?`Known additions: ${formatMoney(p.cost.knownMinor,p.cost.currency)}.`:'No prices entered.'} {p.cost.unknownCount} unpriced items.</p><button disabled={busy||preview.blocked} onClick={()=>stage(p)}>Preview this arrangement</button></article>)}</div>
 {selected&&<section aria-label="Review arrangement"><h3>{selected.title}</h3><p>{selected.cost.currency?`Known additions: ${formatMoney(selected.cost.knownMinor,selected.cost.currency)}.`:'No prices entered.'} {selected.cost.unknownCount} unpriced items.</p><ul className="design-warning">{selected.unmet.map(u=><li key={u}>{u}</li>)}</ul><p>Edit a suggestion before applying. Removing a support also requires removing its supported objects.</p>
 <div className="design-row"><button onClick={()=>revise(selected.operations.map(o=>o.action==='place'?{...o,x:o.x-100}:o))}>Move left 100 mm</button><button onClick={()=>revise(selected.operations.map(o=>o.action==='place'?{...o,x:o.x+100}:o))}>Move right 100 mm</button><button onClick={()=>revise(selected.operations.map(o=>o.action==='place'?{...o,z:o.z-100}:o))}>Move back 100 mm</button><button onClick={()=>revise(selected.operations.map(o=>o.action==='place'?{...o,z:o.z+100}:o))}>Move forward 100 mm</button></div>
 {selected.operations.map((o,i)=>o.action==='place'&&<div className="design-piece" key={i}><strong>{catalog.find(c=>c.id===o.catalogId)?.name}</strong><button disabled={selected.operations.length===1} onClick={()=>revise(selected.operations.filter((_,n)=>n!==i))}>Remove from idea</button><label>Manual unit price in {currency}<input inputMode="decimal" defaultValue={moneyInput(selected.brief.manualPrices.find(q=>q.catalogId===o.catalogId&&q.currency===currency)?.amountMinor??null,currency)} key={selected.id+':'+i} onBlur={e=>{try{const amount=parseMoneyInput(e.target.value,currency),previous=selected.brief.manualPrices.find(q=>q.catalogId===o.catalogId&&q.currency===currency)?.amountMinor??null;if(amount===previous)return;const revised={...selected.brief,manualPrices:[...selected.brief.manualPrices.filter(q=>q.catalogId!==o.catalogId),...(amount===null?[]:[{catalogId:o.catalogId,currency,amountMinor:amount}])]};stage(buildAssistantProposal(plan,revised,selected.operations,selected.title));}catch(error){setError((error as Error).message);}}}/></label></div>)}
 <button disabled={preview.blocked||preview.activeId!==stageId} onClick={apply}>Apply arrangement</button><button onClick={()=>{discard();setSelected(undefined);setNotice('Idea discarded. The saved home is unchanged.');}}>Discard</button></section>}
 {onClose&&<button disabled={busy} onClick={()=>{discard();onClose();}}>Close</button>}
 </section>;
}
