import {useEffect,useState} from 'react';
import type {SceneController} from './scene/SceneController';
import type {HomeShot} from './previewShots';
export function HomePreview({controller,shots,onClose,canCapture}:{controller:SceneController;shots:HomeShot[];onClose():void;canCapture:boolean}){
 const [format,setFormat]=useState('screen');const [frame,setFrame]=useState<{left:number;top:number;width:number;height:number}>();
 useEffect(()=>{const update=()=>setFrame(controller.pictureFrame(format as 'screen'|'landscape'|'portrait'|'square'));update();window.addEventListener('resize',update);return()=>window.removeEventListener('resize',update)},[format,controller]);
 const [index,setIndex]=useState(0),[playing,setPlaying]=useState(false),[orbit,setOrbit]=useState(false),[error,setError]=useState('');
 const reduced=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches??false;
 useEffect(()=>{controller.beginHomePreview();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();onClose();}};window.addEventListener('keydown',key);return()=>{window.removeEventListener('keydown',key);controller.endHomePreview();};},[controller,onClose]);
 useEffect(()=>{controller.showHomeShot(shots[index],orbit&&!reduced);},[controller,shots,index,orbit,reduced]);
 useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setIndex(i=>(i+1)%shots.length),5500);return()=>clearInterval(timer);},[playing,shots.length]);
 return <section className="home-preview" onKeyDown={e=>{e.stopPropagation();if(e.key==='Escape')onClose();if(e.key==='Tab'){const buttons=Array.from(e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),select,input'));const i=buttons.indexOf(document.activeElement as HTMLElement);e.preventDefault();buttons[(i+(e.shiftKey?-1:1)+buttons.length)%buttons.length]?.focus();}}} role="dialog" aria-modal="true" aria-label="Home preview"><>{frame&&<div className="preview-crop-frame" style={frame}><span>Export crop</span></div>}</><header><div><strong>Your furnished home</strong><span>{shots[index].name} · {index+1} / {shots.length}</span></div><button autoFocus onClick={onClose}>Exit preview</button></header><div className="shot-strip" aria-label="Preview viewpoints">{shots.map((shot,i)=><button key={i} aria-pressed={index===i} onClick={()=>{setPlaying(false);setIndex(i)}}>{shot.name}</button>)}</div><footer><label className="preview-format">Picture format<select value={format} onChange={e=>setFormat(e.target.value)}><option value="screen">Current view</option><option value="landscape">Landscape 1600 × 900</option><option value="portrait">Portrait 900 × 1600</option><option value="square">Square 1200 × 1200</option></select></label><button aria-label="Previous view" onClick={()=>{setPlaying(false);setIndex((index+shots.length-1)%shots.length);}}>←</button><button onClick={()=>setPlaying(!playing)}>{playing?'Pause':'Play slideshow'}</button><button aria-label="Next view" onClick={()=>{setPlaying(false);setIndex((index+1)%shots.length);}}>→</button><button aria-pressed={orbit} disabled={reduced} onClick={()=>setOrbit(!orbit)}>Gentle orbit</button><button disabled={!canCapture} title={canCapture?'Download this view':'Picture downloads unavailable with Google scenery'} onClick={()=>{try{const a=document.createElement('a');a.href=controller.screenshot(format as "screen"|"landscape"|"portrait"|"square");a.download=`Nook-and-Nest-${index+1}.png`;a.click();}catch{setError('Could not save the picture. Try again once the view has loaded.');}}}>Save picture</button>{error&&<p role="alert">{error}</p>}</footer></section>;
}
