import {useEffect,useMemo,useRef,useState} from 'react';
import {exportRemixSnapshot,importRemixSnapshot,originalRemixExamples,remixCopySeed,remixTags,type RemixPackage,type RemixPlan} from './remixSnapshot';
import {ideaReports,ideasPage,inspectIdea,moderateIdea,moderationPage,readIdea,remixAvailability,reportIdea,resolveIdeaReport,type IdeaCard,type IdeaReport,type IdeaSubmission} from './remixApi';
import {makeRemixThumbnail} from './remixThumbnail';
import {RemixMiniature,RemixPreview} from './RemixPreview';
import {BookmarkSimple,Check} from '@phosphor-icons/react';
import {listSavedIdeas,saveIdea,removeSavedIdea,SavedIdeasCorruptionError,type SavedIdea} from './savedIdeas';
import {SavedIdeasShelf} from './SavedIdeasShelf';
import './remix-gallery.css';
export function IdeasPanel({onCreatePrivateCopy,onBusyChange}:{onCreatePrivateCopy:(seed:RemixPlan)=>Promise<void>;onBusyChange?:(value:boolean)=>void}){
 const originals=useMemo(originalRemixExamples,[]),[selected,setSelected]=useState<RemixPackage>(),[cards,setCards]=useState<IdeaCard[]>([]),[cursor,setCursor]=useState<string|null>(null),[q,setQ]=useState(''),[tag,setTag]=useState(''),[query,setQuery]=useState({q:'',tag:''}),[community,setCommunity]=useState(false),[copyConsent,setCopyConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[status,setStatus]=useState<Awaited<ReturnType<typeof remixAvailability>>>(),[reportReason,setReportReason]=useState('privacy'),[reportNote,setReportNote]=useState(''),[reportId,setReportId]=useState(()=>crypto.randomUUID()),[queue,setQueue]=useState<Array<IdeaCard&IdeaSubmission>>([]),[queueCursor,setQueueCursor]=useState<string|null>(null),[inspected,setInspected]=useState<Awaited<ReturnType<typeof inspectIdea>>>(),[moderationNote,setModerationNote]=useState(''),[reports,setReports]=useState<IdeaReport[]>([]);
 const [saved,setSaved]=useState<SavedIdea[]>([]),[savedReady,setSavedReady]=useState(false),[shelfError,setShelfError]=useState(''),[collection,setCollection]=useState<'originals'|'saved'>('originals'),[removed,setRemoved]=useState<SavedIdea>(),[damagedId,setDamagedId]=useState<string>(),[selectedFromSaved,setSelectedFromSaved]=useState(false);
 const shelfRequest=useRef(0),selectedRegion=useRef<HTMLElement|null>(null);
 async function refreshShelf(){const request=++shelfRequest.current;try{const values=await listSavedIdeas();if(alive.current&&request===shelfRequest.current){setSaved(values);setShelfError('');setDamagedId(undefined);setSavedReady(true);}}catch(e){if(alive.current&&request===shelfRequest.current){setShelfError((e as Error).message);setDamagedId(e instanceof SavedIdeasCorruptionError?e.ideaId:undefined);setSavedReady(false);}}}
 useEffect(()=>{void refreshShelf();const focus=()=>{if(!working.current)void refreshShelf();};window.addEventListener('focus',focus);return()=>{++shelfRequest.current;window.removeEventListener('focus',focus);};},[]);
 useEffect(()=>{if(selected){selectedRegion.current?.focus({preventScroll:true});selectedRegion.current?.scrollIntoView?.({block:'nearest',behavior:'instant'});}},[selected]);
 const selectedSaved=!!selected&&saved.some(idea=>idea.packet.source.source===selected.source.source&&idea.packet.source.id===selected.source.id&&idea.packet.source.revision===selected.source.revision&&JSON.stringify(idea.packet)===JSON.stringify(selected));
 async function saveSelected(){if(!selected||!savedReady)return;const packet=selected;await run(async signal=>{let current=packet;if(packet.source.source==='gallery'){const fresh=await readIdea(packet.source.id,signal);if(fresh.revision!==packet.source.revision)throw Error('This idea changed. Open its current preview first.');current={...packet,snapshot:fresh.snapshot};}if(!alive.current)return;const idea=await saveIdea(current);if(alive.current){setSaved(previous=>[idea,...previous.filter(item=>item.id!==idea.id)]);setSelected(idea.packet);setSelectedFromSaved(true);setNotice('Idea saved on this device. Your projects are unchanged.');}});}
 async function removeSaved(idea:SavedIdea){await run(async()=>{await removeSavedIdea(idea.id);if(alive.current){setSaved(previous=>previous.filter(item=>item.id!==idea.id));setRemoved(idea);setNotice('Removed from saved ideas. Existing projects are unchanged.');}});}
 async function undoRemove(){if(!removed)return;const previous=removed;await run(async()=>{const idea=await saveIdea(previous.packet);if(alive.current){setSaved(items=>[idea,...items.filter(item=>item.id!==idea.id)]);setRemoved(undefined);setNotice('Idea restored to this device.');}});}
 const alive=useRef(true),working=useRef(false),abort=useRef<AbortController|undefined>(undefined);useEffect(()=>{alive.current=true;return()=>{alive.current=false;abort.current?.abort();onBusyChange?.(false);};},[]);
 async function run(work:(signal:AbortSignal)=>Promise<void>){if(working.current)return;working.current=true;abort.current=new AbortController();setBusy(true);onBusyChange?.(true);setError('');setNotice('');try{await work(abort.current.signal);}catch(e){if(alive.current)setError((e as Error).message);}finally{if(alive.current){setBusy(false);onBusyChange?.(false);}working.current=false;}}
 function choose(packet:RemixPackage,fromSaved=false){setSelected(packet);setSelectedFromSaved(fromSaved);setCopyConsent(false);setReportNote('');setReportId(crypto.randomUUID());}
 async function loadCommunity(next=false){await run(async signal=>{const filter=next?query:{q,tag},page=await ideasPage(filter.q,filter.tag,next?cursor??undefined:undefined,signal);if(alive.current){setCards(page.items);setCursor(page.nextCursor);setQuery(filter);setCommunity(true);}});}
 async function openCard(id:string){await run(async signal=>{const value=await readIdea(id,signal);if(alive.current)choose({schema:'nook-remix-package/1',snapshot:value.snapshot,source:{source:'gallery',id:value.id,revision:value.revision}});});}
 async function copy(exportOnly=false){if(!selected||!exportOnly&&!copyConsent)return;const packet=selected;await run(async signal=>{let snapshot=packet.snapshot;if(packet.source.source==='gallery'&&!selectedFromSaved){const fresh=await readIdea(packet.source.id,signal);if(fresh.revision!==packet.source.revision)throw Error('This idea changed. Open its current preview first.');snapshot=fresh.snapshot;}const seed=remixCopySeed(snapshot,packet.source);if(!alive.current)return;if(exportOnly){exportRemixSnapshot(snapshot,packet.source);return;}await onCreatePrivateCopy(seed);if(alive.current){setCopyConsent(false);setNotice('Independent private copy created with its creator credits. The original is unchanged.');}});}
 async function loadModeration(next=false){await run(async signal=>{const state=await remixAvailability(signal);if(alive.current)setStatus(state);if(!state.isCurator)throw Error(state.moderationConfigured?'This account does not have curator access.':'Curator access has not been configured.');const page=await moderationPage(next?queueCursor??undefined:undefined,signal),reportList=await ideaReports(signal);if(alive.current){setQueue(page.items);setQueueCursor(page.nextCursor);setReports(reportList);}});}
 async function inspect(id:string){await run(async signal=>{const value=await inspectIdea(id,signal);if(alive.current){setInspected(value);setModerationNote('');}});}
 return <section className="remix-tools" aria-label="Ideas gallery"><header><p className="remix-eyebrow">A few thoughtful beginnings</p><h2>Ideas to make your own</h2><p>Collect a little inspiration, then make it your own. Previewing an idea leaves your home unchanged.</p></header>{error&&<p role="alert" className="remix-error">{error}</p>}{notice&&<p role="status">{notice}</p>}{removed&&<button disabled={busy} onClick={()=>void undoRemove()}>Undo removal</button>}
 <nav className="saved-ideas-tabs" aria-label="Idea collections"><button aria-pressed={collection==='originals'} onClick={()=>setCollection('originals')}>Originals</button><button aria-pressed={collection==='saved'} onClick={()=>setCollection('saved')}><BookmarkSimple size={18} aria-hidden="true"/>Saved ideas · {saved.length}</button></nav>
 {shelfError&&<p role="alert" className="remix-error">{shelfError} <button disabled={busy} onClick={()=>void refreshShelf()}>Retry saved ideas</button>{damagedId&&<button disabled={busy} onClick={()=>void run(async()=>{await removeSavedIdea(damagedId);await refreshShelf();})}>Remove damaged saved copy</button>}</p>}
 {collection==='saved'&&(!savedReady&&!shelfError?<p role="status">Loading saved ideas…</p>:<SavedIdeasShelf ideas={saved} busy={busy} onChoose={packet=>choose(packet,true)} onRemove={idea=>void removeSaved(idea)}/>)}
 {collection==='originals'&&<><h3>Original Nook & Nest recipes</h3><div className="idea-grid">{originals.map(example=><article key={example.id}><RemixMiniature value={makeRemixThumbnail(example.snapshot)} label={example.snapshot.title}/><h4>{example.snapshot.title}</h4><p>Original recipe · creator credit: Nook & Nest</p><button disabled={busy} onClick={()=>choose({schema:'nook-remix-package/1',snapshot:example.snapshot,source:{source:'builtin',id:example.id,revision:1}})}>Preview {example.snapshot.title}</button></article>)}</div></>}
 <fieldset disabled={busy}><legend>Open a local room package</legend><label>Import package<input type="file" accept="application/json,.json" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void run(async()=>{const packet=await importRemixSnapshot(file);if(alive.current)choose(packet);});}}/></label><p>Imported credits are self-reported. No imported file is uploaded or submitted automatically.</p></fieldset>
 <fieldset disabled={busy}><legend>Community discovery</legend><div className="remix-row"><label>Search titles and descriptions<input maxLength={80} value={q} onChange={e=>setQ(e.target.value)}/></label><label>Tag<select value={tag} onChange={e=>setTag(e.target.value)}><option value="">Any tag</option>{remixTags.map(t=><option key={t}>{t}</option>)}</select></label></div><button onClick={()=>void loadCommunity()}>Browse approved community ideas</button><p>Community access depends on a configured curator. Submissions require explicit owner permission and review; there is no automatic public feed.</p></fieldset>
 {community&&<><div className="idea-grid">{cards.map(card=><article key={card.id}><RemixMiniature value={card.thumbnail} label={card.title}/><h4>{card.title}</h4><p>Creator credit (self-reported): {card.creator}</p><p>{card.description}</p><p>{card.tags.join(' · ')} · {card.allowCopy?'Copies allowed with credit':'Viewing only'}</p><button disabled={busy} onClick={()=>void openCard(card.id)}>Preview {card.title}</button></article>)}</div>{!cards.length&&<p>No approved ideas match this page.</p>}{cursor&&<button disabled={busy} onClick={()=>void loadCommunity(true)}>Next page of ideas</button>}</>}
 {selected&&<section aria-label="Selected idea" ref={selectedRegion} tabIndex={-1}><RemixPreview snapshot={selected.snapshot}/><div className="saved-ideas-save"><button disabled={busy||!savedReady||!selected.snapshot.allowCopy||selectedSaved} onClick={()=>void saveSelected()}>{selectedSaved?<Check size={18} aria-hidden="true"/>:<BookmarkSimple size={18} aria-hidden="true"/>}{selectedSaved?'Saved on this device':'Save idea on this device'}</button>{!selected.snapshot.allowCopy&&<span>Viewing only · the creator has not allowed saving copies.</span>}</div><fieldset disabled={busy}><legend>Keep the source independent</legend><label className="remix-check"><input type="checkbox" checked={copyConsent} disabled={!selected.snapshot.allowCopy} onChange={e=>setCopyConsent(e.target.checked)}/>Create a new private project and keep every creator credit</label><button disabled={!selected.snapshot.allowCopy||!copyConsent} onClick={()=>void copy()}>Make my own private copy</button><button disabled={!selected.snapshot.allowCopy} onClick={()=>void copy(true)}>Export permitted room package</button><p>Copies already saved cannot be recalled if the owner later disables sharing. Copy permission is a creator assertion, not a verified ownership certificate.</p></fieldset>{selected.source.source==='gallery'&&<details><summary>Report this community idea</summary><fieldset disabled={busy}><legend>Send a report for curator review</legend><p>Sign in through Project before reporting. Your account identity is not shown publicly.</p><label>Reason<select value={reportReason} onChange={e=>{setReportReason(e.target.value);setReportId(crypto.randomUUID());}}>{['privacy','rights','unsafe','spam','other'].map(r=><option key={r}>{r}</option>)}</select></label><label>Explanation<textarea maxLength={500} value={reportNote} onChange={e=>{setReportNote(e.target.value);setReportId(crypto.randomUUID());}}/></label><button onClick={()=>void run(async signal=>{await reportIdea(selected.source.id,{requestId:reportId,reason:reportReason,note:reportNote},signal);if(alive.current)setNotice('Report received for curator review. This does not automatically remove the idea.');})}>Submit report</button></fieldset></details>}</section>}
 <details><summary>Curator tools</summary><p>Only explicitly configured curator accounts can use these tools. This panel does not grant permissions.</p><button disabled={busy} onClick={()=>void loadModeration()}>Check access and load review queue</button>{status?.isCurator&&<><p>Review exact public text, creator credit, inherited permissions and the full arrangement before deciding.</p><ul>{queue.map(item=><li key={item.id}>{item.title} · revision {item.revision} <button disabled={busy} onClick={()=>void inspect(item.id)}>Inspect {item.title}</button></li>)}</ul>{queueCursor&&<button disabled={busy} onClick={()=>void loadModeration(true)}>Next review page</button>}<h3>Open reports</h3>{reports.map(report=><article key={report.id}><p>{report.reason} · {report.note}</p><button disabled={busy} onClick={()=>void inspect(report.ideaId)}>Inspect reported idea</button><button disabled={busy} onClick={()=>void run(async signal=>{await resolveIdeaReport(report.id,signal);if(alive.current)setReports(old=>old.filter(r=>r.id!==report.id));})}>Mark report reviewed</button></article>)}{inspected&&<section aria-label="Curator inspection"><RemixPreview snapshot={inspected.snapshot}/><fieldset disabled={busy}><legend>Decision for revision {inspected.submission.revision} · {inspected.submission.state}</legend><label>Decision note<textarea maxLength={400} value={moderationNote} onChange={e=>setModerationNote(e.target.value)}/></label>{(inspected.submission.state==='pending'?['approve','reject']:inspected.submission.state==='approved'?['remove']:[]).map(decision=><button key={decision} onClick={()=>void run(async signal=>{await moderateIdea(inspected.submission,decision as 'approve'|'reject'|'remove',moderationNote,signal);if(alive.current){setInspected(undefined);setQueue(old=>old.filter(i=>i.id!==inspected.submission.id));setNotice('Decision saved for that exact revision.');}})}>{decision==='approve'?'Approve public listing':decision==='reject'?'Reject with reason':'Remove from public gallery'}</button>)}</fieldset></section>}</>}</details>
 </section>;
}

