import { useEffect, useMemo, useRef, useState } from 'react';
import { ChoiceButtons } from './ChoiceButtons';
import { preparePersonalPhoto } from './personalMedia';
import { importPersonalAssets, loadPersonalPhoto } from './personalStorage';
import { validatePlan } from './planValidation';
import { captureInstallChecklist, downloadInstallChecklist, installCandidates, installRevision, MAX_INSTALL_ITEMS, MAX_INSTALL_PHOTOS, MAX_INSTALL_TASKS, packingSummary, printInstallChecklist, refreshInstallChecklist, reviewInstallChecklist, updateInstallChecklist, type InstallChecklist, type InstallItem, type InstallPlan, type InstallTask, type InstallTemplate } from './installChecklist';
import './modular-install.css';

export interface InstallChecklistPanelProps { plan: InstallPlan; activeFloorId?: string; disabled?: boolean; onChange(base: InstallPlan, next: InstallPlan): void; onSelectItem?(id: string): void; onClose(): void }
const options = <T extends string>(values: readonly T[]) => values.map(value => ({ value, label: value === 'todo' ? 'To do' : value[0].toUpperCase() + value.slice(1) }));
const keyFor = (floorId: string, roomKey: string) => JSON.stringify([floorId, roomKey]);
function PrivatePhoto({ id, onRemove }: { id: string; onRemove(): void }) {
  const [image, setImage] = useState<string>(), [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; setImage(undefined); setLoading(true); loadPersonalPhoto(id).then(asset => { if (active) setImage(asset?.preview); }).catch(() => {}).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [id]);
  return <figure className="install-photo">{image ? <a href={image} target="_blank" rel="noopener noreferrer"><img src={image} alt="Private checklist evidence"/></a> : <span>{loading ? 'Loading local photo…' : 'Photo missing from this browser. Restore its private backup.'}</span>}<button type="button" onClick={onRemove}>Unlink photo</button></figure>;
}
export function InstallChecklistPanel({ plan, activeFloorId, disabled = false, onChange, onSelectItem, onClose }: InstallChecklistPanelProps) {
  const list = plan.installChecklist, candidates = useMemo(() => installCandidates(plan), [plan]), revision = useMemo(() => installRevision(plan), [plan]);
  const review = useMemo(() => list ? reviewInstallChecklist(plan, list) : undefined, [plan, list]), packing = list ? packingSummary(list) : undefined;
  const [template, setTemplate] = useState<InstallTemplate>(list?.template ?? 'install'), [floorId, setFloorId] = useState(activeFloorId ?? ''), [roomKey, setRoomKey] = useState(''), [search, setSearch] = useState('');
  const [selected, setSelected] = useState<Set<string>>(() => new Set(list?.items.filter(i => i.present).map(i => i.placementId) ?? []));
  const [captureOpen, setCaptureOpen] = useState(!list), [replaceConfirmed, setReplaceConfirmed] = useState(false), [removeConfirmed, setRemoveConfirmed] = useState(false);
  const [error, setError] = useState(''), [message, setMessage] = useState(''), [busy, setBusy] = useState(false), [page, setPage] = useState(0), [taskPage, setTaskPage] = useState(0);
  const [edit, setEdit] = useState<{ base: InstallPlan; task: InstallTask; fresh: boolean }>();
  const current = useRef(plan), editor = useRef(edit), operation = useRef(0), mounted = useRef(true); current.current = plan; editor.current = edit;
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; operation.current++; }; }, []);
  useEffect(() => { setEdit(undefined); setSelected(new Set(plan.installChecklist?.items.filter(i => i.present).map(i => i.placementId) ?? [])); setCaptureOpen(!plan.installChecklist); setRemoveConfirmed(false); setReplaceConfirmed(false); setMessage(''); setError(''); operation.current++; setBusy(false); }, [plan.id]);
  useEffect(() => { setPage(0); setTaskPage(0); }, [floorId, roomKey, search]);
  const attempt = (action: () => void) => { setError(''); try { action(); } catch (e) { setError(e instanceof Error ? e.message : 'The checklist could not be saved.'); } };
  const commit = (base: InstallPlan, value: InstallChecklist | undefined) => { if (disabled) throw new Error('Finish the active preview before saving checklist changes.'); onChange(base, updateInstallChecklist(base, current.current, value, validatePlan)); };
  const rooms = useMemo(() => [...new Map([...candidates, ...(list?.rooms ?? [])].map(r => [keyFor(r.floorId, r.roomKey), { floorId: r.floorId, floorName: r.floorName, roomKey: r.roomKey, roomName: r.roomName }])).values()].filter(r => !floorId || r.floorId === floorId), [candidates, list, floorId]);
  const matches = (item: { floorId: string; roomKey: string; name?: string; roomName?: string }) => (!floorId || item.floorId === floorId) && (!roomKey || keyFor(item.floorId, item.roomKey) === roomKey) && `${item.name ?? ''} ${item.roomName ?? ''}`.toLowerCase().includes(search.toLowerCase());
  const visibleCandidates = candidates.filter(matches), visibleItems = (list?.items ?? []).filter(matches);
  const visibleTasks = (list?.tasks ?? []).filter(task => (!floorId || !task.floorId || task.floorId === floorId) && (!roomKey || !task.roomKey || keyFor(task.floorId!, task.roomKey) === roomKey) && `${task.title} ${task.assignee ?? ''} ${task.note ?? ''}`.toLowerCase().includes(search.toLowerCase()));
  const currentIds = new Set(candidates.map(i => i.placementId)), chosen = [...selected].filter(id => currentIds.has(id));
  const newTask = (item?: InstallItem) => { if (!list) return; const room = roomKey ? list.rooms.find(r => keyFor(r.floorId, r.roomKey) === roomKey) : undefined; setEdit({ base: plan, fresh: true, task: { id: crypto.randomUUID(), title: '', ...(item ? { floorId: item.floorId, roomKey: item.roomKey, itemId: item.placementId } : room ? { floorId: room.floorId, roomKey: room.roomKey } : {}), state: 'unknown', photoAssetIds: [], evidenceRevision: list.revision.fingerprint, needsReview: !!review?.stale } }); setError(''); };
  const patchTask = (patch: Partial<InstallTask>) => setEdit(e => e ? { ...e, task: { ...e.task, ...patch } } : e);
  const patchItem = (id: string, patch: Partial<InstallItem>) => attempt(() => { if (!list) return; commit(plan, { ...list, items: list.items.map(i => i.placementId === id ? { ...i, ...patch } : i) }); });
  const addPhoto = async (file: File | undefined) => {
    if (!file || !edit || !list || busy) return; const base = edit.base, taskId = edit.task.id, token = ++operation.current;
    if (base !== current.current) { setError('The project changed. Reopen this task before adding evidence.'); return; }
    if (edit.task.photoAssetIds.length >= 4 || list.tasks.filter(t => t.id !== taskId).reduce((n, t) => n + t.photoAssetIds.length, 0) + edit.task.photoAssetIds.length >= MAX_INSTALL_PHOTOS) { setError('Use up to four photos per task and 32 per checklist.'); return; }
    setBusy(true); setError('');
    try {
      const asset = await preparePersonalPhoto(file); if (!mounted.current || token !== operation.current) return;
      if (current.current !== base || editor.current?.task.id !== taskId) throw new Error('The project or task changed. Reopen the task before adding this photo.');
      await importPersonalAssets({ version: 1, assets: [asset], missing: [] });
      if (!mounted.current || token !== operation.current) return;
      if (current.current !== base || editor.current?.task.id !== taskId) throw new Error('The project changed during photo storage. The photo is local but has not been attached.');
      setEdit(e => e?.task.id === taskId ? { ...e, task: { ...e.task, photoAssetIds: [...new Set([...e.task.photoAssetIds, asset.id])] } } : e);
    } catch (e) { if (mounted.current && token === operation.current) setError(e instanceof Error ? e.message : 'The local photo could not be added.'); }
    finally { if (mounted.current && token === operation.current) setBusy(false); }
  };
  return <section className="install-panel" aria-labelledby="install-heading"><header><div><span className="eyebrow">Make the plan practical</span><h2 id="install-heading">Install &amp; photo day</h2></div><button type="button" onClick={onClose}>Close</button></header>
    <p>Keep a private room checklist against a captured project revision. People, dates and progress are entered manually; nothing is sent or ordered.</p>{disabled && <p className="mi-notice">Finish the active preview before changing this checklist.</p>}
    <div className="mi-choices" role="group" aria-label="Checklist floor"><button type="button" aria-pressed={!floorId} onClick={() => { setFloorId(''); setRoomKey(''); }}>All floors</button>{plan.floors.map(f => <button type="button" key={f.id} aria-pressed={floorId === f.id} onClick={() => { setFloorId(f.id); setRoomKey(''); }}>{f.name}</button>)}</div>
    <div className="mi-choices" role="group" aria-label="Checklist room"><button type="button" aria-pressed={!roomKey} onClick={() => setRoomKey('')}>All rooms</button>{rooms.map((r, index) => <button type="button" key={keyFor(r.floorId, r.roomKey)} aria-pressed={roomKey === keyFor(r.floorId, r.roomKey)} onClick={() => setRoomKey(keyFor(r.floorId, r.roomKey))}>{r.roomName} · {r.floorName} <small>#{index + 1}</small></button>)}</div>
    <label className="mi-search">Find an item or task<input type="search" value={search} onChange={e => setSearch(e.target.value)} placeholder="Room, item, task or person"/></label>
    {list && <div className="mi-card"><strong>{list.template === 'install' ? 'Ready for installation' : 'Ready for photos'} · captured {new Date(list.capturedAt).toLocaleString()}</strong><small>Revision {list.revision.fingerprint}</small><p>{review?.stale ? `The layout changed: ${review.changed.length} captured items changed, ${review.removed.length} were removed. Room or architecture changes may also need review.` : 'The current layout matches the captured revision.'}</p>{review?.stale && <p className="mi-notice">The checklist still shows its captured rooms and dimensions. Review changes and explicitly refresh the capture; tasks never move to a different room automatically.</p>}<div className="mi-actions"><button type="button" onClick={() => { setSelected(new Set(list.items.filter(i => i.present && currentIds.has(i.placementId)).map(i => i.placementId))); setCaptureOpen(v => !v); }}>Review captured items</button><button type="button" onClick={() => attempt(() => downloadInstallChecklist(list, 'csv', revision))}>Download CSV</button><button type="button" onClick={() => attempt(() => downloadInstallChecklist(list, 'html', revision))}>Download printable copy</button><button type="button" onClick={() => attempt(() => printInstallChecklist(list, revision))}>Print / Save PDF</button></div><p className="mi-muted">Downloads include entered people, dates and notes. Photo files are not embedded; use a private project backup to preserve them.</p></div>}
    {captureOpen && <div className="mi-card"><h3>{list ? 'Review this capture' : 'Start a checklist'}</h3><ChoiceButtons<InstallTemplate> label="Checklist template" value={template} options={[{ value: 'install', label: 'Ready to install' }, { value: 'photo-day', label: 'Ready for photos' }]} onChange={setTemplate}/><p>Choose which placed pieces to track. This selection does not include them in packing yet. Up to {MAX_INSTALL_ITEMS} items and 40 rooms; a project-only checklist can start with no items.</p><div className="mi-actions"><button type="button" onClick={() => attempt(() => { const next = new Set([...selected, ...visibleCandidates.map(i => i.placementId)]); if (next.size > MAX_INSTALL_ITEMS) throw new Error('Narrow the room or search before selecting more than 500 items.'); setSelected(next); })}>Choose matching items</button><button type="button" onClick={() => setSelected(new Set())}>Clear choices</button><span>{chosen.length} chosen</span></div>
      <div className="install-capture-items">{visibleCandidates.slice(page * 60, page * 60 + 60).map(i => <label className="mi-check" key={i.placementId}><input type="checkbox" checked={selected.has(i.placementId)} onChange={e => attempt(() => { const next = new Set(selected); if (e.target.checked) next.add(i.placementId); else next.delete(i.placementId); if (next.size > MAX_INSTALL_ITEMS) throw new Error('Choose no more than 500 items.'); setSelected(next); })}/><span>{i.name}<small>{i.floorName} · {i.roomName} · {i.sourceStatus} · {i.placementId.slice(-8)}</small></span></label>)}</div>
      {visibleCandidates.length > 60 && <div className="mi-actions"><button type="button" disabled={!page} onClick={() => setPage(n => n - 1)}>Previous items</button><span>Page {page + 1} of {Math.ceil(visibleCandidates.length / 60)}</span><button type="button" disabled={(page + 1) * 60 >= visibleCandidates.length} onClick={() => setPage(n => n + 1)}>Next items</button></div>}
      {list && <><p>{review?.notIncluded.length} current items are outside this checklist. Refresh retains retired rows and their task evidence, and flags changed decisions for review. It does not create new template tasks for added rooms; use Add task or start a replacement checklist.</p><button type="button" disabled={disabled || busy} onClick={() => attempt(() => { commit(plan, refreshInstallChecklist(plan, list, chosen)); setEdit(undefined); setCaptureOpen(false); setMessage('Capture refreshed. Review marked items and tasks before using their packing counts.'); })}>Refresh captured revision</button><label className="mi-check"><input type="checkbox" checked={replaceConfirmed} onChange={e => setReplaceConfirmed(e.target.checked)}/>Replace this checklist and its task records with a new template</label></>}
      <button type="button" disabled={disabled || busy || !!list && !replaceConfirmed} onClick={() => attempt(() => { commit(plan, captureInstallChecklist(plan, template, chosen)); setEdit(undefined); setCaptureOpen(false); setReplaceConfirmed(false); setMessage('Checklist created. Progress, packing and delivery start unknown.'); })}>{list ? 'Replace checklist' : 'Create checklist'}</button>
    </div>}
    {list && <><div className="mi-card"><h3>Packing · {packing!.count} included physical pieces</h3><p>{packing!.owned} owned · {packing!.selected} selected/ordered · {packing!.wishlist} wishlist · {packing!.unknownStatus} source status unknown. {packing!.received} received · {packing!.pending} pending · {packing!.unknownDelivery} delivery unknown.</p><p>{packing!.undecided} packing choices unknown · {packing!.needsReview} items awaiting review. Only explicitly included, present and reviewed pieces count; purchase-pack quantities never multiply placed models.</p>{review?.stale && <p className="mi-notice">These are captured counts. Refresh and review before using them for the changed layout.</p>}</div>
      <h3>Tasks · {list.tasks.length}/{MAX_INSTALL_TASKS}</h3><button type="button" disabled={disabled || busy || list.tasks.length >= MAX_INSTALL_TASKS} onClick={() => newTask()}>Add task</button>
      {edit && <form className="mi-card install-task-edit" onSubmit={e => { e.preventDefault(); attempt(() => { const captured = edit.base.installChecklist; if (!captured) throw new Error('This checklist no longer exists.'); commit(edit.base, { ...captured, tasks: edit.fresh ? [...captured.tasks, edit.task] : captured.tasks.map(t => t.id === edit.task.id ? edit.task : t) }); setEdit(undefined); setMessage('Task saved. The room layout and design approval are unchanged.'); }); }}><h4>{edit.fresh ? 'New task' : 'Edit task'}</h4>{edit.base !== plan && <p role="alert">The project changed. Cancel and reopen this task before saving.</p>}<fieldset disabled={busy || disabled || edit.base !== plan}><label>Task title<input value={edit.task.title} maxLength={160} required onChange={e => patchTask({ title: e.target.value })}/></label><ChoiceButtons label="Task progress" value={edit.task.state} options={options(['unknown', 'todo', 'done', 'blocked'] as const)} onChange={state => patchTask({ state })}/><div className="mi-fields"><label>Responsible person<input value={edit.task.assignee ?? ''} maxLength={100} placeholder="Unassigned" onChange={e => patchTask({ assignee: e.target.value || undefined })}/></label><label>Due date<input type="date" value={edit.task.dueDate ?? ''} onChange={e => patchTask({ dueDate: e.target.value || undefined })}/></label></div><label>Notes<input value={edit.task.note ?? ''} maxLength={1200} onChange={e => patchTask({ note: e.target.value || undefined })}/></label><p className="mi-muted">Photos remain private and local. Original image metadata may be retained in your private backup. Only add photos you intend to keep with this project.</p><label>Add local photo<input type="file" accept="image/png,image/jpeg,image/webp" disabled={edit.task.photoAssetIds.length >= 4} onChange={e => { const file = e.target.files?.[0]; e.target.value = ''; void addPhoto(file); }}/></label><div className="install-photos">{edit.task.photoAssetIds.map(id => <PrivatePhoto key={id} id={id} onRemove={() => patchTask({ photoAssetIds: edit.task.photoAssetIds.filter(p => p !== id) })}/>)}</div>{edit.task.needsReview && <label className="mi-check"><input type="checkbox" checked={!edit.task.needsReview} disabled={!!review?.stale} onChange={() => patchTask({ needsReview: false, evidenceRevision: revision })}/>I reviewed this task against the current capture</label>}<button type="submit">Save task</button>{!edit.fresh && <button type="button" onClick={() => attempt(() => { const captured = edit.base.installChecklist!; commit(edit.base, { ...captured, tasks: captured.tasks.filter(t => t.id !== edit.task.id) }); setEdit(undefined); setMessage('Task removed. Undo can restore its record and photo links.'); })}>Remove task</button>}</fieldset><button type="button" onClick={() => { operation.current++; setBusy(false); setEdit(undefined); }}>Cancel task edit</button>{busy && <p role="status">Storing the private photo…</p>}</form>}
      <div className="install-tasks">{visibleTasks.slice(taskPage * 30, taskPage * 30 + 30).map(t => { const room = list.rooms.find(r => r.floorId === t.floorId && r.roomKey === t.roomKey); return <article className="mi-card" key={t.id}><strong>{t.title}</strong><small>{room ? `${room.floorName} · ${room.roomName}` : 'Whole project'}{t.itemId ? ` · Item ${t.itemId.slice(-8)}` : ''}</small><p>{t.state} · {t.assignee ?? 'Unassigned'} · {t.dueDate ?? 'No date'}{t.photoAssetIds.length ? ` · ${t.photoAssetIds.length} private photos` : ''}</p>{t.note && <p>{t.note}</p>}{t.needsReview && <p className="mi-notice">Review required after the captured layout changed.</p>}<button type="button" disabled={disabled || busy} onClick={() => { setEdit({ base: plan, task: structuredClone(t), fresh: false }); setError(''); }}>Edit {t.title}</button></article>; })}</div>
      {visibleTasks.length > 30 && <div className="mi-actions"><button type="button" disabled={!taskPage} onClick={() => setTaskPage(n => n - 1)}>Previous tasks</button><button type="button" disabled={(taskPage + 1) * 30 >= visibleTasks.length} onClick={() => setTaskPage(n => n + 1)}>Next tasks</button></div>}
      <details><summary>Captured pieces · {visibleItems.length}</summary><div className="install-items">{visibleItems.slice(0, 80).map(i => <article className="mi-card" key={i.placementId}><strong>{i.name}</strong><small>{i.floorName} · {i.roomName} · {i.placementId.slice(-8)}</small><p>{i.dimensions.widthMm} × {i.dimensions.depthMm} × {i.dimensions.heightMm} mm · {i.sourceStatus}</p>{i.roomWarning && <p>{i.roomWarning}</p>}{!i.present && <p className="mi-notice">Retired from the active capture. Evidence is retained; excluded from packing.</p>}{i.needsReview && <p className="mi-notice">Review the changed piece before including it in the packing count.</p>}<ChoiceButtons label={`Packing for ${i.name}`} disabled={disabled || !i.present} value={i.packing} options={options(['unknown', 'include', 'exclude'] as const)} onChange={packing => patchItem(i.placementId, { packing })}/><ChoiceButtons label={`Delivery for ${i.name}`} disabled={disabled || !i.present} value={i.delivery} options={options(['unknown', 'pending', 'received'] as const)} onChange={delivery => patchItem(i.placementId, { delivery })}/><div className="mi-actions">{i.needsReview && i.present && <button type="button" disabled={disabled || !!review?.stale} onClick={() => patchItem(i.placementId, { needsReview: false })}>Mark item reviewed</button>}<button type="button" disabled={disabled || busy || list.tasks.length >= MAX_INSTALL_TASKS} onClick={() => newTask(i)}>Add task for {i.name}</button>{onSelectItem && currentIds.has(i.placementId) && <button type="button" onClick={() => onSelectItem(i.placementId)}>Find in room</button>}</div></article>)}</div>{visibleItems.length > 80 && <p>Showing 80 matching pieces. Narrow the room or search; exports include all captured pieces.</p>}</details>
      <details><summary>Remove checklist</summary><p>Removes checklist metadata from this project. Undo can restore it; local photo files are retained.</p><label className="mi-check"><input type="checkbox" checked={removeConfirmed} onChange={e => setRemoveConfirmed(e.target.checked)}/>Remove this checklist and its task records</label><button type="button" disabled={disabled || busy || !removeConfirmed} onClick={() => attempt(() => { commit(plan, undefined); setEdit(undefined); setCaptureOpen(true); setRemoveConfirmed(false); })}>Remove checklist</button></details>
    </>}{error && <p className="mi-notice" role="alert">{error}</p>}<p role="status" aria-live="polite">{message}</p>
  </section>;
}
