import {useCallback,useEffect,useRef,useState} from 'react';
import {Camera,Check,DownloadSimple,Images,Pause,PersonSimpleWalk,Play,Plus,Trash,X} from '@phosphor-icons/react';
import type {SceneController} from './scene/SceneController';
import type {PlanDocumentV1} from './types';
import type {WalkDirection} from './walkthrough';
import {homeShots} from './previewShots';
import {listingReadiness,MAX_LISTING_BYTES,MAX_LISTING_MEDIA,mediaLabels,parseListing,type ListingDetails,type ListingDocument,type ListingMedia} from './listingTypes';
import {loadListing,saveListing,saveAgentDefaults} from './listingStorage';
import {downloadListingFile,importListingPhoto,normalizeListingImage,pairListingOriginal} from './listingMedia';
import {exportListingPack} from './listingExport';
import {ListingGenerationPanel} from './ListingGenerationPanel';
import './listing.css';

type Tab='tour'|'details'|'media'|'export'|'video';
type Props={controller:SceneController;plan:PlanDocumentV1;floorId:string;setFloor(id:string):void;onClose():void;canCapture:boolean};
export function ListingStudio({controller,plan,floorId,setFloor,onClose,canCapture}:Props){
 const [tab,setTab]=useState<Tab>('tour'),[listing,setListing]=useState<ListingDocument>(),[error,setError]=useState(''),[notice,setNotice]=useState(''),[saveStatus,setSaveStatus]=useState('Opening local media…'),[busy,setBusy]=useState(false),[walking,setWalking]=useState(false),[playing,setPlaying]=useState(false),[selectedId,setSelectedId]=useState<string>(),[removed,setRemoved]=useState<{media:ListingMedia;index:number}>(),[loadAttempt,setLoadAttempt]=useState(0);
 const latest=useRef<ListingDocument|undefined>(undefined),lastSaved=useRef<ListingDocument|undefined>(undefined),originalFloor=useRef(floorId),root=useRef<HTMLElement>(null),closeButton=useRef<HTMLButtonElement>(null),previousFocus=useRef<HTMLElement|null>(null),pendingShot=useRef<ListingMedia|undefined>(undefined),alive=useRef(true),timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
 const fileInput=useRef<HTMLInputElement>(null),backupInput=useRef<HTMLInputElement>(null),originalInput=useRef<HTMLInputElement>(null);
 const selected=listing?.media.find(m=>m.id===selectedId)??listing?.media[0];
 const selectMedia=(id:string)=>{setPlaying(false);setSelectedId(id)};
 const update=(fn:(d:ListingDocument)=>ListingDocument)=>{if(!latest.current)return;try{const next=fn(latest.current);next.updatedAt=new Date().toISOString();if(next.media!==latest.current.media)parseListing(next);latest.current=next;setListing(next);setSaveStatus('Saving on this device…');setError('');return true}catch(e){setError((e as Error).message);return false}};
 useEffect(()=>{alive.current=true;let cancelled=false;loadListing(plan.id,plan.name).then(d=>{if(!cancelled){latest.current=d;lastSaved.current=d;setListing(d);setSaveStatus('Saved on this device');setError('')}}).catch(()=>{if(!cancelled){setSaveStatus('Storage unavailable');setError('Your listing could not be opened. Allow browser storage and retry. Your 3D project is unchanged.')}});return()=>{cancelled=true}},[plan.id,loadAttempt]);
 useEffect(()=>{if(!listing||listing===lastSaved.current)return;clearTimeout(timer.current);timer.current=setTimeout(()=>{const value=listing;saveListing(value).then(()=>{lastSaved.current=value;if(alive.current&&latest.current===value)setSaveStatus('Saved on this device')}).catch(e=>{if(alive.current){setSaveStatus('Not saved');setError((e as Error).message||'Browser storage is full or unavailable. Download a listing backup before closing.')}})},650);return()=>clearTimeout(timer.current)},[listing]);
 useEffect(()=>{previousFocus.current=document.activeElement as HTMLElement;controller.beginListingPresentation();closeButton.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();controller.endWalkthrough();setWalking(false);setPlaying(false);setTab('tour')}};const unloading=(e:BeforeUnloadEvent)=>{if(latest.current&&latest.current!==lastSaved.current){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',unloading);window.addEventListener('keydown',key,true);return()=>{alive.current=false;window.removeEventListener('beforeunload',unloading);window.removeEventListener('keydown',key,true);clearTimeout(timer.current);if(latest.current&&latest.current!==lastSaved.current)void saveListing(latest.current).catch(()=>{});controller.endListingPresentation();previousFocus.current?.focus()}},[controller]);
 useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),5500);return()=>clearTimeout(id)},[notice]);
 const leave=async()=>{setBusy(true);clearTimeout(timer.current);try{const value=latest.current;if(value&&value!==lastSaved.current){await saveListing(value);lastSaved.current=value}controller.endWalkthrough();setWalking(false);setFloor(originalFloor.current);requestAnimationFrame(()=>{controller.endListingPresentation();onClose()})}catch(e){setSaveStatus('Not saved');setError((e as Error).message||'Could not save your listing. Download a backup first, or retry after freeing browser storage.')}finally{setBusy(false)}};
 const goTab=(next:Tab)=>{setPlaying(false);if(next!=='tour'){controller.endWalkthrough();setWalking(false)}setTab(next);setError('')};
 const jump=useCallback((m:ListingMedia)=>{if(!m.camera)return;controller.endWalkthrough();setWalking(false);setSelectedId(m.id);if(!plan.floors.some(f=>f.id===m.camera!.floorId)){setError('That floor was removed. The picture is still available.');return;}if(m.camera.floorId!==floorId){pendingShot.current=m;setFloor(m.camera.floorId)}else{const ok=controller.restoreCameraShot(m.camera);setWalking(ok&&m.camera.kind==='walkthrough');if(!ok)setError('This viewpoint no longer fits the edited floor. Capture a replacement.');}},[controller,floorId,plan.floors,setFloor]);
 useEffect(()=>{const m=pendingShot.current;if(!m||m.camera?.floorId!==floorId)return;pendingShot.current=undefined;const frame=requestAnimationFrame(()=>{const ok=controller.restoreCameraShot(m.camera!);setWalking(ok&&m.camera?.kind==='walkthrough');if(!ok)setError('This viewpoint no longer fits the edited floor. Capture a replacement.')});return()=>cancelAnimationFrame(frame)},[floorId,controller]);
 useEffect(()=>{if(!playing||!listing?.media.length)return;const next=()=>{if(document.hidden){setPlaying(false);return;}const index=listing.media.findIndex(m=>m.id===selected?.id);const pool=tab==='tour'?listing.media.filter(m=>m.camera):listing.media;if(pool.length<2){setPlaying(false);return;}const current=pool.findIndex(m=>m.id===listing.media[index]?.id),m=pool[(current+1)%pool.length];if(tab==='tour')jump(m);else setSelectedId(m.id)};const id=setTimeout(next,(selected?.seconds??5)*1000);return()=>clearTimeout(id)},[playing,listing,selected?.id,selected?.seconds,tab,jump]);
 const capture=async(replace=false)=>{if(!listing||!canCapture)return;setBusy(true);setError('');try{if(!replace&&listing.media.length>=MAX_LISTING_MEDIA)throw new Error('A presentation holds 24 images. Remove a slide or create another project.');const raw=controller.captureListingImage(listing.format),pose=controller.captureCameraShot(),image=await normalizeListingImage(raw);const m:ListingMedia={id:replace&&selected?selected.id:crypto.randomUUID(),title:replace&&selected?selected.title:`${plan.floors.find(f=>f.id===floorId)?.name??'Home'} · view ${listing.media.filter(m=>m.camera).length+1}`,caption:replace&&selected?selected.caption:'',kind:'render',image,camera:pose,floorId,seconds:selected&&replace?selected.seconds:5};if(!update(d=>({...d,media:replace?d.media.map(old=>old.id===m.id?m:old):[...d.media,m]})))return;setSelectedId(m.id);setNotice('View saved to your shot list.');}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const importPhotos=async(files:File[])=>{if(!listing)return;setBusy(true);setError('');try{if(files.length+listing.media.length>MAX_LISTING_MEDIA)throw new Error('Choose up to 24 images per presentation.');const media:ListingMedia[]=[];for(const f of files)media.push(await importListingPhoto(f));if(!update(d=>({...d,media:[...d.media,...media]})))return;if(media[0])setSelectedId(media[0].id);setNotice('Photos added locally. Originals are kept in the listing backup.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const editMedia=(patch:Partial<ListingMedia>)=>{if(selected)update(d=>({...d,media:d.media.map(m=>m.id===selected.id?{...m,...patch}:m)}))};
 const moveMedia=(id:string,offset:number)=>update(d=>{const media=[...d.media],i=media.findIndex(m=>m.id===id),j=i+offset;if(i<0||j<0||j>=media.length)return d;[media[i],media[j]]=[media[j],media[i]];return {...d,media}});
 const removeMedia=()=>{if(!selected||!listing)return;setPlaying(false);setRemoved({media:selected,index:listing.media.findIndex(m=>m.id===selected.id)});update(d=>({...d,media:d.media.filter(m=>m.id!==selected.id)}))};
 const details=(key:keyof ListingDetails,value:string)=>update(d=>({...d,details:{...d.details,[key]:value}}));
 const formatPicker=listing&&<div className="listing-segments" aria-label="Presentation format">{(['landscape','portrait','square'] as const).map(f=><button key={f} aria-pressed={listing.format===f} onClick={()=>update(d=>({...d,format:f}))}>{f==='landscape'?'16:9':f==='portrait'?'9:16':'Square'}</button>)}</div>;
 const foot=(direction:WalkDirection,label:string)=><button aria-label={label} title={label} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);controller.moveWalkthrough(direction,true)}} onPointerUp={()=>controller.moveWalkthrough(direction,false)} onPointerCancel={()=>controller.moveWalkthrough(direction,false)} onLostPointerCapture={()=>controller.moveWalkthrough(direction,false)} onKeyDown={e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();controller.moveWalkthrough(direction,true)}}} onKeyUp={()=>controller.moveWalkthrough(direction,false)} onBlur={()=>controller.moveWalkthrough(direction,false)}>{label}</button>;
 return <section ref={root} className={`listing-studio listing-tab-${tab}`} role="dialog" aria-modal="true" aria-label="Listing Studio" onKeyDown={e=>{e.stopPropagation();if(e.key==='Tab'){const focusable=Array.from(root.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),textarea,select,a[href],video[controls]')??[]).filter(el=>el.getClientRects().length);const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}}>
  <header className="listing-header"><div><span className="eyebrow">Nook & Nest</span><h1>Listing Studio</h1></div><nav aria-label="Listing workspace">{([{id:'tour',label:'Walk & capture'},{id:'details',label:'Property'},{id:'media',label:'Photos & slides'},{id:'export',label:'Export'},{id:'video',label:'AI video'}] as {id:Tab;label:string}[]).map(t=><button aria-pressed={tab===t.id} onClick={()=>goTab(t.id)} key={t.id}>{t.label}</button>)}</nav><button ref={closeButton} className="listing-close" disabled={busy} onClick={()=>void leave()} aria-label="Close Listing Studio"><X size={20}/><span>Back to design</span></button></header>
  <div className="listing-status" role="status">{saveStatus}{saveStatus==='Not saved'&&<><button onClick={()=>{if(listing)downloadListingFile('listing-backup.json',JSON.stringify(listing))}}>Save backup</button><button onClick={()=>{if(window.confirm('Leave without saving your latest listing changes? Download a backup first to keep them.')){clearTimeout(timer.current);latest.current=undefined;controller.endWalkthrough();setFloor(originalFloor.current);requestAnimationFrame(()=>{controller.endListingPresentation();onClose()})}}}>Leave without saving</button></>}<span>Photos and listing details stay on this device · included in listing backups</span></div>
  {(error||notice)&&<div className="listing-toast" role={error?'alert':'status'}>{error||notice}<button aria-label="Dismiss message" onClick={()=>{setError('');setNotice('')}}><X size={16}/></button></div>}
  {!listing?<div className="listing-workspace"><p>{saveStatus}</p><button onClick={()=>setLoadAttempt(n=>n+1)}>Retry opening listing</button></div>:<>
   {tab==='tour'&&<><aside className="listing-tour-panel"><span className="eyebrow">Explore your design</span><h2>Step inside.</h2><p>{walking?'Drag the view to look. Move with W A S D or the arrows.':'Drag to orbit your home, or start walking at eye level.'}</p><p className="listing-muted">This is a 3D design walkthrough, not a scan of the actual property.</p><div className="listing-segments listing-floors" aria-label="Walkthrough floor">{plan.floors.map(f=><button key={f.id} aria-pressed={f.id===floorId} onClick={()=>{controller.endWalkthrough();setWalking(false);setPlaying(false);setFloor(f.id)}}>{f.name}</button>)}</div><button className={walking?'':'primary'} onClick={()=>{setPlaying(false);if(walking){controller.endWalkthrough();setWalking(false)}else{const ok=controller.beginWalkthrough(floorId);setWalking(ok);if(!ok)setError('Add a floor with enough clear space before starting a walkthrough.')}}}><PersonSimpleWalk size={20}/>{walking?'Return to orbit':'Start walkthrough'}</button>
    {walking&&<div className="listing-walk-pad" aria-label="Walk controls">{foot('turn-left','Look left')}{foot('forward','Forward')}{foot('turn-right','Look right')}{foot('left','Left')}{foot('backward','Back')}{foot('right','Right')}</div>}
    <div className="listing-row">{homeShots(plan,floorId).slice(0,4).map((shot,i)=><button key={i} onClick={()=>{controller.endWalkthrough();setWalking(false);controller.showHomeShot(shot,false)}}>{shot.name}</button>)}</div><div className="listing-divider"/>{formatPicker}<button className="primary" disabled={busy||!canCapture} onClick={()=>void capture()}><Camera size={20}/>Capture this view</button>{!canCapture&&<p>Switch off Google scenery in Outdoors before exporting images.</p>}<small>Captures are labeled as 3D design renders.</small>
    <h3>Saved stops <span>{listing.media.filter(m=>m.camera).length}</span></h3><div className="listing-stops">{listing.media.filter(m=>m.camera).map(m=><button key={m.id} aria-pressed={selected?.id===m.id} onClick={()=>{setPlaying(false);jump(m)}}><img src={m.image} alt=""/><span>{m.title}</span></button>)}</div>{!listing.media.some(m=>m.camera)&&<p className="listing-muted">Capture a view to save the camera position as a stop.</p>}{listing.media.some(m=>m.camera)&&<button disabled={listing.media.filter(m=>m.camera).length<2} aria-pressed={playing} onClick={()=>setPlaying(!playing)}>{playing?<Pause/>:<Play/>}{playing?'Pause guided stops':'Play guided stops'}</button>}
   </aside><div className="listing-tour-caption"><PersonSimpleWalk size={18}/>{walking?'Eye-level walkthrough':'Orbit view'}<span>Esc stops movement</span></div></>}
   {tab==='details'&&<div className="listing-workspace listing-property"><div><span className="eyebrow">A home worth sharing</span><h2>The story of this property</h2><p>Add verified details for the presentation. Blank fields are omitted from exports.</p><div className="listing-fields">{([{key:'title',label:'Listing title'},{key:'address',label:'Address (optional)'},{key:'price',label:'Price or rental rate'},{key:'beds',label:'Bedrooms'},{key:'baths',label:'Bathrooms'},{key:'area',label:'Verified area (include units)'}] as {key:keyof ListingDetails;label:string}[]).map(f=><label key={f.key}>{f.label}<input maxLength={200} value={listing.details[f.key]} onChange={e=>details(f.key,e.target.value)}/></label>)}</div><label>Highlights · one per line<textarea rows={4} maxLength={2000} value={listing.details.highlights} onChange={e=>details('highlights',e.target.value)} placeholder={'South-facing windows\nPrivate balcony\nNearby transit'}/></label><label>Property description<textarea rows={5} maxLength={4000} value={listing.details.description} onChange={e=>details('description',e.target.value)}/></label><p className="listing-muted">Drawing dimensions are planning estimates. Confirm property facts and measurements independently.</p></div><aside><span className="eyebrow">Your signature</span><h2>Agent details</h2><p>Included only in branded exports.</p>{([{key:'agentName',label:'Agent name'},{key:'agency',label:'Agency'},{key:'agentEmail',label:'Business email'},{key:'agentPhone',label:'Business phone'}] as {key:keyof ListingDetails;label:string}[]).map(f=><label key={f.key}>{f.label}<input maxLength={200} value={listing.details[f.key]} onChange={e=>details(f.key,e.target.value)}/></label>)}<button onClick={()=>void saveAgentDefaults(listing.details).then(()=>setNotice('Agent details saved as defaults for new listings on this device.')).catch(()=>setError('Could not save agent defaults.'))}>Use for future listings</button><p className="listing-muted">Stored in this browser, separate from your project’s online save.</p></aside></div>}
   {tab==='media'&&<div className="listing-workspace listing-media-workspace"><aside className="listing-media-list"><div className="listing-row"><h2>Your story, in order</h2><button disabled={busy||listing.media.length>=MAX_LISTING_MEDIA} onClick={()=>fileInput.current?.click()}><Plus/>Add photos</button></div><p>{listing.media.length} / {MAX_LISTING_MEDIA} slides · originals preserved</p>{listing.media.map((m,i)=><div className="listing-media-item" key={m.id}><button className="listing-media-select" aria-pressed={selected?.id===m.id} onClick={()=>selectMedia(m.id)}><img src={m.image} alt=""/><span><strong>{m.title}</strong><small>{mediaLabels[m.kind]} · {m.seconds}s</small></span></button><div className="listing-reorder"><button aria-label={`Move ${m.title} earlier`} disabled={i===0} onClick={()=>moveMedia(m.id,-1)}>↑</button><button aria-label={`Move ${m.title} later`} disabled={i===listing.media.length-1} onClick={()=>moveMedia(m.id,1)}>↓</button></div></div>)}{!listing.media.length&&<div className="listing-empty"><Images size={42}/><h3>Start with the best view.</h3><p>Add property photos or capture views from your design.</p><button onClick={()=>goTab('tour')}>Walk & capture</button></div>}{removed&&<button onClick={()=>{update(d=>{const media=[...d.media];media.splice(removed.index,0,removed.media);return {...d,media}});setRemoved(undefined)}}>Undo removed slide</button>}</aside>
    <div className="listing-slide-editor">{selected?<><div className={`listing-slide-preview format-${listing.format}`}><img src={selected.image} alt={selected.caption||selected.title}/><span>{mediaLabels[selected.kind]}</span></div><div className="listing-row">{formatPicker}<button aria-label="Previous slide" disabled={listing.media.length<2} onClick={()=>{setPlaying(false);setSelectedId(listing.media[(listing.media.findIndex(m=>m.id===selected.id)+listing.media.length-1)%listing.media.length].id)}}>←</button><button disabled={listing.media.length<2} onClick={()=>setPlaying(!playing)}>{playing?<Pause/>:<Play/>}{playing?'Pause':'Play slideshow'}</button><button aria-label="Next slide" disabled={listing.media.length<2} onClick={()=>{setPlaying(false);setSelectedId(listing.media[(listing.media.findIndex(m=>m.id===selected.id)+1)%listing.media.length].id)}}>→</button></div><div className="listing-fields"><label>Slide title<input maxLength={160} value={selected.title} onChange={e=>editMedia({title:e.target.value})}/></label><label>Duration (seconds)<input type="number" min={2} max={20} value={selected.seconds} onChange={e=>{const n=Number(e.target.value);if(n>=2&&n<=20)editMedia({seconds:n})}}/></label></div><label>Caption<textarea rows={2} maxLength={1000} value={selected.caption} onChange={e=>editMedia({caption:e.target.value})}/></label><span>Image type</span><div className="listing-segments">{(Object.keys(mediaLabels) as ListingMedia['kind'][]).map(k=><button key={k} disabled={!!selected.camera&&k==='photo'} aria-pressed={selected.kind===k} onClick={()=>editMedia({kind:k})}>{mediaLabels[k]}</button>)}</div>{['staged','concept'].includes(selected.kind)&&<div className="listing-notice"><p>{selected.originalImage?'An original image is paired for comparison.':'Pair the unaltered property photo so viewers can compare.'}</p><button disabled={busy} onClick={()=>originalInput.current?.click()}>{selected.originalImage?'Replace original':'Pair original photo'}</button>{selected.originalImage&&<img className="listing-original" src={selected.originalImage} alt="Paired original property photo"/>}</div>}<div className="listing-row">{selected.camera&&<><button onClick={()=>{goTab('tour');jump(selected)}}>Revisit viewpoint</button><button disabled={busy||!canCapture} onClick={()=>{goTab('tour');void capture(true)}}>Replace with current view</button></>}<button className="danger" onClick={removeMedia}><Trash/>Remove slide</button></div></>:<div className="listing-empty"><Camera size={42}/><p>Your photos and saved views will appear here.</p></div>}</div></div>}
   {tab==='export'&&<div className="listing-workspace listing-export"><div><span className="eyebrow">Ready for your next showing</span><h2>One polished presentation pack.</h2><p>Download your photos, original sources, floor plans, a printable property sheet, a playable slideshow, listing text and a Seedance storyboard together.</p><div className="listing-segments"><button aria-pressed={!listing.branded} onClick={()=>update(d=>({...d,branded:false}))}>Unbranded</button><button aria-pressed={listing.branded} onClick={()=>update(d=>({...d,branded:true}))}>Agent branded</button></div><p className="listing-muted">{listing.branded?'Agent details appear on the property sheet and slideshow.':'Agent name, agency and contact fields are omitted from the presentation pack.'} Check your local listing service’s media rules.</p>{formatPicker}<button className="primary" disabled={busy||!listing.media.length} onClick={()=>{setBusy(true);void exportListingPack(listing,plan).then(()=>setNotice('Presentation pack downloaded. Unzip it and open index.html or property-sheet.html.')).catch(e=>setError(e.message)).finally(()=>setBusy(false))}}><DownloadSimple/>Download presentation pack</button><p className="listing-muted">This creates files on your device, not a public link. Review AI/staged images and captions before publishing.</p><div className="listing-divider"/><h3>Keep your work</h3><p>Listing backups include photos, originals, details and saved viewpoints. Your floor-plan project is saved separately using the editor’s Save menu.</p><div className="listing-row"><button onClick={()=>downloadListingFile('listing-backup.json',JSON.stringify(listing))}>Download listing backup</button><button disabled={busy} onClick={()=>backupInput.current?.click()}>Restore listing backup</button></div></div><aside><h3>Presentation checklist</h3>{listingReadiness(listing).map(r=><div className="listing-readiness" key={r.label}><span className={r.done?'complete':''}>{r.done?<Check size={16}/>:<span>○</span>}</span>{r.label}</div>)}<p className="listing-muted">These are suggestions, not a verification of the property or its suitability for listing.</p></aside></div>}
   {tab==='video'&&<div className="listing-workspace"><ListingGenerationPanel listing={listing}/></div>}
  </>}
  <input ref={fileInput} hidden type="file" multiple accept="image/jpeg,image/png,image/webp" aria-label="Add listing photos" onChange={e=>{const files=Array.from(e.target.files??[]);e.target.value='';void importPhotos(files)}}/>
  <input ref={originalInput} hidden type="file" accept="image/jpeg,image/png,image/webp" aria-label="Pair original property photo" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(!file||!selected)return;const slideId=selected.id;setBusy(true);void importListingPhoto(file).then(photo=>{update(d=>({...d,media:d.media.map(m=>m.id===slideId?pairListingOriginal(m,photo):m)}))}).catch(e=>setError(e.message)).finally(()=>setBusy(false))}}/>
  <input ref={backupInput} hidden type="file" accept="application/json,.json" aria-label="Restore listing backup" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>MAX_LISTING_BYTES+1024*1024){setError('This backup exceeds the 100 MB limit.');return;}if(!window.confirm('Replace this listing’s photos and details from the backup? Your 3D plan stays unchanged.'))return;setBusy(true);void file.text().then(text=>{const next=parseListing(JSON.parse(text),plan.id);update(()=>next);setSelectedId(undefined);setRemoved(undefined);setNotice('Listing backup restored on this device.')}).catch(e=>setError(e.message)).finally(()=>setBusy(false))}}/>
 </section>;
}
