import {localVideoEndpoint} from './localVideo';
import {parseStillResult,stillId,STILL_LIMITS,verifyStillRequest,type StillMode,type StillRecord,type StillResult} from './stillRender';
import {saveStillRecord} from './stillRenderStorage';

export interface StillConnection {endpoint:string;model:string}
export interface StillCapability {endpoint:string;schema:'nook-still-render/1';idempotency:'request-id';cancelByRequestId:true;resultType:'inline-image';models:Array<{id:string;name:string;modes:StillMode[];qualities:Array<'preview'|'final'>}>}
export interface StillServerJob {schema:'nook-still-job/1';id:string;requestId:string;payloadHash:string;status:'queued'|'running'|'completed'|'failed'|'cancelled';progress?:number;message?:string}
const prefix='/nook/still-render';
const record=(v:unknown):v is Record<string,any>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const string=(v:unknown,max=160):v is string=>typeof v==='string'&&v.length>0&&v.length<=max&&!/[\u0000-\u001f\u007f]/.test(v);
export function stillEndpoint(value:string){const result=localVideoEndpoint(value),host=new URL(result).hostname;if(/(^|\.)(fal\.ai|fal\.run|openai\.com|byteplus\.com|bytepluses\.com)$/.test(host))throw new Error('Choose your own still-render server. Hosted inference providers are not enabled here.');return result;}
async function request(endpoint:string,token:string,path:string,method='GET',body?:unknown,signal?:AbortSignal,limit=STILL_LIMITS.packageBytes):Promise<unknown>{const url=stillEndpoint(endpoint)+prefix+path;if(typeof token!=='string'||token.length>8192||/[\u0000-\u001f\u007f]/.test(token))throw new Error('Enter a valid temporary access token.');let response:Response;try{response=await fetch(url,{method,body:body===undefined?undefined:JSON.stringify(body),headers:{...(token?{Authorization:'Bearer '+token}:{}),...(body?{'Content-Type':'application/json'}:{})},credentials:'omit',redirect:'error',referrerPolicy:'no-referrer',cache:'no-store',signal:AbortSignal.any([AbortSignal.timeout(45000),...(signal?[signal]:[])])});}catch{throw new Error('Cannot confirm the server response. Check HTTPS, CORS and browser local-network permission. A submitted job may still exist.');}if(response.redirected||response.url&&response.url!==url)throw new Error('Use the final server address; redirects are not accepted.');if(!response.ok)throw new Error(`Still server returned ${response.status}. Check its request status before starting another job.`);if(!/^application\/(json|[a-z0-9.+-]+\+json)(;|$)/i.test(response.headers.get('content-type')??''))throw new Error('This address did not return a compatible still-render response.');const reader=response.body?.getReader();if(!reader)throw new Error('Empty server response.');const chunks:Uint8Array[]=[];let size=0;try{for(;;){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>limit)throw new Error('This server response exceeds the image/package limit.');chunks.push(value);}}finally{await reader.cancel().catch(()=>{});reader.releaseLock();}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}try{return JSON.parse(new TextDecoder().decode(bytes));}catch{throw new Error('The server returned invalid JSON.');}}
export async function discoverStillServer(endpoint:string,token:string,signal?:AbortSignal):Promise<StillCapability>{const v=await request(endpoint,token,'/capabilities','GET',undefined,signal,100_000);if(!record(v)||v.schema!=='nook-still-render/1'||v.idempotency!=='request-id'||v.cancelByRequestId!==true||v.resultType!=='inline-image'||!Array.isArray(v.models)||!v.models.length||v.models.length>10)throw new Error('This server does not advertise the separate Nook still-render capability. Video/H3 endpoints cannot render these jobs. Export a portable package instead.');const ids=new Set<string>();for(const m of v.models){if(!record(m)||!string(m.id)||ids.has(m.id)||!string(m.name)||!Array.isArray(m.modes)||!m.modes.length||m.modes.some((x:unknown)=>!['fixed-geometry','generative-styling'].includes(String(x)))||!Array.isArray(m.qualities)||!m.qualities.length||m.qualities.some((x:unknown)=>!['preview','final'].includes(String(x))))throw new Error('Invalid still-render capabilities.');ids.add(m.id);}return {endpoint:stillEndpoint(endpoint),schema:v.schema,idempotency:v.idempotency,cancelByRequestId:true,resultType:v.resultType,models:v.models.map(m=>({id:m.id,name:m.name,modes:[...new Set(m.modes)] as StillMode[],qualities:[...new Set(m.qualities)] as Array<'preview'|'final'>}))};}
function parseJob(v:unknown,r:StillRecord):StillServerJob{if(!record(v)||v.schema!=='nook-still-job/1'||!stillId(v.id)||v.requestId!==r.id||v.payloadHash!==r.request.payloadHash||!['queued','running','completed','failed','cancelled'].includes(v.status)||v.progress!==undefined&&(!Number.isFinite(v.progress)||v.progress<0||v.progress>100)||v.message!==undefined&&!string(v.message,500))throw new Error('The server response does not match this exact render request.');return {schema:v.schema,id:v.id,requestId:v.requestId,payloadHash:v.payloadHash,status:v.status,...(v.progress===undefined?{}:{progress:v.progress}),};}
export async function startStillJob(record:StillRecord,connection:StillConnection,token:string,capability:StillCapability,consent:boolean,signal?:AbortSignal){if(record.exportedAt)throw new Error('Confirm that the exported package is not running elsewhere before starting this job.');if(record.state!=='queued'||!consent)throw new Error('Select a queued job and explicitly approve sending this package.');const endpoint=stillEndpoint(connection.endpoint),model=capability.models.find(m=>m.id===connection.model);if(capability.endpoint!==endpoint||capability.schema!=='nook-still-render/1'||!model?.modes.includes(record.request.settings.mode)||!model.qualities.includes(record.request.settings.quality))throw new Error('Check this server’s compatible still model and quality first.');await verifyStillRequest(record.request);let reserved=await saveStillRecord({...record,state:'submitting',connection:{endpoint,model:model.id}},record.revision);try{const job=parseJob(await request(endpoint,token,'/jobs','POST',{model:model.id,request:reserved.request},signal),reserved);reserved=await saveStillRecord({...reserved,state:job.status==='failed'?'failed':job.status==='cancelled'?'cancelled':'running',serverJobId:job.id,progress:job.progress,...(job.message?{error:job.message}:{})},reserved.revision);return reserved;}catch(error){try{reserved=await saveStillRecord({...reserved,state:'submission-unknown',error:'Submission could not be confirmed. Check status by request ID; do not start it again.'},reserved.revision);}catch{/* A newer persisted state wins. The reservation still prevents another POST. */}throw error;}}
export async function checkStillJob(record:StillRecord,token:string,signal?:AbortSignal){if(!record.connection||!['submitting','submission-unknown','running','cancel-unknown'].includes(record.state))throw new Error('This job has no active server request to check.');const job=parseJob(await request(record.connection.endpoint,token,'/requests/'+encodeURIComponent(record.id),'GET',undefined,signal,100_000),record);let result:StillResult|undefined;if(job.status==='completed')result=parseStillResult(await request(record.connection.endpoint,token,'/requests/'+encodeURIComponent(record.id)+'/result','GET',undefined,signal),record.request);return saveStillRecord({...record,serverJobId:job.id,state:result?'needs-review':job.status==='failed'?'failed':job.status==='cancelled'?'cancelled':record.state==='cancel-unknown'?'cancel-unknown':'running',progress:job.progress,error:job.message,...(result?{result}:{})},record.revision);}
export async function cancelStillJob(record:StillRecord,token:string,signal?:AbortSignal){if(record.state==='queued')return saveStillRecord({...record,state:record.exportedAt?'cancel-unknown':'cancelled',...(record.exportedAt?{error:'This package was exported; external rendering has not been cancelled.'}:{})},record.revision);if(!record.connection||!['submitting','submission-unknown','running','cancel-unknown'].includes(record.state))throw new Error('This job cannot be cancelled here.');let current=await saveStillRecord({...record,state:'cancel-unknown',error:'Cancellation is not yet confirmed; the server may still be running.'},record.revision);const job=parseJob(await request(current.connection!.endpoint,token,'/requests/'+encodeURIComponent(current.id),'DELETE',undefined,signal,100_000),current);if(job.status==='cancelled')current=await saveStillRecord({...current,state:'cancelled',serverJobId:job.id,error:undefined},current.revision);return current;}
