import { useEffect, useMemo, useRef, useState } from 'react';
import { catalog } from './catalog';
import { LengthInput } from './LengthInput';
import { formatLength } from './domain';
import { modelAssetPath } from './modelAssetPath';
import { initialKitPosition, kitFloorFit, type KitPosition } from './furnitureKits';
import type { KitPreviewBridge } from './FurnitureKitsPanel';
import type { PlanDocumentV1 } from './types';
import { buildModularPlacement, defaultModularConfiguration, MAX_MODULAR_COMPONENTS, modularChoices, modularKit, modularSpanMessage, type ModularConfiguration } from './modularFamilyBuilder';
import './modular-install.css';
const byId = new Map(catalog.map(c => [c.id, c]));
export function ModularFurniturePanel({ plan, activeFloorId, preview, onClose }: { plan: PlanDocumentV1; activeFloorId: string; preview: KitPreviewBridge; onClose(): void }) {
  const [configuration, setConfiguration] = useState(defaultModularConfiguration), [position, setPosition] = useState<KitPosition>(), [available, setAvailable] = useState<number>();
  const [error, setError] = useState(''), [stage, setStage] = useState<{ id: string; base: PlanDocumentV1; key: string; warnings: string[] }>();
  const stagedId = useRef<string | undefined>(undefined), bridge = useRef(preview); bridge.current = preview;
  const assembly = useMemo(() => modularKit(configuration), [configuration]), key = JSON.stringify([configuration, position]);
  const fit = useMemo(() => position ? kitFloorFit(plan, activeFloorId, assembly.kit, position) : undefined, [plan, activeFloorId, assembly.kit, position]);
  const clear = () => { if (stagedId.current) bridge.current.discard(stagedId.current); stagedId.current = undefined; setStage(undefined); };
  useEffect(() => () => { if (stagedId.current) bridge.current.discard(stagedId.current); }, []);
  useEffect(() => { clear(); setPosition(undefined); }, [plan.id, activeFloorId]);
  useEffect(() => { if (stage && (stage.base !== plan || stage.key !== key || preview.activeId !== stage.id)) clear(); }, [plan, key, preview.activeId, stage]);
  const update = (patch: Partial<ModularConfiguration>) => { clear(); setError(''); setConfiguration(c => ({ ...c, ...patch })); };
  const moveModule = (index: number, direction: number) => { const modules = [...configuration.modules], target = index + direction; if (target < 0 || target >= modules.length) return; [modules[index], modules[target]] = [modules[target], modules[index]]; update({ modules }); };
  const stageAssembly = () => {
    try { if (preview.blocked) throw new Error('Finish the current preview before assembling modules.'); const anchor = position ?? initialKitPosition(plan, activeFloorId, assembly.kit); clear(); const request = buildModularPlacement(plan, plan, activeFloorId, configuration, anchor), id = preview.stage(request); setPosition(anchor); stagedId.current = id; setStage({ id, base: plan, key: JSON.stringify([configuration, anchor]), warnings: request.warnings.map(w => w.message) }); setError(''); }
    catch (e) { setError(e instanceof Error ? e.message : 'This assembly could not be previewed.'); }
  };
  const fresh = stage && stage.base === plan && stage.key === key && stage.id === preview.activeId;
  return <section className="modular-panel" aria-label="Modular furniture builder"><header><h2>Build a cabinet run</h2><button type="button" onClick={() => { clear(); onClose(); }}>Back</button></header>
    <p>Combine compatible authored modules at their real sizes. Each piece keeps its own identity and material controls.</p>
    <div className="mi-choices" role="group" aria-label="Module family">{(['closet', 'kitchen-base'] as const).map(family => <button key={family} type="button" aria-pressed={configuration.family === family} onClick={() => { clear(); setPosition(undefined); setConfiguration(defaultModularConfiguration(family)); }}>{family === 'closet' ? 'Walk-in storage' : 'Kitchen bases'}</button>)}</div>
    <div className="modular-choices">{modularChoices(configuration.family).map(item => <button type="button" key={item.id} disabled={configuration.modules.length >= MAX_MODULAR_COMPONENTS} onClick={() => update({ modules: [...configuration.modules, { id: crypto.randomUUID(), catalogId: item.id }] })}><img src={modelAssetPath(item.id, true)} alt="" loading="lazy"/><strong>Add {item.name}</strong><small>{item.widthMm} × {item.depthMm} × {item.heightMm} mm</small></button>)}</div>
    <h3>Your run · {configuration.modules.length}/{MAX_MODULAR_COMPONENTS} pieces</h3>
    <ol className="modular-components">{configuration.modules.map((component, index) => <li key={component.id}><span><strong>{index + 1}. {byId.get(component.catalogId)?.name}</strong><small>{byId.get(component.catalogId)?.widthMm} mm wide · front aligned</small></span><button type="button" aria-label={`Move module ${index + 1} left`} disabled={!index} onClick={() => moveModule(index, -1)}>←</button><button type="button" aria-label={`Move module ${index + 1} right`} disabled={index === configuration.modules.length - 1} onClick={() => moveModule(index, 1)}>→</button><button type="button" aria-label={`Remove module ${index + 1}`} disabled={configuration.modules.length === 1} onClick={() => update({ modules: configuration.modules.filter(m => m.id !== component.id) })}>Remove</button></li>)}</ol>
    <div className="mi-card"><strong>{formatLength(assembly.spanMm, plan.units)} wide × {formatLength(assembly.depthMm, plan.units)} deep × {formatLength(assembly.heightMm, plan.units)} high</strong><p>{assembly.joins.length} valid straight side {assembly.joins.length === 1 ? 'join' : 'joins'} · zero modeled gap. Separate side panels and worktop seams remain.</p><svg className="modular-diagram" viewBox={`-30 -60 ${assembly.spanMm + 60} ${assembly.depthMm + 120}`} role="img" aria-label="Module order and supported straight joins">{assembly.kit.pieces.map((p, i) => <g key={i}><rect x={p.x - p.widthMm / 2} y={0} width={p.widthMm} height={p.depthMm}/><text x={p.x} y={p.depthMm / 2} dominantBaseline="middle" textAnchor="middle" fontSize={Math.min(180, p.widthMm / 4)}>{i + 1}</text></g>)}{assembly.joins.map((join, i) => <line key={i} x1={join.x} x2={join.x} y1={0} y2={assembly.depthMm}/>)}</svg></div>
    <label className="mi-check"><input type="checkbox" checked={available !== undefined} onChange={e => setAvailable(e.target.checked ? assembly.spanMm : undefined)}/>Compare with an available wall width</label>{available !== undefined && <LengthInput label="Available width" value={available} units={plan.units} min={1} onChange={setAvailable}/>}<p className="mi-notice">{modularSpanMessage(configuration, available)}</p>
    <p className="mi-muted">Straight, same-facing modules only. Mirrored ends, corner joins, arbitrary fillers, wall units, appliance clearances and manufacturing fit are not covered. Review the visible seams and verify the site.</p>
    <h3>Materials</h3><div className="mi-choices" role="group" aria-label="Module finish">{(['oat', 'sage', 'slate'] as const).map(variant => <button key={variant} type="button" aria-pressed={configuration.variant === variant} onClick={() => update({ variant })}>{variant === 'oat' ? 'Warm neutral' : variant === 'sage' ? 'Soft sage' : 'Deep slate'}</button>)}</div>
    <div className="mi-fields"><label className="mi-check"><input type="checkbox" checked={!!configuration.woodColor} onChange={e => update({ woodColor: e.target.checked ? '#b69970' : undefined })}/>Custom wood color</label>{configuration.woodColor && <label>Wood color<input type="color" value={configuration.woodColor} onChange={e => update({ woodColor: e.target.value })}/></label>}<label className="mi-check"><input type="checkbox" checked={!!configuration.hardwareColor} onChange={e => update({ hardwareColor: e.target.checked ? '#b0a79a' : undefined })}/>Custom hardware color</label>{configuration.hardwareColor && <label>Hardware color<input type="color" value={configuration.hardwareColor} onChange={e => update({ hardwareColor: e.target.value })}/></label>}</div>
    {configuration.family === 'kitchen-base' && <div className="mi-choices" role="group" aria-label="Worktop material">{([['warm-granite', 'Granite'], ['ivory-marble', 'Marble'], ['clay-laminate', 'Laminate'], ['soft-concrete', 'Concrete']] as const).map(([surfaceVariant, label]) => <button type="button" key={surfaceVariant} aria-pressed={configuration.surfaceVariant === surfaceVariant} onClick={() => update({ surfaceVariant })}>{label}</button>)}</div>}
    <label className="mi-check"><input type="checkbox" checked={configuration.group} onChange={e => update({ group: e.target.checked })}/>Group the new pieces for moving together</label><label className="mi-check"><input type="checkbox" checked={configuration.lock} onChange={e => update({ lock: e.target.checked })}/>Lock the new pieces after placement</label><p className="mi-muted">Existing furniture and locks stay as they are. Unlock and ungroup this run later to edit its pieces independently.</p>
    {position && <div className="mi-card"><div className="mi-fields"><LengthInput label="Position X" units={plan.units} min={-100000} value={position.x} onChange={x => { clear(); setPosition({ ...position, x }); }}/><LengthInput label="Position Z" units={plan.units} min={-100000} value={position.z} onChange={z => { clear(); setPosition({ ...position, z }); }}/></div><div className="mi-choices" role="group" aria-label="Assembly direction">{[0, 90, 180, 270].map(rotation => <button type="button" key={rotation} aria-pressed={position.rotation === rotation} onClick={() => { clear(); setPosition({ ...position, rotation }); }}>{rotation}°</button>)}</div>{fit && !fit.fits && <p className="mi-notice">{fit.outside.length} pieces extend beyond the floor or across an opening. Move the run before applying.</p>}</div>}
    {stage?.warnings.length ? <ul className="mi-warnings">{[...new Set(stage.warnings)].map(w => <li key={w}>{w}</li>)}</ul> : null}{error && <p role="alert" className="mi-notice">{error}</p>}
    {preview.blocked && <p className="mi-notice">Finish the active arrangement preview first.</p>}
    <footer><button type="button" onClick={clear}>Discard preview</button><button type="button" disabled={preview.blocked} onClick={stageAssembly}>{stage ? 'Update preview' : 'Preview assembly'}</button><button type="button" disabled={!fresh || preview.blocked} onClick={() => { try { if (!fresh) return; preview.apply(stage!.id); stagedId.current = undefined; setStage(undefined); onClose(); } catch (e) { setError((e as Error).message); } }}>Apply assembly</button></footer>
  </section>;
}
