import {useEffect,useMemo,useRef,useState} from 'react';
import {catalog} from './catalog';
import {floorFinishes,wallFinishes,countertopFinishes} from './surfaces';
import {modelAssetPath} from './modelAssetPath';
import {LengthInput} from './LengthInput';
import {PersonalPhoto} from './PersonalFurniturePanel';
import {preparePersonalPhoto,type PersonalPhotoAsset} from './personalMedia';
import {importPersonalAssets,loadPersonalPhoto} from './personalStorage';
import {furnitureIsLocked,type GroupPlan} from './furnitureGroups';
import type {KitPreviewBridge} from './FurnitureKitsPanel';
import type {PlanDocumentV1} from './types';
import {buildMoodboardPalette,buildPersonalSurface,buildRemovePersonalSurface,deleteMoodboard,resolveMoodboardTarget,saveMoodboard,type PaletteProposal} from './moodboardActions';
import {moodboardMaterialSlots,personalArtModels,swatchMaterialSlots} from './moodboardMaterials';
import {parseMoodboard,parseMoodboardPin,parsePersonalSurface,type Moodboard,type MoodboardPin,type MoodboardPlan,type MoodboardTarget,type PersonalSurface,type SurfacePlacement} from './moodboards';
import {renderPersonalSurfaceImage} from './personalSurfaceImage';
import './moodboards.css';

const finishSets={wall:wallFinishes,floor:floorFinishes,countertop:countertopFinishes};
const labelFor=(id:string)=>catalog.find(c=>c.id===id)?.name??id;
const freshBoard=(floorId:string):Moodboard=>{const now=new Date().toISOString();return {id:crypto.randomUUID(),name:'My room inspiration',createdAt:now,updatedAt:now,pins:[],palette:[{id:crypto.randomUUID(),name:'Warm neutral',color:'#d5c6b4'}],bindings:[],target:{scope:'floor',floorId}};};
export interface MoodboardPanelProps {plan:PlanDocumentV1;floorId:string;preview:KitPreviewBridge;onCommit(base:PlanDocumentV1,next:PlanDocumentV1,label:string):void|Promise<void>;onClose():void;onBusyChange?(busy:boolean):void;onPlaceCatalog?(catalogId:string):void}

function SurfacePreview({surface,photo,projectId}:{surface:PersonalSurface;photo?:PersonalPhotoAsset;projectId:string}){
  const host=useRef<HTMLDivElement>(null),[missing,setMissing]=useState(false),[error,setError]=useState(false),key=JSON.stringify([surface.assetId,surface.hidden,surface.crop,surface.rotation,surface.fallbackColor]);
  useEffect(()=>{let alive=true;const controller=new AbortController();setError(false);setMissing(false);host.current?.replaceChildren();void (async()=>{try{const asset=surface.hidden?undefined:photo??(surface.assetId?await loadPersonalPhoto(surface.assetId):undefined);if(!alive)return;const result=await renderPersonalSurfaceImage(surface,asset,512,true,controller.signal);if(alive){host.current?.replaceChildren(result.canvas);setMissing(result.missing)}}catch{if(alive){setError(true);setMissing(true)}}})();return()=>{alive=false;controller.abort()}},[key,photo,projectId]);
  return <div className="mood-surface-preview"><div ref={host} role="img" aria-label={`${surface.label}, cropped preview`}/>{missing&&<small>{error?'Image preview unavailable.':'Private image missing or hidden.'} The selected fallback color remains visible.</small>}</div>;
}

/** Controlled content for the parent's one dialog; one shared reversible candidate at a time. */
export function MoodboardPanel({plan,floorId,preview,onCommit,onClose,onBusyChange,onPlaceCatalog}:MoodboardPanelProps){
  const boards=(plan as MoodboardPlan).moodboards?.boards??[],floor=plan.floors.find(f=>f.id===floorId);
  const [tab,setTab]=useState<'boards'|'images'>('boards'),[choice,setChoice]=useState<string>(),[draft,setDraft]=useState<Moodboard>(),[pendingPhotos,setPendingPhotos]=useState<PersonalPhotoAsset[]>([]);
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[removeBoard,setRemoveBoard]=useState(false),[candidate,setCandidate]=useState<{id:string;changed:number;locked:number;unmatched:number}>();
  const [pinKind,setPinKind]=useState<MoodboardPin['kind']>('image'),[pinLabel,setPinLabel]=useState(''),[pinText,setPinText]=useState(''),[pinCredit,setPinCredit]=useState(''),[pinSource,setPinSource]=useState(''),[pinImage,setPinImage]=useState<PersonalPhotoAsset>(),[catalogSearch,setCatalogSearch]=useState(''),[catalogId,setCatalogId]=useState(catalog[0].id),[finishKind,setFinishKind]=useState<'wall'|'floor'|'countertop'>('wall'),[finishId,setFinishId]=useState(wallFinishes[0].id);
  const [surfaceKind,setSurfaceKind]=useState<'art'|'swatch'>('art'),[pieceId,setPieceId]=useState(''),[surface,setSurface]=useState<PersonalSurface>(),[surfacePhoto,setSurfacePhoto]=useState<PersonalPhotoAsset>();
  const alive=useRef(true),running=useRef(false),livePlan=useRef(plan),editBase=useRef(plan),bridge=useRef(preview),stageId=useRef<string|undefined>(undefined);livePlan.current=plan;bridge.current=preview;
  const clearPreview=()=>{if(stageId.current)bridge.current.discard(stageId.current);stageId.current=undefined;setCandidate(undefined)};
  useEffect(()=>{alive.current=true;return()=>{alive.current=false;if(stageId.current)bridge.current.discard(stageId.current)}},[]);
  useEffect(()=>{clearPreview();setSurface(undefined);setPieceId('');setSurfacePhoto(undefined)},[plan,floorId]);
  useEffect(()=>{if(candidate&&preview.activeId!==candidate.id){stageId.current=undefined;setCandidate(undefined)}},[preview.activeId,candidate]);
  const assertCurrent=(base:PlanDocumentV1)=>{if(!alive.current||livePlan.current!==base)throw new Error('The project changed while you were editing. Reopen this board or piece before applying. Any stored photo remains private on this device.');};
  const run=async(work:()=>Promise<void>)=>{if(running.current)return;running.current=true;setBusy(true);onBusyChange?.(true);setError('');setNotice('');try{await work()}catch(e){if(alive.current)setError((e as Error).message||'This inspiration edit could not be completed.')}finally{running.current=false;if(alive.current)setBusy(false);onBusyChange?.(false)}};
  const stageProposal=(result:PaletteProposal)=>{assertCurrent(result.base);if(preview.blocked)throw new Error('Finish the other preview first.');if(stageId.current)preview.discard(stageId.current);const id=preview.stage(result);stageId.current=id;setCandidate({id,changed:result.changedIds.length,locked:result.skippedLockedIds.length,unmatched:result.unmatchedIds.length});setNotice('Preview only. Apply to keep this design, or discard it.');};
  const board=boards.find(b=>b.id===choice),target=draft?.target??board?.target;
  const scopeOptions=useMemo(()=>{const rooms=[...new Map((floor?.blueprint?.rooms??[]).map(r=>[r.groupId??r.id,{id:r.groupId??r.id,name:r.name}])).values()],groups=(plan as GroupPlan).furnitureGroups?.groups.filter(g=>g.floorId===floorId)??[];return [{label:'Current floor',value:{scope:'floor' as const,floorId}},...rooms.map(r=>({label:`Room: ${r.name}`,value:{scope:'room' as const,floorId,id:r.id}})),...groups.map(g=>({label:`Group: ${g.name}`,value:{scope:'group' as const,floorId,id:g.id}}))]},[plan,floorId]);
  const slots=useMemo(()=>{let pieces=plan.furniture.filter(p=>p.floorId===floorId);if(target)try{pieces=resolveMoodboardTarget(plan,target)}catch{}return [...new Map(pieces.flatMap(p=>moodboardMaterialSlots(p.catalogId)).map(slot=>[slot.id,slot])).values()].sort((a,b)=>a.label.localeCompare(b.label))},[plan,floorId,target]);
  const openBoard=(value?:Moodboard)=>{clearPreview();editBase.current=plan;setDraft(value?structuredClone(value):freshBoard(floorId));setPendingPhotos([]);setPinImage(undefined);setPinLabel('');setPinText('');setPinCredit('');setPinSource('');setRemoveBoard(false);setError('');};
  const saveBoard=()=>run(async()=>{if(!draft)return;const base=editBase.current;assertCurrent(base);const valid=parseMoodboard(draft),next=saveMoodboard(base,valid),ids=new Set(valid.pins.filter(p=>p.kind==='image').map(p=>p.assetId)),assets=pendingPhotos.filter(p=>ids.has(p.id));if(assets.length)await importPersonalAssets({version:1,assets:[...new Map(assets.map(a=>[a.id,a])).values()],missing:[]});assertCurrent(base);await onCommit(base,next,'Save inspiration board');if(alive.current){setChoice(valid.id);setDraft(undefined);setPendingPhotos([]);setNotice('Board updated. Check the project Save control for device-save status. Photos stay private.')}});
  const addPin=()=>{if(!draft)return;try{const base={id:crypto.randomUUID(),label:pinLabel.trim()||(pinKind==='catalog'?labelFor(catalogId):'My reference')};let pin:MoodboardPin;
    if(pinKind==='image'){if(!pinImage)throw new Error('Choose a private reference image first.');pin={...base,kind:'image',assetId:pinImage.id,...(pinCredit?{attribution:pinCredit}:{}),...(pinSource?{sourceUrl:pinSource}:{})};}
    else if(pinKind==='catalog')pin={...base,kind:'catalog',catalogId};else if(pinKind==='finish')pin={...base,label:pinLabel.trim()||finishSets[finishKind].find(f=>f.id===finishId)?.name||'Saved finish',kind:'finish',finishKind,finishId};else pin={...base,kind:'note',text:pinText};
    const next=parseMoodboard({...draft,pins:[...draft.pins,parseMoodboardPin(pin)]});setDraft(next);if(pinImage&&pinKind==='image')setPendingPhotos(values=>[...values.filter(v=>v.id!==pinImage.id),pinImage]);setPinImage(undefined);setPinLabel('');setPinText('');setPinCredit('');setPinSource('');setError('');}catch(e){setError((e as Error).message)}};
  const apply=()=>{if(!candidate||preview.activeId!==candidate.id||preview.blocked||busy)return;try{preview.apply(candidate.id);stageId.current=undefined;setCandidate(undefined);setNotice('Design applied. Undo restores the previous appearance.')}catch(e){setError((e as Error).message)}};
  const surfaceCandidates=plan.furniture.filter(p=>p.floorId===floorId&&(surfaceKind==='art'?personalArtModels[p.catalogId]:swatchMaterialSlots(p.catalogId).length));
  const choosePiece=(id:string)=>{clearPreview();setPieceId(id);setSurfacePhoto(undefined);editBase.current=plan;const p=surfaceCandidates.find(p=>p.id===id);if(!p){setSurface(undefined);return;}const existing=(p as SurfacePlacement).personalSurface;
    setSurface(existing?.kind===surfaceKind?structuredClone(existing):{version:1,kind:surfaceKind,label:surfaceKind==='art'?'My artwork':'My fabric swatch',slotId:surfaceKind==='art'?personalArtModels[p.catalogId].imageSlot:swatchMaterialSlots(p.catalogId)[0].id,hidden:true,crop:{x:0,y:0,width:1,height:1},rotation:0,fallbackColor:'#d8cebf',...(surfaceKind==='art'?{frameColor:'#86614d'}:{repeatWidthMm:200,repeatHeightMm:200})});};
  const previewSurface=()=>run(async()=>{if(!surface)return;const base=editBase.current;assertCurrent(base);if(surface.hidden)throw new Error('Choose a private image before previewing this surface.');const valid=parsePersonalSurface(surface),result=buildPersonalSurface(base,floorId,pieceId,valid);if(surfacePhoto)await importPersonalAssets({version:1,assets:[surfacePhoto],missing:[]});assertCurrent(base);stageProposal(result);});
  const pinCard=(pin:MoodboardPin,index:number,editable=false)=>{const finish=pin.kind==='finish'?finishSets[pin.finishKind].find(f=>f.id===pin.finishId):undefined;return <article key={pin.id} className="mood-pin"><h4>{pin.label}</h4>{pin.kind==='image'?<><PersonalPhoto id={pin.assetId} preview={pendingPhotos.find(a=>a.id===pin.assetId)?.preview}/>{pin.attribution&&<small>{pin.attribution}</small>}{pin.sourceUrl&&<a href={pin.sourceUrl} target="_blank" rel="noopener noreferrer">Source link</a>}</>:pin.kind==='catalog'?<><img src={modelAssetPath(pin.catalogId,true)} alt={pin.label} loading="lazy"/><small>{labelFor(pin.catalogId)}</small></>:pin.kind==='finish'?<><span className="mood-finish" style={{backgroundColor:finish?.color??'#d3c8b8',...(finish?.texture?{backgroundImage:`url(${finish.texture})`}:{})}}/><small>{finish?.name??'Finish unavailable'} · {pin.finishKind}</small></>:<p>{pin.text}</p>}{editable&&<div className="mood-actions"><button disabled={busy||index===0} onClick={()=>setDraft(current=>{if(!current)return current;const pins=[...current.pins];[pins[index-1],pins[index]]=[pins[index],pins[index-1]];return {...current,pins}})} aria-label={`Move ${pin.label} earlier`}>Earlier</button><button disabled={busy} onClick={()=>setDraft(current=>current&&({...current,pins:current.pins.filter(p=>p.id!==pin.id)}))}>Remove pin</button></div>}</article>;};
  return <section className="moodboards-panel" aria-label="Inspiration and personal images" aria-busy={busy}>
    <header><div><span className="eyebrow">A room that feels like you</span><h2>Inspiration &amp; personal art</h2></div><button disabled={busy} onClick={()=>{clearPreview();onClose()}}>Close</button></header>
    <p>Collect ideas, link colors to specific parts, or place your own memories in existing frames. Original uploads stay private and unchanged.</p>
    <div className="mood-tabs" role="group" aria-label="Inspiration tools"><button disabled={busy||!!draft} aria-pressed={tab==='boards'} onClick={()=>{clearPreview();setTab('boards')}}>Moodboards</button><button disabled={busy||!!draft} aria-pressed={tab==='images'} onClick={()=>{clearPreview();setTab('images')}}>My art &amp; fabric</button></div>
    {error&&<p role="alert" className="mood-warning">{error}</p>}{notice&&<p role="status">{notice}</p>}{preview.blocked&&<p className="mood-warning">Finish or discard the other placement or design preview first.</p>}
    {candidate&&<section className="mood-candidate" aria-label="Review design"><strong>{candidate.changed} pieces in this preview</strong><p>{candidate.locked} locked pieces preserved · {candidate.unmatched} pieces without matching roles skipped</p><div className="mood-actions"><button className="primary" disabled={busy||preview.blocked||preview.activeId!==candidate.id} onClick={apply}>Apply design</button><button disabled={busy} onClick={()=>{clearPreview();setNotice('Preview discarded. Your home is unchanged.')}}>Discard preview</button></div></section>}
    {tab==='boards'?(draft?<>
      <label>Board name<input maxLength={80} value={draft.name} disabled={busy} onChange={e=>setDraft({...draft,name:e.target.value})}/></label>
      <label>Linked room or group<select disabled={busy} value={JSON.stringify(draft.target??scopeOptions[0].value)} onChange={e=>setDraft({...draft,target:JSON.parse(e.target.value) as MoodboardTarget})}>{draft.target&&!scopeOptions.some(s=>JSON.stringify(s.value)===JSON.stringify(draft.target))&&<option value={JSON.stringify(draft.target)}>Previously linked target — choose a current room</option>}{scopeOptions.map(s=><option key={JSON.stringify(s.value)} value={JSON.stringify(s.value)}>{s.label}</option>)}</select></label>
      <p className="mood-note">Rooms select pieces by their center point. Check the preview before applying; item and group locks stay protected. Parts with a personal image keep their image.</p>
      <section aria-label="Named palette"><h3>Palette &amp; material roles</h3>{draft.palette.map(entry=><div className="mood-color-row" key={entry.id}><input aria-label={`Color for ${entry.name}`} type="color" value={entry.color} disabled={busy} onChange={e=>setDraft({...draft,palette:draft.palette.map(c=>c.id===entry.id?{...c,color:e.target.value}:c)})}/><input aria-label="Color name" maxLength={60} value={entry.name} disabled={busy} onChange={e=>setDraft({...draft,palette:draft.palette.map(c=>c.id===entry.id?{...c,name:e.target.value}:c)})}/><button disabled={busy} onClick={()=>setDraft({...draft,palette:draft.palette.filter(c=>c.id!==entry.id),bindings:draft.bindings.filter(b=>b.paletteId!==entry.id)})}>Remove color</button></div>)}<button disabled={busy||draft.palette.length>=8} onClick={()=>setDraft({...draft,palette:[...draft.palette,{id:crypto.randomUUID(),name:'New color',color:'#9aaa8b'}]})}>Add palette color</button>
      <div className="mood-bindings">{slots.map(slot=><label key={slot.id}>{slot.label}<select disabled={busy} value={draft.bindings.find(b=>b.slotId===slot.id)?.paletteId??''} onChange={e=>setDraft({...draft,bindings:[...draft.bindings.filter(b=>b.slotId!==slot.id),...(e.target.value?[{slotId:slot.id,paletteId:e.target.value}]:[])]})}><option value="">Leave unchanged</option>{draft.palette.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>)}</div>{!slots.length&&<p>Add furniture to this target to link its material parts.</p>}</section>
      <div className="mood-pin-grid">{draft.pins.map((pin,index)=>pinCard(pin,index,true))}</div>
      <section className="mood-add-pin" aria-label="Add inspiration pin"><h3>Add a reference</h3><label>Pin type<select value={pinKind} disabled={busy} onChange={e=>setPinKind(e.target.value as MoodboardPin['kind'])}><option value="image">Private image</option><option value="catalog">Catalog piece</option><option value="finish">Finish</option><option value="note">Note</option></select></label><label>Accessible label<input maxLength={120} value={pinLabel} disabled={busy} onChange={e=>setPinLabel(e.target.value)} placeholder="Morning light and warm linen"/></label>
      {pinKind==='image'?<><label>Private image<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void run(async()=>{const base=editBase.current;assertCurrent(base);const asset=await preparePersonalPhoto(file);assertCurrent(base);setPinImage(asset)})}}/></label>{pinImage&&<PersonalPhoto preview={pinImage.preview}/>}<label>Attribution<input maxLength={300} value={pinCredit} disabled={busy} onChange={e=>setPinCredit(e.target.value)} placeholder="My photo, or creator / source"/></label><label>Source link (optional)<input type="url" maxLength={2048} value={pinSource} disabled={busy} onChange={e=>setPinSource(e.target.value)} placeholder="https://…"/></label><small>Local PNG, JPEG or WebP up to 5 MB. Source links are bookmarks; nothing is scraped.</small></>:pinKind==='catalog'?<><label>Find a piece<input disabled={busy} value={catalogSearch} onChange={e=>setCatalogSearch(e.target.value)}/></label><label>Catalog reference<select disabled={busy} value={catalogId} onChange={e=>setCatalogId(e.target.value)}><option value={catalogId}>{labelFor(catalogId)}</option>{catalog.filter(c=>c.id!==catalogId&&`${c.name} ${c.category}`.toLowerCase().includes(catalogSearch.toLowerCase())).slice(0,120).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></>:pinKind==='finish'?<><label>Finish family<select value={finishKind} disabled={busy} onChange={e=>{const kind=e.target.value as typeof finishKind;setFinishKind(kind);setFinishId(finishSets[kind][0].id)}}><option value="wall">Walls</option><option value="floor">Floors</option><option value="countertop">Countertops</option></select></label><label>Finish reference<select value={finishId} disabled={busy} onChange={e=>setFinishId(e.target.value)}>{finishSets[finishKind].map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label></>:<label>Private note<textarea rows={3} maxLength={2000} disabled={busy} value={pinText} onChange={e=>setPinText(e.target.value)}/></label>}
      <button disabled={busy||draft.pins.length>=32} onClick={addPin}>Pin to board</button></section>
      <div className="mood-actions"><button className="primary" disabled={busy||!draft.name.trim()} onClick={()=>void saveBoard()}>Save board</button><button disabled={busy} onClick={()=>{setDraft(undefined);setPendingPhotos([]);setPinImage(undefined)}}>Cancel board edits</button></div>
    </>:<><div className="mood-actions"><button className="primary" disabled={busy||boards.length>=8} onClick={()=>openBoard()}>New moodboard</button><label>Saved board<select value={choice??''} disabled={busy} onChange={e=>{clearPreview();setChoice(e.target.value||undefined);setRemoveBoard(false)}}><option value="">Choose a board</option>{boards.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label></div>{!boards.length&&<p>Pin a room reference, a favorite catalog piece or a finish, then name a palette for your home.</p>}{board&&<><h3>{board.name}</h3><div className="mood-palette">{board.palette.map(c=><span key={c.id}><i style={{backgroundColor:c.color}}/>{c.name}</span>)}</div><div className="mood-actions"><button disabled={busy} onClick={()=>openBoard(board)}>Edit board &amp; links</button><button disabled={busy||preview.blocked||board.target?.floorId!==floorId} onClick={()=>{try{stageProposal(buildMoodboardPalette(plan,board))}catch(e){setError((e as Error).message)}}}>Preview linked palette</button><button disabled={busy} onClick={()=>setRemoveBoard(true)}>Delete board…</button></div>{board.target?.floorId!==floorId&&<p>Open the linked floor or edit this board’s target before previewing its palette.</p>}{removeBoard&&<div className="mood-warning"><p>Delete “{board.name}” from this project? Private image files stay available to other saved copies.</p><button disabled={busy} onClick={()=>void run(async()=>{const base=plan;assertCurrent(base);await onCommit(base,deleteMoodboard(base,board.id),'Delete inspiration board');if(alive.current){setChoice(undefined);setRemoveBoard(false);setNotice('Board removed. Undo restores it.')}})}>Delete board</button><button disabled={busy} onClick={()=>setRemoveBoard(false)}>Keep board</button></div>}<div className="mood-pin-grid">{board.pins.map((pin,index)=>pinCard(pin,index))}</div></>}</>) : <>
      <label>Personal image use<select disabled={busy} value={surfaceKind} onChange={e=>{clearPreview();setSurfaceKind(e.target.value as 'art'|'swatch');setSurface(undefined);setSurfacePhoto(undefined);setPieceId('')}}><option value="art">Framed artwork</option><option value="swatch">Fabric material swatch</option></select></label>
      <p className="mood-note">Use your own or permitted images. Uploads are private. Public shares show a neutral placeholder; sharing images requires a separate explicit inclusion flow.</p>
      {!surfaceCandidates.length&&<p>{surfaceKind==='art'?'Place a supported framed painting first.':'Place a piece with a supported fabric material first.'} {surfaceKind==='art'&&onPlaceCatalog&&<button disabled={busy||preview.blocked} onClick={()=>{clearPreview();onPlaceCatalog('landscape-painting')}}>Choose a frame in the room</button>}</p>}
      <label>Piece on this floor<select value={pieceId} disabled={busy} onChange={e=>choosePiece(e.target.value)}><option value="">Choose a piece</option>{surfaceCandidates.map(p=><option key={p.id} value={p.id}>{labelFor(p.catalogId)} · {p.id.slice(0,6)}{furnitureIsLocked(plan,p.id)?' · Locked':''}</option>)}</select></label>
      {surface&&<><label>Image label<input maxLength={120} disabled={busy} value={surface.label} onChange={e=>{clearPreview();setSurface({...surface,label:e.target.value})}}/></label><label>Upload image<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void run(async()=>{const base=editBase.current;assertCurrent(base);const asset=await preparePersonalPhoto(file);assertCurrent(base);clearPreview();setSurfacePhoto(asset);setSurface(current=>current&&({...current,assetId:asset.id,hidden:undefined}));})}}/></label>
      <label>Or reuse a pinned private image<select disabled={busy} value={surface.assetId??''} onChange={e=>{if(!e.target.value)return;clearPreview();const pin=boards.flatMap(b=>b.pins).find(p=>p.kind==='image'&&p.assetId===e.target.value);if(pin?.kind==='image'){setSurfacePhoto(undefined);setSurface({...surface,assetId:pin.assetId,hidden:undefined,label:pin.label,attribution:pin.attribution,sourceUrl:pin.sourceUrl})}}}><option value="">Choose an image from a saved board</option>{surface.assetId&&!boards.some(b=>b.pins.some(p=>p.kind==='image'&&p.assetId===surface.assetId))&&<option value={surface.assetId}>Current private image</option>}{[...new Map(boards.flatMap(b=>b.pins).filter(p=>p.kind==='image').map(p=>[p.assetId,p])).values()].map(pin=><option key={pin.id} value={pin.assetId}>{pin.label}</option>)}</select></label>
      {surfaceKind==='swatch'&&<label>Fabric material role<select disabled={busy} value={surface.slotId} onChange={e=>{clearPreview();setSurface({...surface,slotId:e.target.value})}}>{swatchMaterialSlots(surfaceCandidates.find(p=>p.id===pieceId)?.catalogId??'').map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label>}
      <div className="mood-actions">{(surfaceCandidates.find(p=>p.id===pieceId) as SurfacePlacement|undefined)?.personalSurface&&<button disabled={busy||preview.blocked||furnitureIsLocked(plan,pieceId)} onClick={()=>{try{assertCurrent(editBase.current);stageProposal(buildRemovePersonalSurface(editBase.current,floorId,pieceId))}catch(e){setError((e as Error).message)}}}>Preview original catalog appearance</button>}</div><SurfacePreview surface={surface} photo={surfacePhoto} projectId={plan.id}/><fieldset className="mood-crop"><legend>Crop (percent of original)</legend>{(['x','y','width','height'] as const).map(key=><label key={key}>{({x:'Left',y:'Top',width:'Width',height:'Height'})[key]}<input type="number" min={key==='width'||key==='height'?1:0} max={100} step={1} disabled={busy} value={Math.round(surface.crop[key]*100)} onChange={e=>{const value=e.target.valueAsNumber;if(!Number.isFinite(value))return;clearPreview();const next={...surface.crop,[key]:Math.max((key==='width'||key==='height') ? 0.01 : 0,Math.min(1,value/100))};if(key==='x')next.width=Math.min(next.width,1-next.x);if(key==='y')next.height=Math.min(next.height,1-next.y);if(key==='width')next.x=Math.min(next.x,1-next.width);if(key==='height')next.y=Math.min(next.y,1-next.height);if(next.width>0&&next.height>0)setSurface({...surface,crop:next})}}/></label>)}</fieldset>
      <div className="mood-actions"><button disabled={busy} onClick={()=>{clearPreview();setSurface({...surface,rotation:((surface.rotation+90)%360) as PersonalSurface['rotation']})}}>Turn image 90°</button><button disabled={busy} onClick={()=>{clearPreview();setSurface({...surface,crop:{x:0,y:0,width:1,height:1},rotation:0})}}>Reset crop</button></div>
      {surfaceKind==='swatch'?<div className="mood-repeats"><LengthInput label="Pattern repeat width" units={plan.units} value={surface.repeatWidthMm??200} min={10} disabled={busy} onChange={repeatWidthMm=>{clearPreview();setSurface({...surface,repeatWidthMm})}}/><LengthInput label="Pattern repeat height" units={plan.units} value={surface.repeatHeightMm??200} min={10} disabled={busy} onChange={repeatHeightMm=>{clearPreview();setSurface({...surface,repeatHeightMm})}}/></div>:<label>Frame color<input type="color" disabled={busy} value={surface.frameColor??'#86614d'} onChange={e=>{clearPreview();setSurface({...surface,frameColor:e.target.value})}}/></label>}
      <label>Fallback color<input type="color" disabled={busy} value={surface.fallbackColor} onChange={e=>{clearPreview();setSurface({...surface,fallbackColor:e.target.value})}}/></label><p className="mood-note">This color shows while the image is unavailable or private. To keep large homes responsive, the scene displays up to 16 distinct private images at once, prioritizing the selected piece and current floor. Fabric appearance depends on the authored model’s texture mapping; these are design previews, not manufacturer-verified materials.</p><label>Attribution<input maxLength={300} disabled={busy} value={surface.attribution??''} onChange={e=>{clearPreview();setSurface({...surface,attribution:e.target.value||undefined})}}/></label><label>Source link (optional)<input maxLength={2048} disabled={busy} value={surface.sourceUrl??''} onChange={e=>{clearPreview();setSurface({...surface,sourceUrl:e.target.value||undefined})}}/></label>
      <button className="primary" disabled={busy||preview.blocked||surface.hidden||furnitureIsLocked(plan,pieceId)} onClick={()=>void previewSurface()}>Preview image in room</button><p className="mood-note">Previewing stores a private copy of the photo on this device. Discarding changes keeps that photo in private storage; manage it in My furniture.</p></>}
    </>}
  </section>;
}
