import {useEffect,useMemo,useRef,useState} from 'react';
import {parseProjectBackup} from './projectBackup';
import {checkOnlineMedia,deleteOnlineMedia,downloadOnlineMedia,listOnlineMedia,prepareOnlineMedia,replaceOnlineMediaHead,restoreOnlineMediaCopy,resumeOnlineMedia,startOnlineMedia,type MediaProgress,type DownloadedOnlineMedia} from './onlineMediaClient';
import {listPreparedMedia,removePreparedMedia,type PreparedOnlineMedia} from './onlineMediaStorage';
import type {OnlineMediaProject,OnlineMediaSelection,OnlineMediaSnapshot,OnlineMediaStatus} from './onlineMedia';
import type {ListingDocument} from './listingTypes';
import type {PlanDocumentV1} from './types';
import './online-media.css';
type Props={plan?:PlanDocumentV1;listing?:ListingDocument;disabled?:boolean;beforeRestore?():Promise<void>;onBusyChange?(busy:boolean):void;onRestored(plan:PlanDocumentV1):void|Promise<void>};
const size=(n:number)=>(n/1024/1024).toFixed(2)+' MiB';
export function OnlineMediaPanel(props:Props){
 const [status,setStatus]=useState<OnlineMediaStatus>(),[projects,setProjects]=useState<OnlineMediaProject[]>([]),[selection,setSelection]=useState<OnlineMediaSelection>({listing:false,references:false,personal:false}),[prepared,setPrepared]=useState<PreparedOnlineMedia>(),[recovery,setRecovery]=useState<Awaited<ReturnType<typeof listPreparedMedia>>>([]),[download,setDownload]=useState<DownloadedOnlineMedia>(),[confirmUpload,setConfirmUpload]=useState(false),[remove,setRemove]=useState<OnlineMediaSnapshot>(),[replace,setReplace]=useState<{snapshot:OnlineMediaSnapshot;expectedRevision:number}>(),[busy,setBusy]=useState(''),[progress,setProgress]=useState<MediaProgress>(),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const active=useRef<AbortController|null>(null),generation=useRef(0),alive=useRef(true),latest=useRef(props);latest.current=props;
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;generation.current++;active.current?.abort();latest.current.onBusyChange?.(false);};},[]);
 useEffect(()=>{generation.current++;active.current?.abort();active.current=null;setPrepared(undefined);setDownload(undefined);setConfirmUpload(false);setBusy('');setProgress(undefined);setError('');setRemove(undefined);setReplace(undefined);latest.current.onBusyChange?.(false);},[props.plan?.id]);
 async function work(label:string,fn:(signal:AbortSignal,current:()=>boolean)=>Promise<void>){if(active.current||props.disabled)return;const controller=new AbortController(),ticket=generation.current;active.current=controller;setBusy(label);setError('');setNotice('');setProgress(undefined);latest.current.onBusyChange?.(true);const current=()=>alive.current&&generation.current===ticket&&!controller.signal.aborted;try{await fn(controller.signal,current);}catch(e){if(current())setError(e instanceof Error?e.message:'This operation could not finish.');}finally{if(alive.current&&generation.current===ticket){active.current=null;setBusy('');latest.current.onBusyChange?.(false);}}}
 async function refresh(key:string,signal:AbortSignal,current:()=>boolean){const [all,local]=await Promise.all([listOnlineMedia(key,signal),listPreparedMedia(key)]);if(current()){setProjects(all);setRecovery(local);}}
 function inspect(){void work('Checking storage',async(signal,current)=>{const value=await checkOnlineMedia(signal);if(!current())return;if(value.accountKey!==status?.accountKey){setPrepared(undefined);setConfirmUpload(false);setDownload(undefined);}setStatus(value);setProjects([]);setRecovery([]);if(value.signedIn&&value.manageAvailable&&value.accountKey)await refresh(value.accountKey,signal,current);});}
 const key=status?.accountKey,locked=!!busy||!!props.disabled,currentProject=projects.find(p=>p.projectId===props.plan?.id),currentReserved=currentProject?.snapshots.reduce((n,s)=>n+s.bytes,0)??0;
 const previews=useMemo(()=>{if(!prepared)return [];try{const b=parseProjectBackup(new TextDecoder().decode(prepared.bytes));return [...(b.listing?.media.map(m=>({src:m.image,label:m.title||'Listing image'}))??[]),...(b.personalAssets?.assets.map(p=>({src:p.preview,label:'Private original included'}))??[])];}catch{return [];}},[prepared]);
 function completed(current:()=>boolean){if(current()){setNotice('Upload complete. Every declared chunk is stored. Included and missing media are listed with this snapshot.');setPrepared(undefined);setConfirmUpload(false);}}
 return <section className="online-media" aria-label="Private online media backups">
  <h3>Private online media backups</h3>
  <p>Optionally keep a small complete-file snapshot in your signed-in library. Your plan, private labels and notes are included. Photographs and reference originals require the choices below. This does not publish a link.</p>
  <p className="online-media-muted">Portable local backups remain available. Online storage is a bounded pilot and may be unavailable. Partial uploads and older complete copies both use your quota.</p>
  <button type="button" disabled={locked} onClick={inspect}>{status?'Refresh online storage':'Check online storage'}</button>
  {status&&!status.signedIn&&<p>Sign in using the project library, then check again. Nothing has been uploaded.</p>}
  {status?.reason&&<p role="status">{status.reason}</p>}
  {status?.signedIn&&<p>Stored and reserved for this account: {size(projects.flatMap(p=>p.snapshots).reduce((n,s)=>n+s.bytes,0))} / 50 MiB. Project limit: 20 MiB, including previous complete copies. New uploads also depend on the service’s shared pilot capacity.</p>}
  {status?.available&&key&&props.plan&&<fieldset disabled={locked}>
   <legend>Prepare a snapshot of {props.plan.name}</legend>
   <p>Choose the originals to send. Leaving them out keeps explicit missing-media records in the backup. Plan text and personal item notes still travel with the plan.</p>
   {(['listing','references','personal'] as const).map(field=><label key={field}><input type="checkbox" checked={selection[field]} onChange={e=>{setSelection({...selection,[field]:e.target.checked});setPrepared(undefined);setConfirmUpload(false);}}/>{({listing:'Listing details, photos, paired originals and viewpoints',references:'Floor-plan reference files, previews and saved versions',personal:'Personal furniture, art and moodboard image originals'} as const)[field]}</label>)}
   <button type="button" onClick={()=>void work('Preparing on this browser',async(_signal,current)=>{const result=await prepareOnlineMedia(props.plan!,selection,key,currentProject?.revision??0,props.listing);if(current()){setPrepared(result);setConfirmUpload(false);}})}>Prepare locally</button>
  </fieldset>}
  {prepared&&<div className="online-media-card">
   <h4>Review this exact snapshot</h4><p>{prepared.manifest.projectName} · {size(prepared.manifest.totalBytes)} · {new Date(prepared.manifest.exportedAt).toLocaleString()}</p>
   <p>{prepared.manifest.counts.floors} floors · {prepared.manifest.counts.listingMedia} listing images · {prepared.manifest.counts.personalAssets} private originals · {prepared.manifest.counts.references} references</p>
   {previews.length>0&&<details><summary>Review selected images ({previews.length})</summary><div className="online-media-previews">{previews.map((p,i)=><figure key={i}><img src={p.src} alt={p.label} loading="lazy"/><figcaption>{p.label}</figcaption></figure>)}</div></details>}
   <Notices notices={prepared.manifest.notices}/>
   {currentReserved+prepared.manifest.totalBytes>20*1024*1024&&<p role="alert">This snapshot and the stored copies exceed the project quota. Remove an older copy or reduce the included media. The current complete copy will never be removed automatically.</p>}
   <label><input type="checkbox" disabled={locked} checked={confirmUpload} onChange={e=>setConfirmUpload(e.target.checked)}/>Upload these exact bytes privately, including all chosen images, original documents, plan labels and notes.</label>
   <button type="button" disabled={locked||!confirmUpload||currentReserved+prepared.manifest.totalBytes>20*1024*1024} onClick={()=>void work('Uploading private snapshot',async(signal,current)=>{await startOnlineMedia(prepared,confirmUpload,signal,p=>{if(current())setProgress(p);});completed(current);if(current())await refresh(key!,signal,current);})}>Upload private snapshot</button>
   <button type="button" disabled={locked} onClick={()=>{setPrepared(undefined);setConfirmUpload(false);}}>Discard preparation</button>
  </div>}
  {key&&recovery.length>0&&<div className="online-media-card"><h4>Recovery copies on this browser</h4><p>Resume sends only missing chunks using the original upload identity. Removing these local bytes does not delete any online snapshot.</p><ul>{recovery.map(r=><li key={r.id}><span>{r.name} · {size(r.bytes)}</span><button type="button" disabled={locked||!status?.available} onClick={()=>void work('Resuming private upload',async(signal,current)=>{await resumeOnlineMedia(r.id,key,signal,p=>{if(current())setProgress(p);});completed(current);if(current())await refresh(key,signal,current);})}>Resume / check completion</button><button type="button" disabled={locked} onClick={()=>void work('Removing local recovery bytes',async(signal,current)=>{await removePreparedMedia(r.id,key);if(current()){await refresh(key,signal,current);setNotice('Local recovery bytes removed. Online copies are unchanged.');}})}>Remove local recovery copy</button></li>)}</ul></div>}
  {key&&projects.some(p=>p.snapshots.length)&&<div className="online-media-card"><h4>Private online snapshots</h4><p>Download and review any complete snapshot before creating a new local project. An incomplete upload needs its original recovery bytes on the browser that prepared it.</p>{projects.filter(p=>p.snapshots.length).map(p=><div key={p.projectId}><h5>{p.snapshots[0].name}</h5><ul>{p.snapshots.map(s=><li key={s.id}><span>{new Date(s.createdAt).toLocaleString()} · {size(s.bytes)} · {s.state==='complete'?'Complete':'Incomplete'}{p.headId===s.id?' · Current':''}{s.state==='uploading'&&s.expiresAt<Date.now()?' · Expired':''}</span>{s.state==='complete'&&<button type="button" disabled={locked} onClick={()=>void work('Downloading and verifying',async(signal,current)=>{const value=await downloadOnlineMedia(s.id,key,signal,p=>{if(current())setProgress(p);});if(current())setDownload(value);})}>Download and review</button>}{s.state==='uploading'&&s.baseRevision!==p.revision&&recovery.some(r=>r.id===s.id)&&<button type="button" disabled={locked||!status?.available} onClick={()=>setReplace({snapshot:s,expectedRevision:p.revision})}>Review competing snapshot</button>}<button type="button" disabled={locked} onClick={()=>setRemove(s)}>Delete online copy</button></li>)}</ul></div>)}</div>}
  {replace&&key&&<div className="online-media-confirm"><p>A newer snapshot completed after this upload was prepared. Finishing this older preparation will make it current; previous complete copies remain until you delete them.</p><button type="button" disabled={locked} onClick={()=>void work('Replacing current snapshot',async(signal,current)=>{await replaceOnlineMediaHead(replace.snapshot.id,key,replace.expectedRevision,replace.snapshot.stateVersion,true,signal,p=>{if(current())setProgress(p);});if(current()){setReplace(undefined);completed(current);await refresh(key,signal,current);}})}>Make this prepared upload current</button><button type="button" disabled={locked} onClick={()=>setReplace(undefined)}>Keep current snapshot</button></div>}
  {remove&&key&&<div className="online-media-confirm"><p>Delete the {remove.state==='complete'?'complete':'incomplete'} online copy of {remove.name} from {new Date(remove.createdAt).toLocaleString()}? Its stored chunks will be removed. If it is current, the most recent remaining complete copy becomes current. Local projects and published links are unchanged.</p><button type="button" disabled={locked} onClick={()=>void work('Deleting online copy',async(signal,current)=>{await deleteOnlineMedia(remove.id,key,remove.stateVersion,signal);if(current()){setRemove(undefined);await refresh(key,signal,current);setNotice('Online copy deleted. Local projects are unchanged.');}})}>Confirm online deletion</button><button type="button" disabled={locked} onClick={()=>setRemove(undefined)}>Keep online copy</button></div>}
  {download&&<div className="online-media-card"><h4>Ready to restore {download.backup.plan.name}</h4><p>All downloaded bytes and included private image hashes passed validation. This creates an independent local project with a new identity.</p><Notices notices={download.notices}/><button type="button" disabled={locked} onClick={()=>void work('Creating local project',async(_signal,current)=>{await props.beforeRestore?.();if(!current())return;const result=await restoreOnlineMediaCopy(download.backup,true);if(!current())return;setDownload(undefined);try{await latest.current.onRestored(result);}catch{throw Error('The new project was restored successfully, but could not be opened. Find it in your local project library.');}if(current())setNotice('A new local project copy was created. Existing projects are unchanged.');})}>Create and open new local copy</button><button type="button" disabled={locked} onClick={()=>setDownload(undefined)}>Discard download</button></div>}
  {busy&&<p role="status">{busy}{progress?` · ${size(progress.done)} / ${size(progress.total)}`:''}</p>}
  {busy&&busy!=='Creating local project'&&<button type="button" onClick={()=>{active.current?.abort();setNotice('Stopped waiting. Any incomplete online upload and its recovery bytes remain available. Refresh storage before resuming.');}}>Stop transfer</button>}
  {notice&&<p role="status">{notice}</p>}{error&&<p role="alert">{error}</p>}
 </section>;
}
function Notices({notices}:{notices:string[]}){return notices.length?<details open><summary>Included-media limitations ({notices.length})</summary><ul>{notices.map((n,i)=><li key={i}>{n}</li>)}</ul></details>:<p>Every referenced asset is present in this package.</p>;}
