import {openDB} from 'idb';
import {ONLINE_MEDIA_LIMITS as L,mediaDigest,mediaHash,mediaId,mediaInteger,parseOnlineMediaManifest,type OnlineMediaManifest} from './onlineMedia';
export interface PreparedOnlineMedia {id:string;accountKey:string;baseRevision:number;manifest:OnlineMediaManifest;bytes:Uint8Array;createdAt:number}
const database=()=>openDB('nook-private-media-transfers',1,{upgrade(db){db.createObjectStore('prepared',{keyPath:'id'});}});
export async function verifyPreparedMedia(value:PreparedOnlineMedia):Promise<PreparedOnlineMedia>{
 const manifest=parseOnlineMediaManifest(value.manifest);if(!mediaId(value.id)||!mediaHash(value.accountKey))throw Error('Invalid upload identity.');mediaInteger(value.baseRevision);mediaInteger(value.createdAt);
 const bytes=new Uint8Array(value.bytes);if(bytes.length!==manifest.totalBytes||await mediaDigest(bytes)!==manifest.archiveHash)throw Error('The prepared backup bytes changed. Prepare a fresh backup.');
 let offset=0;for(const chunk of manifest.chunks){if(await mediaDigest(bytes.subarray(offset,offset+chunk.bytes))!==chunk.hash)throw Error('A prepared backup chunk is damaged.');offset+=chunk.bytes;}
 return {...value,manifest,bytes};
}
/** Mandatory durable exact bytes BEFORE any server reservation or photo upload. */
export async function savePreparedMedia(input:PreparedOnlineMedia){const value=await verifyPreparedMedia(input),db=await database();try{const tx=db.transaction('prepared','readwrite');try{const old=await tx.store.get(value.id),all=await tx.store.getAll();if(old&&(old.accountKey!==value.accountKey||JSON.stringify(old.manifest)!==JSON.stringify(value.manifest)||old.baseRevision!==value.baseRevision))throw Error('This upload identity is already in use.');const others=all.filter((r:PreparedOnlineMedia)=>r.id!==value.id);if(others.length>=4||others.reduce((n:number,r:PreparedOnlineMedia)=>n+r.bytes.byteLength,0)+value.bytes.byteLength>L.account)throw Error('Local recovery cache is full (four uploads / 50 MiB). Remove finished recovery copies first.');await tx.store.put(value);await tx.done;}catch(error){try{tx.abort();}catch{}await tx.done.catch(()=>{});throw error;}}finally{db.close();}}
export async function listPreparedMedia(accountKey:string){if(!mediaHash(accountKey))throw Error('Check the current account first.');const db=await database();try{return (await db.getAll('prepared') as PreparedOnlineMedia[]).filter(r=>r.accountKey===accountKey).map(r=>({id:r.id,projectId:r.manifest.projectId,name:r.manifest.projectName,bytes:r.manifest.totalBytes}));}finally{db.close();}}
export async function loadPreparedMedia(id:string,accountKey:string){const db=await database();try{const value=await db.get('prepared',id) as PreparedOnlineMedia|undefined;if(!value||value.accountKey!==accountKey)throw Error('The exact prepared bytes are unavailable for this account on this browser. Complete snapshots can still be downloaded; remove an incomplete online upload if its missing bytes are lost.');return await verifyPreparedMedia(value);}finally{db.close();}}
export async function removePreparedMedia(id:string,accountKey:string){const db=await database();try{const tx=db.transaction('prepared','readwrite'),value=await tx.store.get(id);if(value?.accountKey===accountKey)await tx.store.delete(id);await tx.done;}finally{db.close();}}
