import {useState} from 'react';
export const popularPaints=[['Soft white','#f1eee4'],['Warm ivory','#eee7d9'],['Pale oak','#dcd5c9'],['Greige','#c9c3b8'],['Warm gray','#b7b3aa'],['Charcoal','#454844'],['Soft sage','#a6b09c'],['Olive','#737b5b'],['Forest','#344c40'],['Deep navy','#414c59'],['Misty blue','#b3c5ca'],['Slate','#6c818b'],['Dusty rose','#c59c96'],['Clay','#bf876e'],['Buttercream','#e7d49c'],['Black ink','#292b2a']];
export function hsvHex(h:number,s:number,v:number){const f=(n:number)=>{const k=(n+h/60)%6;return Math.round(255*(v-v*s*Math.max(0,Math.min(k,4-k,1)))).toString(16).padStart(2,'0')};return '#'+f(5)+f(3)+f(1)}
export function PaintPicker({onChoose}:{onChoose:(id:string)=>void}){
 const [h,setH]=useState(90),[sat,setSat]=useState(.2),[value,setValue]=useState(.9),[hex,setHex]=useState('#cfd9b8');
 const pick=(e:React.PointerEvent<HTMLDivElement>)=>{const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)/(r.width/2),y=(e.clientY-r.top-r.height/2)/(r.height/2),hue=(Math.atan2(y,x)*180/Math.PI+450)%360,s=Math.min(1,Math.hypot(x,y));setH(hue);setSat(s);setHex(hsvHex(hue,s,value))};
 const valid=/^#[0-9a-f]{6}$/i.test(hex);
 return <section className="paint-picker" aria-label="Paint colors"><h3>Popular color families</h3><div className="paint-presets">{popularPaints.map(([name,color])=><button key={name} aria-label={`Paint ${name}`} title={name} style={{backgroundColor:color}} onClick={()=>{setHex(color);onChoose('paint-'+color.slice(1))}}/>)}</div><details><summary>Mix any paint color</summary><div className="paint-wheel" role="img" aria-label="Hue and saturation wheel; use sliders below for keyboard control" style={{filter:`brightness(${value})`}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);pick(e)}} onPointerMove={e=>{if(e.buttons===1)pick(e)}}><i style={{left:`${50+48*sat*Math.sin(h*Math.PI/180)}%`,top:`${50-48*sat*Math.cos(h*Math.PI/180)}%`}}/></div><label>Hue<input aria-label="Paint hue" type="range" min="0" max="359" value={h} onChange={e=>{setH(+e.target.value);setHex(hsvHex(+e.target.value,sat,value))}}/></label><label>Saturation<input aria-label="Paint saturation" type="range" min="0" max="100" value={sat*100} onChange={e=>{setSat(+e.target.value/100);setHex(hsvHex(h,+e.target.value/100,value))}}/></label><label>Brightness<input aria-label="Paint brightness" type="range" min="0" max="100" value={value*100} onChange={e=>{setValue(+e.target.value/100);setHex(hsvHex(h,sat,+e.target.value/100))}}/></label><div className="paint-color-input"><span style={{backgroundColor:valid?hex:'transparent'}}/><input aria-label="Paint hex color" value={hex} maxLength={7} onChange={e=>setHex(e.target.value)}/><button disabled={!valid} onClick={()=>onChoose('paint-'+hex.slice(1).toLowerCase())}>Use color</button></div></details></section>
}
