import {useEffect,useMemo,useRef,useState} from 'react';
import {LengthInput} from './LengthInput';
import type {KitPreviewBridge} from './FurnitureKitsPanel';
import type {KitPosition} from './furnitureKits';
import {buildPersonalPlacement,initialPersonalPosition,personalProxyCatalog} from './personalPlacement';
import {parsePersonalCollectionItem,type PersonalCollectionItem} from './personalItems';
import {preparePersonalPhoto,type PersonalPhotoAsset} from './personalMedia';
import {deletePersonalItem,listPersonalItems,listStoredPersonalPhotos,loadPersonalPhoto,removeStoredPersonalPhoto,savePersonalItem,type StoredPersonalPhoto} from './personalStorage';
import {readableLength} from './measurement';
import {modelAssetPath} from './modelAssetPath';
import type {PlanDocumentV1} from './types';
import './personal-furniture.css';

/** No photo is fetched from a URL or an online service. */
export function PersonalPhoto({id,preview}: {id?:string;preview?:string}){
  const [source,setSource]=useState(preview),[missing,setMissing]=useState(false);
  useEffect(()=>{let alive=true;setSource(preview);setMissing(false);if(id&&!preview)void loadPersonalPhoto(id).then(asset=>{if(alive){setSource(asset?.preview);setMissing(!asset);}}).catch(()=>{if(alive)setMissing(true)});return()=>{alive=false}},[id,preview]);
  return source?<img className="personal-photo" src={source} alt="Your private reference photo"/>:<span className="personal-photo personal-photo-empty">{missing?'Photo unavailable on this device':id?'Opening private photo…':'No photo added'}</span>;
}
export interface PersonalFurniturePanelProps {plan:PlanDocumentV1;floorId:string;preview:KitPreviewBridge;onClose():void;onBusyChange?(busy:boolean):void}
/** Embed in the existing arrangements dialog. The bridge retains all preview/undo ownership. */
export function PersonalFurniturePanel({plan,floorId,preview,onClose,onBusyChange}:PersonalFurniturePanelProps){
  const [items,setItems]=useState<PersonalCollectionItem[]>([]),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [form,setForm]=useState<PersonalCollectionItem>(),[photo,setPhoto]=useState<PersonalPhotoAsset>(),[search,setSearch]=useState(''),[proxySearch,setProxySearch]=useState('');
  const [selected,setSelected]=useState<PersonalCollectionItem>(),[position,setPosition]=useState<KitPosition>(),[stage,setStage]=useState<{id:string;warnings:string[]}>(),[remove,setRemove]=useState<PersonalCollectionItem>(),[removePhoto,setRemovePhoto]=useState(false);
  const [storedPhotos,setStoredPhotos]=useState<StoredPersonalPhoto[]>(),[deletingAsset,setDeletingAsset]=useState<string>(),[photoEpoch,setPhotoEpoch]=useState(0);
  const alive=useRef(true),running=useRef(false),bridge=useRef(preview),stageId=useRef<string|undefined>(undefined),epoch=useRef(0);bridge.current=preview;
  const clearPreview=()=>{if(stageId.current)bridge.current.discard(stageId.current);stageId.current=undefined;setStage(undefined);setSelected(undefined);setPosition(undefined);};
  const refresh=async()=>{const current=++epoch.current;try{const next=await listPersonalItems();if(alive.current&&epoch.current===current){setItems(next);setLoaded(true)}}catch(e){if(alive.current&&epoch.current===current){setLoaded(false);setError((e as Error).message||'Allow device storage, then retry your collection.')}}};
  useEffect(()=>{alive.current=true;void refresh();return()=>{alive.current=false;++epoch.current;if(stageId.current)bridge.current.discard(stageId.current)}},[]);
  useEffect(()=>{clearPreview()},[plan,floorId]);
  useEffect(()=>{if(stage&&preview.activeId!==stage.id){stageId.current=undefined;setStage(undefined)}},[preview.activeId,stage]);
  const run=async(work:()=>Promise<void>)=>{if(running.current)return;running.current=true;setBusy(true);onBusyChange?.(true);setError('');setNotice('');try{await work()}catch(e){if(alive.current)setError((e as Error).message||'The item could not be saved.')}finally{running.current=false;if(alive.current)setBusy(false);onBusyChange?.(false)}};
  const proxyChoices=useMemo(()=>personalProxyCatalog.filter(c=>proxySearch.trim()?`${c.name} ${c.category}`.toLowerCase().includes(proxySearch.toLowerCase()):['sofa','armchair','side-table','desk','bed','dining-table'].includes(c.id)).slice(0,8),[proxySearch]);
  const beginEdit=(item?:PersonalCollectionItem)=>{clearPreview();setPhoto(undefined);setRemove(undefined);setRemovePhoto(false);setProxySearch('');setError('');const now=new Date().toISOString(),proxy=personalProxyCatalog.find(c=>c.id==='sofa')??personalProxyCatalog[0];setForm(item?structuredClone(item):{version:1,id:crypto.randomUUID(),name:'',catalogId:proxy.id,widthMm:proxy.widthMm,depthMm:proxy.depthMm,heightMm:proxy.heightMm,status:'keep',revision:0,createdAt:now,updatedAt:now});};
  const save=()=>run(async()=>{if(!form)return;const valid=parsePersonalCollectionItem(form);if(!personalProxyCatalog.some(c=>c.id===valid.catalogId))throw new Error('Choose an available catalog approximation.');await savePersonalItem(valid,photo);if(alive.current){setForm(undefined);setPhoto(undefined);setNotice('Saved in your private device collection. Existing placed copies stay unchanged.');await refresh();}});
  const stageItem=(item:PersonalCollectionItem,next:KitPosition)=>{if(preview.blocked||busy)return;setError('');try{const result=buildPersonalPlacement(plan,floorId,item,next);if(stageId.current)preview.discard(stageId.current);const id=preview.stage(result);stageId.current=id;setStage({id,warnings:result.warnings.map(w=>w.message)});setSelected(item);setPosition(next);setNotice('Preview only. Your exact dimensions are applied to an approximate visual model.');}catch(e){setError((e as Error).message)}};
  const choose=(item:PersonalCollectionItem)=>{try{stageItem(item,initialPersonalPosition(plan,floorId,item))}catch(e){setError((e as Error).message)}};
  const apply=()=>{if(!stage||preview.activeId!==stage.id||preview.blocked||busy)return;try{preview.apply(stage.id);stageId.current=undefined;setStage(undefined);setSelected(undefined);setPosition(undefined);setNotice('Item added. Undo removes this placement; your collection stays saved.')}catch(e){setError((e as Error).message)}};
  const nudge=plan.units==='imperial'?254:250,dimension=(mm:number)=>readableLength(mm,plan.units);
  const currentProxy=personalProxyCatalog.find(c=>c.id===form?.catalogId),shown=items.filter(i=>`${i.name} ${i.status}`.toLowerCase().includes(search.toLowerCase()));
  const close=()=>{if(busy)return;clearPreview();onClose()};
  const refreshPhotos=()=>run(async()=>{const photos=await listStoredPersonalPhotos();if(alive.current)setStoredPhotos(photos)});
  return <section className="personal-furniture" aria-label="My furniture and belongings" aria-busy={busy}>
    <header><div><span className="eyebrow">Make room for what is yours</span><h2>My furniture</h2></div><button type="button" disabled={busy} onClick={close} aria-label="Close my furniture">Close</button></header>
    <p>Plan around your own furniture with exact measurements and an <strong>approximate visual model</strong>.</p>
    <details className="personal-privacy"><summary>Private on this device · backup details</summary><p className="personal-note">Private to this browser, not your account. Placed names, measurements and notes travel with private project saves. Photo files stay on this device unless included in a complete backup. Public links omit photos and notes; item names remain visible.</p></details>
    {error&&<p role="alert" className="personal-warning">{error} {!loaded&&<button disabled={busy} onClick={()=>void refresh()}>Retry collection</button>}</p>}{notice&&<p role="status">{notice}</p>}
    {preview.blocked&&<p className="personal-warning">Finish or discard the other preview before placing a personal item.</p>}
    {form?<section className="personal-form" aria-label={form.revision?'Edit personal item':'New personal item'}>
      <h3>{form.revision?'Edit collection item':'Add something you own'}</h3>
      <label>Item name<input autoFocus maxLength={100} value={form.name} disabled={busy} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Grandma’s reading chair"/></label>
      <label>Find a visual approximation<input value={proxySearch} disabled={busy} onChange={e=>setProxySearch(e.target.value)} placeholder="Chair, desk, cabinet…"/></label>
      <div className="personal-proxy-choices" role="group" aria-label="Catalog approximation">{proxyChoices.map(c=><button key={c.id} disabled={busy} aria-pressed={form.catalogId===c.id} onClick={()=>setForm({...form,catalogId:c.id})}><img src={modelAssetPath(c.id,true)} alt="" loading="lazy"/><span>{c.name}</span></button>)}</div>{!proxyChoices.length&&<p>No matching models. Try a furniture type or another name.</p>}

      {currentProxy&&<div className="personal-proxy"><img src={modelAssetPath(currentProxy.id,true)} alt={`${currentProxy.name} visual approximation`} loading="lazy"/><span>Approximate shape only. Changing the model keeps the measurements you entered.</span></div>}
      <div className="personal-dimensions">{(['widthMm','depthMm','heightMm'] as const).map((key,index)=><LengthInput key={key} label={['Width','Depth','Height'][index]} value={form[key]} units={plan.units} min={1} disabled={busy} onChange={value=>setForm(current=>current&&({...current,[key]:value}))}/>)}</div>
      <p className="personal-note">Enter the outside dimensions yourself. Sizes are retained exactly; appearance, clearances and fit still need your review.</p>
      <div className="personal-actions" role="group" aria-label="Plan for this item">{(['keep','replace'] as const).map(status=><button key={status} disabled={busy} aria-pressed={form.status===status} onClick={()=>setForm({...form,status})}>{status==='keep'?'Keep':'Replace'}</button>)}</div>
      <label>Private notes<textarea maxLength={2000} rows={3} value={form.notes??''} disabled={busy} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Measured with the handles included…"/></label>
      <div className="personal-photo-row"><PersonalPhoto id={form.photoAssetId} preview={photo?.preview}/><div><label>Optional private photo<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void run(async()=>{const asset=await preparePersonalPhoto(file);if(alive.current){setPhoto(asset);setForm(current=>current&&({...current,photoAssetId:asset.id}));}})}}/></label><small>PNG, JPEG or WebP · up to 5 MB. Photos are never uploaded automatically.</small>{form.photoAssetId&&<div className="personal-actions"><button disabled={busy} onClick={()=>{setForm({...form,photoAssetId:undefined});setPhoto(undefined)}}>Remove from this item</button>{!photo&&<button disabled={busy} onClick={()=>setRemovePhoto(true)}>Delete stored photo…</button>}</div>}</div></div>
      {removePhoto&&form.photoAssetId&&<div className="personal-warning" role="alert"><p>Delete this photo from this device? Every saved copy using the same photo will show a missing-photo placeholder. Downloaded backups are unaffected.</p><button disabled={busy} onClick={()=>void run(async()=>{await removeStoredPersonalPhoto(form.photoAssetId!);if(alive.current){setForm(current=>current&&({...current,photoAssetId:undefined}));setRemovePhoto(false);setNotice('Stored photo deleted. Save the item to keep your edited details.')}})}>Delete photo from device</button><button disabled={busy} onClick={()=>setRemovePhoto(false)}>Keep stored photo</button></div>}
      <div className="personal-actions"><button className="primary" disabled={busy||!form.name.trim()} onClick={()=>void save()}>Save to my collection</button><button disabled={busy} onClick={()=>{setForm(undefined);setPhoto(undefined);setRemovePhoto(false)}}>Cancel edits</button></div>
    </section>:<>
      <div className="personal-actions"><button className="primary" disabled={busy||!loaded} onClick={()=>beginEdit()}>Add my item</button><button disabled={busy} onClick={()=>void refresh()}>Refresh collection</button></div>
      {selected&&position&&<section className="personal-preview" aria-label="Personal item placement"><h3>Preview: {selected.name}</h3><p>{dimension(selected.widthMm)} × {dimension(selected.depthMm)} × {dimension(selected.heightMm)} · Approximate visual</p><div className="personal-actions">{([{label:'Left',x:-nudge,z:0},{label:'Right',x:nudge,z:0},{label:'Back',x:0,z:-nudge},{label:'Forward',x:0,z:nudge}]).map(move=><button key={move.label} disabled={busy||preview.blocked} onClick={()=>stageItem(selected,{...position,x:position.x+move.x,z:position.z+move.z})}>{move.label}</button>)}<button disabled={busy||preview.blocked} onClick={()=>stageItem(selected,{...position,rotation:(position.rotation+45)%360})}>Turn 45°</button></div>{!!stage?.warnings.length&&<details><summary>Check the fit ({stage.warnings.length})</summary><ul>{stage.warnings.map((warning,index)=><li key={index}>{warning}</li>)}</ul></details>}<div className="personal-actions"><button className="primary" disabled={busy||preview.blocked||!stage||preview.activeId!==stage.id} onClick={apply}>Confirm placement</button><button disabled={busy} onClick={clearPreview}>Discard preview</button></div></section>}
      <label>Search my furniture<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Item name or keep / replace"/></label>
      {!loaded&&!error&&<p role="status">Opening your private collection…</p>}{loaded&&!items.length&&<p>Add your first chair, desk or keepsake. Your public catalog stays unchanged.</p>}
      <div className="personal-cards">{shown.map(item=><article key={item.id}><PersonalPhoto key={photoEpoch} id={item.photoAssetId}/><div><h3>{item.name}</h3><span className="personal-badge">Approximate visual · {item.status==='keep'?'Keep':'Replace'}</span><p>{dimension(item.widthMm)} × {dimension(item.depthMm)} × {dimension(item.heightMm)}</p><div className="personal-actions"><button disabled={busy||preview.blocked} onClick={()=>choose(item)}>Preview in room</button><button disabled={busy} onClick={()=>beginEdit(item)}>Edit details</button><button disabled={busy} onClick={()=>setRemove(item)}>Remove…</button></div>{remove?.id===item.id&&<div className="personal-warning"><p>Remove “{item.name}” from your collection? Placed copies and their photos stay saved.</p><button disabled={busy} onClick={()=>void run(async()=>{await deletePersonalItem(item.id,item.revision);if(alive.current){if(selected?.id===item.id)clearPreview();setRemove(undefined);await refresh();setNotice('Removed from your collection. Placed copies are unchanged.')}})}>Remove collection item</button><button disabled={busy} onClick={()=>setRemove(undefined)}>Keep item</button></div>}</div></article>)}</div>
      <details className="personal-storage"><summary>Manage private photo storage</summary><p>Collection removal keeps photos for placed copies and saved layout ideas. Back up your projects before deleting stored originals here.</p><button disabled={busy} onClick={()=>void refreshPhotos()}>{storedPhotos?'Refresh stored photos':'Show stored photos'}</button>{storedPhotos&&<><p>{storedPhotos.length} photos · {(storedPhotos.reduce((total,asset)=>total+asset.bytes,0)/1024/1024).toFixed(1)} of 64 MB</p><div className="personal-cards">{storedPhotos.map(asset=><article key={asset.id}><PersonalPhoto preview={asset.preview}/><div><p>{(asset.bytes/1024/1024).toFixed(2)} MB · private original and preview</p><button disabled={busy} onClick={()=>setDeletingAsset(asset.id)}>Delete stored photo…</button>{deletingAsset===asset.id&&<div className="personal-warning"><p>Delete this photo from this device? Every collection item and placed copy using it will show a missing-photo placeholder. Downloaded backups keep their copy.</p><button disabled={busy} onClick={()=>void run(async()=>{await removeStoredPersonalPhoto(asset.id);const photos=await listStoredPersonalPhotos();if(alive.current){setStoredPhotos(photos);setDeletingAsset(undefined);setPhotoEpoch(value=>value+1);setNotice('Photo removed from device storage. Item measurements and notes are unchanged.')}})}>Delete photo from device</button><button disabled={busy} onClick={()=>setDeletingAsset(undefined)}>Keep stored photo</button></div>}</div></article>)}</div></>}</details>
    </>}
  </section>;
}
