import {useEffect,useRef,useState,type PointerEvent} from 'react';
import type {ListingMedia} from './listingTypes';
import {blankPhotoRecipe,drawPhotoPrivacy,flattenPhotoPrivacy,MAX_PHOTO_MASKS,photoMaskBetween,photoOutputSize,photoSourceKey,photoSourcePoint,reviewedPhotoPrivacy,type PhotoPrivacy,type PhotoPrivacyRecipe,type PhotoRect} from './photoPrivacy';
import './photoPrivacy.css';

interface Props {media:ListingMedia;onSave(copy:PhotoPrivacy,source:string):boolean;onClose():void;onBusyChange?(busy:boolean):void}
export function PhotoPrivacyEditor({media,onSave,onClose,onBusyChange}:Props){
 const [recipe,setRecipe]=useState<PhotoPrivacyRecipe>(),[error,setError]=useState(''),[candidate,setCandidate]=useState(''),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[drag,setDrag]=useState<PhotoRect>();
 const canvas=useRef<HTMLCanvasElement>(null),source=useRef<HTMLImageElement|undefined>(undefined),start=useRef<{pointer:number;point:{x:number;y:number}}|undefined>(undefined),alive=useRef(true),generating=useRef(false);
 useEffect(()=>{alive.current=true;const image=new Image();let cancelled=false;try{const initial=blankPhotoRecipe(media.image),saved=media.privacy;setRecipe(saved&&saved.sourceKey===photoSourceKey(media.image)?saved.recipe:initial);image.onload=()=>{if(!cancelled){source.current=image;setRecipe(r=>r?{...r}:r);}};image.onerror=()=>{if(!cancelled)setError('This photo could not be opened.');};image.src=media.image;}catch(e){setError((e as Error).message);}return()=>{cancelled=true;alive.current=false;source.current=undefined;image.onload=image.onerror=null;image.src='';};},[media.image]);
 useEffect(()=>{if(canvas.current&&source.current&&recipe)try{drawPhotoPrivacy(canvas.current,source.current,drag?{...recipe,masks:[...recipe.masks,drag]}:recipe);}catch(e){setError((e as Error).message);}},[recipe,drag,candidate]);
 useEffect(()=>{onBusyChange?.(busy);return()=>onBusyChange?.(false);},[busy,onBusyChange]);
 function change(next:PhotoPrivacyRecipe){setRecipe(next);setCandidate('');setReviewed(false);setError('');}
 function point(event:PointerEvent<HTMLCanvasElement>){const box=event.currentTarget.getBoundingClientRect();return photoSourcePoint(recipe!,box.width?(event.clientX-box.left)/box.width:0,box.height?(event.clientY-box.top)/box.height:0);}
 function stop(event:PointerEvent<HTMLCanvasElement>,commit:boolean){if(!recipe||start.current?.pointer!==event.pointerId)return;const mask=photoMaskBetween(recipe,start.current.point,point(event));start.current=undefined;setDrag(undefined);if(commit)change({...recipe,masks:[...recipe.masks,mask]});if(event.currentTarget.hasPointerCapture?.(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);}
 function crop(key:keyof PhotoRect,value:number){if(!recipe||!Number.isSafeInteger(value))return;const next={...recipe.crop,[key]:value};if(next.x<0||next.y<0||next.width<1||next.height<1||next.x+next.width>recipe.width||next.y+next.height>recipe.height){setError('Keep the crop inside the source photo. Reduce width or height before moving its left or top edge.');return;}change({...recipe,crop:next});}
 async function preview(){if(!recipe||generating.current)return;generating.current=true;setBusy(true);setError('');try{const image=await flattenPhotoPrivacy(media.image,recipe);if(alive.current){setCandidate(image);setReviewed(false);}}catch(e){if(alive.current)setError((e as Error).message);}finally{generating.current=false;if(alive.current)setBusy(false);}}
 const size=recipe&&photoOutputSize(recipe);
 return <section className="photo-privacy-editor" aria-label="Photo privacy editor"><header><div><h3>Review photo privacy</h3><p>Cover faces, addresses and personal details with opaque black masks. Your private source stays unchanged.</p></div><button type="button" disabled={busy} onClick={onClose}>Cancel privacy edit</button></header>
  {error&&<p role="alert">{error}</p>}
  {recipe&&<><p className="listing-muted">Work on the local photo preview, up to 1,600 pixels per side. Crop and rotation keep masks aligned with the source. Nothing is shared here.</p>
   {candidate?<div className="photo-privacy-raster"><img src={candidate} alt="Flattened photo privacy copy to review"/><p>Inspect the full flattened copy. Manual masking cannot guarantee that every personal detail has been removed.</p></div>:<><p id="photo-privacy-draw">Drag over the image to add a mask, or use Add centered mask and edit its coordinates below.</p><canvas ref={canvas} aria-label="Photo mask drawing area" aria-describedby="photo-privacy-draw" width={size?.width} height={size?.height} onPointerDown={e=>{if(busy||recipe.masks.length>=MAX_PHOTO_MASKS||e.button!==0||start.current)return;e.preventDefault();e.currentTarget.setPointerCapture?.(e.pointerId);start.current={pointer:e.pointerId,point:point(e)};setDrag(photoMaskBetween(recipe,point(e),point(e)));}} onPointerMove={e=>{if(start.current?.pointer===e.pointerId)setDrag(photoMaskBetween(recipe,start.current.point,point(e)));}} onPointerUp={e=>stop(e,true)} onPointerCancel={e=>stop(e,false)} onLostPointerCapture={()=>{start.current=undefined;setDrag(undefined);}}/>
    <fieldset disabled={busy}><legend>Crop source photo · pixels</legend><div className="photo-privacy-fields">{(['x','y','width','height'] as const).map(key=><label key={key}>{({x:'Left',y:'Top',width:'Width',height:'Height'})[key]}<input type="number" min={key==='x'||key==='y'?0:1} max={key==='x'||key==='width'?recipe.width:recipe.height} step={1} value={recipe.crop[key]} onChange={e=>crop(key,e.target.valueAsNumber)}/></label>)}</div><div className="listing-row"><button type="button" onClick={()=>change({...recipe,crop:{x:0,y:0,width:recipe.width,height:recipe.height}})}>Reset crop</button><button type="button" onClick={()=>change({...recipe,turns:((recipe.turns+3)%4) as PhotoPrivacyRecipe['turns']})}>Rotate left 90°</button><button type="button" onClick={()=>change({...recipe,turns:((recipe.turns+1)%4) as PhotoPrivacyRecipe['turns']})}>Rotate right 90°</button></div></fieldset>
    <fieldset disabled={busy}><legend>Opaque masks · {recipe.masks.length}/{MAX_PHOTO_MASKS}</legend><div className="listing-row"><button type="button" disabled={recipe.masks.length>=MAX_PHOTO_MASKS} onClick={()=>{const c=recipe.crop;change({...recipe,masks:[...recipe.masks,photoMaskBetween(recipe,{x:c.x+c.width*.35,y:c.y+c.height*.35},{x:c.x+c.width*.65,y:c.y+c.height*.65})]});}}>Add centered mask</button><button type="button" disabled={!recipe.masks.length} onClick={()=>change({...recipe,masks:recipe.masks.slice(0,-1)})}>Undo last mask</button></div><div className="photo-privacy-masks">{recipe.masks.map((mask,index)=><div key={index} className="photo-privacy-mask"><strong>Mask {index+1}</strong><div className="photo-privacy-fields">{(['x','y','width','height'] as const).map(key=><label key={key}>{({x:'Left',y:'Top',width:'Width',height:'Height'})[key]}<input aria-label={`Mask ${index+1} ${key}`} type="number" min={key==='x'||key==='y'?0:1} value={mask[key]} onChange={e=>{const v=e.target.valueAsNumber,next={...mask,[key]:v};if(!Number.isSafeInteger(v)||next.x<0||next.y<0||next.width<1||next.height<1||next.x+next.width>recipe.width||next.y+next.height>recipe.height){setError('Keep every mask inside the source photo.');return;}change({...recipe,masks:recipe.masks.map((old,i)=>i===index?next:old)});}}/></label>)}</div><button type="button" aria-label={`Remove mask ${index+1}`} onClick={()=>change({...recipe,masks:recipe.masks.filter((_,i)=>i!==index)})}>Remove</button></div>)}</div></fieldset></>}
   <div className="photo-privacy-actions">{candidate?<><label><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I reviewed the flattened copy, including every mask after crop and rotation.</label><div className="listing-row"><button type="button" onClick={()=>{setCandidate('');setReviewed(false);}}>Back to masks</button><button type="button" className="primary" disabled={!reviewed||busy} onClick={()=>{try{if(onSave(reviewedPhotoPrivacy(media.image,recipe,candidate),media.image))onClose();}catch(e){setError((e as Error).message);}}}>Save reviewed copy</button></div></>:<button type="button" className="primary" disabled={busy||!source.current} onClick={()=>void preview()}>{busy?'Flattening copy…':'Preview flattened copy'}</button>}</div>
  </>}
 </section>;
}
