import {modelAssetPath} from './modelAssetPath';
import {useState} from 'react';
import {Check,MagnifyingGlass} from '@phosphor-icons/react';
import {usePlanner} from './store';
import {catalog} from './catalog';
import {plantingIds} from './planting';
import type {CatalogItem} from './types';
export function PlantingSettings({onPlace}:{onPlace?:(item:CatalogItem)=>void}={}){
 const s=usePlanner(),b=s.plantingBrush;
 const [search,setSearch]=useState(''),[single,setSingle]=useState(false);
 const plants=plantingIds.map(id=>catalog.find(c=>c.id===id)!).filter(c=>c.name.toLowerCase().includes(search.toLowerCase()));
 return <><div className="task-content planting-browser"><h2>Plant your garden</h2><div className="tool-search"><MagnifyingGlass/><input aria-label="Search plants" placeholder="Search plants…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="tool-visual-grid plant-choices">{plants.map(c=><button key={c.id} aria-label={`Plant: ${c.name}`} aria-pressed={b.catalogId===c.id} onClick={()=>{s.setPlantingBrush({...b,catalogId:c.id});if(single&&onPlace)onPlace(c);else s.setTool('planting')}}><img src={modelAssetPath(c.id,true)} alt=""/><strong>{c.name}</strong>{b.catalogId===c.id&&<Check className="choice-check" weight="bold"/>}</button>)}</div>{!plants.length&&<p role="status">No matching plants.</p>}<div className="brush-controls"><label><span>Radius <strong>{b.radius.toFixed(1)} m</strong></span><input disabled={single} aria-label="Planting brush radius" type="range" min="0.5" max="4" step="0.5" value={b.radius} onChange={e=>s.setPlantingBrush({...b,radius:+e.target.value})}/></label><label><span>Spacing <strong>{b.spacing.toFixed(1)} m</strong></span><input disabled={single} aria-label="Plant spacing" type="range" min="0.3" max="2" step="0.1" value={b.spacing} onChange={e=>s.setPlantingBrush({...b,spacing:+e.target.value})}/></label></div>{onPlace&&<div className="task-subtabs"><button aria-pressed={single} onClick={()=>{setSingle(true);s.setTool('select')}}>Single plant</button><button aria-pressed={!single} onClick={()=>{setSingle(false);s.setTool('planting')}}>Brush</button></div>}<p className="tool-hint">{single?'Choose a plant to place.': 'Drag outside your home to preview.'}</p></div><footer className="tool-footer">{s.plantingDraft?<><p role="status">{s.plantingDraft.items.length} plants ready</p><div className="tool-footer-actions"><button onClick={()=>s.cancelPlanting()}>Cancel stroke</button><button className="primary" disabled={!s.plantingDraft.items.length} onClick={()=>s.confirmPlanting()}>Confirm planting</button></div></>:single?<button className="primary" onClick={()=>onPlace?.(catalog.find(c=>c.id===b.catalogId)!)}>Place selected plant</button>:<button className={s.tool==='planting'?'':'primary'} onClick={()=>s.setTool(s.tool==='planting'?'select':'planting')}>{s.tool==='planting'?'Done planting':'Paint plants'}</button>}</footer></>;
}
