import {useEffect,useRef,useState} from 'react';
import {validatePlan} from './planValidation';
import type {ListingDocument} from './listingTypes';
import type {MoodboardPlan} from './moodboards';
import type {SurveyPlan} from './siteSurvey';
import {defaultPresentation,loadBrandTemplates,saveBrandTemplate,removeBrandTemplate,updatePresentationSettings,type BrandTemplate,type PresentationPlan,type PresentationSettings} from './presentationTypes';
import {buildPresentationPack,downloadPresentationPack,printPresentation,type PresentationResult} from './presentationPack';
import './presentation.css';
type PackPlan=PresentationPlan&MoodboardPlan&SurveyPlan;
export interface PresentationPanelProps {plan:PackPlan;listing?:ListingDocument;disabled?:boolean;onCommit(base:PackPlan,next:PackPlan):void;onClose?():void}
export function PresentationPanel({plan,listing,disabled=false,onCommit,onClose}:PresentationPanelProps){
  const [base,setBase]=useState(plan),[settings,setSettings]=useState(()=>structuredClone(plan.presentation??defaultPresentation())),[templates,setTemplates]=useState<BrandTemplate[]>([]),[templateName,setTemplateName]=useState(''),[prepared,setPrepared]=useState<PresentationResult>(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  const current=useRef({plan,listing,settings}),reviewed=useRef<{plan:PackPlan;listing?:ListingDocument;settings:PresentationSettings}|undefined>(undefined),run=useRef<AbortController|undefined>(undefined),pending=useRef<string|undefined>(undefined),mounted=useRef(true);current.current={plan,listing,settings};
  useEffect(()=>{mounted.current=true;try{setTemplates(loadBrandTemplates());}catch{setError('Saved brand templates could not be read. You can still prepare this presentation.');}return()=>{mounted.current=false;run.current?.abort();};},[]);
  useEffect(()=>{run.current?.abort();setBusy(false);setPrepared(undefined);if(pending.current&&base!==plan){const expected=pending.current;pending.current=undefined;if(JSON.stringify(plan.presentation)===expected){setBase(plan);setMessage('Presentation choices saved.');}}},[plan,listing,settings,base]);
  const patch=(value:Partial<PresentationSettings>)=>{setSettings(s=>({...s,...value}));setMessage('');};
  const toggle=(key:'floorIds'|'layoutIds'|'listingMediaIds'|'boardIds'|'surveyNoteIds',id:string)=>patch({[key]:settings[key].includes(id)?settings[key].filter(v=>v!==id):[...settings[key],id]});
  const attempt=(action:()=>void)=>{setError('');try{action();}catch(e){setError((e as Error).message);}};
  const preview=async()=>{run.current?.abort();const controller=new AbortController();run.current=controller;const snapshot=current.current;setBusy(true);setError('');setPrepared(undefined);try{const result=await buildPresentationPack(snapshot.plan,snapshot.listing,snapshot.settings,{signal:controller.signal});if(!mounted.current||controller.signal.aborted||current.current.plan!==snapshot.plan||current.current.listing!==snapshot.listing||current.current.settings!==snapshot.settings)return;reviewed.current=snapshot;setPrepared(result);}catch(e){if(!controller.signal.aborted&&mounted.current)setError((e as Error).message);}finally{if(run.current===controller&&mounted.current)setBusy(false);}};
  const checkedExport=(action:(result:PresentationResult)=>void)=>attempt(()=>{const previous=reviewed.current;if(!prepared||!previous||previous.plan!==plan||previous.listing!==listing||previous.settings!==settings)throw new Error('This preview is out of date. Prepare it again before exporting.');action(prepared);});
  const missing=(key:'floorIds'|'layoutIds'|'listingMediaIds'|'boardIds'|'surveyNoteIds',existing:string[])=>settings[key].filter(id=>!existing.includes(id)).map(id=><div className="pack-missing" key={id}>A saved choice is unavailable. <button onClick={()=>toggle(key,id)}>Remove unavailable choice</button></div>);
  const cards=(label:string,key:'floorIds'|'layoutIds'|'listingMediaIds'|'boardIds'|'surveyNoteIds',values:{id:string;name:string;image?:string}[])=> <fieldset><legend>{label}</legend><div className="pack-choices">{values.map(v=><button key={v.id} aria-pressed={settings[key].includes(v.id)} onClick={()=>toggle(key,v.id)}>{v.image&&<img src={v.image} alt=""/>}{v.name}</button>)}</div>{!values.length&&<small>None available yet.</small>}{missing(key,values.map(v=>v.id))}</fieldset>;
  return <section className="presentation-panel" aria-labelledby="pack-title"><header><div><span className="eyebrow">Prepare a client handoff</span><h2 id="pack-title">Presentation pack</h2></div>{onClose&&<button onClick={onClose}>Close</button>}</header>
    <div className="pack-fields"><label>Presentation title<input maxLength={160} value={settings.title} onChange={e=>patch({title:e.target.value})}/></label><label>Subtitle<input maxLength={500} value={settings.subtitle} onChange={e=>patch({subtitle:e.target.value})}/></label></div><label>Revision notes<textarea maxLength={1800} value={settings.revisionSummary} onChange={e=>patch({revisionSummary:e.target.value})} placeholder="What changed and what the client should review"/></label>
    <div className="pack-toggles" role="group" aria-label="Branding"><button aria-pressed={!settings.branded} onClick={()=>patch({branded:false})}>Unbranded</button><button aria-pressed={settings.branded} onClick={()=>patch({branded:true})}>Branded</button></div>{!settings.branded&&<small>Dedicated branding is omitted. Review names, logos and addresses inside your own text and images.</small>}
    <details><summary>Reusable brand template</summary><div className="pack-fields">{(['name','organization','contact'] as const).map(key=><label key={key}>{key==='name'?'Your name':key==='organization'?'Studio / brokerage':'Contact details'}<input value={settings.brand[key]} maxLength={key==='contact'?300:160} onChange={e=>patch({brand:{...settings.brand,[key]:e.target.value}})}/></label>)}<label>Accent color<input type="color" value={settings.brand.accent} onChange={e=>patch({brand:{...settings.brand,accent:e.target.value}})}/></label></div><div className="pack-choices">{templates.map(t=><article key={t.id}><strong>{t.name}</strong><button onClick={()=>patch({brand:structuredClone(t.brand)})}>Use template</button><button onClick={()=>attempt(()=>setTemplates(removeBrandTemplate(t.id)))}>Remove template</button></article>)}</div><label>Save a new template<input value={templateName} maxLength={60} onChange={e=>setTemplateName(e.target.value)} placeholder="For example, Warm studio"/></label><button onClick={()=>attempt(()=>{setTemplates(saveBrandTemplate({version:1,id:crypto.randomUUID(),name:templateName,brand:settings.brand}));setTemplateName('');setMessage('Brand template saved on this device.');})}>Save template on this device</button></details>
    {cards('Floors','floorIds',plan.floors.map(f=>({id:f.id,name:f.name})))}<div className="pack-toggles"><button aria-pressed={settings.currentLayout} onClick={()=>patch({currentLayout:!settings.currentLayout})}>Current layout</button><button aria-pressed={settings.includeAreas} onClick={()=>patch({includeAreas:!settings.includeAreas})}>Area classifications</button><button aria-pressed={settings.includeSchedule} onClick={()=>patch({includeSchedule:!settings.includeSchedule})}>Room selections</button></div>
    {settings.includeSchedule&&<div className="pack-toggles"><button aria-pressed={settings.includePrices} onClick={()=>patch({includePrices:!settings.includePrices})}>Include manual prices</button><button aria-pressed={settings.includeProductSources} onClick={()=>patch({includeProductSources:!settings.includeProductSources})}>Include product sources</button></div>}
    {cards('Compare saved layouts','layoutIds',(plan.layoutAlternatives?.options??[]).map(o=>({id:o.id,name:o.name})))}
    {cards('Listing photos and captured views','listingMediaIds',(listing?.media??[]).map(m=>({id:m.id,name:m.title||'Untitled view',image:m.image})))}{!listing&&<small>Open Listing Studio to load its saved images, then return here.</small>}
    {cards('Inspiration boards','boardIds',(plan.moodboards?.boards??[]).map(b=>({id:b.id,name:b.name})))}{settings.boardIds.length>0&&<button aria-pressed={settings.includeBoardImages} onClick={()=>patch({includeBoardImages:!settings.includeBoardImages})}>Include selected boards’ private images</button>}
    {cards('Private site notes','surveyNoteIds',(plan.siteSurvey?.notes??[]).map(n=>({id:n.id,name:n.title})))}{settings.surveyNoteIds.length>0&&<button aria-pressed={settings.includeSurveyPhotos} onClick={()=>patch({includeSurveyPhotos:!settings.includeSurveyPhotos})}>Include selected notes’ private photos</button>}
    {base!==plan&&<p role="status">The project changed. Reload saved choices before saving. You can preview the current selection against the current project.</p>}<div className="pack-actions"><button disabled={disabled||base!==plan||busy} onClick={()=>attempt(()=>{const next=updatePresentationSettings(base,plan,settings,validatePlan);pending.current=JSON.stringify(next.presentation);try{onCommit(base,next);}catch(e){pending.current=undefined;throw e;}})}>Save presentation choices</button><button onClick={()=>{pending.current=undefined;setBase(plan);setSettings(structuredClone(plan.presentation??defaultPresentation()));}}>Reload saved choices</button><button disabled={busy} onClick={()=>void preview()}>{busy?'Preparing preview…':'Preview presentation'}</button></div>
    {prepared&&<section><h3>{prepared.pageCount} pages ready to review</h3>{prepared.warnings.map(w=><p className="pack-missing" key={w}>{w}</p>)}{!!prepared.assets.length&&<details open><summary>Exact images included in this export</summary><div className="pack-choices">{prepared.assets.map((a,i)=><figure key={i}>{a.image?<img src={a.image} alt={a.label}/>:<p>Image unavailable</p>}<figcaption>{a.label}<small>{a.source}</small></figcaption></figure>)}</div></details>}<iframe title="Presentation preview" sandbox="" srcDoc={prepared.html}/><div className="pack-actions"><button onClick={()=>checkedExport(downloadPresentationPack)}>Download reviewed ZIP</button><button onClick={()=>checkedExport(printPresentation)}>Print / Save PDF</button></div><small>ZIP contains printable HTML, selected schedules and a source manifest. Nothing is uploaded. Check print pagination and the diagram reference bar.</small></section>}
    {error&&<p role="alert">{error}</p>}<p role="status" aria-live="polite">{message}</p>
  </section>;
}
