import type {PlanDocumentV1} from './types';
import {allowedKeys,surveyIdentity,surveyText} from './siteSurveySchema';
export interface PresentationBrand {name:string;organization:string;contact:string;accent:string}
export interface BrandTemplate {version:1;id:string;name:string;brand:PresentationBrand}
export interface PresentationSettings {version:1;title:string;subtitle:string;revisionSummary:string;branded:boolean;brand:PresentationBrand;currentLayout:boolean;floorIds:string[];layoutIds:string[];listingMediaIds:string[];boardIds:string[];surveyNoteIds:string[];includeBoardImages:boolean;includeSurveyPhotos:boolean;includeAreas:boolean;includeSchedule:boolean;includePrices:boolean;includeProductSources:boolean}
export type PresentationPlan=PlanDocumentV1&{presentation?:PresentationSettings};
const object=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v);
export const blankBrand=():PresentationBrand=>({name:'',organization:'',contact:'',accent:'#426653'});
export function defaultPresentation():PresentationSettings{return {version:1,title:'Home design presentation',subtitle:'',revisionSummary:'',branded:false,brand:blankBrand(),currentLayout:true,floorIds:[],layoutIds:[],listingMediaIds:[],boardIds:[],surveyNoteIds:[],includeBoardImages:false,includeSurveyPhotos:false,includeAreas:true,includeSchedule:false,includePrices:false,includeProductSources:false};}
export function parsePresentationBrand(v:unknown):PresentationBrand {if(!object(v)||typeof v.accent!=='string'||!/^#[a-f\d]{6}$/i.test(v.accent))throw new Error('Choose a valid presentation color.');allowedKeys(v,['name','organization','contact','accent']);return {name:surveyText(v.name,120,true),organization:surveyText(v.organization,160,true),contact:surveyText(v.contact,300,true),accent:v.accent.toLowerCase()};}
export function parsePresentationSettings(v:unknown):PresentationSettings {
  if(!object(v)||v.version!==1)throw new Error('Invalid presentation settings.');allowedKeys(v,['version','title','subtitle','revisionSummary','branded','brand','currentLayout','floorIds','layoutIds','listingMediaIds','boardIds','surveyNoteIds','includeBoardImages','includeSurveyPhotos','includeAreas','includeSchedule','includePrices','includeProductSources']);
  const result={version:1,title:surveyText(v.title,160),subtitle:surveyText(v.subtitle,500,true),revisionSummary:surveyText(v.revisionSummary,1800,true),brand:parsePresentationBrand(v.brand)} as PresentationSettings;
  for(const key of ['branded','currentLayout','includeBoardImages','includeSurveyPhotos','includeAreas','includeSchedule','includePrices','includeProductSources'] as const){if(typeof v[key]!=='boolean')throw new Error('Invalid presentation choice.');result[key]=v[key];}
  for(const [key,max] of [['floorIds',20],['layoutIds',6],['listingMediaIds',24],['boardIds',8],['surveyNoteIds',30]] as const){const ids=v[key];if(!Array.isArray(ids)||ids.length>max)throw new Error('Too many selected presentation pages.');result[key]=ids.map(surveyIdentity);if(new Set(result[key]).size!==ids.length)throw new Error('Duplicate presentation selection.');}
  if(new TextEncoder().encode(JSON.stringify(result)).byteLength>30_000)throw new Error('Presentation settings are too large.');return result;
}
export function updatePresentationSettings(base:PresentationPlan,current:PresentationPlan,value:unknown,validate:(p:unknown)=>void):PresentationPlan {if(base!==current)throw new Error('The project changed. Reload presentation choices before saving.');const next={...base,presentation:parsePresentationSettings(value)};validate(next);if(new TextEncoder().encode(JSON.stringify(next)).byteLength>8_000_000)throw new Error('This project exceeds the 8 MB save limit.');return next;}
export function parseBrandTemplate(v:unknown):BrandTemplate {if(!object(v)||v.version!==1)throw new Error('Invalid brand template.');allowedKeys(v,['version','id','name','brand']);return {version:1,id:surveyIdentity(v.id),name:surveyText(v.name,60),brand:parsePresentationBrand(v.brand)};}
const key='nook.presentation-brands.v1';
export function loadBrandTemplates(storage:Pick<Storage,'getItem'>=localStorage):BrandTemplate[]{const raw=storage.getItem(key);if(!raw)return [];if(raw.length>30_000)throw new Error('Saved brand templates are too large.');const value:unknown=JSON.parse(raw);if(!Array.isArray(value)||value.length>8)throw new Error('Invalid saved brand templates.');const templates=value.map(parseBrandTemplate);if(new Set(templates.map(t=>t.id)).size!==templates.length)throw new Error('Duplicate brand templates.');return templates;}
/** Explicit device-local preference write. Never part of plan autosave or an account profile. */
export function saveBrandTemplate(template:BrandTemplate,storage:Pick<Storage,'getItem'|'setItem'>=localStorage):BrandTemplate[]{const checked=parseBrandTemplate(template),current=loadBrandTemplates(storage),next=[...current.filter(t=>t.id!==checked.id),checked];if(next.length>8)throw new Error('Keep up to eight reusable brand templates.');storage.setItem(key,JSON.stringify(next));return next;}
export function removeBrandTemplate(id:string,storage:Pick<Storage,'getItem'|'setItem'>=localStorage):BrandTemplate[]{const next=loadBrandTemplates(storage).filter(t=>t.id!==id);storage.setItem(key,JSON.stringify(next));return next;}
