import {strToU8,zipSync} from 'fflate';
import {catalog} from './catalog';
import {comparisonBounds} from './LayoutComparison';
import {floorBoundaryWalls,floorRects} from './floorGeometry';
import {formatLength} from './domain';
import {captureLayout,layoutDifference,type LayoutSnapshot} from './layoutAlternatives';
import {isListingImage,mediaLabels,parseListing,type ListingDocument} from './listingTypes';
import {buildSelectionSchedule,formatMoney,selectionTotals,type SelectionRow} from './selectionSchedule';
import {parseMoodboards,type MoodboardPlan} from './moodboards';
import {loadPersonalPhoto} from './personalStorage';
import {verifyPersonalPhotoAsset,type PersonalPhotoAsset} from './personalMedia';
import {parsePresentationSettings,type PresentationPlan,type PresentationSettings} from './presentationTypes';
import {parseSiteSurvey,siteAreaBreakdown,siteNoteStatus,stableFingerprint,type SurveyPlan} from './siteSurvey';
import type {PlanDocumentV1} from './types';
import {validatePlan} from './planValidation';

export interface PresentationResult {html:string;files:Record<string,Uint8Array>;pageCount:number;revision:string;warnings:string[];assets:{label:string;image?:string;source:string}[]}
type PackPlan=PresentationPlan&SurveyPlan&MoodboardPlan;
export const MAX_PRESENTATION_BYTES=40*1024*1024,MAX_PRESENTATION_PAGES=80;
export const presentationEscape=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const e=presentationEscape;
const csv=(v:unknown)=>{let s=String(v??'');if(/^[\s\u0000-\u001f]*[=+\-@]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};
const chunks=<T,>(values:T[],size:number)=>Array.from({length:Math.ceil(values.length/size)},(_,i)=>values.slice(i*size,(i+1)*size));
const fmt=(n:number)=>Number(n.toFixed(3));
const shortened=(value:string,max=120)=>e(value.length>max?value.slice(0,max)+'… (full text in CSV)':value);
const names=new Map(catalog.map(c=>[c.id,c.name]));
function diagram(layout:LayoutSnapshot,floorId:string,viewBox:string,units:PlanDocumentV1['units']):string {
  const floor=layout.floors.find(f=>f.id===floorId);if(!floor)return '<p class="missing">This floor is absent from this layout.</p>';
  const [left,top,width,height]=viewBox.split(' ').map(Number),scale=Math.max(25,...[25,50,100,200,500,1000].filter(s=>width/s<180&&height/s<160).slice(0,1)),bar=width>=1500?1000:100,barZ=top+height-70;
  const floors=floorRects(floor,layout.gridSizeMm).map(r=>`<polygon points="${(r.polygon??[{x:r.x,z:r.z},{x:r.x+r.width,z:r.z},{x:r.x+r.width,z:r.z+r.depth},{x:r.x,z:r.z+r.depth}]).map(p=>`${fmt(p.x)},${fmt(p.z)}`).join(' ')}"/>`).join('');
  const walls=[...floorBoundaryWalls(floor,layout.gridSizeMm),...floor.walls].map(w=>`<line x1="${fmt(w.ax*layout.gridSizeMm)}" y1="${fmt(w.az*layout.gridSizeMm)}" x2="${fmt(w.bx*layout.gridSizeMm)}" y2="${fmt(w.bz*layout.gridSizeMm)}"/>`).join('');
  const pieces=layout.furniture.filter(p=>p.floorId===floorId).map(p=>`<rect x="${fmt(p.x-p.widthMm/2)}" y="${fmt(p.z-p.depthMm/2)}" width="${p.widthMm}" height="${p.depthMm}" transform="rotate(${-p.rotation} ${p.x} ${p.z})"/>`).join('');
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${fmt(width/scale)}mm" height="${fmt(height/scale)}mm" viewBox="${e(viewBox)}" role="img" aria-label="${e(floor.name)} top view"><g fill="#f2f1ea" stroke="none">${floors}</g><g stroke="#33483d" stroke-width="35">${walls}</g><g fill="#bbd1bd" fill-opacity=".75" stroke="#4e6e55" stroke-width="12">${pieces}</g><g stroke="#243b30" stroke-width="12"><line x1="${left+70}" y1="${barZ}" x2="${left+70+bar}" y2="${barZ}" data-scale-bar-mm="${bar}"/></g><text x="${left+70}" y="${barZ-25}" font-size="${Math.max(50,width/65)}">${e(formatLength(bar,units))} reference</text></svg><small>Model footprints · intended 1:${scale} before page fitting · dimensions shown in ${units==='metric'?'metric units':'feet/inches'}. Check the reference bar; paper fitting may change scale. Opening symbols and small details are omitted.</small>`;
}
function scheduleRows(rows:SelectionRow[],settings:PresentationSettings):string {return `<table><thead><tr><th>Room / item</th><th>Size</th><th>Selection</th>${settings.includePrices?'<th>Manual price</th>':''}${settings.includeProductSources?'<th>Source</th>':''}</tr></thead><tbody>${rows.map(r=>`<tr><td>${e(r.floorName)} · ${e(r.room.name)}<strong>${shortened(r.name)}</strong><small>${e(r.catalogName)}${r.room.warning?' · '+e(r.room.warning):''}</small></td><td>${r.dimensions.widthMm} × ${r.dimensions.depthMm} × ${r.dimensions.heightMm} mm</td><td>${e(r.specification.status)} · ${e(r.specification.match)}<small>${r.specification.purchase.quantity} ${e(r.specification.purchase.unit)}</small></td>${settings.includePrices?`<td>${r.netMinor===null?'Unknown':e(formatMoney(r.netMinor,r.specification.currency!))}<small>Checked ${e(r.specification.checkedOn??'unknown')}</small></td>`:''}${settings.includeProductSources?`<td>${shortened(r.specification.vendor??'Unspecified',60)}<small>${shortened(r.specification.productUrl??'',80)}</small></td>`:''}</tr>`).join('')}</tbody></table>`;}
/** Snapshot inputs before any async private-asset load. Callers must discard this result if their base changed. */
export async function buildPresentationPack(input:PackPlan,listingInput:ListingDocument|undefined,choices:PresentationSettings,options:{loadPhoto?:(id:string)=>Promise<PersonalPhotoAsset|undefined>;signal?:AbortSignal;generatedAt?:string}={}):Promise<PresentationResult> {
  const settings=parsePresentationSettings(choices);if(new TextEncoder().encode(JSON.stringify(input)).byteLength>8_000_000)throw new Error('This project exceeds the 8 MB presentation source limit.');
  const plan=structuredClone(input),date=options.generatedAt??new Date().toISOString();validatePlan(plan);if(!Number.isFinite(Date.parse(date)))throw new Error('Invalid presentation date.');
  if(plan.siteSurvey)plan.siteSurvey=parseSiteSurvey(plan.siteSurvey);if(plan.moodboards)plan.moodboards=parseMoodboards(plan.moodboards);
  if(listingInput&&listingInput.planId!==plan.id)throw new Error('The selected listing belongs to another project.');
  // Deliberately exclude every raw original/source and all dedicated listing agent fields.
  const listing=listingInput?parseListing({...listingInput,details:{title:'',address:'',price:'',beds:'',baths:'',area:'',highlights:'',description:'',agentName:'',agentEmail:'',agentPhone:'',agency:''},media:listingInput.media.filter(m=>settings.listingMediaIds.includes(m.id)).map(({id,title,caption,kind,image,camera,floorId,seconds})=>({id,title,caption,kind,image,camera,floorId,seconds}))}):undefined;
  const revision=`${plan.updatedAt} / ${stableFingerprint([plan.gridSizeMm,plan.floors,plan.furniture,plan.siteSurvey,settings.floorIds])}`,warnings:string[]=[],assets:PresentationResult['assets']=[],pages:Array<{title:string;body:string;sourceRevision?:string}>=[],files:Record<string,Uint8Array>={};let mediaBytes=0;
  const cancelled=()=>{if(options.signal?.aborted)throw new DOMException('Presentation preview cancelled.','AbortError');};
  const addImage=(label:string,image:string,source:string)=>{if(!isListingImage(image,3*1024*1024))throw new Error('A chosen image is invalid. Remove it from this pack and choose a readable photo.');mediaBytes+=image.length;if(mediaBytes>24*1024*1024)throw new Error('Chosen previews exceed 24 MB. Select fewer images.');assets.push({label,image,source});return `<figure><img alt="${e(label)}" src="${image}"/><figcaption>${e(label)}<small>${e(source)}</small></figcaption></figure>`;};
  const assetCache=new Map<string,string|undefined>();
  const privateImage=async(id:string,label:string,source:string)=>{cancelled();if(!assetCache.has(id)){try{const asset=await (options.loadPhoto??loadPersonalPhoto)(id);cancelled();if(asset){const checked=await verifyPersonalPhotoAsset(asset);cancelled();if(checked.id!==id)throw new Error('Photo identity mismatch.');assetCache.set(id,checked.preview);}else assetCache.set(id,undefined);}catch(error){if(options.signal?.aborted)throw error;assetCache.set(id,undefined);}}
    const image=assetCache.get(id);if(image)return addImage(label,image,source);warnings.push(`${label}: private photo is missing or unreadable. Restore its private media backup or remove the photo from the pack.`);assets.push({label,source});return `<p class="missing">${e(label)} — photo unavailable. Restore its private media backup or leave this placeholder.</p>`;
  };
  const floorIds=settings.floorIds;for(const id of floorIds)if(!plan.floors.some(f=>f.id===id))warnings.push('A selected floor no longer exists; it was not replaced with another floor.');
  pages.push({title:settings.title,body:`<p class="subtitle">${e(settings.subtitle)}</p>${settings.revisionSummary?`<h2>Revision notes</h2><p>${e(settings.revisionSummary)}</p>`:''}<p>Prepared ${e(date)} · ${plan.units==='metric'?'Metric':'Imperial'} display units</p><p>Design proposal and author-supplied information. Dimensions and classifications need site review; this pack is not a certified survey or legal living-area statement.</p>${!settings.branded?'<p class="review">Dedicated branding is omitted. Review free text and images for names, logos, addresses or other identifying content.</p>':''}`});
  const current=captureLayout(plan),optionsById=new Map((plan.layoutAlternatives?.options??[]).map(o=>[o.id,o]));
  for(const floorId of floorIds){const floor=plan.floors.find(f=>f.id===floorId);if(!floor)continue;if(settings.currentLayout)pages.push({title:`Current layout · ${floor.name}`,body:diagram(current,floorId,comparisonBounds([current],floorId),plan.units)});
    for(const id of settings.layoutIds){const alternative=optionsById.get(id);if(!alternative)continue;const viewBox=comparisonBounds([current,alternative.snapshot],floorId),diff=layoutDifference(current,alternative.snapshot);pages.push({title:`${alternative.name} · ${floor.name}`,sourceRevision:`Saved option ${alternative.createdAt} / ${stableFingerprint(alternative.snapshot)}`,body:`<p>Same model frame as the current layout. Saved option: ${e(alternative.createdAt)}.</p><div class="comparison"><div><h3>Current</h3>${diagram(current,floorId,viewBox,plan.units)}</div><div><h3>${e(alternative.name)}</h3>${diagram(alternative.snapshot,floorId,viewBox,plan.units)}</div></div><p>Compared with current: ${diff.added} added, ${diff.removed} removed, ${diff.changed} changed items; ${diff.floorsChanged} changed floors. Counts cover the whole saved option.</p>`});}}
  for(const id of settings.layoutIds)if(!optionsById.has(id))warnings.push('A selected layout idea is unavailable; it was not substituted.');
  for(const id of settings.listingMediaIds){const media=listing?.media.find(m=>m.id===id);if(!media){warnings.push('A selected listing photo/view is unavailable. Reopen Listing Studio or remove it from the presentation.');continue;}const source=`${mediaLabels[media.kind]} · ${media.camera?'Saved 3D viewpoint; capture-time design revision is unavailable, so the image may show an earlier layout':'Image supplied by the author; capture date and authenticity not independently verified'}`;pages.push({title:media.title||'Property view',body:addImage(media.title||'Property view',media.image,source)+`<p>${e(media.caption)}</p><small>Caption is author-supplied. ${media.kind==='photo'?'Confirm that the photo represents the existing property.':'Design/staged imagery illustrates a possibility and is not a photograph of the existing property.'} Image revision: ${stableFingerprint(media.image)}. No uploaded original is included.</small>`});}
  const boards=plan.moodboards?.boards??[];for(const id of settings.boardIds){const board=boards.find(b=>b.id===id);if(!board){warnings.push('A selected inspiration board is unavailable; it was not substituted.');continue;}const pins:string[]=[];for(const pin of board.pins){cancelled();if(pin.kind==='image')pins.push(settings.includeBoardImages?await privateImage(pin.assetId,pin.label,`Inspiration image · ${pin.attribution??'Author-supplied source'}`):`<p>${e(pin.label)} — private image omitted.</p>`);else if(pin.kind==='note')for(const part of chunks([...pin.text],500))pins.push(`<article><h3>${e(pin.label)}</h3><p>${e(part.join(''))}</p></article>`);else if(pin.kind==='catalog')pins.push(`<article><h3>${e(pin.label)}</h3><p>${e(names.get(pin.catalogId)??'Catalog item unavailable')} · visual catalog reference</p></article>`);else pins.push(`<article><h3>${e(pin.label)}</h3><p>${e(pin.finishKind)} finish · ${e(pin.finishId)}</p></article>`);}
    for(const [index,part] of (chunks(pins,4).length?chunks(pins,4):[[]]).entries())pages.push({title:`${board.name}${index?' · continued':''}`,sourceRevision:`Board ${board.updatedAt} / ${stableFingerprint(board)}`,body:`<div class="swatches">${board.palette.map(c=>`<span><i style="background:${c.color}"></i>${e(c.name)} ${e(c.color)}</span>`).join('')}</div><div class="board">${part.join('')}</div>`});}
  if(settings.includeAreas){const areas=siteAreaBreakdown(plan).filter(a=>floorIds.includes(a.floorId));for(const part of chunks(areas,22))pages.push({title:'Area classification',body:`<p>Categories are author choices, not legal living-area classifications. Unclassified and outside areas are never silently included.</p><table><thead><tr><th>Floor / space</th><th>Category</th><th>Area m²</th><th>Review</th></tr></thead><tbody>${part.map(a=>`<tr><td>${e(a.floorName)} · ${e(a.name)}</td><td>${e(a.classification)}</td><td>${a.areaM2===null?'Unavailable':fmt(a.areaM2)}</td><td>${e(a.warning??'')}${e(a.basis)}</td></tr>`).join('')}</tbody></table>`});
    const summary=['included','excluded','outdoor','unclassified'].map(category=>{const rows=areas.filter(a=>a.classification===category);return {category,areaM2:rows.some(r=>r.areaM2===null)?null:rows.reduce((s,r)=>s+r.areaM2!,0)};});if(areas.length)pages.push({title:'Area totals',body:`<p>Chosen floor footprint unions, including wall footprints and before stair-void deductions.</p><ul>${summary.map(s=>`<li>${e(s.category)}: ${s.areaM2===null?'Unavailable':fmt(s.areaM2)+' m²'}</li>`).join('')}</ul><p>These categories reconcile to the authored footprint; included does not mean certified interior living area.</p>`});
    files['area-classification.csv']=strToU8('\ufeff'+[['Revision','Floor','Space','Classification','Area m2','Basis','Review'],...areas.map(a=>[revision,a.floorName,a.name,a.classification,a.areaM2??'Unavailable',a.basis,a.warning??''])].map(r=>r.map(csv).join(',')).join('\r\n'));}
  if(settings.includeSchedule){const schedule=buildSelectionSchedule(plan,date),rows=schedule.rows.filter(r=>floorIds.includes(r.floorId));if(rows.length>300)throw new Error('Choose fewer floors: a presentation holds up to 300 scheduled items. Export the full schedule separately.');
    for(const part of chunks(rows,6))pages.push({title:'Room selections',sourceRevision:schedule.revision,body:scheduleRows(part,settings)});
    if(settings.includePrices&&rows.length){const totals=selectionTotals(rows);pages.push({title:'Selection totals',sourceRevision:schedule.revision,body:`<p>Manual prices; currencies remain separate. Known non-owned amounts exclude owned items. Tax, delivery, installation and availability are not included.</p><ul>${totals.map(t=>`<li>${e(t.currency??'Currency unknown')}: ${t.currency?e(formatMoney(t.knownMinor,t.currency)):'Unknown'} known; ${t.unknown} missing non-owned prices. Owned separately: ${t.currency?e(formatMoney(t.ownedKnownMinor,t.currency)):'Unknown'} known; ${t.ownedUnknown} missing.</li>`).join('')}</ul>`});}
    files['selections.csv']=strToU8('\ufeff'+[['Revision','Floor','Room','Item','Width mm','Depth mm','Height mm','Status','Match',...(settings.includePrices?['Currency','Line minor units','Price checked']:[]),...(settings.includeProductSources?['Vendor','Product URL']:[])],...rows.map(r=>[schedule.revision,r.floorName,r.room.name,r.name,r.dimensions.widthMm,r.dimensions.depthMm,r.dimensions.heightMm,r.specification.status,r.specification.match,...(settings.includePrices?[r.specification.currency??'Unknown',r.netMinor??'Unknown',r.specification.checkedOn??'Unknown']:[]),...(settings.includeProductSources?[r.specification.vendor??'',r.specification.productUrl??'']:[])])].map(r=>r.map(csv).join(',')).join('\r\n'));}
  for(const id of settings.surveyNoteIds){const note=plan.siteSurvey?.notes.find(n=>n.id===id);if(!note){warnings.push('A chosen site note no longer exists; it was not replaced.');continue;}const status=siteNoteStatus(plan,note),pictures:string[]=[];if(settings.includeSurveyPhotos)for(const assetId of note.photoAssetIds)pictures.push(await privateImage(assetId,note.title,'Private site-note image explicitly included by author; photo authenticity is not verified.'));
    pages.push({title:`Site note · ${note.title}`,body:`<p class="review">${e(status.message)}</p><p>${e(note.text)}</p>${!settings.includeSurveyPhotos&&note.photoAssetIds.length?'<p>Private survey photos omitted.</p>':''}`});
    for(const c of note.checks){const checkStatus=siteNoteStatus(plan,{...note,checks:[c]});pages.push({title:`Measurement record · ${note.title}`,sourceRevision:`${c.recordedAt} / ${c.modelFingerprint}`,body:`<h3>${e(c.checkedOn)} · ${e(c.source)} · ${e(c.reviewer)}</h3><p>Self-reported evidence. Measured: ${e(Object.entries(c.measured).map(([k,v])=>`${k.replace('Mm','')}: ${v} mm`).join(', '))}</p><p>Then-current model: ${e(Object.entries(c.model).map(([k,v])=>`${k.replace('Mm','')}: ${fmt(v!)} mm`).join(', '))}</p><p>${e(c.question)}</p><p class="review">${e(checkStatus.message)}</p>`});}
    if(pictures.length)pages.push({title:`Site photos · ${note.title}`,body:`<div class="board">${pictures.join('')}</div>`});}
  cancelled();for(const part of chunks([...new Set(warnings)],4))pages.push({title:'Items to review',body:part.map(w=>`<p class="review">${e(w)}</p>`).join('')});if(pages.length>MAX_PRESENTATION_PAGES)throw new Error('This presentation exceeds 80 pages. Choose fewer views, boards or layouts.');
  const uniqueWarnings=[...new Set(warnings)],brand=settings.branded?settings.brand:{...settings.brand,name:'',organization:'',contact:''};
  const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="referrer" content="no-referrer"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>${e(settings.title)}</title><style>:root{font-family:Arial,sans-serif;color:#23372e;--accent:${brand.accent}}*{box-sizing:border-box}body{background:#e8ebe4;margin:0}.page{overflow-wrap:anywhere;width:210mm;max-width:100%;min-height:275mm;margin:12px auto;padding:16mm;background:white;break-after:page;position:relative;border-top:5px solid var(--accent)}h1{font:30px Georgia,serif}h2{font-size:18px}h3{font-size:14px}p{white-space:pre-line;line-height:1.5}strong,small{display:block}small,footer{font-size:10px;color:#506257;line-height:1.5}header{font-size:12px;color:var(--accent)}footer{border-top:1px solid #bccabb;margin-top:20px;padding-top:8px;overflow-wrap:anywhere}figure{margin:10px 0;break-inside:avoid}img{max-width:100%;max-height:120mm;object-fit:contain}table{border-collapse:collapse;width:100%;font-size:10px;overflow-wrap:anywhere}td,th{padding:7px;border-bottom:1px solid #ced8cc;text-align:left;vertical-align:top}thead{display:table-header-group}tr,article{break-inside:avoid}.comparison,.board{display:grid;grid-template-columns:1fr 1fr;gap:12px}.comparison svg{max-width:100%;height:auto}.board{font-size:12px}.board p{line-height:1.4}.board img{max-height:45mm}.swatches{display:flex;gap:12px;flex-wrap:wrap}.swatches i{display:inline-block;width:20px;height:20px;vertical-align:middle;margin-right:5px}.review,.missing{background:#f7ecd2;padding:12px}.subtitle{font-size:18px}.brand{white-space:pre-line}@page{size:A4;margin:0}@media print{body{background:white}.page{margin:0;box-shadow:none;max-width:none}.page:last-child{break-after:auto}}</style></head><body>${pages.map((p,index)=>`<section class="page">${settings.branded?`<header class="brand">${[brand.name,brand.organization,brand.contact].filter(Boolean).map(e).join(' · ')}</header>`:''}<h1>${e(p.title)}</h1>${p.body}<footer>Design revision: ${e(revision)}${p.sourceRevision?`<br>Included source: ${e(p.sourceRevision)}`:''}<br>Prepared ${e(date)} · Page ${index+1}/${pages.length} · ${plan.units==='metric'?'Metric':'Imperial'} display; schedule dimensions in mm, areas in m²</footer></section>`).join('')}</body></html>`;
  files['presentation.html']=strToU8(html);files['manifest.json']=strToU8(JSON.stringify({version:1,title:settings.title,preparedAt:date,revision,units:plan.units,pageCount:pages.length,...(settings.branded?{brand}:{}),pages:pages.map(p=>({title:p.title,revision:p.sourceRevision??revision})),media:assets.map(a=>({label:a.label,source:a.source,available:!!a.image})),warnings:uniqueWarnings},null,2));
  if(Object.values(files).reduce((n,f)=>n+f.byteLength,0)>MAX_PRESENTATION_BYTES)throw new Error('The presentation exceeds 40 MB. Choose fewer images.');return {html,files,pageCount:pages.length,revision,warnings:uniqueWarnings,assets};
}
export function downloadPresentationPack(result:PresentationResult):void {const bytes=zipSync(result.files,{level:6}),url=URL.createObjectURL(new Blob([bytes as BlobPart],{type:'application/zip'})),a=document.createElement('a');a.href=url;a.download='home-presentation.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function printPresentation(result:PresentationResult):void {const page=window.open('about:blank','_blank');if(!page)throw new Error('Allow the printable window or download the presentation instead.');page.opener=null;page.document.open();page.document.write(result.html);page.document.close();page.focus();void Promise.all([...page.document.images].map(image=>image.decode().catch(()=>{}))).then(()=>{if(!page.closed)page.print();});}
