import {parseRemixSnapshot,remixId,remixTags,REMIX_LIMITS,type RemixSnapshot} from './remixSnapshot';
import {parseRemixThumbnail,type RemixThumbnail} from './remixThumbnail';
export interface RemixShare {id:string;projectId:string;revision:number;accessVersion:number;expiresAt:number;revoked:boolean;createdAt:number}
export interface IdeaSubmission {id:string;shareId:string;revision:number;state:'pending'|'approved'|'rejected'|'withdrawn'|'removed';stateVersion:number;createdAt:number;updatedAt:number;moderationNote?:string}
export interface IdeaCard {id:string;revision:number;title:string;creator:string;description:string;kind:'kit'|'room';allowCopy:boolean;tags:string[];thumbnail:RemixThumbnail;createdAt:number}
export interface RemixView {id:string;revision:number;snapshot:RemixSnapshot}
const id=(v:string)=>{if(!remixId(v))throw Error('Invalid arrangement identifier.');return encodeURIComponent(v);};
async function call(path:string,{method='GET',body,token,signal,publicRead=false}:{method?:string;body?:unknown;token?:string;signal?:AbortSignal;publicRead?:boolean}={}){const response=await fetch('/api/'+path,{method,credentials:token||publicRead?'omit':'same-origin',cache:'no-store',redirect:'error',referrerPolicy:'no-referrer',signal,headers:{...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{})});const reader=response.body?.getReader();if(!reader)throw Error('Sharing is unavailable.');let size=0;const chunks:Uint8Array[]=[];try{for(;;){const {value,done}=await reader.read();if(done)break;size+=value.byteLength;if(size>1_000_000)throw Error('This sharing response is too large.');chunks.push(value);}}finally{await reader.cancel().catch(()=>{});reader.releaseLock();}const bytes=new Uint8Array(size);let offset=0;for(const c of chunks){bytes.set(c,offset);offset+=c.length;}let value:any;try{value=JSON.parse(new TextDecoder().decode(bytes));}catch{throw Error('The sharing service returned invalid data.');}if(!response.ok)throw Error(typeof value?.error==='string'&&value.error.length<=500?value.error:'Sharing is temporarily unavailable.');if(!value||typeof value!=='object')throw Error('Invalid sharing response.');return value;}
function share(v:any):RemixShare{if(!v||!remixId(v.id)||!remixId(v.projectId)||!Number.isSafeInteger(v.revision)||v.revision<1||v.revision>10||!Number.isSafeInteger(v.accessVersion)||v.accessVersion<1||![v.expiresAt,v.createdAt].every(Number.isFinite)||typeof v.revoked!=='boolean')throw Error('Invalid share response.');return v;}
function submission(v:any):IdeaSubmission{if(!v||!remixId(v.id)||!remixId(v.shareId)||!Number.isSafeInteger(v.revision)||v.revision<1||!Number.isSafeInteger(v.stateVersion)||v.stateVersion<1||!['pending','approved','rejected','withdrawn','removed'].includes(v.state)||![v.createdAt,v.updatedAt].every(Number.isFinite)||v.moderationNote!==undefined&&(typeof v.moderationNote!=='string'||v.moderationNote.length>400))throw Error('Invalid submission response.');return v;}
function card(v:any):IdeaCard{if(!v||!remixId(v.id)||!Number.isSafeInteger(v.revision)||v.revision<1||typeof v.title!=='string'||v.title.length>80||typeof v.creator!=='string'||v.creator.length>60||typeof v.description!=='string'||v.description.length>400||!['kit','room'].includes(v.kind)||typeof v.allowCopy!=='boolean'||!Array.isArray(v.tags)||v.tags.length>4||v.tags.some((t:any)=>!remixTags.includes(t))||!Number.isFinite(v.createdAt))throw Error('Invalid gallery card.');return {...v,thumbnail:parseRemixThumbnail(v.thumbnail)};}
function page(v:any){if(!Array.isArray(v.items)||v.items.length>REMIX_LIMITS.page||v.nextCursor!==null&&(typeof v.nextCursor!=='string'||!/^\d{1,16}_[a-zA-Z0-9-]{1,100}$/.test(v.nextCursor)))throw Error('Invalid gallery page.');return {items:v.items.map(card),nextCursor:v.nextCursor as string|null};}
function view(v:any):RemixView{if(!remixId(v.id)||!Number.isSafeInteger(v.revision)||v.revision<1)throw Error('Invalid snapshot identity.');return {id:v.id,revision:v.revision,snapshot:parseRemixSnapshot(v.snapshot)};}
export async function remixAvailability(signal?:AbortSignal){const v=await call('remix/status',{signal});if(['available','signedIn','moderationConfigured','isCurator'].some(k=>typeof v[k]!=='boolean'))throw Error('Invalid sharing status.');return v as {available:boolean;signedIn:boolean;moderationConfigured:boolean;isCurator:boolean};}
export async function createRemixShare(projectId:string,snapshot:RemixSnapshot,expiryHours:number,rightsConfirmed:boolean,previous?:RemixShare,signal?:AbortSignal){const v=await call('remix'+(previous?'/'+id(previous.id)+'/revisions':''),{method:'POST',body:{projectId,snapshot:parseRemixSnapshot(snapshot),expiryHours,rightsConfirmed,...(previous?{expectedRevision:previous.revision,expectedAccessVersion:previous.accessVersion}:{})},signal});if(!/^[A-Za-zA-Z0-9_-]{43}$/.test(v.token))throw Error('Invalid private link.');return {share:share(v.share),token:v.token as string};}
export async function listRemixShares(projectId:string,signal?:AbortSignal){const v=await call('remix?projectId='+id(projectId),{signal});if(!Array.isArray(v.shares)||v.shares.length>40)throw Error('Invalid share list.');return v.shares.map(share);}
export async function ownedRemixShare(shareId:string,signal?:AbortSignal){const v=await call('remix/'+id(shareId),{signal});if(!Array.isArray(v.submissions)||v.submissions.length>10)throw Error('Invalid submissions.');return {share:share(v.share),snapshot:parseRemixSnapshot(v.snapshot),submissions:v.submissions.map(submission)};}
export async function revokeRemixShare(value:RemixShare,signal?:AbortSignal){return call('remix/'+id(value.id)+'/access',{method:'POST',body:{expectedVersion:value.accessVersion,action:'revoke'},signal});}
export async function deleteRemixShare(value:RemixShare,signal?:AbortSignal){return call('remix/'+id(value.id),{method:'DELETE',body:{expectedVersion:value.accessVersion},signal});}
export async function readRemixShare(shareId:string,revision:number,token:string,signal?:AbortSignal){return view(await call('remix/'+id(shareId)+'/view?revision='+revision,{token,signal}));}
export async function submitIdea(value:RemixShare,publicConfirmed:boolean,rightsConfirmed:boolean,signal?:AbortSignal){const v=await call('ideas/submit',{method:'POST',body:{shareId:value.id,revision:value.revision,publicConfirmed,rightsConfirmed},signal});return submission(v.submission);}
export async function ideasPage(q='',tag='',cursor?:string,signal?:AbortSignal){return page(await call('ideas?'+new URLSearchParams({q,tag,...(cursor?{cursor}:{})}),{signal,publicRead:true}));}
export async function readIdea(ideaId:string,signal?:AbortSignal){return view(await call('ideas/'+id(ideaId),{signal,publicRead:true}));}
export async function myIdeas(signal?:AbortSignal){const v=await call('ideas/mine',{signal});if(!Array.isArray(v.submissions)||v.submissions.length>40)throw Error('Invalid submission list.');return v.submissions.map(submission);}
export async function withdrawIdea(value:IdeaSubmission,signal?:AbortSignal){return call('ideas/'+id(value.id)+'/withdraw',{method:'POST',body:{expectedVersion:value.stateVersion},signal});}
export async function reportIdea(ideaId:string,input:{requestId:string;reason:string;note:string},signal?:AbortSignal){return call('ideas/'+id(ideaId)+'/report',{method:'POST',body:input,signal});}
export async function moderationPage(cursor?:string,signal?:AbortSignal){const v=await call('ideas/moderation'+(cursor?'?cursor='+encodeURIComponent(cursor):''),{signal}),p=page(v);return {...p,items:v.items.map((v:any)=>({...card(v),...submission(v)})) as Array<IdeaCard&IdeaSubmission>};}
export async function inspectIdea(ideaId:string,signal?:AbortSignal){const v=await call('ideas/'+id(ideaId)+'/inspect',{signal});return {submission:submission(v.submission),snapshot:parseRemixSnapshot(v.snapshot)};}
export async function moderateIdea(value:IdeaSubmission,decision:'approve'|'reject'|'remove',note:string,signal?:AbortSignal){return call('ideas/'+id(value.id)+'/moderate',{method:'POST',body:{expectedVersion:value.stateVersion,revision:value.revision,decision,note},signal});}
export interface IdeaReport {id:string;ideaId:string;reason:string;note:string;createdAt:number}
export async function ideaReports(signal?:AbortSignal):Promise<IdeaReport[]>{const v=await call('ideas/reports',{signal});if(!Array.isArray(v.reports)||v.reports.length>50||v.reports.some((r:any)=>!remixId(r.id)||!remixId(r.ideaId)||typeof r.note!=='string'||r.note.length>500||!['privacy','rights','unsafe','spam','other'].includes(r.reason)||!Number.isFinite(r.createdAt)))throw Error('Invalid report queue.');return v.reports;}
export async function resolveIdeaReport(reportId:string,signal?:AbortSignal){return call('ideas/reports/'+id(reportId),{method:'POST',body:{resolved:true},signal});}
export function remixLink(origin:string,value:RemixShare,token:string){if(!/^[A-Za-z0-9_-]{43}$/.test(token))throw Error('Invalid private link.');const u=new URL(origin);u.pathname='/';u.search='';u.hash=new URLSearchParams({remix:value.id,revision:String(value.revision),key:token}).toString();return u.href;}
export function remixLocation(hash:string):{kind:'share';id:string;revision:number;token:string}|{kind:'gallery';id:string}|{kind:'builtin';id:string}|null{const p=new URLSearchParams(hash.replace(/^#/,''));if(p.has('idea')){const value=p.get('idea');if(!remixId(value))throw Error('Invalid idea link.');return value.startsWith('original-')?{kind:'builtin',id:value.slice(9)}:{kind:'gallery',id:value};}if(!p.has('remix'))return null;const value=p.get('remix'),token=p.get('key'),revision=Number(p.get('revision'));if(!remixId(value)||!token||!/^[A-Za-z0-9_-]{43}$/.test(token)||!Number.isSafeInteger(revision)||revision<1||revision>10)throw Error('This arrangement link is incomplete.');return {kind:'share',id:value,revision,token};}

