/** Public provenance only. Never store account identities, bearer keys or arbitrary URLs here. */
export interface RemixCredit {source:'builtin'|'share'|'gallery'|'file';id:string;revision:number;title:string;creator:string;permission:'remix-with-credit-v1'}
export interface RemixAttribution {version:1;credits:RemixCredit[]}
const object=(v:unknown):v is Record<string,any>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const exact=(v:unknown,keys:string[])=>{if(!object(v)||Object.keys(v).some(k=>!keys.includes(k)))throw new Error('This attribution contains unsupported data.');return v;};
const text=(v:unknown,max:number)=>{if(typeof v!=='string'||!v.trim()||v.length>max||/[\u0000-\u001f\u007f<>]/.test(v))throw Error('Use short plain creator credit text.');return v.trim();};
export function parseRemixAttribution(value:unknown):RemixAttribution{const v=exact(value,['version','credits']);if(v.version!==1||!Array.isArray(v.credits)||v.credits.length>8)throw new Error('This attribution chain is too long or invalid.');const keys=new Set<string>();return {version:1,credits:v.credits.map(c=>{exact(c,['source','id','revision','title','creator','permission']);if(!['builtin','share','gallery','file'].includes(c.source)||typeof c.id!=='string'||!/^[a-zA-Z0-9_-]{1,100}$/.test(c.id)||!Number.isSafeInteger(c.revision)||c.revision<1||c.revision>1000||c.permission!=='remix-with-credit-v1'||keys.has(c.source+':'+c.id+':'+c.revision))throw new Error('This attribution entry is invalid.');keys.add(c.source+':'+c.id+':'+c.revision);return {source:c.source,id:c.id,revision:c.revision,title:text(c.title,80),creator:text(c.creator,60),permission:c.permission};})};}
export function remixCreditPath(credit:RemixCredit){parseRemixAttribution({version:1,credits:[credit]});return credit.source==='gallery'?'/?#idea='+encodeURIComponent(credit.id):credit.source==='builtin'?'/?#idea=original-'+encodeURIComponent(credit.id):undefined;}
export function mergeRemixAttributions(...values:Array<RemixAttribution|undefined>):RemixAttribution|undefined{const credits:RemixCredit[]=[];for(const value of values){if(!value)continue;for(const credit of parseRemixAttribution(value).credits){const old=credits.find(c=>c.source===credit.source&&c.id===credit.id&&c.revision===credit.revision);if(old){if(JSON.stringify(old)!==JSON.stringify(credit))throw Error('Conflicting creator credits for the same source.');}else credits.push(credit);}}return credits.length?parseRemixAttribution({version:1,credits}):undefined;}
/** Compose with the app's visual privacy sanitizer; this helper handles only the public credit field. */
export function withRemixAttribution<T extends object>(visual:T,source:{remixAttribution?:unknown}):T&{remixAttribution?:RemixAttribution}{return {...visual,...(source.remixAttribution===undefined?{}:{remixAttribution:parseRemixAttribution(source.remixAttribution)})};}
