import {useEffect,useRef,useState} from 'react';
import {readIdea,readRemixShare,remixLocation,reportIdea,type RemixView} from './remixApi';
import {exportRemixSnapshot,originalRemixExamples,remixCopySeed,type RemixPlan,type RemixCredit} from './remixSnapshot';
import {RemixPreview} from './RemixPreview';
import './remix-gallery.css';
type Location=NonNullable<ReturnType<typeof remixLocation>>;
/** Dedicated link route. Parent must not mount the editor/store/WebMCP alongside it. */
export function RemixViewer({location:value,onCreatePrivateCopy,onExit}:{location:Location;onCreatePrivateCopy:(seed:RemixPlan)=>Promise<void>;onExit:()=>void}){const [view,setView]=useState<RemixView>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[consent,setConsent]=useState(false),[reportReason,setReportReason]=useState('privacy'),[reportNote,setReportNote]=useState(''),[reportId,setReportId]=useState(()=>crypto.randomUUID()),[notice,setNotice]=useState('');const alive=useRef(true),latest=useRef(value),abort=useRef<AbortController|undefined>(undefined);latest.current=value;
 async function load(signal:AbortSignal){if(value.kind==='share')return readRemixShare(value.id,value.revision,value.token,signal);if(value.kind==='gallery')return readIdea(value.id,signal);const original=originalRemixExamples().find(r=>r.id===value.id);if(!original)throw Error('This original idea was not found.');return {id:original.id,revision:1,snapshot:original.snapshot};}
 useEffect(()=>{alive.current=true;abort.current?.abort();abort.current=new AbortController();setView(undefined);setConsent(false);setReportNote('');setReportId(crypto.randomUUID());setNotice('');setError('');setBusy(true);void load(abort.current.signal).then(v=>{if(alive.current&&latest.current===value)setView(v);}).catch(e=>{if(alive.current&&latest.current===value)setError(e.message);}).finally(()=>{if(alive.current&&latest.current===value)setBusy(false);});return()=>{alive.current=false;abort.current?.abort();};},[value]);
 const source=(v:RemixView):Pick<RemixCredit,'source'|'id'|'revision'>=>({source:value.kind==='share'?'share':value.kind==='gallery'?'gallery':'builtin',id:v.id,revision:v.revision});
 async function copy(exportOnly=false){if(!view||busy||!view.snapshot.allowCopy||!exportOnly&&!consent)return;setBusy(true);setError('');abort.current=new AbortController();try{const fresh=await load(abort.current.signal);if(!alive.current||latest.current!==value)return;if(fresh.revision!==view.revision)throw Error('The arrangement changed. Open its new preview first.');const seed=remixCopySeed(fresh.snapshot,source(fresh));if(exportOnly)exportRemixSnapshot(fresh.snapshot,source(fresh));else await onCreatePrivateCopy(seed);}catch(e){if(alive.current&&latest.current===value)setError((e as Error).message);}finally{if(alive.current&&latest.current===value)setBusy(false);}}
 async function report(){if(value.kind!=='gallery'||busy)return;setBusy(true);setError('');abort.current=new AbortController();try{await reportIdea(value.id,{requestId:reportId,reason:reportReason,note:reportNote},abort.current.signal);if(alive.current&&latest.current===value)setNotice('Report received for curator review. This does not automatically remove the idea.');}catch(e){if(alive.current&&latest.current===value)setError((e as Error).message);}finally{if(alive.current&&latest.current===value)setBusy(false);}}
 return <main className="remix-viewer"><header><p className="remix-eyebrow">Nook & Nest · shared arrangement</p><h1>Preview first. Make it yours.</h1><p>This view is read-only. It does not open the creator’s project library or change your home.</p></header>{error&&<p role="alert" className="remix-error">{error}</p>}{notice&&<p role="status">{notice}</p>}{busy&&!view&&<p role="status">Opening this arrangement…</p>}{view&&<><RemixPreview snapshot={view.snapshot}/><fieldset disabled={busy}><legend>Independent private copy</legend><label className="remix-check"><input type="checkbox" checked={consent} disabled={!view.snapshot.allowCopy} onChange={e=>setConsent(e.target.checked)}/>Create a new local project with its creator credits</label><button disabled={!view.snapshot.allowCopy||!consent} onClick={()=>void copy()}>Make my own private copy</button><button disabled={!view.snapshot.allowCopy} onClick={()=>void copy(true)}>Export permitted room package</button><p>The owner may disable future access. Copies already downloaded remain independent.</p></fieldset>{value.kind==='gallery'&&<details><summary>Report this idea</summary><fieldset disabled={busy}><legend>Curator report</legend><p>Reporting requires sign-in through Project. Your account identity is not public.</p><label>Reason<select value={reportReason} onChange={e=>{setReportReason(e.target.value);setReportId(crypto.randomUUID());}}>{['privacy','rights','unsafe','spam','other'].map(reason=><option key={reason}>{reason}</option>)}</select></label><label>Explanation<textarea maxLength={500} value={reportNote} onChange={e=>{setReportNote(e.target.value);setReportId(crypto.randomUUID());}}/></label><button onClick={()=>void report()}>Submit report</button></fieldset></details>}</>}<button disabled={busy} onClick={onExit}>Back to Nook & Nest</button></main>;
}

