import { useEffect, useMemo, useRef, useState } from 'react';
import { ChoiceButtons } from './ChoiceButtons';
import { LengthInput } from './LengthInput';
import { validatePlan } from './planValidation';
import type { KitPreviewBridge } from './FurnitureKitsPanel';
import { initialSeasonalLook, seasonalPreview, seasonalScope, seasonalSpeciesNames, type SeasonalLook, type SeasonalPalette, type SeasonalPlan } from './seasonalLook';
import './living-play.css';
export function SeasonalLookPanel({ plan, activeFloorId, preview, onClose }: { plan: SeasonalPlan; activeFloorId: string; preview: KitPreviewBridge; onClose(): void }) {
  const [look, setLook] = useState(() => initialSeasonalLook(plan, activeFloorId)), [original, setOriginal] = useState(!plan.environment?.seasonalLook), [error, setError] = useState('');
  const [stage, setStage] = useState<{ id: string; base: SeasonalPlan; key: string }>(), stagedId = useRef<string | undefined>(undefined), bridge = useRef(preview); bridge.current = preview;
  const key = JSON.stringify([original, look]), scope = useMemo(() => seasonalScope(plan, look), [plan, look]);
  const discard = () => { if (stagedId.current) bridge.current.discard(stagedId.current); stagedId.current = undefined; setStage(undefined); };
  useEffect(() => () => { if (stagedId.current) bridge.current.discard(stagedId.current); }, []);
  useEffect(() => { discard(); setLook(initialSeasonalLook(plan, activeFloorId)); setOriginal(!plan.environment?.seasonalLook); }, [plan.id, activeFloorId]);
  useEffect(() => { if (stage && (stage.base !== plan || stage.key !== key || stage.id !== preview.activeId)) discard(); }, [plan, key, stage, preview.activeId]);
  const patch = (region: Partial<SeasonalLook['region']>) => { discard(); setLook(v => ({ ...v, region: { ...v.region, ...region } })); };
  const fresh = !!stage && stage.base === plan && stage.key === key && stage.id === preview.activeId;
  return <section className="seasonal-panel" aria-labelledby="seasonal-heading"><header><div><span className="eyebrow">A different garden mood</span><h2 id="seasonal-heading">Seasonal colors</h2></div><button type="button" onClick={() => { discard(); onClose(); }}>Close</button></header><p>Preview cosmetic colors on reviewed leaves and petals inside a region. This keeps every plant’s species, position, size and identity. Winter is a muted palette, not growth, climate or bare-branch simulation.</p>
    <ChoiceButtons<SeasonalPalette | 'original'> label="Garden palette" value={original ? 'original' : look.palette} options={[{ value: 'original', label: 'Original' }, { value: 'spring', label: 'Spring' }, { value: 'summer', label: 'Summer' }, { value: 'autumn', label: 'Autumn' }, { value: 'winter', label: 'Winter' }]} onChange={value => { discard(); setOriginal(value === 'original'); if (value !== 'original') setLook(v => ({ ...v, palette: value })); }}/>
    {!original && <div className="lp-card"><strong>Selected region · plant centers</strong><div className="lp-fields"><LengthInput label="Region X" value={look.region.x} units={plan.units} min={-100000} onChange={x => patch({ x })}/><LengthInput label="Region Z" value={look.region.z} units={plan.units} min={-100000} onChange={z => patch({ z })}/><LengthInput label="Region width" value={look.region.width} units={plan.units} min={100} onChange={width => patch({ width })}/><LengthInput label="Region depth" value={look.region.depth} units={plan.units} min={100} onChange={depth => patch({ depth })}/></div><p>{scope.supported.length} reviewed placed plants · {scope.unsupported.length} other plants keep their original materials.</p>{scope.fieldPlants > 0 && <p className="lp-notice">Dense field-brush plants retain their authored appearance. Their existing render budgets and saved seeds are unchanged.</p>}<p className="lp-muted">Reviewed species: {seasonalSpeciesNames.join(', ')}. Bark, pots and unreviewed material roles stay untouched. A bounded material cache may leave additional unique finishes unchanged.</p></div>}
    {original && <p className="lp-card">Original restores the exact authored or custom material colors beneath the seasonal view.</p>}{error && <p role="alert" className="lp-notice">{error}</p>}{preview.blocked && <p className="lp-notice">Finish the active placement or preview first.</p>}
    <footer className="lp-actions"><button type="button" onClick={discard}>Discard preview</button><button type="button" disabled={preview.blocked} onClick={() => { try { discard(); const id = preview.stage(seasonalPreview(plan, plan, activeFloorId, original ? undefined : look, validatePlan)); stagedId.current = id; setStage({ id, base: plan, key }); setError(''); } catch (e) { setError((e as Error).message); } }}>Preview colors</button><button type="button" disabled={!fresh || preview.blocked} onClick={() => { try { if (!fresh) return; preview.apply(stage!.id); stagedId.current = undefined; setStage(undefined); onClose(); } catch (e) { setError((e as Error).message); } }}>Apply colors</button></footer>
  </section>;
}
