import {ChoiceButtons} from './ChoiceButtons';
import {isFurnitureLocked} from './furnitureGroups';
import {useMemo,useState} from 'react';
import {validatePlan} from './planValidation';
import {SelectionBudgetPanel} from './SelectionBudgetPanel';
import {buildSelectionSchedule,defaultSpecification,specificationFor,downloadSelectionSchedule,formatMoney,moneyInput,parseMoneyInput,printSelectionSchedule,updatePlacementSpecification,type CurrencyTotal,type PlacementSpecification,type SelectionPlan} from './selectionSchedule';
import './selection-schedule.css';

export interface SelectionSchedulePanelProps {plan:SelectionPlan;activeFloorId?:string;disabled?:boolean;onCommit(base:SelectionPlan,next:SelectionPlan):void;onClose?():void}
type Edit={base:SelectionPlan;id:string;spec:PlacementSpecification;price:string;discount:string};
function Totals({totals}:{totals:CurrencyTotal[]}){return <ul className="selection-totals">{totals.map(total=><li key={total.currency??'unknown'}><strong>{total.currency?formatMoney(total.knownMinor,total.currency):'Currency not set'}</strong><span>{total.unknown?`Known subtotal · ${total.unknown} missing prices`:'Non-owned selections'}</span>{(total.ownedKnownMinor>0||total.ownedUnknown>0)&&<small>Owned separately: {total.currency?formatMoney(total.ownedKnownMinor,total.currency):'currency not set'} · {total.ownedUnknown} missing prices</small>}</li>)}</ul>;}
export function SelectionSchedulePanel({plan,activeFloorId,disabled=false,onCommit,onClose}:SelectionSchedulePanelProps){
  const schedule=useMemo(()=>buildSelectionSchedule(plan),[plan]);
  const [floorId,setFloorId]=useState(activeFloorId??''),[search,setSearch]=useState(''),[edit,setEdit]=useState<Edit>(),[error,setError]=useState(''),[message,setMessage]=useState('');
  const rows=schedule.rows.filter(row=>(!floorId||row.floorId===floorId)&&`${row.name} ${row.catalogName} ${row.room.name} ${row.specification.vendor??''}`.toLowerCase().includes(search.toLowerCase()));
  const attempt=(action:()=>void)=>{setError('');try{action();}catch(e){setError(e instanceof Error?e.message:'The selection could not be saved.');}};
  const start=(id:string)=>{const item=plan.furniture.find(p=>p.id===id);if(!item)return;const spec=structuredClone(specificationFor(item));setEdit({base:plan,id,spec,price:moneyInput(spec.unitPriceMinor,spec.currency),discount:spec.discount.kind==='percent'?String(spec.discount.value/100):spec.discount.kind==='fixed'?moneyInput(spec.discount.value,spec.currency):'0'});setError('');setMessage('');};
  const patch=(changes:Partial<PlacementSpecification>)=>setEdit(current=>current?{...current,spec:{...current.spec,...changes}}:current);
  const save=()=>attempt(()=>{
    if(!edit||disabled)return;
    const currency=edit.spec.currency,unitPriceMinor=edit.price.trim()?parseMoneyInput(edit.price,currency??''):null;
    let discountValue=0;
    if(edit.spec.discount.kind==='percent'){if(!/^\d+(?:\.\d{1,2})?$/.test(edit.discount))throw new Error('Use a percentage between 0 and 100, with up to two decimal places.');discountValue=Math.round(Number(edit.discount)*100);}
    else if(edit.spec.discount.kind==='fixed')discountValue=parseMoneyInput(edit.discount,currency??'')??0;
    const next=updatePlacementSpecification(edit.base,plan,edit.id,{...edit.spec,unitPriceMinor,discount:{kind:edit.spec.discount.kind,value:discountValue}},validatePlan);onCommit(edit.base,next);setEdit(undefined);setMessage('Selection saved. Undo restores the previous specification.');
  });
  return <section className="selection-schedule" aria-labelledby="selection-schedule-heading"><header><div><span className="eyebrow">Plan what to keep and buy</span><h2 id="selection-schedule-heading">Selections &amp; budget</h2></div>{onClose&&<button onClick={onClose}>Close</button>}</header>
    <p>Enter your own product links and prices. Currencies stay separate; missing prices remain unknown. Owned items are shown separately. Tax, delivery, installation and availability are not estimated.</p>
    {disabled&&<p role="status">Finish the active placement or preview before editing selections.</p>}
    <h3>Whole project</h3><Totals totals={schedule.totals}/>
    <SelectionBudgetPanel plan={plan} schedule={schedule} disabled={disabled} onCommit={onCommit}/>
    <div className="selection-actions"><button onClick={()=>attempt(()=>downloadSelectionSchedule(schedule,'csv'))}>Export full CSV</button><button onClick={()=>attempt(()=>printSelectionSchedule(schedule))}>Print / Save PDF</button><button onClick={()=>attempt(()=>downloadSelectionSchedule(schedule,'html'))}>Download printable copy</button></div>
    <div className="selection-filters"><label>Floor<select value={floorId} onChange={e=>setFloorId(e.target.value)}><option value="">All floors</option>{plan.floors.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Find a selection<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Item, vendor, or room"/></label></div>
    <details><summary>Floor and room totals</summary>{schedule.floors.filter(f=>!floorId||f.floorId===floorId).map(f=><section key={f.floorId}><h3>{f.floorName}</h3><Totals totals={f.totals}/>{schedule.rooms.filter(r=>r.floorId===f.floorId).map(r=><div key={r.roomKey}><strong>{r.roomName}</strong><Totals totals={r.totals}/></div>)}</section>)}</details>
    {edit&&<form className="selection-edit" onSubmit={e=>{e.preventDefault();save();}}><h3>Edit selection</h3>{edit.base!==plan&&<p role="alert">The project changed. Close this form and reopen the item before saving.</p>}<div className="selection-fields">
      <label>Product name<input value={edit.spec.productName??''} maxLength={160} onChange={e=>patch({productName:e.target.value||undefined})}/></label><label>Vendor<input value={edit.spec.vendor??''} maxLength={160} onChange={e=>patch({vendor:e.target.value||undefined})}/></label><label className="selection-wide">Product link<input type="url" value={edit.spec.productUrl??''} maxLength={2048} placeholder="https://…" onChange={e=>patch({productUrl:e.target.value||undefined})}/></label>
      <ChoiceButtons label="Model match" value={edit.spec.match} options={[{value:'unspecified',label:'Not specified'},{value:'exact',label:'Exact product'},{value:'visual-substitute',label:'Visual substitute'}]} onChange={match=>patch({match})}/><ChoiceButtons label="Status" value={edit.spec.status} options={(['owned','wishlist','selected','ordered'] as const).map(value=>({value,label:value[0].toUpperCase()+value.slice(1)}))} onChange={status=>patch({status})}/>

      <label>Currency code<input value={edit.spec.currency??''} maxLength={3} placeholder="USD, CAD, EUR…" onChange={e=>patch({currency:e.target.value.toUpperCase()||null})}/></label><label>{edit.spec.purchase.unit==='pack'?'Price per pack':'Price for this item'}<input inputMode="decimal" value={edit.price} placeholder="Unknown" onChange={e=>setEdit({...edit,price:e.target.value,spec:{...edit.spec,checkedOn:edit.spec.checkedOn??(e.target.value.trim()?new Date().toISOString().slice(0,10):null)}})}/></label><label>Price checked on<input type="date" value={edit.spec.checkedOn??''} onChange={e=>patch({checkedOn:e.target.value||null})}/></label>
      <ChoiceButtons label="Purchase unit" value={edit.spec.purchase.unit} options={[{value:'item',label:'One item'},{value:'pack',label:'Pack'}]} onChange={unit=>patch({purchase:unit==='pack'?{unit:'pack',quantity:1,unitsPerPack:1}:{unit:'item',quantity:1}})}/>

      {edit.spec.purchase.unit==='pack'&&<><label>Packs to buy<input type="number" min={1} max={1000} value={edit.spec.purchase.quantity} onChange={e=>patch({purchase:{...edit.spec.purchase,quantity:e.target.valueAsNumber}})}/></label><label>Units per pack<input type="number" min={1} max={1000} value={edit.spec.purchase.unitsPerPack} onChange={e=>patch({purchase:{...edit.spec.purchase,unitsPerPack:e.target.valueAsNumber}})}/></label><p className="selection-wide">A pack purchase belongs to this one schedule line. Record it once to avoid charging the same pack to several placed pieces. Pack quantity does not add models.</p></>}
      <ChoiceButtons label="Line discount" value={edit.spec.discount.kind} options={[{value:'none',label:'None'},{value:'percent',label:'Percent'},{value:'fixed',label:'Amount'}]} onChange={kind=>setEdit({...edit,discount:'0',spec:{...edit.spec,discount:{kind,value:0}}})}/>{edit.spec.discount.kind!=='none'&&<label>{edit.spec.discount.kind==='percent'?'Discount (%)':'Fixed discount in selected currency'}<input inputMode="decimal" value={edit.discount} onChange={e=>setEdit({...edit,discount:e.target.value})}/></label>}
    </div><p>A discount applies once to this line after multiplying the per-item or per-pack price. Prices are never fetched from the link.</p><div className="selection-actions"><button disabled={disabled||edit.base!==plan}>Save selection</button><button type="button" onClick={()=>setEdit(undefined)}>Cancel editing</button><button type="button" disabled={disabled||edit.base!==plan} onClick={()=>attempt(()=>{const next=updatePlacementSpecification(edit.base,plan,edit.id,undefined,validatePlan);onCommit(edit.base,next);setEdit(undefined);setMessage('Specification removed. The placed model is unchanged.');})}>Clear specification</button></div></form>}
    <div className="selection-table"><table><thead><tr><th>Item</th><th>Room</th><th>Status / match</th><th>Known line price</th><th>Actions</th></tr></thead><tbody>{rows.slice(0,100).map(row=><tr key={row.id}><td>{row.name}<small>{row.dimensions.widthMm} × {row.dimensions.depthMm} × {row.dimensions.heightMm} mm</small></td><td>{row.room.name}{row.room.warning&&<small>{row.room.warning}</small>}</td><td>{row.specified?row.specification.status:'Not specified'}<small>{row.specification.match==='exact'?'Exact product':row.specification.match==='visual-substitute'?'Visual substitute':'Match not specified'}</small></td><td>{row.netMinor===null?'Unknown':formatMoney(row.netMinor,row.specification.currency!)}<small>{row.specification.checkedOn?'Checked '+row.specification.checkedOn:'Price date unknown'}</small>{row.specification.status==='owned'&&<small>Owned — excluded from amount to buy</small>}</td><td><button disabled={disabled||isFurnitureLocked(plan,row.id)} title={isFurnitureLocked(plan,row.id)?"Unlock this furniture in Groups before editing its specification":undefined} onClick={()=>start(row.id)}>Edit {row.name}</button>{isFurnitureLocked(plan,row.id)&&<small>Locked furniture</small>}</td></tr>)}</tbody></table></div>
    {!rows.length&&<p>No items match this view.</p>}{rows.length>100&&<p>Showing the first 100 matching items. Narrow the search; the full exports include every placed item.</p>}{error&&<p role="alert">{error}</p>}<p role="status" aria-live="polite">{message}</p><small>Snapshot: {schedule.revision}. Private product links and prices are left out of public shares.</small>
  </section>;
}
