import {ChoiceButtons} from './ChoiceButtons';
import {useState} from 'react';
import {validatePlan} from './planValidation';
import {compareSelectionBudgets,parseBudgetAmount,updateSelectionBudget,type SelectionBudgetTarget} from './selectionBudgets';
import {formatMoney,type SelectionPlan,type SelectionSchedule} from './selectionSchedule';
export function SelectionBudgetPanel({plan,schedule,disabled,onCommit}:{plan:SelectionPlan;schedule:SelectionSchedule;disabled?:boolean;onCommit(base:SelectionPlan,next:SelectionPlan):void}){
  const [scope,setScope]=useState<SelectionBudgetTarget['scope']>('project'),[floorId,setFloorId]=useState(plan.floors[0]?.id??''),[roomKey,setRoomKey]=useState(''),[currency,setCurrency]=useState(''),[amount,setAmount]=useState(''),[error,setError]=useState('');
  const floor=plan.floors.find(f=>f.id===floorId),rooms=[...new Map((floor?.blueprint?.rooms??[]).map(room=>[room.groupId??room.id,room])).values()];
  const change=(target:SelectionBudgetTarget,remove=false)=>{try{setError('');if(disabled)return;const next=updateSelectionBudget(plan,plan,target,remove,validatePlan);onCommit(plan,next);}catch(e){setError((e as Error).message);}};
  return <details className="selection-budgets"><summary>Budget targets</summary><p>Targets compare only the same currency. Missing prices and unassigned rooms keep estimates incomplete.</p><div className="selection-fields"><ChoiceButtons<SelectionBudgetTarget["scope"]> label="Budget scope" value={scope} disabled={disabled} options={[{value:'project',label:'Whole project'},{value:'floor',label:'Floor'},{value:'room',label:'Room'}]} onChange={setScope}/>{scope!=='project'&&<label>Budget floor<select disabled={disabled} value={floorId} onChange={e=>{setFloorId(e.target.value);setRoomKey('');}}>{plan.floors.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>}{scope==='room'&&<label>Budget room<select disabled={disabled} value={roomKey} onChange={e=>setRoomKey(e.target.value)}><option value="">Choose a room</option>{rooms.map(room=><option key={room.groupId??room.id} value={room.groupId??room.id}>{room.name}</option>)}</select></label>}<label>Budget currency<input value={currency} maxLength={3} placeholder="USD, CAD…" onChange={e=>setCurrency(e.target.value.toUpperCase())}/></label><label>Target amount<input value={amount} inputMode="decimal" onChange={e=>setAmount(e.target.value)}/></label></div><button disabled={disabled||!amount||!currency||scope==='room'&&!roomKey} onClick={()=>{try{change({scope,currency,amountMinor:parseBudgetAmount(amount,currency),...(scope==='project'?{}:{floorId}),...(scope==='room'?{roomKey}:{})});}catch(e){setError((e as Error).message);}}}>Save target</button><ul className="selection-totals">{compareSelectionBudgets(plan,schedule,plan.selectionBudgets).map(result=><li key={JSON.stringify(result.target)}><strong>{result.label} · {formatMoney(result.target.amountMinor,result.target.currency)}</strong>{result.orphaned?<span>Target retained — this floor or room is no longer available.</span>:<><span>{result.overTargetMinor?`Over target by ${formatMoney(result.overTargetMinor,result.target.currency)} from known prices`:`${formatMoney(result.remainingMinor,result.target.currency)} remaining from known prices`}</span><small>{result.unknownPrices} missing prices · {result.unassignedRows} unassigned room items</small></>}<button disabled={disabled} onClick={()=>change(result.target,true)}>Remove target</button></li>)}</ul>{error&&<p role="alert">{error}</p>}</details>;
}

