import {useEffect,useMemo,useRef,useState} from 'react';
import type {PlanDocumentV1} from './types';
import {validatePlan} from './planValidation';
import {pointOnPlate} from './surfaceGeometry';
import {wallPlateLabel} from './wallElevation';
import {downloadSurfaceFile} from './surfaceExports';
import {prepareServicePoint,removeServicePoint,saveServicePoint,servicePointKinds,servicePointPosition,servicePointStatus,servicePointWalls,servicePointsCsv,verifyServicePoint,type ServicePoint,type ServicePointInput} from './servicePoints';
import {ServicePointOverlay,ServicePointSymbol} from './ServicePointOverlay';
import './service-points.css';

export interface ServicePointsPanelProps {plan:PlanDocumentV1;activeFloorId?:string;disabled?:boolean;onCommit(base:PlanDocumentV1,next:PlanDocumentV1):void}
type Draft=Omit<ServicePointInput,'offsetMm'|'heightMm'>&{offsetMm:string;heightMm:string};
const form=(point:ServicePointInput):Draft=>({...point,offsetMm:String(point.offsetMm),heightMm:String(point.heightMm)});
function input(draft:Draft):ServicePointInput {if(!draft.offsetMm.trim()||!draft.heightMm.trim())throw new Error('Enter the measured wall distance and height.');return {...draft,offsetMm:Number(draft.offsetMm),heightMm:Number(draft.heightMm)};}
function sameMeasurements(a:ServicePointInput,b:ServicePointInput){return ['id','kind','label','floorId','wallKey','face','offsetMm','heightMm'].every(key=>a[key as keyof ServicePointInput]===b[key as keyof ServicePointInput]);}

export function ServicePointsPanel({plan,activeFloorId,disabled=false,onCommit}:ServicePointsPanelProps){
  const [base,setBase]=useState(plan),[floorId,setFloorId]=useState(activeFloorId??plan.floors[0]?.id??''),[draft,setDraft]=useState<Draft>(),[visible,setVisible]=useState(true),[reviewer,setReviewer]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[acknowledged,setAcknowledged]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
  const pending=useRef<string|undefined>(undefined),map=useRef<SVGSVGElement>(null);
  useEffect(()=>{if(pending.current&&base!==plan){const expected=pending.current;pending.current=undefined;if(JSON.stringify(plan.siteSurvey)===expected){setBase(plan);setMessage('Service point record saved.');setAcknowledged(false);}}},[plan,base]);
  const points=plan.siteSurvey?.servicePoints??[],selected=points.find(p=>p.id===draft?.id),floor=plan.floors.find(f=>f.id===floorId),stale=base!==plan;
  const geometry=useMemo(()=>{try{return {walls:servicePointWalls(plan,floorId)};}catch(e){return {walls:[],error:(e as Error).message};}},[plan,floorId]);
  const walls=geometry.walls,wall=walls.find(w=>w.key===draft?.wallKey);
  const preview=useMemo(()=>{if(!draft)return {};try{return {point:prepareServicePoint(plan,input(draft))};}catch(e){return {error:(e as Error).message};}},[plan,draft]);
  const dirty=!!draft&&(!selected||!preview.point||!sameMeasurements(input(draft),selected));
  const bounds=useMemo(()=>{const positions=[...walls.flatMap(w=>[pointOnPlate(w,0),pointOnPlate(w,w.lengthMm)]),...points.filter(p=>p.floorId===floorId).map(servicePointPosition)];if(!positions.length)return {x:-500,z:-500,width:6000,height:4500};const xs=positions.map(p=>p.x),zs=positions.map(p=>p.z),width=Math.max(1500,Math.max(...xs)-Math.min(...xs)),height=Math.max(1500,Math.max(...zs)-Math.min(...zs)),pad=Math.max(width,height)*.18;return {x:Math.min(...xs)-pad,z:Math.min(...zs)-pad,width:width+pad*2,height:height+pad*2};},[walls,points,floorId]);
  const size=Math.max(bounds.width,bounds.height)/28;
  const open=(point:ServicePoint)=>{setBase(plan);setFloorId(point.floorId);setDraft(form(point));setAcknowledged(false);setError('');setMessage('');};
  const attempt=(action:()=>PlanDocumentV1,remove=false)=>{setError('');try{const next=action();pending.current=JSON.stringify(next.siteSurvey);try{onCommit(plan,next);if(remove)setDraft(undefined);}catch(e){pending.current=undefined;throw e;}}catch(e){setError((e as Error).message);}};
  const chooseWall=(key:string)=>{if(draft)setDraft({...draft,wallKey:key});};
  const newPoint=()=>{setBase(plan);setDraft({id:crypto.randomUUID(),kind:'outlet',label:`Outlet ${points.length+1}`,floorId,wallKey:walls[0]?.key??'',face:'front',offsetMm:String(Math.min(500,(walls[0]?.lengthMm??1000)/2)),heightMm:'300'});setAcknowledged(false);setError('');setMessage('');};
  const exportMap=()=>{setError('');try{if(!map.current)return;const svg=map.current.cloneNode(true) as SVGSVGElement;svg.setAttribute('xmlns','http://www.w3.org/2000/svg');svg.setAttribute('width','1400');svg.setAttribute('height',String(Math.round(1400*bounds.height/bounds.width)));svg.querySelectorAll('[data-preview]').forEach(n=>n.remove());svg.querySelectorAll('[role="button"]').forEach(n=>{n.removeAttribute('role');n.removeAttribute('tabindex');});downloadSurfaceFile(new XMLSerializer().serializeToString(svg),'service-points-map.svg','image/svg+xml');setMessage('Saved the visible map layer. Draft marker previews are excluded.');}catch(e){setError((e as Error).message);}};
  const missing=points.filter(p=>!plan.floors.some(f=>f.id===p.floorId));
  return <section className="service-points" aria-labelledby="service-points-title"><h3 id="service-points-title">Service points</h3><p>Record measured outlets, switches, data connections and vents. Positions are planning notes; they do not describe hidden wiring, circuits, airflow or code compliance.</p>
    <div className="service-toolbar"><label>Map floor<select value={floorId} onChange={e=>{setFloorId(e.target.value);setDraft(undefined);setBase(plan);setError('');}}>{!floor&&<option value={floorId}>Removed floor · retained markers</option>}{plan.floors.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label className="service-check"><input type="checkbox" checked={visible} onChange={e=>setVisible(e.target.checked)}/>Show service points</label><button disabled={disabled||!walls.length||points.length>=200} onClick={newPoint}>Add service point</button></div>
    <div className="service-points-grid"><div><svg ref={map} className="service-map" role="img" aria-label={`${floor?.name??'Removed floor'} service point map`} viewBox={`${bounds.x} ${bounds.z} ${bounds.width} ${bounds.height}`}><title>{floor?.name??'Removed floor'} · measured service points · planning notes</title><desc>O outlet; S switch; D data; V vent. Red RECHECK markers retain earlier locations after geometry changes. Measurements are millimetres. Draft previews are not exported.</desc><rect x={bounds.x} y={bounds.z} width={bounds.width} height={bounds.height} fill="#faf8f1"/>{walls.map((w,i)=>{const a=pointOnPlate(w,0),b=pointOnPlate(w,w.lengthMm);return <g key={w.key}><line x1={a.x} y1={a.z} x2={b.x} y2={b.z} stroke={wall?.key===w.key?'#b47c26':'#627268'} strokeWidth={wall?.key===w.key?7:4} vectorEffect="non-scaling-stroke"/>{draft&&<line aria-label={`Select wall ${i+1}`} role="button" tabIndex={0} x1={a.x} y1={a.z} x2={b.x} y2={b.z} stroke="transparent" strokeWidth={18} vectorEffect="non-scaling-stroke" onClick={()=>chooseWall(w.key)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();chooseWall(w.key);}}}/>}</g>;})}{wall&&draft&&<g data-preview="wall-reference" fill="#805919" fontFamily="Arial,sans-serif" fontSize={size*2}>{[0,wall.lengthMm].map((distance,i)=>{const p=pointOnPlate(wall,distance);return <text key={i} x={p.x-size} y={p.z-size*1.5}>{i?'B':'A'}</text>;})}</g>}{visible&&<ServicePointOverlay plan={plan} floorId={floorId} size={size} selectedId={draft?.id}/>} {visible&&preview.point&&dirty&&<g data-preview="service-point" data-testid="service-point-draft" opacity={.7}><ServicePointSymbol point={preview.point} size={size} selected/></g>}</svg>
      <p className="service-legend">O Outlet · S Switch · D Data · V Vent<br/>Gold: unchecked · Green: self-reported check · Red: recheck geometry</p><div className="service-actions"><button onClick={exportMap}>Export visible map SVG</button><button disabled={!points.some(p=>p.floorId===floorId)} onClick={()=>downloadSurfaceFile(servicePointsCsv(plan,floorId),'service-points-measurements.csv','text/csv;charset=utf-8')}>Export floor measurements CSV</button></div><small>The SVG follows the visible layer; the CSV lists all saved markers on this floor, including earlier checks and changed anchors. Exports exclude the unsaved draft.</small>
      <div className="service-records" aria-label="Saved service points">{points.filter(p=>p.floorId===floorId).map(p=><button key={p.id} aria-pressed={p.id===draft?.id} onClick={()=>open(p)}><strong>{p.label}</strong><small>{servicePointKinds.find(k=>k.id===p.kind)?.name} · {p.offsetMm} mm from A · {p.heightMm} mm high</small><small>{servicePointStatus(plan,p).message}</small></button>)}</div>{!points.some(p=>p.floorId===floorId)&&<p>No saved service points on this floor.</p>}{missing.length>0&&<details open><summary>Markers on removed floors ({missing.length})</summary>{missing.filter(p=>p.floorId!==floorId).map(p=><button key={p.id} onClick={()=>open(p)}>{p.label} · choose a current floor to relink</button>)}</details>}
    </div><div>{draft?<><h4>{selected?'Edit measured marker':'New measured marker'}</h4><div className="service-fields"><label>Marker type<select value={draft.kind} onChange={e=>setDraft({...draft,kind:e.target.value as Draft['kind']})}>{servicePointKinds.map(k=><option key={k.id} value={k.id}>{k.name}</option>)}</select></label><label>Marker label<input value={draft.label} maxLength={120} onChange={e=>setDraft({...draft,label:e.target.value})}/></label><label>Marker floor<select value={draft.floorId} onChange={e=>{setFloorId(e.target.value);setDraft({...draft,floorId:e.target.value,wallKey:''});}}>{!plan.floors.some(f=>f.id===draft.floorId)&&<option value={draft.floorId}>Removed floor</option>}{plan.floors.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Measured wall<select value={draft.wallKey} onChange={e=>chooseWall(e.target.value)}><option value="">Choose a current wall</option>{!wall&&draft.wallKey&&<option value={draft.wallKey}>Earlier wall · choose current geometry</option>}{walls.map((w,i)=><option key={w.key} value={w.key}>{wallPlateLabel(w,i)}</option>)}</select></label><label>Wall face<select value={draft.face} onChange={e=>setDraft({...draft,face:e.target.value as Draft['face']})}><option value="front">Front · left of A → B</option><option value="back">Back · right of A → B</option></select></label><label>Distance from A (mm)<input type="number" min={0} max={wall?.lengthMm} step="any" value={draft.offsetMm} onChange={e=>setDraft({...draft,offsetMm:e.target.value})}/></label><label>Height above floor (mm)<input type="number" min={0} max={wall?.heightMm??20000} step="any" value={draft.heightMm} onChange={e=>setDraft({...draft,heightMm:e.target.value})}/></label></div>
      <p>Measure the marker centre from wall endpoint A along A → B, and vertically above this floor. Face selection does not reverse the distance.</p>{wall&&<small>A: {Math.round(pointOnPlate(wall,0).x)}, {Math.round(pointOnPlate(wall,0).z)} mm · B: {Math.round(pointOnPlate(wall,wall.lengthMm).x)}, {Math.round(pointOnPlate(wall,wall.lengthMm).z)} mm</small>}{preview.error&&<p role="status">{preview.error}</p>}{stale&&<p role="status">The project changed. Reload the saved marker before saving this draft.</p>}<div className="service-actions"><button disabled={disabled||stale||!preview.point} onClick={()=>attempt(()=>saveServicePoint(base,plan,input(draft),validatePlan))}>Save measured marker</button><button onClick={()=>{setBase(plan);setAcknowledged(false);setError('');if(selected)open(selected);else setDraft(undefined);}}>Reload saved marker</button><button onClick={()=>setDraft(undefined)}>Cancel draft</button>{selected&&<button disabled={disabled||stale} onClick={()=>attempt(()=>removeServicePoint(base,plan,selected.id,validatePlan),true)}>Remove marker</button>}</div>
      {selected&&<div className="service-verification"><h4>On-site verification</h4><p>{servicePointStatus(plan,selected).message}</p>{dirty&&<small>Save the changed measurements before recording a check.</small>}<label>Checked by<input maxLength={120} value={reviewer} onChange={e=>setReviewer(e.target.value)}/></label><label>Check date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="service-check"><input type="checkbox" checked={acknowledged} onChange={e=>setAcknowledged(e.target.checked)}/>I checked this wall, position and height on site</label><button disabled={disabled||stale||dirty||!acknowledged||!reviewer.trim()||!date||servicePointStatus(plan,selected).state==='changed'} onClick={()=>attempt(()=>verifyServicePoint(base,plan,selected.id,{reviewer,checkedOn:date},validatePlan))}>Record on-site check</button></div>}
    </>:<p>Select a saved marker or add one, then choose its wall on the map or in the measured-wall list. Saving adds one undo step; a new marker stays a preview until saved.</p>}</div></div>
    {geometry.error&&<p role="status">{geometry.error} Earlier markers remain available.</p>}{error&&<p role="alert">{error}</p>}<p role="status" aria-live="polite">{message}</p>
  </section>;
}
