import {useEffect,useRef,useState} from 'react';
import {catalog} from './catalog';
import {kitPieceProblem} from './furnitureKits';
import {buildRemixSnapshot,exportRemixSnapshot,remixRooms,remixTags,type RemixPlan,type RemixSnapshot,type RemixTag} from './remixSnapshot';
import {createRemixShare,deleteRemixShare,listRemixShares,ownedRemixShare,remixAvailability,remixLink,revokeRemixShare,submitIdea,withdrawIdea,type RemixShare,type IdeaSubmission} from './remixApi';
import {RemixPreview} from './RemixPreview';
import './remix-gallery.css';
export function ShareArrangementPanel({plan,floorId,onBusyChange}:{plan:RemixPlan;floorId:string;onBusyChange?:(value:boolean)=>void}){
 const [kind,setKind]=useState<'kit'|'room'>('kit'),[room,setRoom]=useState(''),[ids,setIds]=useState<string[]>([]),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[creator,setCreator]=useState(''),[tags,setTags]=useState<RemixTag[]>([]),[allowCopy,setAllowCopy]=useState(false),[snapshot,setSnapshot]=useState<RemixSnapshot>(),[rights,setRights]=useState(false),[publicConsent,setPublicConsent]=useState(false),[hours,setHours]=useState(168),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[link,setLink]=useState(''),[status,setStatus]=useState<Awaited<ReturnType<typeof remixAvailability>>>(),[shares,setShares]=useState<RemixShare[]>([]),[owned,setOwned]=useState<Awaited<ReturnType<typeof ownedRemixShare>>>(),[confirmDelete,setConfirmDelete]=useState(false);
 const latest=useRef(plan),alive=useRef(true),epoch=useRef(0),running=useRef(false),abort=useRef<AbortController|undefined>(undefined),base=useRef(plan);latest.current=plan;
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;epoch.current++;abort.current?.abort();onBusyChange?.(false);};},[]);
 useEffect(()=>{epoch.current++;abort.current?.abort();running.current=false;setBusy(false);onBusyChange?.(false);setSnapshot(undefined);setIds([]);setRoom('');setRights(false);setPublicConsent(false);setLink('');setOwned(undefined);setShares([]);},[plan,floorId]);
 function invalidate(){setSnapshot(undefined);setRights(false);setPublicConsent(false);setLink('');}
 async function run(work:(valid:()=>boolean,signal:AbortSignal)=>Promise<void>){if(running.current)return;running.current=true;const version=epoch.current;abort.current=new AbortController();const valid=()=>alive.current&&version===epoch.current;setBusy(true);onBusyChange?.(true);setError('');setNotice('');try{await work(valid,abort.current.signal);}catch(e){if(valid())setError((e as Error).message);}finally{if(valid()){running.current=false;setBusy(false);onBusyChange?.(false);}}}
 function preview(){try{const value=buildRemixSnapshot(plan,{kind,floorId,roomKey:room,selectedIds:ids,title,description,creator,tags,allowCopy});base.current=plan;setSnapshot(value);setRights(false);setPublicConsent(false);setError('');}catch(e){setError((e as Error).message);}}
 async function refresh(valid:()=>boolean,signal:AbortSignal){const state=await remixAvailability(signal);if(valid())setStatus(state);if(state.signedIn&&state.available){const list=await listRemixShares(plan.id,signal);if(valid())setShares(list);}}
 async function publish(previous?:RemixShare){if(!snapshot||base.current!==latest.current)return;const value=snapshot;await run(async(valid,signal)=>{const result=await createRemixShare(plan.id,value,hours,rights,previous,signal);if(valid()){setLink(remixLink(location.origin,result.share,result.token));setOwned({share:result.share,snapshot:value,submissions:[]});setPublicConsent(false);setNotice('Unlisted link created. It has not been submitted to the gallery. Keep the link: its key is shown only now.');await refresh(valid,signal);}});}
 const candidates=plan.furniture.filter(p=>p.floorId===floorId&&!kitPieceProblem(p));
 return <section className="remix-tools" aria-label="Share an arrangement"><header><p className="remix-eyebrow">Share only what you choose</p><h2>A room someone can remix</h2><p>Prepare a room outline or furniture kit. Names, creator credit and description below are public; leave out addresses or personal details. Uploaded images, private artwork, notes and account information are excluded.</p></header>{error&&<p role="alert" className="remix-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <fieldset disabled={busy}><legend>Choose the snapshot</legend><div className="remix-row"><label>Package<select value={kind} onChange={e=>{setKind(e.target.value as typeof kind);invalidate();}}><option value="kit">Furniture kit</option><option value="room">Measured room</option></select></label>{kind==='room'&&<label>Room<select value={room} onChange={e=>{setRoom(e.target.value);invalidate();}}><option value="">Choose a measured room</option>{remixRooms(plan,floorId).map(r=><option key={r.key} value={r.key}>{r.name}</option>)}</select></label>}</div><label>Public title<input maxLength={80} value={title} onChange={e=>{setTitle(e.target.value);invalidate();}}/></label><label>Creator credit (self-reported)<input maxLength={60} value={creator} onChange={e=>{setCreator(e.target.value);invalidate();}}/></label><label>Public description<textarea maxLength={400} value={description} onChange={e=>{setDescription(e.target.value);invalidate();}}/></label><details><summary>Choose individual pieces ({ids.length}/40)</summary>{candidates.map(p=><label className="remix-check" key={p.id}><input type="checkbox" checked={ids.includes(p.id)} disabled={!ids.includes(p.id)&&ids.length>=40} onChange={e=>{setIds(old=>e.target.checked?[...old,p.id]:old.filter(id=>id!==p.id));invalidate();}}/>{catalog.find(c=>c.id===p.catalogId)?.name} · {p.widthMm} × {p.depthMm} mm</label>)}{!candidates.length&&<p>Add compatible freestanding furniture first.</p>}</details><details><summary>Tags ({tags.length}/4)</summary>{remixTags.map(t=><label className="remix-check" key={t}><input type="checkbox" checked={tags.includes(t)} disabled={!tags.includes(t)&&tags.length>=4} onChange={e=>{setTags(old=>e.target.checked?[...old,t]:old.filter(k=>k!==t));invalidate();}}/>{t}</label>)}</details><label className="remix-check"><input type="checkbox" checked={allowCopy} onChange={e=>{setAllowCopy(e.target.checked);invalidate();}}/>Allow independent copies and adaptations in Nook & Nest with creator credit</label><button onClick={preview}>Preview exact shared snapshot</button></fieldset>
 {snapshot&&<><RemixPreview snapshot={snapshot}/><fieldset disabled={busy}><legend>After reviewing this snapshot</legend><p>Revocation stops future access. It cannot erase copies already downloaded or saved by someone else.</p><button onClick={()=>exportRemixSnapshot(snapshot,{source:'file',id:crypto.randomUUID(),revision:1})}>Export room package locally</button><label className="remix-check"><input type="checkbox" checked={rights} onChange={e=>setRights(e.target.checked)}/>I can share this arrangement, have kept earlier creator credits, and have checked its public text</label><label>Link lifetime<select value={hours} onChange={e=>setHours(Number(e.target.value))}><option value={24}>1 day</option><option value={168}>7 days</option><option value={720}>30 days</option><option value={2160}>90 days</option></select></label><button disabled={!rights} onClick={()=>void publish()}>Create unlisted link</button>{owned&&!owned.share.revoked&&<><p>A replacement revision disables its older link and any gallery entry until separately submitted and approved.</p><button disabled={!rights} onClick={()=>void publish(owned.share)}>Publish as new revision of selected link</button></>}</fieldset></>}
 {link&&<label>Unlisted link<input readOnly value={link} onFocus={e=>e.target.select()}/><button onClick={()=>void run(async valid=>{await navigator.clipboard.writeText(link);if(valid())setNotice('Link copied. Send it yourself when ready.');})}>Copy link</button></label>}
 <fieldset disabled={busy}><legend>My links and submissions</legend><button onClick={()=>void run(refresh)}>Refresh online sharing</button>{status&&!status.signedIn&&<p>Sign in through Project to manage links or submit an idea.</p>}{status&&!status.moderationConfigured&&<p>The community submission queue is closed until a curator is configured. Local packages and original examples still work.</p>}<label>My project links<select value={owned?.share.id??''} onChange={e=>{const id=e.target.value;if(!id){setOwned(undefined);return;}void run(async(valid,signal)=>{const value=await ownedRemixShare(id,signal);if(valid()){setOwned(value);setPublicConsent(false);setRights(false);setConfirmDelete(false);}});}}><option value="">Choose a link</option>{shares.map(s=><option key={s.id} value={s.id}>Revision {s.revision} · {new Date(s.createdAt).toLocaleDateString()} · {s.revoked?'Revoked':'Active until '+new Date(s.expiresAt).toLocaleDateString()}</option>)}</select></label></fieldset>
 {owned&&<section aria-label="Selected published snapshot"><RemixPreview snapshot={owned.snapshot}/><fieldset disabled={busy}><legend>Manage exact published revision {owned.share.revision}</legend><label className="remix-check"><input type="checkbox" checked={publicConsent} onChange={e=>setPublicConsent(e.target.checked)}/>Submit this displayed snapshot and creator credit to the public gallery moderation queue</label><label className="remix-check"><input type="checkbox" checked={rights} onChange={e=>setRights(e.target.checked)}/>I have permission to publish this arrangement and all earlier attribution is included</label><button disabled={!status?.moderationConfigured||!rights||!publicConsent||owned.share.revoked} onClick={()=>void run(async(valid,signal)=>{await submitIdea(owned.share,publicConsent,rights,signal);const refreshed=await ownedRemixShare(owned.share.id,signal);if(valid()){setOwned(refreshed);setPublicConsent(false);setNotice('Submitted for curator review. It is not public until approved.');}})}>Submit this revision for review</button><button disabled={owned.share.revoked} onClick={()=>void run(async(valid,signal)=>{await revokeRemixShare(owned.share,signal);const refreshed=await ownedRemixShare(owned.share.id,signal);if(valid()){setOwned(refreshed);setLink('');setNotice('Future link and gallery access disabled. Existing private copies cannot be recalled.');}})}>Disable future access</button><button onClick={()=>setConfirmDelete(true)}>Delete link and submissions</button>{confirmDelete&&<p className="remix-warning">Permanently delete this link, published snapshot and its submissions? Existing copies remain. <button onClick={()=>void run(async(valid,signal)=>{await deleteRemixShare(owned.share,signal);if(valid()){setOwned(undefined);setLink('');setConfirmDelete(false);await refresh(valid,signal);}})}>Confirm deletion</button><button onClick={()=>setConfirmDelete(false)}>Keep link</button></p>}{owned.submissions.map((s:IdeaSubmission)=><div key={s.id}><p>Revision {s.revision} · {s.state}{s.moderationNote?' · '+s.moderationNote:''}</p>{s.state!=='withdrawn'&&<button onClick={()=>void run(async(valid,signal)=>{await withdrawIdea(s,signal);const value=await ownedRemixShare(owned.share.id,signal);if(valid())setOwned(value);})}>Withdraw revision {s.revision} from gallery</button>}</div>)}</fieldset></section>}
 </section>;
}
