import {SurveyTarget,MeasurementValues,MeasurementSource,MeasurementCheck,SiteNote,AreaClassification,SiteSurvey,SurveyPlan,MAX_SITE_NOTES,blankSiteSurvey,record,surveyText,surveyIdentity,allowedKeys,realDate,timestamp,values,parseSurveyTarget,parseCheck,parseSiteSurvey,MAX_SITE_CHECKS,MAX_SITE_PHOTOS} from './siteSurveySchema';
export * from './siteSurveySchema';
import type {PlanDocumentV1} from './types';
import {floorBoundaryWalls} from './floorGeometry';
import {geometryKey} from './blueprint';
import {floorQuantityGeometry,areaM2} from './surfaceGeometry';
import {catalog} from './catalog';

export function stableFingerprint(value:unknown):string {const input=JSON.stringify(value);let hash=2166136261;for(let i=0;i<input.length;i++)hash=Math.imul(hash^input.charCodeAt(i),16777619);return `${input.length}-${(hash>>>0).toString(16)}`;}
export interface ResolvedSurveyTarget {label:string;values:MeasurementValues;fingerprint:string}
export function resolveSurveyTarget(plan:PlanDocumentV1,target:SurveyTarget):ResolvedSurveyTarget|undefined {
  const floor=plan.floors.find(f=>f.id===target.floorId);if(!floor)return;let v:MeasurementValues,shape:unknown,label:string;
  if(target.kind==='object'){const p=plan.furniture.find(p=>p.id===target.id&&p.floorId===floor.id);if(!p)return;v={widthMm:p.widthMm,depthMm:p.depthMm,heightMm:p.heightMm};shape=[p.x,p.z,p.rotation,p.elevationMm,v];label=p.personalItem?.name??catalog.find(c=>c.id===p.catalogId)?.name??'Object';}
  else if(target.kind==='wall'){const w=[...floorBoundaryWalls(floor,plan.gridSizeMm),...floor.walls].find(w=>w.id===target.id);if(!w)return;v={lengthMm:Math.hypot(w.bx-w.ax,w.bz-w.az)*plan.gridSizeMm,heightMm:w.heightMm??floor.heightMm};shape=[w,plan.gridSizeMm,v];label=`Wall · ${(v.lengthMm!/1000).toFixed(2)} m`;}
  else {if(floor.blueprint?.geometryKey!==geometryKey(floor))return;const rooms=floor.blueprint.rooms.filter(r=>(r.groupId??r.id)===target.id);if(!rooms.length)return;const points=rooms.flatMap(r=>r.polygon??[{x:r.x,z:r.z},{x:r.x+r.width,z:r.z+r.depth}]);v={widthMm:Math.max(...points.map(p=>p.x))-Math.min(...points.map(p=>p.x)),depthMm:Math.max(...points.map(p=>p.z))-Math.min(...points.map(p=>p.z)),heightMm:floor.heightMm};shape=rooms.map(r=>({x:r.x,z:r.z,width:r.width,depth:r.depth,polygon:r.polygon}));label=rooms[0].name;}
  return {label,values:v,fingerprint:stableFingerprint([target,shape,v])};
}
export function siteNoteStatus(plan:PlanDocumentV1,note:SiteNote):{state:'unchecked'|'recorded'|'checked'|'changed'|'discrepancy';message:string}{
  const current=resolveSurveyTarget(plan,note.target),check=note.checks.at(-1);if(!current)return {state:'changed',message:'Referenced geometry is missing or changed; relink before using these measurements.'};if(!check)return {state:'unchecked',message:'No measurement check recorded.'};if(check.modelFingerprint!==current.fingerprint)return {state:'changed',message:'Model geometry changed since this check; the earlier evidence is retained.'};
  if(Object.entries(check.measured).some(([k,v])=>current.values[k as keyof MeasurementValues]===undefined||Math.abs(v!-current.values[k as keyof MeasurementValues]!)>1))return {state:'discrepancy',message:'Entered measurements differ from the current model by more than 1 mm.'};
  return ['tape','laser'].includes(check.source)?{state:'checked',message:'Self-reported site check matches the model within 1 mm.'}:{state:'recorded',message:'Reference/model evidence recorded; no on-site measurement is claimed.'};
}
function checkedUpdate(base:SurveyPlan,current:SurveyPlan,survey:SiteSurvey,validate:(p:unknown)=>void):SurveyPlan {if(base!==current)throw new Error('The project changed. Reload site notes before saving.');const next={...base,siteSurvey:parseSiteSurvey(survey)};validate(next);if(new TextEncoder().encode(JSON.stringify(next)).byteLength>8_000_000)throw new Error('This project exceeds the 8 MB save limit.');return next;}
export function saveSiteNote(base:SurveyPlan,current:SurveyPlan,input:Omit<SiteNote,'checks'>,validate:(p:unknown)=>void):SurveyPlan {
  const survey=base.siteSurvey??blankSiteSurvey(),previous=survey.notes.find(n=>n.id===input.id);if(previous&&JSON.stringify(previous.target)!==JSON.stringify(input.target))throw new Error('Keep an existing evidence target unchanged. Create a new note to link another target.');if(!previous&&!resolveSurveyTarget(base,input.target))throw new Error('Choose current geometry for a new site note.');const note={...input,checks:previous?.checks??[]};return checkedUpdate(base,current,{...survey,notes:previous?survey.notes.map(n=>n.id===note.id?note:n):[...survey.notes,note]},validate);
}
export function appendMeasurementCheck(base:SurveyPlan,current:SurveyPlan,noteId:string,input:{source:MeasurementSource;checkedOn:string;reviewer:string;measured:MeasurementValues;question:string},validate:(p:unknown)=>void,now=new Date().toISOString()):SurveyPlan {
  const survey=base.siteSurvey??blankSiteSurvey(),note=survey.notes.find(n=>n.id===noteId);if(!note)throw new Error('This site note is unavailable.');const target=resolveSurveyTarget(base,note.target);if(!target)throw new Error('The referenced geometry changed. Keep this evidence and create a new note for the current target.');const check=parseCheck({...input,id:crypto.randomUUID(),recordedAt:now,units:'mm',model:target.values,modelFingerprint:target.fingerprint});return checkedUpdate(base,current,{...survey,notes:survey.notes.map(n=>n.id===noteId?{...n,checks:[...n.checks,check]}:n)},validate);
}
export function classifySiteArea(base:SurveyPlan,current:SurveyPlan,floorId:string,roomKey:string,classification:AreaClassification,validate:(p:unknown)=>void):SurveyPlan {const survey=base.siteSurvey??blankSiteSurvey();if(!floorQuantityGeometry(base,floorId).regions.some(r=>r.key===roomKey))throw new Error('This room area changed. Choose a current area.');return checkedUpdate(base,current,{...survey,areas:[...survey.areas.filter(a=>a.floorId!==floorId||a.roomKey!==roomKey),{floorId,roomKey,classification}]},validate);}
export interface ClassifiedArea {floorId:string;floorName:string;roomKey:string;name:string;classification:AreaClassification;areaM2:number|null;basis:string;warning?:string}
export function siteAreaBreakdown(plan:SurveyPlan):ClassifiedArea[]{const rows:ClassifiedArea[]=[];for(const floor of plan.floors){try{const geometry=floorQuantityGeometry(plan,floor.id);for(const region of geometry.regions){const parts=floor.blueprint?.rooms.filter(r=>(r.groupId??r.id)===region.key)??[],explicit=plan.siteSurvey?.areas.find(a=>a.floorId===floor.id&&a.roomKey===region.key),outdoor=parts.some(p=>p.kind==='Outdoor'),classification=explicit?.classification??(outdoor?'outdoor':'unclassified');rows.push({floorId:floor.id,floorName:floor.name,roomKey:region.key,name:region.name,classification,areaM2:areaM2(region.shape),basis:'Authored floor footprint union; includes wall footprints; before stair-void deduction.',warning:[region.warning,outdoor&&classification==='included'?'Outdoor geometry explicitly marked included; do not describe this as interior living area.':undefined,!explicit&&!outdoor?'Classification has not been supplied.':undefined].filter(Boolean).join(' ')||undefined});}}catch(e){rows.push({floorId:floor.id,floorName:floor.name,roomKey:'unavailable',name:'Unavailable geometry',classification:'unclassified',areaM2:null,basis:'Unavailable',warning:(e as Error).message});}}return rows;}
type HistoryCarrier={designHistory?:{checkpoints:Array<{snapshot:unknown}&Record<string,unknown>>}&Record<string,unknown>};
export function collectSurveyAssetIds(plan:PlanDocumentV1):string[]{const ids=new Set<string>();const visit=(p:unknown)=>{for(const note of (p as SurveyPlan).siteSurvey?.notes??[])for(const id of note.photoAssetIds)ids.add(id);};visit(plan);for(const option of plan.layoutAlternatives?.options??[])visit(option.snapshot);for(const checkpoint of (plan as PlanDocumentV1&HistoryCarrier).designHistory?.checkpoints??[])visit(checkpoint.snapshot);return [...ids];}
export function publicSurveyPlan<T extends PlanDocumentV1>(plan:T):T {const strip=(p:unknown)=>{const {siteSurvey:_survey,presentation:_presentation,...rest}=p as T&{siteSurvey?:unknown;presentation?:unknown};return rest;};const history=(plan as T&HistoryCarrier).designHistory;return {...strip(plan),...(plan.layoutAlternatives?{layoutAlternatives:{...plan.layoutAlternatives,options:plan.layoutAlternatives.options.map(o=>({...o,snapshot:strip(o.snapshot)}))}}:{}),...(history?{designHistory:{...history,checkpoints:history.checkpoints.map(c=>({...c,snapshot:strip(c.snapshot)}))}}:{})} as T;}
/** Generic status only: callers can warn quantity/export users without exposing private note text. */
export function measurementEvidenceSummary(plan:SurveyPlan){const result={checked:0,recorded:0,changed:0,discrepancy:0,unchecked:0};for(const note of plan.siteSurvey?.notes??[])result[siteNoteStatus(plan,note).state]++;return result;}
