import {useEffect,useMemo,useRef,useState} from 'react';
import {catalog} from './catalog';
import {geometryKey} from './blueprint';
import {floorBoundaryWalls} from './floorGeometry';
import {validatePlan} from './planValidation';
import {preparePersonalPhoto} from './personalMedia';
import {importPersonalAssets,loadPersonalPhoto} from './personalStorage';
import {appendMeasurementCheck,classifySiteArea,resolveSurveyTarget,saveSiteNote,siteAreaBreakdown,siteNoteStatus,type AreaClassification,type MeasurementSource,type MeasurementValues,type SiteNote,type SurveyPlan,type SurveyTarget} from './siteSurvey';
import './presentation.css';
import {ServicePointsPanel} from './ServicePointsPanel';
export interface SiteSurveyPanelProps {plan:SurveyPlan;activeFloorId?:string;disabled?:boolean;onCommit(base:SurveyPlan,next:SurveyPlan):void;onClose?():void}
const sources:{id:MeasurementSource;name:string}[]=[{id:'tape',name:'Tape measure'},{id:'laser',name:'Laser measure'},{id:'document',name:'Source document'},{id:'trace',name:'Traced reference'},{id:'ai',name:'AI suggestion'},{id:'model',name:'Model only'}];
const names=new Map(catalog.map(c=>[c.id,c.name]));
function SurveyPhoto({id,index}:{id:string;index:number}){const [image,setImage]=useState<string>(),[missing,setMissing]=useState(false);useEffect(()=>{let active=true;setImage(undefined);setMissing(false);void loadPersonalPhoto(id).then(asset=>{if(!active)return;if(asset?.id===id)setImage(asset.preview);else setMissing(true);}).catch(()=>{if(active)setMissing(true);});return()=>{active=false;};},[id]);return image?<img className="survey-photo" src={image} alt={`Private site photo ${index+1}`}/>:<small>{missing?'Photo missing on this device. Restore its private media backup or attach it again.':'Loading private photo…'}</small>;}
export function SiteSurveyPanel({plan,activeFloorId,disabled=false,onCommit,onClose}:SiteSurveyPanelProps){
  const [base,setBase]=useState(plan),[floorId,setFloorId]=useState(activeFloorId??plan.floors[0]?.id??''),[view,setView]=useState<'notes'|'areas'|'services'>('notes'),[query,setQuery]=useState(''),[kind,setKind]=useState<SurveyTarget['kind']>('room'),[draft,setDraft]=useState<Omit<SiteNote,'checks'>>(),[source,setSource]=useState<MeasurementSource>('tape'),[reviewer,setReviewer]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[measured,setMeasured]=useState<MeasurementValues>({}),[question,setQuestion]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  const current=useRef({plan,draft}),pending=useRef<string|undefined>(undefined),mounted=useRef(true);current.current={plan,draft};useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
  useEffect(()=>{if(pending.current&&base!==plan){const expected=pending.current;pending.current=undefined;if(JSON.stringify(plan.siteSurvey)===expected){setBase(plan);setMessage('Site record updated.');}}},[plan,base]);
  const choices=useMemo(()=>{const floor=plan.floors.find(f=>f.id===floorId);if(!floor)return [];const targets:Array<{target:SurveyTarget;label:string}>=[];if(kind==='room'&&floor.blueprint?.geometryKey===geometryKey(floor)){const used=new Set<string>();for(const r of floor.blueprint.rooms){const id=r.groupId??r.id;if(used.has(id))continue;used.add(id);targets.push({target:{kind,floorId,id},label:r.name});}}
    if(kind==='wall')for(const [i,w] of [...floorBoundaryWalls(floor,plan.gridSizeMm),...floor.walls].entries())targets.push({target:{kind,floorId,id:w.id},label:`Wall ${i+1} · ${(Math.hypot(w.bx-w.ax,w.bz-w.az)*plan.gridSizeMm/1000).toFixed(2)} m`});
    if(kind==='object')for(const [i,p] of plan.furniture.filter(p=>p.floorId===floorId).entries())targets.push({target:{kind,floorId,id:p.id},label:`${p.personalItem?.name??names.get(p.catalogId)??'Object'} · ${i+1}`});return targets;},[plan,floorId,kind]);
  const areas=useMemo(()=>siteAreaBreakdown(plan).filter(a=>a.floorId===floorId),[plan,floorId]),selected=plan.siteSurvey?.notes.find(n=>n.id===draft?.id),target=draft?resolveSurveyTarget(plan,draft.target):undefined;
  const attempt=(action:()=>SurveyPlan)=>{setError('');try{const next=action();pending.current=JSON.stringify(next.siteSurvey);try{onCommit(plan,next);}catch(e){pending.current=undefined;throw e;}}catch(e){setError((e as Error).message);}};
  const openNote=(note:SiteNote)=>{setBase(plan);setDraft({id:note.id,target:structuredClone(note.target),title:note.title,text:note.text,photoAssetIds:[...note.photoAssetIds]});setMeasured({});setError('');};
  const upload=async(file:File)=>{const snapshot=current.current;if(!snapshot.draft)return;setBusy(true);setError('');try{const asset=await preparePersonalPhoto(file);if(!mounted.current||current.current.plan!==snapshot.plan||current.current.draft!==snapshot.draft)throw new Error('The note changed. Choose the photo again for the current note.');await importPersonalAssets({version:1,assets:[asset],missing:[]});if(!mounted.current||current.current.plan!==snapshot.plan||current.current.draft!==snapshot.draft)throw new Error('The note changed. The photo is stored privately; choose it again to attach it.');setDraft({...snapshot.draft,photoAssetIds:[...new Set([...snapshot.draft.photoAssetIds,asset.id])]});}catch(e){if(mounted.current)setError((e as Error).message);}finally{if(mounted.current)setBusy(false);}};
  return <section className="presentation-panel" aria-labelledby="survey-title"><header><div><span className="eyebrow">Keep the source with the design</span><h2 id="survey-title">Site notes &amp; measurements</h2></div>{onClose&&<button disabled={busy} onClick={onClose}>Close</button>}</header><div className="pack-toggles" role="group" aria-label="Site record view"><button aria-pressed={view==='notes'} onClick={()=>setView('notes')}>Site notes</button><button aria-pressed={view==='areas'} onClick={()=>setView('areas')}>Area categories</button><button aria-pressed={view==='services'} onClick={()=>setView('services')}>Service points</button></div><div className="pack-toggles" role="group" aria-label="Site record floor" hidden={view==='services'}>{plan.floors.map(f=><button key={f.id} aria-pressed={floorId===f.id} onClick={()=>setFloorId(f.id)}>{f.name}</button>)}</div>
    {view==='services'?<ServicePointsPanel plan={plan} activeFloorId={floorId} disabled={disabled} onCommit={onCommit}/>:view==='areas'?<><p>Areas use the authored floor union, including wall footprints and before stair voids. Categories are your choices, not certified living area.</p>{areas.map(a=><article className="survey-area" key={a.roomKey}><strong>{a.name} · {a.areaM2===null?'Unavailable':a.areaM2.toFixed(2)+' m²'}</strong><small>{a.warning}</small><div className="pack-toggles" role="group" aria-label={`Category for ${a.name}`}>{(['included','excluded','outdoor','unclassified'] as AreaClassification[]).map(value=><button key={value} disabled={disabled||busy||a.areaM2===null} aria-pressed={a.classification===value} onClick={()=>attempt(()=>classifySiteArea(plan,plan,floorId,a.roomKey,value,validatePlan))}>{value[0].toUpperCase()+value.slice(1)}</button>)}</div></article>)}</>:<>
      <div className="pack-choices">{(plan.siteSurvey?.notes??[]).map(note=><button key={note.id} disabled={busy} aria-pressed={draft?.id===note.id} onClick={()=>openNote(note)}>{note.title}<small>{siteNoteStatus(plan,note).message}</small></button>)}</div>
      <details open={!draft}><summary>Attach a new note</summary><div className="pack-toggles" role="group" aria-label="Note target type">{(['room','wall','object'] as const).map(value=><button key={value} aria-pressed={kind===value} onClick={()=>setKind(value)}>{value[0].toUpperCase()+value.slice(1)}</button>)}</div><label>Find a place or object<input value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="pack-choices">{choices.filter(c=>c.label.toLowerCase().includes(query.toLowerCase())).slice(0,40).map(c=><button key={c.target.id} disabled={busy} onClick={()=>{setBase(plan);setDraft({id:crypto.randomUUID(),target:c.target,title:c.label,text:'',photoAssetIds:[]});setMeasured({});setError('');}}>{c.label}</button>)}</div>{choices.length>40&&<small>Showing up to 40 matches. Refine the search.</small>}{!choices.length&&<small>No current targets of this type on this floor.</small>}</details>
      {draft&&<><h3>{target?.label??'Earlier geometry — retained evidence'}</h3><div className="pack-fields"><label>Note title<input maxLength={120} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Private note<textarea maxLength={2000} value={draft.text} onChange={e=>setDraft({...draft,text:e.target.value})}/></label></div><p>{draft.photoAssetIds.length} private photo(s) attached. They are excluded from public links and presentations unless explicitly chosen.</p><label>Add a site photo (up to 5 MB)<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy||draft.photoAssetIds.length>=4} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void upload(file);}}/></label>{draft.photoAssetIds.map((id,index)=><div key={id}><SurveyPhoto id={id} index={index}/><button disabled={busy} onClick={()=>setDraft({...draft,photoAssetIds:draft.photoAssetIds.filter(p=>p!==id)})}>Remove photo {index+1} from note</button></div>)}
        {base!==plan&&<p role="status">The project changed. Reopen this note before saving your draft.</p>}<button disabled={disabled||busy||base!==plan} onClick={()=>attempt(()=>saveSiteNote(base,plan,draft,validatePlan))}>Save private note</button>
        {selected&&<><h3>Record a measurement check</h3><p>Self-reported evidence. This records a check; it does not resize the model or certify a survey.</p><div className="pack-toggles" role="group" aria-label="Measurement source">{sources.map(s=><button key={s.id} aria-pressed={source===s.id} onClick={()=>setSource(s.id)}>{s.name}</button>)}</div><div className="pack-fields"><label>Checked by<input maxLength={120} value={reviewer} onChange={e=>setReviewer(e.target.value)}/></label><label>Check date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>{Object.entries(target?.values??{}).map(([key,value])=><label key={key}>{key.replace('Mm','')} (mm) · model {value!.toFixed(1)}<input type="number" min={1} step="any" value={measured[key as keyof MeasurementValues]??''} onChange={e=>setMeasured(v=>{const next={...v};if(e.target.value==='')delete next[key as keyof MeasurementValues];else next[key as keyof MeasurementValues]=e.target.valueAsNumber;return next;})}/></label>)}</div><label>Question or discrepancy<textarea maxLength={1000} value={question} onChange={e=>setQuestion(e.target.value)}/></label><button disabled={disabled||busy||base!==plan||!target||selected.checks.length>=12} onClick={()=>attempt(()=>appendMeasurementCheck(base,plan,selected.id,{source,checkedOn:date,reviewer,measured,question},validatePlan))}>Add dated check</button><p>{siteNoteStatus(plan,selected).message}</p><details><summary>Earlier evidence ({selected.checks.length}/12)</summary>{selected.checks.map(c=><article key={c.id}><strong>{c.checkedOn} · {sources.find(s=>s.id===c.source)?.name} · {c.reviewer}</strong><p>{Object.entries(c.measured).map(([k,v])=>`${k.replace('Mm','')}: ${v} mm`).join(' · ')}</p><small>Then-current model: {Object.entries(c.model).map(([k,v])=>`${k.replace('Mm','')}: ${v!.toFixed(1)} mm`).join(' · ')}</small><p>{c.question}</p></article>)}</details></>}
      </>}
    </>}{error&&<p role="alert">{error}</p>}<p role="status" aria-live="polite">{busy?'Preparing private photo…':message}</p>
  </section>;
}
