import React,{useEffect,useRef,useState} from 'react';
import {stagingApi,type StagingCalendar,type StagingWorkspace} from './stagingApi';
import {stagingSample,stagingEventLabel,stagingOverlap,stagingDateRange,toStagingVisualProxy,STOCK_CONDITIONS,type StagingCatalogEntry,type StagingVisualProxy,type StockUnit,type StockCondition,type ReservationDetail,type StockUnitDetail} from './stagingInventory';
import './staging-inventory.css';

const empty:StagingCalendar={units:[],reservations:[],next:null};
const initialDates=()=>{const d=new Date();const start=d.toISOString().slice(0,10);d.setUTCDate(d.getUTCDate()+7);return {start,end:d.toISOString().slice(0,10)};};
/** Separate private surface. The callback receives only a catalog/dimension draft, never stock identity. */
export function StagingInventoryPanel({catalog,onPreviewProxy,onClose,onBusyChange,api=stagingApi}:{catalog:readonly StagingCatalogEntry[];onPreviewProxy?:(proxy:StagingVisualProxy)=>void;onClose:()=>void;onBusyChange?:(busy:boolean)=>void;api?:typeof stagingApi}){
 const [status,setStatus]=useState<{enabled:boolean;signedIn:boolean;canEnroll:boolean}|null>(null),[workspaces,setWorkspaces]=useState<StagingWorkspace[]>([]),[workspace,setWorkspace]=useState(''),[sample,setSample]=useState(true);
 const [dates,setDates]=useState({start:'2026-10-01',end:'2026-10-08'}),[calendar,setCalendar]=useState<StagingCalendar>(empty),[detail,setDetail]=useState<ReservationDetail|null>(null),[checked,setChecked]=useState<string[]>([]),[busy,setBusyState]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[loaded,setLoaded]=useState(false),[refresh,setRefresh]=useState(0);
 const [property,setProperty]=useState(''),[newInventory,setNewInventory]=useState(''),[catalogId,setCatalogId]=useState(catalog[0]?.id??''),[stockCode,setStockCode]=useState(''),[label,setLabel]=useState(''),[dimensions,setDimensions]=useState({widthMm:catalog[0]?.widthMm??1000,depthMm:catalog[0]?.depthMm??600,heightMm:catalog[0]?.heightMm??800}),[stockCondition,setStockCondition]=useState<StockCondition>('good');
 const [unitHistory,setUnitHistory]=useState<Pick<StockUnitDetail,'events'|'next'>>({events:[],next:null});
 const [selectedUnit,setSelectedUnit]=useState<StockUnit|null>(null),[editCondition,setEditCondition]=useState<StockCondition>('good'),[retired,setRetired]=useState(false),[returnCondition,setReturnCondition]=useState<StockCondition>('good'),[returnNote,setReturnNote]=useState('');
 const busyRef=useRef(false);const setBusy=(value:boolean)=>{busyRef.current=value;setBusyState(value);onBusyChange?.(value);};
 useEffect(()=>()=>onBusyChange?.(false),[onBusyChange]);
 const active=workspaces.find(w=>w.id===workspace),canWrite=!sample&&(active?.role==='owner'||active?.role==='manager');
 useEffect(()=>{let live=true;api.status().then(async s=>{if(!live)return;setStatus(s);if(s.enabled&&s.signedIn){const result=await api.workspaces();if(live){setWorkspaces(result.workspaces);if(result.workspaces[0]){setWorkspace(result.workspaces[0].id);setDates(initialDates());setSample(false);}}}}).catch(e=>{if(live)setMessage(e.message);});return()=>{live=false;};},[api]);
 useEffect(()=>{let live=true;setLoaded(false);setDetail(null);setSelectedUnit(null);setChecked([]);if(sample){setLoaded(true);return;}if(!workspace)return;let range;try{range=stagingDateRange(dates.start,dates.end);}catch(e){setError((e as Error).message);return;}api.calendar(workspace,range.start,range.end).then(c=>{if(live){setCalendar(c);setLoaded(true);}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[api,workspace,sample,dates.start,dates.end,refresh]);
 const view:StagingCalendar=sample?{units:stagingSample.units.map(u=>({...u,available:!u.retired&&['good','fair'].includes(u.condition)&&!(u.id==='sample-sofa-01'&&stagingOverlap(dates,stagingSample.reservations[0]))})),reservations:stagingSample.reservations.filter(r=>stagingOverlap(dates,r)),next:null}:calendar;
 async function run(action:()=>Promise<void>,reload=true){if(busyRef.current)return;setBusy(true);setError('');setMessage('');try{await action();if(reload)setRefresh(v=>v+1);}catch(e){setError((e as Error).message);setRefresh(v=>v+1);}finally{setBusy(false);}}
 async function showReservation(id:string){if(busyRef.current)return;setError('');if(sample){setDetail({reservation:stagingSample.reservations[0],units:[{...stagingSample.units[0],status:'reserved',conditionOut:'good',conditionIn:null,returnNote:null,packedAt:null,returnedAt:null}],events:[]});return;}setBusy(true);try{setDetail(await api.detail(workspace,id));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function chooseUnit(unit:StockUnit){if(busyRef.current)return;setSelectedUnit(unit);setEditCondition(unit.condition);setRetired(unit.retired);setUnitHistory({events:[],next:null});if(sample){setUnitHistory({events:stagingSample.events.filter(e=>e.unitId===unit.id),next:null});return;}setBusy(true);try{const result=await api.unitDetail(workspace,unit.id);setSelectedUnit(result.unit);setEditCondition(result.unit.condition);setRetired(result.unit.retired);setUnitHistory(result);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function preview(unit:StockUnit){if(busyRef.current)return;const proxy=toStagingVisualProxy(unit,catalog);if(proxy)onPreviewProxy?.(proxy);}
 return <section className="staging-panel" aria-label="Staging inventory">
  <header><div><p className="staging-kicker">Professional pilot</p><h2>Staging inventory</h2></div><button disabled={busy} onClick={onClose} aria-label="Close staging inventory">Close</button></header>
  <p>Track individual physical pieces, reserve dates, and check items out and back in. Catalog models are visual proxies; editing your home never changes this ledger.</p>
  <nav aria-label="Inventory source"><button disabled={busy} aria-pressed={sample} onClick={()=>{setSample(true);setDates({start:'2026-10-01',end:'2026-10-08'});setMessage('');}}>Explore sample inventory</button>{workspaces.map(w=><button disabled={busy} key={w.id} aria-pressed={!sample&&workspace===w.id} onClick={()=>{setSample(false);setWorkspace(w.id);setDates(initialDates());}}>{w.name} · {w.role}</button>)}</nav>
  {sample&&<aside className="staging-note"><strong>Read-only sample · no real stock or reservations</strong><p>This fictional ledger shows one booked sofa, a second free unit, and a table awaiting repair. Real reservations require a staging-business pilot and an explicitly enrolled owner. Business pilot acceptance has not been established.</p><button disabled={busy} onClick={()=>setDates({start:'2026-10-01',end:'2026-10-08'})}>Show sample booking week</button></aside>}
  {status&&!status.enabled&&<p>Real reservations are currently disabled. Local planning and the sample remain available.</p>}
  {status?.enabled&&!status.signedIn&&<p>Sign in through the project library to check pilot access.</p>}
  {status?.canEnroll&&<form onSubmit={e=>{e.preventDefault();void run(async()=>{const result=await api.enroll(newInventory);setWorkspaces(v=>[...v,result.workspace]);setWorkspace(result.workspace.id);setSample(false);setMessage('Private pilot inventory created. Add only stock you physically own.');});}}><label>New pilot inventory name<input required maxLength={80} value={newInventory} onChange={e=>setNewInventory(e.target.value)}/></label><button disabled={busy||!newInventory.trim()}>Create private pilot inventory</button></form>}
  {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
  <div className="staging-dates"><label>Stock needed from<input type="date" disabled={busy} value={dates.start} onChange={e=>setDates(v=>({...v,start:e.target.value}))}/></label><label>First free day after return<input type="date" disabled={busy} value={dates.end} onChange={e=>setDates(v=>({...v,end:e.target.value}))}/></label>{!sample&&<button disabled={busy} onClick={()=>setRefresh(v=>v+1)}>Refresh availability</button>}</div>
  <p>Dates reserve whole UTC calendar days, up to 366 days. Include transport and cleaning time before the first free day. Availability is a preview; the server checks again when you reserve.</p>
  {!sample&&!loaded?<p role="status">{error?"Availability is unavailable. Refresh to try again.":"Loading private inventory…"}</p>:<>
  <h3>Physical stock · {view.units.length} {view.units.length===1?'unit':'units'}</h3><div className="staging-table"><table><thead><tr><th>Choose</th><th>Stock code / piece</th><th>Condition</th><th>Availability</th><th>Visual proxy</th></tr></thead><tbody>{view.units.map(u=><tr key={u.id}><td><input type="checkbox" aria-label={`Reserve ${u.stockCode}`} disabled={!canWrite||busy||!u.available} checked={checked.includes(u.id)} onChange={e=>setChecked(v=>e.target.checked?[...v,u.id]:v.filter(id=>id!==u.id))}/></td><td><button disabled={busy} onClick={()=>chooseUnit(u)}>{u.stockCode}</button><br/>{u.label}<small>{u.widthMm} × {u.depthMm} × {u.heightMm} mm</small></td><td>{u.condition}{u.retired?' · retired':''}</td><td>{u.available?'Free for these dates':'Unavailable'}</td><td>{u.catalogId}{onPreviewProxy&&<button disabled={busy||!toStagingVisualProxy(u,catalog)} onClick={()=>preview(u)}>Preview piece</button>}</td></tr>)}</tbody></table></div>
  {!view.units.length&&<p>No physical units yet. Adding a catalog piece to the floor plan does not create stock.</p>}
  {selectedUnit&&<aside className="staging-note"><h4>{selectedUnit.stockCode} · stock condition</h4><label>Condition<select disabled={!canWrite||busy} value={editCondition} onChange={e=>setEditCondition(e.target.value as StockCondition)}>{STOCK_CONDITIONS.map(c=><option key={c}>{c}</option>)}</select></label><label><input type="checkbox" disabled={!canWrite||busy} checked={retired} onChange={e=>setRetired(e.target.checked)}/>Retired from service</label>{canWrite&&<button disabled={busy} onClick={()=>void run(async()=>{await api.updateUnit(workspace,selectedUnit,editCondition,retired);setMessage('Stock condition recorded. Existing reservations remain in the ledger; check their pack lists.');})}>Record stock condition</button>}{<ul>{unitHistory.events.map(e=><li key={e.id}>{e.at.slice(0,10)} · {stagingEventLabel(e.kind)} · {String(e.detail.condition??e.detail.conditionIn??e.detail.conditionOut??'Recorded')}</li>)}</ul>}{unitHistory.next&&unitHistory.events.length<500&&<button disabled={busy} onClick={()=>void run(async()=>{const result=await api.unitDetail(workspace,selectedUnit.id,unitHistory.next!);setUnitHistory(v=>({events:[...v.events,...result.events],next:result.next}));},false)}>Older stock history</button>}{unitHistory.next&&unitHistory.events.length>=500&&<p>Showing the latest 500 stock events. Older records remain in the private ledger.</p>}</aside>}
  {canWrite&&<form onSubmit={e=>{e.preventDefault();void run(async()=>{await api.reserve(workspace,{requestId:crypto.randomUUID(),propertyLabel:property,...dates,unitIds:checked});setChecked([]);setMessage('Reservation confirmed for every selected physical unit.');});}}><label>Private property label<input required maxLength={100} value={property} onChange={e=>setProperty(e.target.value)}/></label><button disabled={busy||!checked.length||checked.length>50}>Reserve {checked.length} physical {checked.length===1?'unit':'units'}</button></form>}
  <h3>Reservation calendar</h3><div className="staging-table"><table><thead><tr><th>Property</th><th>From</th><th>First free day</th><th>State</th><th>Pack / return list</th></tr></thead><tbody>{view.reservations.map(r=><tr key={r.id}><td>{r.propertyLabel}</td><td>{r.start}</td><td>{r.end}</td><td>{r.state}</td><td><button disabled={busy} onClick={()=>void showReservation(r.id)}>Open {r.unitCount} {r.unitCount===1?'unit':'units'}</button></td></tr>)}</tbody></table></div>
  {!view.reservations.length&&<p>No reservations in this date range.</p>}{view.next&&<button disabled={busy} onClick={()=>void run(async()=>{const next=await api.calendar(workspace,dates.start,dates.end,view.next!);setCalendar(v=>({...next,reservations:[...v.reservations,...next.reservations]}));},false)}>Load more reservations</button>}
  {detail&&<section aria-label="Pack and return list" className="staging-note"><h3>{detail.reservation.propertyLabel} · pack and return list</h3><p>{detail.reservation.start} to {detail.reservation.end} (first free day) · version {detail.reservation.revision}</p><ul>{detail.units.map(u=><li key={u.id}><strong>{u.stockCode}</strong> · {u.label} · {u.status} · out: {u.conditionOut}{u.conditionIn&&` · returned: ${u.conditionIn}`}{u.returnNote&&<p>{u.returnNote}</p>}{onPreviewProxy&&<button disabled={busy} onClick={()=>preview(u)}>Preview {u.stockCode}</button>}{canWrite&&u.status==='packed'&&<button disabled={busy} onClick={()=>void run(async()=>{await api.action(workspace,detail.reservation.id,'return',{expectedRevision:detail.reservation.revision,unitId:u.id,condition:returnCondition,note:returnNote});setMessage(`Return recorded for ${u.stockCode}. Refresh its list to inspect the updated history.`);})}>Record return of {u.stockCode}</button>}</li>)}</ul>
   {canWrite&&detail.reservation.state==='reserved'&&<div><button disabled={busy} onClick={()=>void run(async()=>{await api.action(workspace,detail.reservation.id,'pack',{expectedRevision:detail.reservation.revision});setMessage('Every unit marked packed.');})}>Confirm all units packed</button><button disabled={busy} onClick={()=>void run(async()=>{await api.action(workspace,detail.reservation.id,'cancel',{expectedRevision:detail.reservation.revision});setMessage('Reservation cancelled. Its dates, units and ledger remain recorded.');})}>Cancel reservation · keep history</button></div>}
   {canWrite&&detail.reservation.state==='packed'&&<fieldset><legend>Condition for the next returned unit</legend><label>Return condition<select value={returnCondition} onChange={e=>setReturnCondition(e.target.value as StockCondition)}>{STOCK_CONDITIONS.map(c=><option key={c}>{c}</option>)}</select></label><label>Return discrepancy or note<input maxLength={300} value={returnNote} onChange={e=>setReturnNote(e.target.value)}/></label><p>Damaged or missing units stay unavailable. Record one physical return at a time.</p></fieldset>}
   <h4>Preserved reservation ledger</h4><ul>{detail.events.map(e=><li key={e.id}>{e.at} · {stagingEventLabel(e.kind)}{e.detail.note?` · ${e.detail.note}`:''}</li>)}</ul>{sample&&<p>Sample reservation only. Packing, returns and cancellation are disabled.</p>}
  </section>}
  </>}
  {canWrite&&<details><summary>Add one physical stock unit</summary><p>Enter the code physically attached to one piece. This adds stock to the private inventory only. The catalog choice is a visual approximation.</p><form onSubmit={e=>{e.preventDefault();void run(async()=>{await api.addUnit(workspace,{requestId:crypto.randomUUID(),stockCode,label,catalogId,...dimensions,condition:stockCondition});setStockCode('');setLabel('');setMessage('Physical stock unit registered.');});}}><label>Physical stock code<input required maxLength={48} value={stockCode} onChange={e=>setStockCode(e.target.value)}/></label><label>Stock label<input required maxLength={100} value={label} onChange={e=>setLabel(e.target.value)}/></label><label>Catalog visual proxy<select value={catalogId} onChange={e=>{setCatalogId(e.target.value);const c=catalog.find(v=>v.id===e.target.value);if(c)setDimensions({widthMm:c.widthMm,depthMm:c.depthMm,heightMm:c.heightMm});}}>{catalog.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{(['widthMm','depthMm','heightMm'] as const).map(key=><label key={key}>{key==='widthMm'?'Measured width':key==='depthMm'?'Measured depth':'Measured height'} (mm)<input type="number" min={10} max={20000} step={1} required value={dimensions[key]} onChange={e=>setDimensions(v=>({...v,[key]:Number(e.target.value)}))}/></label>)}<label>Initial condition<select value={stockCondition} onChange={e=>setStockCondition(e.target.value as StockCondition)}>{STOCK_CONDITIONS.map(c=><option key={c}>{c}</option>)}</select></label><button disabled={busy}>Register physical unit</button></form></details>}
 </section>;
}





