import {openDB} from 'idb';
import {canonicalStill,parseStillRecord,STILL_LIMITS,verifyStillRequest,type StillRecord,type StillState} from './stillRender';
const database=()=>openDB('nook-still-render-queue',1,{upgrade(db){db.createObjectStore('jobs',{keyPath:'id'});}});
const transitions:Record<StillState,StillState[]>={queued:['queued','submitting','cancelled','cancel-unknown','needs-review'],submitting:['submission-unknown','running','failed','cancelled','needs-review','cancel-unknown'],'submission-unknown':['submission-unknown','running','failed','cancelled','needs-review','cancel-unknown'],running:['running','failed','cancelled','needs-review','cancel-unknown'],'cancel-unknown':['cancel-unknown','running','failed','cancelled','needs-review'],'needs-review':['needs-review','accepted'],accepted:['accepted'],failed:['failed'],cancelled:['cancelled']};
export async function listStillRecords(projectId:string):Promise<StillRecord[]> {const db=await database();try{return (await db.getAll('jobs')).filter(v=>v.projectId===projectId).map(parseStillRecord).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));}finally{db.close();}}
/** Exact payload verified before the atomic transaction. A failed reservation prevents network submission. */
export async function saveStillRecord(input:StillRecord,expectedRevision:number):Promise<StillRecord>{const next=parseStillRecord(input);await verifyStillRequest(next.request);if(next.revision!==expectedRevision)throw new Error('The render queue changed. Refresh before continuing.');const db=await database(),tx=db.transaction('jobs','readwrite');try{const raw=await tx.store.get(next.id),old=raw===undefined?undefined:parseStillRecord(raw);if(old?.revision!==expectedRevision&&!(old===undefined&&expectedRevision===0))throw new Error('The render queue changed in another tab. Refresh before continuing.');if(old){if(old.projectId!==next.projectId||old.sourcePlanHash!==next.sourcePlanHash||old.sourceUpdatedAt!==next.sourceUpdatedAt||canonicalStill(old.request)!==canonicalStill(next.request)||old.createdAt!==next.createdAt||old.parentJobId!==next.parentJobId)throw new Error('A render request is immutable. Create a separate attempt.');if(!transitions[old.state].includes(next.state))throw new Error('This render job cannot move backwards. Refresh its status.');if(old.connection&&canonicalStill(old.connection)!==canonicalStill(next.connection))throw new Error('A submitted request belongs to its original server.');if(old.serverJobId&&old.serverJobId!==next.serverJobId)throw new Error('This response belongs to a different render job.');if(old.result&&canonicalStill(old.result)!==canonicalStill(next.result))throw new Error('A result cannot be replaced after review.');}
const all=await tx.store.getAll();if(!old&&all.length>=STILL_LIMITS.jobs)throw new Error('The device queue holds up to 12 jobs. Remove a finished job first.');const saved={...next,revision:expectedRevision+1,updatedAt:new Date().toISOString()};const bytes=all.filter(r=>r.id!==next.id).reduce((n,r)=>n+new TextEncoder().encode(JSON.stringify(r)).length,0)+new TextEncoder().encode(JSON.stringify(saved)).length;if(bytes>STILL_LIMITS.storageBytes)throw new Error('The render queue has reached its 96 MB device limit. Export and remove a finished result.');await tx.store.put(saved);await tx.done;return saved;}catch(error){try{tx.abort();}catch{}await tx.done.catch(()=>{});throw error;}finally{db.close();}}
export async function removeStillRecord(record:StillRecord){if(record.state==='queued'&&record.exportedAt||!['queued','failed','cancelled','needs-review','accepted'].includes(record.state))throw new Error('Check or cancel this request first; its server may still be rendering.');const db=await database(),tx=db.transaction('jobs','readwrite');try{const current=await tx.store.get(record.id);if(current?.projectId!==record.projectId||current?.revision!==record.revision)throw new Error('The queue changed. Refresh before removing a job.');await tx.store.delete(record.id);await tx.done;}catch(e){try{tx.abort();}catch{}await tx.done.catch(()=>{});throw e;}finally{db.close();}}
