import {useEffect,useRef,useState} from 'react';
import type {PlanDocumentV1} from './types';
import type {ListingMedia} from './listingTypes';
import {normalizeListingImage} from './listingMedia';
import {cancelStillJob,checkStillJob,discoverStillServer,startStillJob,stillEndpoint,type StillCapability} from './localStillRender';
import {downloadStillPackage,makeStillRecord,parseStillResult,retryStillRecord,stillHash,STILL_LIMITS,verifyStillRequest,type StillRecord,type StillMode,type StillEvaluation} from './stillRender';
import {listStillRecords,removeStillRecord,saveStillRecord} from './stillRenderStorage';
import {buildStillEvaluationPack,downloadStillEvaluationPack} from './stillRenderEvaluation';
import './design-assistant.css';
export interface StillRenderPanelProps {plan:PlanDocumentV1;media:ListingMedia[];onAddToListing?:(media:ListingMedia)=>Promise<void>|void;onBusyChange?:(busy:boolean)=>void}
const labels={queued:'Ready locally',submitting:'Submission may be in progress','submission-unknown':'Submission unknown',running:'Server working','needs-review':'Result needs your review',accepted:'Reviewed result',failed:'Failed',cancelled:'Cancelled','cancel-unknown':'Cancellation unconfirmed'};
export function StillRenderPanel({plan,media,onAddToListing,onBusyChange}:StillRenderPanelProps){
 const shots=media.filter(m=>m.kind==='render'&&m.camera&&plan.floors.some(f=>f.id===m.camera?.floorId));
 const [jobs,setJobs]=useState<StillRecord[]>([]),[selectedId,setSelectedId]=useState(''),[shotId,setShotId]=useState(''),[quality,setQuality]=useState<'preview'|'final'>('preview'),[mode,setMode]=useState<StillMode>('fixed-geometry'),[includeImage,setIncludeImage]=useState(false),[endpoint,setEndpoint]=useState(''),[token,setToken]=useState(''),[ownServer,setOwnServer]=useState(false),[capability,setCapability]=useState<StillCapability|null>(null),[model,setModel]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[confirmRemove,setConfirmRemove]=useState(false),[externalStopped,setExternalStopped]=useState(false),[evaluation,setEvaluation]=useState<StillEvaluation>({geometry:false,furnishings:false,appearance:false,notes:''});
 const alive=useRef(true),running=useRef(false),epoch=useRef(0),controller=useRef<AbortController|undefined>(undefined),latest=useRef(plan);latest.current=plan;const selected=jobs.find(j=>j.id===selectedId),shot=shots.find(s=>s.id===shotId);
 const [matchesCurrent,setMatchesCurrent]=useState<boolean|null>(null);
 useEffect(()=>()=>{alive.current=false;epoch.current++;controller.current?.abort();onBusyChange?.(false);},[]);
 useEffect(()=>{alive.current=true;epoch.current++;controller.current?.abort();running.current=false;setBusy(false);onBusyChange?.(false);setJobs([]);setSelectedId('');setShotId('');setIncludeImage(false);setConsent(false);setError('');const current=epoch.current;void listStillRecords(plan.id).then(v=>{if(alive.current&&current===epoch.current){setJobs(v);setSelectedId(v[0]?.id??'');}}).catch(e=>{if(alive.current&&current===epoch.current)setError(e.message);});},[plan.id]);
 useEffect(()=>{setConsent(false);setConfirmRemove(false);setExternalStopped(false);setEvaluation(selected?.evaluation??{geometry:false,furnishings:false,appearance:false,notes:''});},[selectedId]);
 useEffect(()=>{let cancelled=false;setMatchesCurrent(null);if(selected)void stillHash(plan).then(hash=>{if(!cancelled)setMatchesCurrent(hash===selected.sourcePlanHash);}).catch(()=>{if(!cancelled)setMatchesCurrent(false);});return()=>{cancelled=true;};},[plan,selectedId]);
 async function run(work:(valid:()=>boolean,signal:AbortSignal)=>Promise<void>){if(running.current)return;running.current=true;const current=epoch.current,projectId=plan.id;controller.current=new AbortController();const valid=()=>alive.current&&epoch.current===current&&latest.current.id===projectId;setBusy(true);onBusyChange?.(true);setError('');setNotice('');try{await work(valid,controller.current.signal);}catch(e){if(valid())setError((e as Error).message);}finally{if(current===epoch.current)running.current=false;if(valid()){try{const refreshed=await listStillRecords(projectId);if(valid())setJobs(refreshed);}catch(e){if(valid())setError((e as Error).message);}setBusy(false);}if(current===epoch.current)onBusyChange?.(false);}}
 async function enqueue(){if(!shot?.camera)return;const base=plan;await run(async valid=>{const record=await makeStillRecord(base,{id:shot.id,name:shot.title,camera:shot.camera!,...(includeImage?{referenceImage:shot.image,referenceProvenance:'saved-revision-unverified' as const}:{})},quality,mode,includeImage);if(latest.current!==base)throw new Error('The home changed while preparing this job. Capture its current revision again.');const saved=await saveStillRecord(record,0);if(valid()){setSelectedId(saved.id);setNotice('Exact plan and camera snapshot added to the device queue. No server was contacted.');}});}
 async function importResult(file?:File){if(!selected||!file)return;const job=selected;await run(async valid=>{if(file.size>STILL_LIMITS.packageBytes)throw new Error('This result package is too large.');await verifyStillRequest(job.request);const result=parseStillResult(JSON.parse(await file.text()),job.request);const saved=await saveStillRecord({...job,result,state:'needs-review'},job.revision);if(valid()){setSelectedId(saved.id);setNotice('Result matched this exact request. Review its geometry and furnishings before using it.');}});}
 async function addToListing(){if(!selected?.result||selected.state!=='accepted'||!onAddToListing)return;const job=selected;await run(async valid=>{const image=await normalizeListingImage(job.result!.image);if(!valid())return;await onAddToListing({id:'still-'+job.id,title:(job.request.shot.name+' · '+job.request.settings.quality).slice(0,160),caption:job.result!.kind==='concept'?'Reviewed AI design concept; not proof of property condition.':'Reviewed design render; not a property photograph.',kind:job.result!.kind,image,sourceImage:job.result!.image,camera:job.request.shot.camera,floorId:job.request.shot.camera.floorId,seconds:5});if(valid())setNotice('Added as a separately labeled design image. Original property photos stay unchanged.');});}
 const sameServer=(()=>{try{return !!selected?.connection&&stillEndpoint(endpoint)===selected.connection.endpoint;}catch{return false;}})();
 const active=selected&&['submitting','submission-unknown','running','cancel-unknown'].includes(selected.state);
 return <section className="design-tools" aria-label="Still-render queue"><header><p className="design-eyebrow">One view, one fixed request</p><h2>Final still renders</h2><p>Prepare a portable package or explicitly use your own compatible still-render server. The video connector does not support this new capability. Nothing connects or starts automatically.</p></header>{error&&<p role="alert" className="design-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <fieldset disabled={busy}><legend>Prepare a local job</legend><label>Saved design camera<select value={shotId} onChange={e=>{setShotId(e.target.value);setIncludeImage(false);}}><option value="">Choose a saved 3D render</option>{shots.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label>{!shots.length&&<p>Save a 3D camera render in Listing Studio first.</p>}
 <div className="design-row"><label>Quality<select value={quality} onChange={e=>setQuality(e.target.value as typeof quality)}><option value="preview">Preview · 960 × 540</option><option value="final">Final · 3840 × 2160</option></select></label><label>Output mode<select value={mode} onChange={e=>setMode(e.target.value as StillMode)}><option value="fixed-geometry">Fixed geometry render</option><option value="generative-styling">Generative design concept</option></select></label></div>
 {shot&&<><img className="still-reference" src={shot.image} alt="Selected saved design render"/><label className="design-check"><input type="checkbox" checked={includeImage} onChange={e=>setIncludeImage(e.target.checked)}/>Include this image’s visible contents, including any personal artwork</label><p>Optional reference only: its capture revision is unverified. The package uses the current plan with this saved camera. Private notes, budget data and uploaded original files are excluded.</p></>}
 <button disabled={!shot} onClick={()=>void enqueue()}>Add exact snapshot to queue</button></fieldset>
 <fieldset disabled={busy}><legend>Optional: connect my still server</legend><label>Server address<input value={endpoint} placeholder="https://your-server.example" onChange={e=>{setEndpoint(e.target.value);setToken('');setCapability(null);setConsent(false);setOwnServer(false);}}/></label><label>Temporary token (never saved)<input type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)}/></label><label className="design-check"><input type="checkbox" checked={ownServer} onChange={e=>setOwnServer(e.target.checked)}/>This is my server, and I want to check its capabilities and browser access</label><button disabled={!ownServer||!endpoint} onClick={()=>void run(async(valid,signal)=>{const result=await discoverStillServer(endpoint,token,signal);if(valid()){setCapability(result);setModel(result.models[0].id);setNotice('Still capability responded. This does not prove GPU compatibility or rendering quality.');}})}>Check still capability</button>
 {capability&&<label>Still model<select value={model} onChange={e=>{setModel(e.target.value);setConsent(false);}}>{capability.models.map(m=><option key={m.id} value={m.id}>{m.name} · {m.modes.join(', ')}</option>)}</select></label>}</fieldset>
 <label>Device queue ({jobs.length}/{STILL_LIMITS.jobs})<select disabled={busy} value={selectedId} onChange={e=>setSelectedId(e.target.value)}><option value="">Choose a job</option>{jobs.map(j=><option value={j.id} key={j.id}>{j.request.shot.name} · {j.request.settings.quality} · {labels[j.state]}</option>)}</select></label>
 {selected&&<section aria-label="Selected render job"><h3>{selected.request.shot.name}</h3><p><strong>{labels[selected.state]}</strong>{selected.progress===undefined?'':` · ${selected.progress}%`} · {selected.request.settings.mode}</p><p>Snapshot saved {new Date(selected.createdAt).toLocaleString()}. Later home edits do not change this request.</p>{matchesCurrent===false&&<p className="design-warning">The current home has changed. This job still renders its original snapshot.</p>}{selected.error&&<p className="design-warning">{selected.error}</p>}
 <fieldset disabled={busy}><legend>Export or run this exact request</legend><button onClick={()=>void run(async valid=>{await verifyStillRequest(selected.request);const saved=await saveStillRecord({...selected,exportedAt:new Date().toISOString()},selected.revision);if(valid()){downloadStillPackage(saved.request);setNotice('Package exported. No renderer was started; use a compatible local tool, then import its result.');}})}>Export portable job package</button><label>Import matching result package<input type="file" accept="application/json,.json" disabled={['accepted','needs-review','failed','cancelled'].includes(selected.state)} onChange={e=>{void importResult(e.target.files?.[0]);e.target.value='';}}/></label>
 {selected.state==='queued'&&<>{selected.exportedAt&&<div className="design-warning"><p>This request was exported and may be running elsewhere. Import its result, or confirm it is not running before a server submission.</p><label className="design-check"><input type="checkbox" checked={externalStopped} onChange={e=>setExternalStopped(e.target.checked)}/>I confirmed no external render is running for this package</label><button disabled={!externalStopped} onClick={()=>void run(async()=>{await saveStillRecord({...selected,exportedAt:undefined},selected.revision);})}>Allow a server start</button></div>}<label className="design-check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Send this exact snapshot{selected.request.shot.referenceImage?' and its included image':''} to the selected server; my server may consume compute</label><button disabled={!ownServer||!capability||!consent||!!selected.exportedAt} onClick={()=>void run(async(_valid,signal)=>{await startStillJob(selected,{endpoint,model},token,capability!,consent,signal);})}>Start selected job on my server</button></>}
 {active&&selected.connection&&<><p>Recovery server: {selected.connection.endpoint}. Status checks never resubmit the job.</p>{!sameServer&&<button onClick={()=>{setEndpoint(selected.connection!.endpoint);setModel(selected.connection!.model);setToken('');setOwnServer(false);setCapability(null);}}>Use this job’s server address</button>}<button disabled={!sameServer||!ownServer} onClick={()=>void run(async(_valid,signal)=>{await checkStillJob(selected,token,signal);})}>Check status by request ID</button></>}
 {(['queued','submitting','submission-unknown','running'].includes(selected.state)||(selected.state==='cancel-unknown'&&!!selected.connection))&&<button disabled={!!selected.connection&&(!sameServer||!ownServer)} onClick={()=>void run(async(_valid,signal)=>{await cancelStillJob(selected,token,signal);})}>Cancel / request cancellation</button>}
 {selected.state==='cancel-unknown'&&!selected.connection&&<><p>The exported package may be running elsewhere. This app cannot cancel that external process.</p><label className="design-check"><input type="checkbox" checked={externalStopped} onChange={e=>setExternalStopped(e.target.checked)}/>I confirmed the external renderer has stopped this request</label><button disabled={!externalStopped} onClick={()=>void run(async()=>{await saveStillRecord({...selected,state:'cancelled',error:undefined},selected.revision);})}>Confirm externally cancelled</button></>}
 {['failed','cancelled'].includes(selected.state)&&<button onClick={()=>void run(async valid=>{const retry=await retryStillRecord(selected),saved=await saveStillRecord(retry,0);if(valid()){setSelectedId(saved.id);setNotice('A separate retry is queued locally. It has not been submitted.');}})}>Queue a separate retry</button>}
 <button disabled={!!active||(selected.state==='queued'&&!!selected.exportedAt)} onClick={()=>setConfirmRemove(true)}>Remove local job</button>{confirmRemove&&<div className="design-warning"><p>Remove this job and its stored images from this device? Export anything you want to keep first.</p><button onClick={()=>void run(async valid=>{await removeStillRecord(selected);if(valid()){setSelectedId('');setConfirmRemove(false);}})}>Confirm removal</button><button onClick={()=>setConfirmRemove(false)}>Keep job</button></div>}
 </fieldset>
 {selected.result&&<section aria-label="Review still output"><h3>Compare before using</h3><div className="still-compare"><figure>{selected.request.shot.referenceImage?<img src={selected.request.shot.referenceImage} alt="Original saved design reference"/>:<p>No reference image was included.</p>}<figcaption>Saved design reference · capture revision may differ</figcaption></figure><figure><img src={selected.result.image} alt="New rendered design output"/><figcaption>{selected.result.kind==='concept'?'Generative design concept':'Fixed-geometry design render'} · {selected.result.engine}</figcaption></figure></div><p>{selected.result.runtimeMs===undefined?'Runtime not reported.':`Reported runtime: ${(selected.result.runtimeMs/1000).toFixed(1)} seconds.`} Provider labels and matching hashes do not prove visual fidelity.</p>
 <fieldset disabled={busy||selected.state==='accepted'}><legend>My output check</legend>{(['geometry','furnishings','appearance'] as const).map(key=><label className="design-check" key={key}><input type="checkbox" checked={evaluation[key]} onChange={e=>setEvaluation(old=>({...old,[key]:e.target.checked}))}/>{key==='geometry'?'Walls, openings and room proportions match':key==='furnishings'?'Furniture count, dimensions and placement match':'Lighting, materials and image quality are usable'}</label>)}<label>Review notes<textarea maxLength={1000} value={evaluation.notes} onChange={e=>setEvaluation(old=>({...old,notes:e.target.value}))}/></label><button disabled={!evaluation.geometry||!evaluation.furnishings||!evaluation.appearance} onClick={()=>void run(async()=>{await saveStillRecord({...selected,state:'accepted',evaluation},selected.revision);})}>Accept this design output</button></fieldset>
 {selected.state==='accepted'&&onAddToListing&&<button disabled={busy} onClick={()=>void addToListing()}>Add as separate listing design image</button>}<button onClick={()=>{const a=document.createElement('a');a.href=selected.result!.image;a.download='still-'+selected.id+'.'+(selected.result!.image.startsWith('data:image/png')?'png':selected.result!.image.startsWith('data:image/webp')?'webp':'jpg');a.click();}}>Download full result</button></section>}
 </section>}
 <button disabled={busy} onClick={()=>void run(async()=>{})}>Refresh local queue</button>
 <details><summary>Evaluate my still renderer</summary><p>Export three synthetic rooms to compare geometry, furnishings, image quality and reported runtime. This prepares files only; run them explicitly on your renderer.</p><button disabled={busy} onClick={()=>void run(async valid=>{const pack=await buildStillEvaluationPack();if(valid()){downloadStillEvaluationPack(pack);setNotice('Three evaluation requests exported. No renderer has run.');}})}>Export evaluation set</button></details>
 </section>;
}

