import {reviewPlan} from './clientReview';
import {publicAtmospherePlan} from './sceneAtmosphere';
import {validatePlan} from './planValidation';
import {validCameraShot,type CameraShotPose} from './walkthrough';
import {isListingImage} from './listingTypes';
import {imageDimensions} from './imageDimensions';
import type {PlanDocumentV1} from './types';

export const STILL_LIMITS={jobs:12,storageBytes:96*1024*1024,packageBytes:12*1024*1024,imageChars:8*1024*1024,pixels:16_000_000} as const;
export type StillMode='fixed-geometry'|'generative-styling';
export type StillState='queued'|'submitting'|'submission-unknown'|'running'|'needs-review'|'accepted'|'failed'|'cancelled'|'cancel-unknown';
export interface StillRequest {schema:'nook-still-render/1';requestId:string;createdAt:string;plan:PlanDocumentV1;shot:{id:string;name:string;camera:CameraShotPose;referenceImage?:string;referenceProvenance?:'captured-with-snapshot'|'saved-revision-unverified'};settings:{quality:'preview'|'final';mode:StillMode;width:number;height:number};payloadHash:string}
export interface StillResult {schema:'nook-still-result/1';requestId:string;payloadHash:string;image:string;kind:'render'|'concept';engine:string;runtimeMs?:number}
export interface StillEvaluation {geometry:boolean;furnishings:boolean;appearance:boolean;notes:string}
export interface StillRecord {version:1;id:string;revision:number;projectId:string;sourcePlanHash:string;sourceUpdatedAt:string;request:StillRequest;state:StillState;createdAt:string;updatedAt:string;connection?:{endpoint:string;model:string};serverJobId?:string;progress?:number;error?:string;result?:StillResult;evaluation?:StillEvaluation;parentJobId?:string;exportedAt?:string}
export const stillId=(v:unknown):v is string=>typeof v==='string'&&/^[a-zA-Z0-9_-]{1,160}$/.test(v);
const object=(v:unknown):v is Record<string,any>=>!!v&&typeof v==='object'&&!Array.isArray(v);
function fail():never{throw new Error('This still-render package contains invalid or unsupported data.');}
const exact=(v:unknown,keys:string[])=>{if(!object(v)||Object.keys(v).some(k=>!keys.includes(k)))fail();return v;};
const text=(v:unknown,max:number)=>typeof v==='string'&&v.length>0&&v.length<=max&&!/[\u0000-\u001f\u007f]/.test(v);
export function canonicalStill(value:unknown):string {if(Array.isArray(value))return '['+value.map(canonicalStill).join(',')+']';if(object(value))return '{'+Object.keys(value).filter(k=>value[k]!==undefined).sort().map(k=>JSON.stringify(k)+':'+canonicalStill(value[k])).join(',')+'}';return JSON.stringify(value);}
export async function stillHash(value:unknown){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonicalStill(value)))),v=>v.toString(16).padStart(2,'0')).join('');}
export function stillVisualPlan(plan:PlanDocumentV1){const visual=reviewPlan(plan,'Still-render snapshot'),lighting=publicAtmospherePlan(plan).environment?.atmosphere;visual.environment={...visual.environment!,citySource:'standard',...(lighting?{atmosphere:lighting}:{})};return visual;}
export function validStillImage(value:unknown):value is string {try{if(!isListingImage(value,STILL_LIMITS.imageChars))return false;const d=imageDimensions(Uint8Array.from(atob(value.slice(value.indexOf(',')+1)),c=>c.charCodeAt(0)));return d.width>0&&d.height>0&&d.width<=4096&&d.height<=4096&&d.width*d.height<=STILL_LIMITS.pixels;}catch{return false;}}
export function parseStillRequest(value:unknown):StillRequest {
 const v=exact(value,['schema','requestId','createdAt','plan','shot','settings','payloadHash']);if(v.schema!=='nook-still-render/1'||!stillId(v.requestId)||!text(v.createdAt,40)||!Number.isFinite(Date.parse(v.createdAt))||typeof v.payloadHash!=='string'||!/^[a-f0-9]{64}$/.test(v.payloadHash))fail();
 validatePlan(v.plan);if(canonicalStill(stillVisualPlan(v.plan))!==canonicalStill(v.plan))throw new Error('This render package contains private or unsupported plan metadata.');const shot=exact(v.shot,['id','name','camera','referenceImage','referenceProvenance']);if(!stillId(shot.id)||!text(shot.name,120)||!validCameraShot(shot.camera)||!v.plan.floors.some((f:{id:string})=>f.id===shot.camera.floorId))fail();exact(shot.camera,['version','kind','floorId','target','alpha','beta','radius','mode','fov']);exact(shot.camera.target,['x','y','z']);
 if(shot.referenceImage!==undefined&&(!validStillImage(shot.referenceImage)||!['captured-with-snapshot','saved-revision-unverified'].includes(shot.referenceProvenance))||shot.referenceImage===undefined&&shot.referenceProvenance!==undefined)fail();
 const settings=exact(v.settings,['quality','mode','width','height']);if(!['preview','final'].includes(settings.quality)||!['fixed-geometry','generative-styling'].includes(settings.mode)||!Number.isInteger(settings.width)||!Number.isInteger(settings.height)||settings.width<256||settings.height<256||settings.width>3840||settings.height>3840||settings.width*settings.height>STILL_LIMITS.pixels)fail();
 if(new TextEncoder().encode(JSON.stringify(v)).length>STILL_LIMITS.packageBytes)fail();return structuredClone(v) as StillRequest;
}
export async function verifyStillRequest(value:unknown){const v=parseStillRequest(value),{payloadHash,...payload}=v;if(await stillHash(payload)!==payloadHash)throw new Error('This render package has changed since it was prepared.');return v;}
export async function makeStillRecord(plan:PlanDocumentV1,shot:StillRequest['shot'],quality:'preview'|'final',mode:StillMode,includeVisibleImage:boolean):Promise<StillRecord>{
 validatePlan(plan);if(shot.referenceImage&&!includeVisibleImage)throw new Error('Confirm including the visible content in the selected render.');
 const visual=stillVisualPlan(plan);
 const now=new Date().toISOString(),id=crypto.randomUUID(),payload={schema:'nook-still-render/1' as const,requestId:id,createdAt:now,plan:visual,shot:structuredClone(shot),settings:{quality,mode,width:quality==='final'?3840:960,height:quality==='final'?2160:540}};
 const request=await verifyStillRequest({...payload,payloadHash:await stillHash(payload)});
 return {version:1,id,revision:0,projectId:plan.id,sourcePlanHash:await stillHash(plan),sourceUpdatedAt:plan.updatedAt,request,state:'queued',createdAt:now,updatedAt:now};
}
export function parseStillResult(value:unknown,request:StillRequest):StillResult {const v=exact(value,['schema','requestId','payloadHash','image','kind','engine','runtimeMs']);if(v.schema!=='nook-still-result/1'||v.requestId!==request.requestId||v.payloadHash!==request.payloadHash||!validStillImage(v.image)||v.kind!==(request.settings.mode==='fixed-geometry'?'render':'concept')||!text(v.engine,120)||v.runtimeMs!==undefined&&(!Number.isFinite(v.runtimeMs)||v.runtimeMs<0||v.runtimeMs>604800000))fail();const dimensions=imageDimensions(Uint8Array.from(atob(v.image.slice(v.image.indexOf(',')+1)),c=>c.charCodeAt(0)));if(dimensions.width!==request.settings.width||dimensions.height!==request.settings.height)throw new Error('The output dimensions do not match this render request.');return structuredClone(v) as StillResult;}
export function parseStillRecord(value:unknown):StillRecord {const v=exact(value,['version','id','revision','projectId','sourcePlanHash','sourceUpdatedAt','request','state','createdAt','updatedAt','connection','serverJobId','progress','error','result','evaluation','parentJobId','exportedAt']);if(v.version!==1||!stillId(v.id)||!text(v.projectId,160)||!Number.isSafeInteger(v.revision)||v.revision<0||typeof v.sourcePlanHash!=='string'||!/^[a-f0-9]{64}$/.test(v.sourcePlanHash)||!['queued','submitting','submission-unknown','running','needs-review','accepted','failed','cancelled','cancel-unknown'].includes(v.state))fail();for(const key of ['sourceUpdatedAt','createdAt','updatedAt'])if(!text(v[key],40)||!Number.isFinite(Date.parse(v[key])))fail();const request=parseStillRequest(v.request);if(request.requestId!==v.id)fail();if(v.connection!==undefined){exact(v.connection,['endpoint','model']);if(!text(v.connection.endpoint,2048)||!text(v.connection.model,160))fail();}if(v.serverJobId!==undefined&&!stillId(v.serverJobId)||v.parentJobId!==undefined&&!stillId(v.parentJobId)||v.progress!==undefined&&(!Number.isFinite(v.progress)||v.progress<0||v.progress>100)||v.error!==undefined&&!text(v.error,500))fail();if(v.result){if(!['needs-review','accepted'].includes(v.state))fail();parseStillResult(v.result,request);}if(['needs-review','accepted'].includes(v.state)&&!v.result)fail();if(v.exportedAt!==undefined&&(!text(v.exportedAt,40)||!Number.isFinite(Date.parse(v.exportedAt))))fail();if(v.evaluation!==undefined){const e=exact(v.evaluation,['geometry','furnishings','appearance','notes']);if(['geometry','furnishings','appearance'].some(k=>typeof e[k]!=='boolean')||typeof e.notes!=='string'||e.notes.length>1000)fail();}if(v.state==='accepted'&&(!v.evaluation?.geometry||!v.evaluation?.furnishings||!v.evaluation?.appearance))fail();return structuredClone({...v,request}) as StillRecord;}
export async function retryStillRecord(record:StillRecord){if(!['failed','cancelled'].includes(record.state))throw new Error('Check or cancel the original request before creating another attempt.');const now=new Date().toISOString(),id=crypto.randomUUID(),{payloadHash:_hash,...old}=record.request,payload={...old,requestId:id,createdAt:now},request=await verifyStillRequest({...payload,payloadHash:await stillHash(payload)});return parseStillRecord({version:1,id,revision:0,projectId:record.projectId,sourcePlanHash:record.sourcePlanHash,sourceUpdatedAt:record.sourceUpdatedAt,request,state:'queued',createdAt:now,updatedAt:now,parentJobId:record.id});}
export function downloadStillPackage(request:StillRequest){const blob=new Blob([JSON.stringify(request,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`nook-still-${request.requestId}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
