import {useEffect,useMemo,useRef,useState} from 'react';
import {validatePlan} from './planValidation';
import {floorQuantityGeometry} from './surfaceGeometry';
import {defaultTakeoffSettings,evaluateSurfaceQuantities,rateFor,updateSurfaceTakeoffSettings,type CoverageRate,type QuantitySurface,type TakeoffPlan} from './surfaceTakeoff';
import {wallElevation,wallElevationSvg,elevationScales} from './wallElevation';
import {downloadSurfaceFile,elevationPrintHtml,printSurfaceDocument,surfaceQuantitiesCsv,surfaceQuantitiesHtml} from './surfaceExports';
import './surface-planning.css';

export interface SurfacePlanningPanelProps {plan:TakeoffPlan;activeFloorId?:string;disabled?:boolean;onCommit(base:TakeoffPlan,next:TakeoffPlan):void;onClose?():void}
const amount=(value:number|null)=>value===null?'Unavailable':value.toLocaleString(undefined,{maximumFractionDigits:3});
export function SurfacePlanningPanel({plan,activeFloorId,disabled=false,onCommit,onClose}:SurfacePlanningPanelProps){
  const [view,setView]=useState<'quantities'|'elevation'>('quantities'),[base,setBase]=useState(plan),[settings,setSettings]=useState(()=>structuredClone(plan.surfaceTakeoffSettings??defaultTakeoffSettings())),[floorId,setFloorId]=useState(activeFloorId??plan.floors[0]?.id??''),[wallKey,setWallKey]=useState(''),[face,setFace]=useState<'front'|'back'>('front'),[scale,setScale]=useState<number>(50),[notes,setNotes]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[rateTarget,setRateTarget]=useState<{surface:QuantitySurface;finishId?:string}>({surface:'wall'});
  const pendingSave=useRef<string|null>(null),assumptions=useRef<HTMLDetailsElement>(null);
  useEffect(()=>{if(pendingSave.current&&base!==plan){const expected=pendingSave.current;pendingSave.current=null;if(JSON.stringify(plan.surfaceTakeoffSettings)===expected){setBase(plan);setMessage('Surface assumptions saved.');}}},[plan,base]);
  const calculated=useMemo(()=>{try{return {report:evaluateSurfaceQuantities(plan,settings)};}catch(e){return {error:(e as Error).message};}},[plan,settings]);
  const geometry=useMemo(()=>{try{return {value:floorQuantityGeometry(plan,floorId)};}catch(e){return {error:(e as Error).message};}},[plan,floorId]);
  const drawing=useMemo(()=>{if(!wallKey)return {};try{const value=wallElevation(plan,floorId,wallKey,settings,{face,scale,notes});return {value,svg:wallElevationSvg(value)};}catch(e){return {error:(e as Error).message};}},[plan,floorId,wallKey,settings,face,scale,notes]);
  const rate=rateTarget.finishId?rateFor(settings,rateTarget.surface,rateTarget.finishId):settings.rates[rateTarget.surface];
  const patchRate=(patch:Partial<CoverageRate>)=>setSettings(current=>rateTarget.finishId?{...current,finishRates:[...current.finishRates.filter(r=>!(r.surface===rateTarget.surface&&r.finishId===rateTarget.finishId)),{...rateFor(current,rateTarget.surface,rateTarget.finishId!),...patch,surface:rateTarget.surface,finishId:rateTarget.finishId!}]}:{...current,rates:{...current.rates,[rateTarget.surface]:{...current.rates[rateTarget.surface],...patch}}});
  const attempt=(action:()=>void)=>{setError('');try{action();}catch(e){setError((e as Error).message);}};
  const floor=plan.floors.find(f=>f.id===floorId);
  const report=calculated.report,rows=report?.rows.filter(r=>r.floorId===floorId)??[];
  return <section className="surface-planning" aria-labelledby="surface-planning-title"><header><div><span className="eyebrow">Measure the saved design</span><h2 id="surface-planning-title">Surfaces &amp; wall drawings</h2></div>{onClose&&<button onClick={onClose}>Close</button>}</header><p>Planning estimates from the model. Review heights, openings and finish coverage before ordering. These are not construction or code-certified documents.</p>
    <div className="surface-toggles" role="group" aria-label="Surface tool"><button aria-pressed={view==='quantities'} onClick={()=>setView('quantities')}>Finish quantities</button><button aria-pressed={view==='elevation'} onClick={()=>setView('elevation')}>Wall elevations</button></div>
    <div className="surface-toggles" role="group" aria-label="Drawing floor">{plan.floors.map(f=><button key={f.id} aria-pressed={floorId===f.id} onClick={()=>{setFloorId(f.id);setWallKey('');}}>{f.name}</button>)}</div>
    <details className="surface-assumptions" ref={assumptions}><summary>Calculation assumptions</summary><p>Changes preview below. Save assumptions adds one undo step and never resizes the home.</p>{base!==plan&&<p role="status">The project changed. Reload the saved assumptions before committing this edit.</p>}
      <p>Wall faces</p><div className="surface-toggles" role="group" aria-label="Counted wall faces">{[{id:'room-side',name:'Room-facing sides'},{id:'exterior',name:'Outside footprint'},{id:'both',name:'Both sides'}].map(v=><button key={v.id} aria-pressed={settings.wallFaces===v.id} onClick={()=>setSettings({...settings,wallFaces:v.id as typeof settings.wallFaces})}>{v.name}</button>)}</div><small>Room-facing counts one boundary face and both partition faces. Outside may mean the exterior, a courtyard or a void; verify that distinction.</small>
      <div className="surface-toggles" role="group" aria-label="Opening deductions"><button aria-pressed={settings.deductOpenings} onClick={()=>setSettings({...settings,deductOpenings:true})}>Deduct openings</button><button aria-pressed={!settings.deductOpenings} onClick={()=>setSettings({...settings,deductOpenings:false})}>Gross wall area</button></div>
      <div className="surface-toggles" role="group" aria-label="Ceiling assumption"><button aria-pressed={settings.ceiling==='not-included'} onClick={()=>setSettings({...settings,ceiling:'not-included'})}>Ceiling unconfirmed</button><button aria-pressed={settings.ceiling==='floor-projection'} onClick={()=>setSettings({...settings,ceiling:'floor-projection'})}>Assume flat floor outline</button></div><small>Ceiling projection needs review for open-air areas, slopes, stairs and soffits.</small>
      <h3>Coverage and waste</h3><div className="surface-toggles" role="group" aria-label="Default surface rate">{(['floor','wall','ceiling'] as const).map(surface=><button key={surface} aria-pressed={rateTarget.surface===surface&&!rateTarget.finishId} onClick={()=>setRateTarget({surface})}>{surface[0].toUpperCase()+surface.slice(1)} default</button>)}</div>
      {rateTarget.finishId&&<p>Editing the chosen {rateTarget.surface} finish rate. Other finishes keep their defaults.</p>}<div className="surface-fields"><label>Waste (%)<input type="number" min={0} max={100} value={rate.wastePercent} onChange={e=>{if(Number.isFinite(e.target.valueAsNumber))patchRate({wastePercent:e.target.valueAsNumber});}}/></label><label>Coats / layers<input type="number" min={1} max={10} step={1} value={rate.coats} onChange={e=>{if(Number.isFinite(e.target.valueAsNumber))patchRate({coats:e.target.valueAsNumber});}}/></label><label>Coverage (m² per unit)<input type="number" min={.001} step="any" value={rate.coverageM2PerUnit??''} placeholder="Unknown" onChange={e=>patchRate({coverageM2PerUnit:e.target.value===''?null:e.target.valueAsNumber})}/></label><label>Coverage unit name<input value={rate.unitLabel} maxLength={60} placeholder="For example, 2.5 L can" onChange={e=>patchRate({unitLabel:e.target.value})}/></label></div>
      {!!floor?.openings.length&&<details><summary>Measure older door/window markers</summary><p>These markers have no saved height. Enter measured height and sill in millimetres; otherwise net wall quantities remain unavailable.</p>{floor.openings.map((opening,index)=>{const value=settings.legacyOpenings.find(o=>o.floorId===floor.id&&o.openingId===opening.id),patch=(change:{heightMm?:number|null;sillMm?:number})=>setSettings(current=>({...current,legacyOpenings:[...current.legacyOpenings.filter(o=>!(o.floorId===floor.id&&o.openingId===opening.id)),{floorId:floor.id,openingId:opening.id,heightMm:value?.heightMm??null,sillMm:value?.sillMm??0,...change}]}));return <div className="surface-fields" key={opening.id}><strong>{opening.kind==='door'?'Door':'Window'} marker {index+1} · {opening.widthMm} mm wide</strong><label>Opening height (mm)<input type="number" min={1} max={20000} value={value?.heightMm??''} onChange={e=>patch({heightMm:e.target.value===''?null:e.target.valueAsNumber})}/></label><label>Sill / bottom (mm)<input type="number" min={0} max={20000} value={value?.sillMm??0} onChange={e=>{if(Number.isFinite(e.target.valueAsNumber))patch({sillMm:e.target.valueAsNumber});}}/></label></div>;})}</details>}
      <div className="surface-actions"><button disabled={disabled||base!==plan||!!calculated.error} onClick={()=>attempt(()=>{const next=updateSurfaceTakeoffSettings(base,plan,settings,validatePlan);pendingSave.current=JSON.stringify(next.surfaceTakeoffSettings);try{onCommit(base,next);}catch(e){pendingSave.current=null;throw e;}})}>Save assumptions</button><button onClick={()=>{pendingSave.current=null;setBase(plan);setSettings(structuredClone(plan.surfaceTakeoffSettings??defaultTakeoffSettings()));setError('');}}>Reload saved assumptions</button></div>
    </details>
    {view==='quantities'&&report&&<><div className="surface-actions"><button onClick={()=>attempt(()=>downloadSurfaceFile(surfaceQuantitiesCsv(report),'surface-quantities.csv','text/csv;charset=utf-8'))}>Export full CSV</button><button onClick={()=>attempt(()=>printSurfaceDocument(surfaceQuantitiesHtml(report)))}>Print quantities / Save PDF</button><button onClick={()=>attempt(()=>downloadSurfaceFile(surfaceQuantitiesHtml(report),'surface-quantities.html','text/html'))}>Download printable quantities</button></div><p>Net area × waste allowance × coats/layers gives required coverage. Packs round up per room/finish line; coverage left blank stays unknown.</p><div className="surface-table"><table><thead><tr><th>Room / finish</th><th>Gross − openings</th><th>Net / required</th><th>Purchase units</th><th>Review</th></tr></thead><tbody>{rows.slice(0,150).map((row,index)=><tr key={index}><td>{row.roomName}<small>{row.surface} · {row.finishName}</small><button onClick={()=>{setRateTarget({surface:row.surface,finishId:row.finishId});if(assumptions.current)assumptions.current.open=true;}}>Edit this finish rate</button></td><td>{amount(row.grossM2)} − {amount(row.deductionM2)} m²</td><td>{amount(row.netM2)} m²<small>{amount(row.requiredM2)} m² with assumptions</small></td><td>{row.purchaseUnits??'Unknown'} {row.rate.unitLabel}</td><td>{row.warnings.join(' ')}</td></tr>)}</tbody></table></div>{rows.length>150&&<p>First 150 lines shown; exports include the full schedule.</p>}{!rows.length&&<p>No measurable surface rows on this floor.</p>}{report.warnings.map(w=><p key={w}>{w}</p>)}<small>Revision: {report.revision}</small></>}
    {view==='elevation'&&<><p>Choose a continuous wall. Front and Back show opposite sides of the wall; switch sides to see the furniture facing you.</p><div className="surface-wall-cards">{geometry.value?.plates.map((wall,index)=><button key={wall.key} aria-pressed={wallKey===wall.key} onClick={()=>setWallKey(wall.key)}><strong>Wall {index+1} · {(wall.lengthMm/1000).toFixed(2)} m</strong><small>{wall.boundary?'Floor boundary':'Partition'} · {wall.heightMm===null?'height unknown':(wall.heightMm/1000).toFixed(2)+' m high'}</small></button>)}</div><div className="surface-toggles" role="group" aria-label="Elevation face">{(['front','back'] as const).map(value=><button key={value} aria-pressed={face===value} onClick={()=>setFace(value)}>{value==='front'?'Front face':'Back face'}</button>)}</div><div className="surface-toggles" role="group" aria-label="Drawing scale">{elevationScales.map(value=><button key={value} aria-pressed={scale===value} onClick={()=>setScale(value)}>1:{value}</button>)}</div><label>Drawing notes<textarea value={notes} maxLength={1500} onChange={e=>setNotes(e.target.value)} placeholder="Measurements or mounting details to verify"/></label>{drawing.svg&&drawing.value&&<><img className="elevation-preview" alt="Selected wall planning elevation" src={'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(drawing.svg)}/><div className="surface-actions"><button onClick={()=>attempt(()=>downloadSurfaceFile(drawing.svg!,'wall-elevation.svg','image/svg+xml'))}>Export scaled SVG</button><button onClick={()=>attempt(()=>printSurfaceDocument(elevationPrintHtml(drawing.value!)))}>Print elevation / Save PDF</button><button onClick={()=>attempt(()=>downloadSurfaceFile(elevationPrintHtml(drawing.value!),'wall-elevation.html','text/html'))}>Download printable elevation</button></div><p>The preview fits this panel. Print at 100% and measure the scale bar on paper before relying on scale.</p></>}{!wallKey&&<p>Select a wall to prepare its drawing.</p>}</>}
    {[error,calculated.error,geometry.error,view==='elevation'?drawing.error:undefined].filter(Boolean).map((value,index)=><p role="alert" key={index}>{value}</p>)}<p role="status" aria-live="polite">{message}</p>
  </section>;
}
