import type {SurfaceQuantityReport} from './surfaceTakeoff';
import {escapeDrawingText,wallElevationSvg,type WallElevation} from './wallElevation';
const number=(value:number|null)=>value===null?'Unavailable':Number(value.toFixed(4)).toString();
const cell=(value:unknown)=>{let v=String(value??'');if(/^[\s\u0000-\u001f]*[=+\-@]/.test(v))v="'"+v;return '"'+v.replaceAll('"','""')+'"';};
export function surfaceQuantitiesCsv(report:SurfaceQuantityReport):string {
  const rows=[['Project','Revision','Wall faces','Opening deduction','Ceiling assumption','Floor','Room','Surface','Finish','Gross m2','Deductions m2','Net m2','Waste percent','Coats/layers','Coverage m2 per unit','Unit label','Required m2','Rounded units','Notes'],...report.rows.map(r=>[report.projectName,report.revision,report.settings.wallFaces,report.settings.deductOpenings?'Model + measured legacy openings':'Gross only',report.settings.ceiling,r.floorName,r.roomName,r.surface,r.finishName,number(r.grossM2),number(r.deductionM2),number(r.netM2),r.rate.wastePercent,r.rate.coats,r.rate.coverageM2PerUnit??'Unknown',r.rate.unitLabel,number(r.requiredM2),r.purchaseUnits??'Unknown',[...r.warnings,...report.warnings].join(' ')])];return '\ufeff'+rows.map(r=>r.map(cell).join(',')).join('\r\n')+'\r\n';
}
export function surfaceQuantitiesHtml(report:SurfaceQuantityReport):string {
  const e=escapeDrawingText;return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'"><title>${e(report.projectName)} — surface quantities</title><style>body{font:12px system-ui;color:#20342b;margin:20px}table{width:100%;border-collapse:collapse;font-size:10px}td,th{border:1px solid #b6c1b5;padding:6px;text-align:left;vertical-align:top}thead{display:table-header-group}tr{break-inside:avoid}small{display:block}h1{font-size:22px}@page{size:landscape;margin:12mm}</style></head><body><h1>${e(report.projectName)} — surface quantities</h1><p>Model revision: ${e(report.revision)}</p><p>Planning estimates, not construction or code certification. All areas in square metres. Wall faces: ${e(report.settings.wallFaces)}. Opening deduction: ${report.settings.deductOpenings?'current model apertures and explicitly measured legacy openings':'none; gross wall faces'}. Ceiling: ${e(report.settings.ceiling)}.</p><p>Required area = net area × (1 + waste / 100) × coats/layers. Purchase units = ceiling(required area / entered coverage). Rounding is per room/finish line; combine suitable materials when sharing packs. Unknown coverage or geometry is not zero.</p>${report.warnings.map(w=>`<p>${e(w)}</p>`).join('')}<table><thead><tr><th>Floor / room</th><th>Surface / finish</th><th>Gross − deductions = net m²</th><th>Assumptions</th><th>Required / purchase</th><th>Review notes</th></tr></thead><tbody>${report.rows.map(r=>`<tr><td>${e(r.floorName)}<small>${e(r.roomName)}</small></td><td>${e(r.surface)}<small>${e(r.finishName)}</small></td><td>${number(r.grossM2)} − ${number(r.deductionM2)} = ${number(r.netM2)}</td><td>${r.rate.wastePercent}% waste; ${r.rate.coats} coats/layers<small>${r.rate.coverageM2PerUnit??'Unknown'} m² per ${e(r.rate.unitLabel)}</small></td><td>${number(r.requiredM2)} m²<small>${r.purchaseUnits??'Unknown'} ${e(r.rate.unitLabel)}</small></td><td>${r.warnings.map(e).join(' ')}</td></tr>`).join('')}</tbody></table></body></html>`;
}
export function elevationPrintHtml(elevation:WallElevation):string {const svg=wallElevationSvg(elevation),size=svg.match(/width="([\d.]+)mm" height="([\d.]+)mm"/)!;return `<!doctype html><html><head><meta charset="utf-8"><title>Wall elevation</title><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'"><style>html,body{margin:0;padding:0}svg{display:block}@page{size:${size[1]}mm ${size[2]}mm;margin:0}</style></head><body>${svg}</body></html>`;}
export function downloadSurfaceFile(contents:string,filename:string,mime:string){const url=URL.createObjectURL(new Blob([contents],{type:mime})),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function printSurfaceDocument(html:string){const page=window.open('about:blank','_blank');if(!page)throw new Error('Allow the printable window or download a copy instead.');page.opener=null;page.document.open();page.document.write(html);page.document.close();page.focus();page.setTimeout(()=>page.print(),100);}
