import {useState} from 'react';
const topics=[
 ['Create rooms','Open Floor plan studio. Import a reference for online analysis, or add a room by dimensions. Review the layout before creating the 3D home. Switching measurement units never resizes your plan.'],
 ['Move furniture','Select a piece, then enable the four-arrow Move button. Movement starts locked to prevent accidental edits. Use the inspector for precise size, position and rotation. Done locks movement again.'],
 ['Place furniture','Choose a library piece, position its preview, then confirm with the checkmark or Enter. Escape cancels. On a phone, tap a library piece, then tap its location in the home.'],
 ['Paint and undo','Select Paint and choose Walls or Floor. Floor areas are previews until confirmed. Wall brush changes apply when clicked. Terrain and planting update live; releasing completes one undoable stroke. Undo is always in the top bar.'],
 ['Save and reopen','Autosave keeps your 3D edits on this device. In Floor plan studio, use Save draft before closing. Save online keeps a private account copy. Export a backup for a portable file. Open My projects to resume. Shared links are snapshots.'],
 ['Landscape and plants','Open Outdoors. Terrain sculpts land and adds water. Plants offers individual pieces, whole-map grass coverage and large landscapes up to two million logical plants. Distant detail is reduced automatically; close plants retain detail.'],
 ['Camera and touch','One finger navigates when no editing tool is active. Use two fingers to pan and pinch to zoom while editing. Center home restores the floor in view. Selecting furniture never changes your zoom. Preview offers room views and pictures.'],
 ['Keyboard','Tab reaches controls; Enter activates them. Escape dismisses dialogs or cancels a draft. R toggles rotation. Ctrl/Cmd+Z undoes. Delete removes selected furniture. Numerical room and furniture controls provide alternatives to dragging.'],
 ['Automatic furnishing','Quick layout places a starter arrangement immediately. Undo restores the previous arrangement. Browser agent uses your browser’s connected agent for custom requests; it requires browser support. Browser agent proposals require review unless you explicitly enable direct agent edits.'],
];
export function TaskHelp(){const [query,setQuery]=useState('');return <><h2>How can we help?</h2><input aria-label="Search help" placeholder="Search moving, saving, planting…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="help-topics">{topics.filter(t=>t.join(' ').toLowerCase().includes(query.toLowerCase())).map(([title,body])=><details key={title} open={!!query}><summary>{title}</summary><p>{body}</p></details>)}</div></>}
