import {Wall,Trash,ArrowsVertical,Eye} from '@phosphor-icons/react';
import {getWallVisibility} from './wallVisibility';
import {useEffect,useState} from 'react';
import {usePlanner} from './store';
import {floorBoundaryWalls} from './floorGeometry';
import {wallRuns} from './windows';
import {catalog} from './catalog';

export function WallConstructionControls({embedded=false}:{embedded?:boolean}={}){
 const s=usePlanner(),floor=s.plan.floors.find(f=>f.id===s.activeFloorId)!,grid=s.plan.gridSizeMm;
 const wall=[...floorBoundaryWalls(floor,grid),...floor.walls].find(w=>w.id===s.selectedWallId);
 const run=wall&&wallRuns(floor,grid).find(r=>r.horizontal===(wall.az===wall.bz)&&Math.abs(r.line-(r.horizontal?wall.az:wall.ax)*grid)<1&&r.start<=Math.min(r.horizontal?wall.ax:wall.az,r.horizontal?wall.bx:wall.bz)*grid&&r.end>=Math.max(r.horizontal?wall.ax:wall.az,r.horizontal?wall.bx:wall.bz)*grid);
 const [start,setStart]=useState(0),[length,setLength]=useState(1000),[railing,setRailing]=useState('');
 useEffect(()=>{setStart(0);setLength(run?Math.round(run.end-run.start):1000)},[s.selectedWallId]);
 const valid=run&&start>=0&&length>0&&start+length<=run.end-run.start+.1;
 return <details className="wall-construction" open={embedded||s.tool==='wall-cut'||!!wall}><summary hidden={embedded}>Walls & balcony rails</summary>{getWallVisibility(s.plan.camera)!=='all-visible'&&<button onClick={()=>s.toggleCameraSetting('transparentWalls')}><Eye size={18}/> Show walls for editing</button>}<div className="build-choices"><button aria-pressed={s.tool==='wall'} onClick={()=>s.setTool('wall')}><Wall size={32}/><strong>Draw wall</strong></button><button aria-pressed={s.tool==='wall-cut'} onClick={()=>s.setTool('wall-cut')}><Trash size={32}/><strong>Remove wall section</strong></button></div><label className="wall-height-control"><ArrowsVertical size={20}/> Wall height · this floor<select aria-label="Wall height" value={floor.heightMm} onChange={e=>s.setWallHeight(+e.target.value)}>{![2438,2743,3048,3658].includes(floor.heightMm)&&<option value={floor.heightMm}>{(floor.heightMm/1000).toFixed(2)} m · current</option>}<option value={2438}>Standard · 8 ft / 2.44 m</option><option value={2743}>Airy · 9 ft / 2.74 m</option><option value={3048}>High · 10 ft / 3.05 m</option><option value={3658}>Loft · 12 ft / 3.66 m</option></select></label>{s.tool==='wall-cut'&&<p>Drag along a wall to remove that span. Undo restores it.</p>}{run?<><label>Start along wall (mm)<input type="number" min="0" value={start} onChange={e=>setStart(Number(e.target.value))}/></label><label>Section length (mm)<input type="number" min="10" max={run.end-run.start} value={length} onChange={e=>setLength(Number(e.target.value))}/></label><label>Replace with<select value={railing} onChange={e=>setRailing(e.target.value)}><option value="">Open space</option>{catalog.filter(item=>item.id.startsWith('balcony-rail-')).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button disabled={!valid} onClick={()=>{if(!run)return;const a=(run.start+start)/grid,b=(run.start+start+length)/grid,line=run.line/grid;s.cutWalls([{ax:run.horizontal?a:line,az:run.horizontal?line:a,bx:run.horizontal?b:line,bz:run.horizontal?line:b}],railing||undefined)}}>{railing?'Replace section with railing':'Remove selected section'}</button></>:<p>Select a visible wall for exact section lengths or railing replacement.</p>}</details>
}
